### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by qwertyuiuytrewq** [instabot-py/instabot.py#1020]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 10
## Python Version?
2 / 3
3
## Description

Type the description of your issue here.
I have followed the video for how to set up with Windows. 
I have followed EXACTLY as the video goes.

I have noticed one thing though. In the video, the requirements.txt file in the video was "requests==2.12.4" and the one from the latest download was 
"requests fake-useragent"

I have tried both of these, with the same exact result. 

I have tried using instagram username as the user name.
I have tried using instagram email as the user name.

And all combinations of username/email/requirements.txt

Could somebody please help?

03/14/2018

```
Include the contents of the error.log here (if applicable).
C:\Users\xxxxx\Downloads\instabot.py-master\instabot.py-master>python example.py
14.03.2018_00:46 Instabot v1.2.0 started at 14.03.2018 00:46:

14.03.2018_00:46 Trying to login as xxxxxxxxxx...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['nike', 'instagram'])
  File "C:\Users\xxxxx\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\xxxxx\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\xxxxx\Downloads\instabot.py-master\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

C:\Users\xxxxx\Downloads\instabot.py-master\instabot.py-master>

**Comment by qwertyuiuytrewq** [comment]
Thanks to "porsamini" i have found it. 
Sorry but I am new here, and did not find the other person/people who asked.
his comment was "This is currently known issue. See #1017"
