### ISSUE TITLE
How can i solve this? (KeyError: 'user')

### ISSUE THREAD

**Issue by privatefound** [instabot-py/instabot.py#1023]
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/xxx/Documenti/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/xxx/Documenti/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/xxx/Documenti/instabot.py/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by gaaraxpo** [comment]
I thought it was just me. I also have this problem when I run the script today. This didn't happen yesterday.

**Comment by N1CHTN3BIH** [comment]
Same here. Maybe there was an Instagram API change lately?

**Comment by privatefound** [comment]
Kk

**Comment by hendrikbgr** [comment]
@N1CHTN3BIH Thank you so much! Worked perfectly for me!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
