### ISSUE TITLE
Error in "fake-useragent"

### ISSUE THREAD

**Issue by kabauterman** [instabot-py/instabot.py#1052]
Error.log says:

WARNING:root:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 144, in get_browser_versions
    'No browsers version found for {browser}'.format(browser=browser))
FakeUserAgentError: No browsers version found for Edge/IE
WARNING:root:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 144, in get_browser_versions
    'No browsers version found for {browser}'.format(browser=browser))
FakeUserAgentError: No browsers version found for Edge/IE

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
