### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ArielEcker** [instabot-py/instabot.py#1064]
Hi, 
this error appears when I run "example.py". Can you help me?

======== RESTART: C:\Users\ariel\Downs\instabot.py-master\example.py ========
18.03.2018_18:58 Instabot v1.2.0 started at 18.03.2018 18:58:

18.03.2018_18:58 Trying to login as eckrphoto...

Traceback (most recent call last):
  File "C:\Users\ariel\Downs\instabot.py-master\example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\ariel\Downs\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\ariel\Downs\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\ariel\Downs\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
>>>

**Comment by cristianaortiga** [comment]
same here

**Comment by pocheche** [comment]
Same

**Comment by pocheche** [comment]
Now working all_data['graphql']['user']['id'] have to be replaced in instabot.py and userinfo.py. Thank you.

**Comment by AutumnClove** [comment]
@pocheche could you explain a little more by what you mean by have to be replaced? Trying to help someone get this set up.

**Comment by unknowndrone** [comment]
@pocheche what exactly did you replace it with?

**Comment by Curtis777** [comment]
got the same troubles...

**Comment by AutumnClove** [comment]
@unknowndrone @Curtis777 if you guys go into instabot.py and userinfo.py you'll see it's `all_data = ['user']['id']` you have to change it to `all data = ['graphql']['user']['id']` at least that's what I did for my friend who I set this up for. I hope this helps.
