### ISSUE TITLE
Cant fix "FakeUserAgentError('Maximum amount of retries reached')"

### ISSUE THREAD

**Issue by billionbucks** [instabot-py/instabot.py#1065]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
MACoS Sierra V10.12.4
## Python Version?
2 / 3
2
## Description

Type the description of your issue here.

This bot used to work for me but now it's not working anymore, i searched a bit and tried following solutions:
#968 
#980 

Still no luck... any fixes?

```
Include the contents of the error.log here (if applicable).

Traceback (most recent call last):
  File "/Users/blabla/Downloads/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=[])
  File "/Users/blabla/Downloads/instabot.py-master/src/instabot.py", line 162, in __init__
    fake_ua = UserAgent()
  File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by Glen-Cocoa** [comment]
I am having the same issue!

**Comment by SpaceTraveller1** [comment]
Same :/

**Comment by omi10859** [comment]
same problem!!

**Comment by Subway19** [comment]
Same problem!!

**Comment by Patrikkk** [comment]
Same when running example.py  
Running on pythonanywhere, pyhton 2.7

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by herwincamargo** [comment]
Same issue here.

**Comment by Marten123123** [comment]
Got the same problem, anyone got it fixed before it got closed?

**Comment by AngusWG** [comment]
Same issue .

**Comment by Syslog777** [comment]
same

**Comment by amirpzk** [comment]
same ..

**Comment by micmalti** [comment]
Same here.

**Comment by zakariakhayri90** [comment]
same

**Comment by zakariakhayri90** [comment]
Please someone fix it please

**Comment by Molar3NK** [comment]
same issue

**Comment by gwest123** [comment]
Error is still occurring.

**Comment by dnoah1** [comment]
Having the same error? Any solution?

**Comment by dnoah1** [comment]
Having the same error...any fix?
