### ISSUE TITLE
unfollowing in mode 3 not working

### ISSUE THREAD

**Issue by Tidle999** [instabot-py/instabot.py#1074]
Hey all,

i am using the new userinfo.py and user_info.py and instabot.py. so i thought everything should work now, but as i am trying to cleanup the following i want to use mode 3 for unfollowing all that are not following and based on folowers_db so i wont unfollow my friends.
actually only mode 0 is working. (but without ufollowing)
i get these errors:

` python doit_leen2.py
10:36 Instabot v1.2.0 started at 20.03.2018 10:36:

10:36 Trying to login as test-account...

10:36 test-account login success!
10:36 test-account : Get media id on recent feed
 20.03.2018 10:36
10:36 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
10:37 test-account : Get media id on recent feed
 20.03.2018 10:37
10:37 Except on get media!!
10:37 ======> Get media id by Tag <======
10:37 Get media by user success!
10:37 Current Index = 3 of 40 medias
Traceback (most recent call last):
  File "doit_leen2.py", line 98, in <module>
    unfollow_protocol(bot)
  File "\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File " \src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File " \src\feed_scanner.py", line 56, in feed_scanner
    likers_graber_protocol(self)
  File " \src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File " \src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'`

**Comment by rinat-khantimirov** [comment]
25 - 39 lines in user_info.py
```
                follows = user_info['graphql']['user']['edge_follow']['count']
                follower = user_info['graphql']['user']['edge_followed_by']['count']
                if self.is_self_checking is not False:
                    self.self_following = follows
                    self.self_follower = follower
                    self.is_self_checking = False
                    self.is_checked = True
                    return 0
                media = user_info['graphql']['user']['edge_owner_to_timeline_media']['count']
                follow_viewer = user_info['graphql']['user']['follows_viewer']
                followed_by_viewer = user_info['graphql']['user']['followed_by_viewer']
                requested_by_viewer = user_info['graphql']['user'][
                    'requested_by_viewer']
                has_requested_viewer = user_info['graphql']['user'][
                    'has_requested_viewer']
```
