### ISSUE TITLE
Added ['graphql'] to id_user, new error

### ISSUE THREAD

**Issue by xavierfe** [instabot-py/instabot.py#1076]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description
Added id_user=['graphql']['user...etc

Now I get this error:

python surf2.py
Traceback (most recent call last):
  File "surf2.py", line 6, in <module>
    from src import InstaBot
  File "/data/data/com.termux/files/home/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/data/data/com.termux/files/home/instabot.py/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/data/data/com.termux/files/home/instabot.py/src/userinfo.py", line 3
    import json import requests class
                     ^
SyntaxError: invalid syntax
```

**Comment by xavierfe** [comment]
Update: it works on the laptop but not in the cell phone. Any ideas how to get it to work on the phone?

**Comment by ivanrkv** [comment]
Your tabs might be off. Check the indentation in the userinfo.py file is proper.

**Comment by xavierfe** [comment]
You were right, fixed!!!

**Comment by ivanrkv** [comment]
Glad to help :)

Please mark the issue as resolved/closed.
