### ISSUE TITLE
KeyError Issue

### ISSUE THREAD

**Issue by bool2web** [instabot-py/instabot.py#1081]
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 

## Python Version?
3

## Description

Can't login...
Stop error.

Traceback (most recent call last):
  File "/Users/xxx/Documents/instabot.py-master/example.py", line 45, in <module>
    unfollow_whitelist=[])
  File "/Users/xxx/Documents/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/xxx/Documents/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/xxx/Documents/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by Hiwakea** [comment]
Did you sort the problem? I can't log in either, I have a similar issue;

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/dieopauel/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/dieopauel/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/dieopauel/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by bhatmohsin1913** [comment]
I am getting the same issue .plz help me..mail me at bhatmohsin1913@gmail.com
