### ISSUE TITLE
The script stopped running, any idea to fix this error?

### ISSUE THREAD

**Issue by AnuragSinghChaudhary** [instabot-py/instabot.py#1083]
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/anuragchaudhary/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/anuragchaudhary/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/anuragchaudhary/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by DubDubDan** [comment]
I'm experiencing the same after setting up a fresh bot... i'm just reading thought the recent fixes and will let you know if anything has already been mentioned.

**Comment by DubDubDan** [comment]
This was fixed a few days ago by another user (I'm no way taking credit for this) but the fix is...

Instagram changed their api and 'user' is now in 'graphql' in all_data. So on line 42 in userinfo.py you got to change it to id_user = all_data['graphql']['user']['id'].

**Comment by nammye** [comment]
Than you. been dealing with that same issue as well.

**Comment by Leastham2** [comment]
the line i fixed was 45
thanks bruh
