### ISSUE TITLE
Login Error !

### ISSUE THREAD

**Issue by levisoares** [instabot-py/instabot.py#1086]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [X ] I have searched for other issues with the same problem.

## Hosting
- [VPS ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ X] Bug
- [ ] Feature Request
- [ X] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / **Linux** / Android

## Python Version?
2 / **3**

## Description

Type the description of your issue here.
22.03.2018_08:33 Trying to login as xxxxxxxx...

Traceback (most recent call last):
  File "xxxxxxxx.py", line 53, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/root/instabot.py/src/instabot.py", line 227, in __init__
    self.login()
  File "/root/instabot.py/src/instabot.py", line 296, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/root/instabot.py/src/userinfo.py", line 45, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

Include the contents of the error.log here (if applicable).
```

**Comment by focamonca** [comment]
I have the exact same problem

**Comment by heldausberlin** [comment]
Same to me.

**Comment by TVBrowntown** [comment]
same issue, had a look at the code but it's beyond me sadly :(

**Comment by FrancescoRosati** [comment]
same problem here!

**Comment by TVBrowntown** [comment]
I've found a fix from a YouTube comment of all places. 

In file src/userinfo.py Replace line 42

id_user = all_data['user']['id'] 

with 

`id_user = all_data['graphql']['user']['id']`

**Comment by bodeezl** [comment]
I have the same issue, I used TVBrowntown's suggestion and the bot logs in then out, see below.

22.03.2018_21:17 Instabot v1.2.0 started at 22.03.2018 21:17:

22.03.2018_21:17 Trying to login as cow__tipper...

22.03.2018_21:18 username login success!
Traceback (most recent call last):
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
AttributeError: 'tuple' object has no attribute 'new_auto_mod'
22.03.2018_21:18 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
22.03.2018_21:18 Bot work time: 0:00:07.790433
22.03.2018_21:18 Logout success!

Anyone else have a fix?

**Comment by focamonca** [comment]
It doesn't work for me

**Comment by fab976** [comment]
@TVBrowntown 
That worked for me for one of my scripts!
Thank you so much, was searching for days now

**Comment by levisoares** [comment]
@TVBrowntown solution worked on mine!
Thank you !
