### ISSUE TITLE
Script breaks after login

### ISSUE THREAD

**Issue by heldausberlin** [instabot-py/instabot.py#1088]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Linux

## Python Version?
2 / 3

## Description

Since this morning the script breaks after trying to login. Before I had already and successfully fixed the 'graphql' bug:

```
Traceback (most recent call last):
  File "/Users/Instabot/instabot.py/example.py", line 46, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
  File "/Users/Instabot/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/Instabot/instabot.py/src/instabot.py", line 281, in login
    r = self.s.get(self.url)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
	requests.exceptions.ConnectionError: ('Connection aborted.', error(60, 'Operation timed out'))
```

**Comment by heldausberlin** [comment]
I didn’t change anything. But now the script works fine again. Can’t tell why.

**Comment by fab976** [comment]
For me its still broken...

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
