### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by FrancescoRosati** [instabot-py/instabot.py#1092]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
MAC el capitain 10.11.3
## Python Version?
2 / 3
3
## Description
ImportError
Type the description of your issue here.

MBPdiFrancesco:instabot.py-master Francesco$ python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/Francesco/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/Francesco/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/Francesco/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests

```
Include the contents of the error.log here (if applicable).
```

**Comment by Lartten** [comment]
I have the same problem if I execute with pythton2. 
python2 instabot/instabot.py/example.py
Traceback (most recent call last):
  File "instabot/instabot.py/example.py", line 6, in <module>
    from src import InstaBot
  File "/home/xxxx/instabot/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/xxxx/instabot/instabot.py/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/home/xxxx/instabot/instabot.py/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests

If I use python3 I get this:
`24.03.2018_00:56 Instabot v1.2.0 started at 24.03.2018 00:56:

24.03.2018_00:56 Trying to login as xxxxxxx...

Traceback (most recent call last):
  File "instabot/instabot.py/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/xxxx/instabot/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/xxxx/instabot/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/xxxx/instabot/instabot.py/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
`

Regards Lartten

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
