### ISSUE TITLE
Cannot import name JSONDecodeError

### ISSUE THREAD

**Issue by monanabanana** [instabot-py/instabot.py#1101]
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Android 8.0.0

## Python Version?
2.2.3-1

## Description

```
26.03.2018_20:07 Login error! Connection error!
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/projects/instabot.py-master/main.py", line 52, in <module>
    unfollow_whitelist=[])
  File "/storage/emulated/0/qpython/projects/instabot.py-master/src/instabot.py", line 232, in _init_
    self.populate_user_blacklist()
  File "/storage/emulated/0/qpython/projects/instabot.py-master/src/instabot.py", line 242, in populate_user_blacklist
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
1|F8331:/ $
```

**Comment by napster2091** [comment]
try to do:

from simplejson import JSONDecodeError

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
