### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by guangmiw8** [instabot-py/instabot.py#1121]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 10
## Python Version?
2 / 3
3
## Description

Type the description of your issue here.
``` 
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))
failed to validate certificate

Include the contents of the error.log here (if applicable).
```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Python36\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python36\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Python36\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "C:\Python36\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python36\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 59, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "D:\git\instabot.py\src\instabot.py", line 231, in __init__
    self.login()
  File "D:\git\instabot.py\src\instabot.py", line 281, in login
    r = self.s.get(self.url)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

**Comment by guangmiw8** [comment]
What do you mean where? I tried both on Windows and MacOS. It used to work and suddenly stopped working after i killed the program and tried to start again.

**Comment by ChipWolf** [comment]
Strange; I assume you can get to the website via your browser just fine?

Try running this `pip install -U requests[security]`

**Comment by guangmiw8** [comment]
Yup, I am able to access https://www.instagram.com in my browser. the pip install command didn't solve this problem. It's most likely my python's problem, I've tried reinstalling from scratch but no luck. thanks for the help.

**Comment by ChipWolf** [comment]
Python 3.6?

**Comment by guangmiw8** [comment]
Just checked the console error message when using python 3.6, I missed the call stack trace at the top:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\urllib3\contrib\pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "C:\Python36\lib\site-packages\OpenSSL\SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Python36\lib\site-packages\OpenSSL\SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "C:\Python36\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

this seems to be the root cause

**Comment by ChipWolf** [comment]
Yeah, that doesn't really tell me much else than it can't validate the TLS certificate from Instagram. I would add the `verify=False` attribute to all references of the requests function being used, but that'll just band-aid the problem.

Run these two commands from the root of the bot

`python3 -m pip install -r requirements.txt --upgrade`
`python3 example.py`

**Comment by guangmiw8** [comment]
not a python expert, is python3 the alias you defined for python3.6 to differentiate from python 2.7? the packages declared in requirement.txt are already up to date.

**Comment by ChipWolf** [comment]
Yeah, correct @guangmiw8 there's issues with people running python2

**Comment by not-inept** [comment]
@guangmiw8, are you running the bot from a corporate network? That may be the cause, it looks like a number of folks have hit similar SSL issues because of their network policies (whether they be corporate, or some of the other odd ones like Amtrak). I'm looking for a solution for the same error encountered by a different bot right now, so let me know if you figured something out beyond just using verify=false.

**Comment by guangmiw8** [comment]
@not-inept yes, it was running from a corporate network, I didn't try the verify=false solution, did it work for you?

**Comment by not-inept** [comment]
So, I was actually running into the issue with the real time messaging API (rtm_connect), which uses websockets.

I set the environmental variable `WEBSOCKET_CLIENT_CA_BUNDLE=<location of my company CA file>` for that. To get requests to work, I had previously set `REQUESTS_CA_BUNDLE=<location of my company CA file>` to get requests to work. 

What was weird was that passing the ca bundle as an ssl_opt in a modified version of the slackclient library did not work, however I'm now all set after having those two environmental variables properly set.

**Comment by ngageby** [comment]
Same issue here on multiple versions of Python and across Mac and Windows.  I have found a lot of speculation but no fix as of yet.    Has anyone located a step by step answer for this issue?

**Comment by kddww8** [comment]
I'm running on a partitioned drive, operating windows on a mac. I've gotten the same error, however my cmd prompt does not recognize the python3 "is not recognized as internal or external cmd" - so I'm using py or just pip. Am I missing something?
