### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by focamonca** [instabot-py/instabot.py#1124]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
 Linux

## Python Version?
3

## Description

Won't start. I have a bot running since 35 days ( now is at like #27954) but this new one give me this error log:

pi@raspberrypi:~/Desktop/instabot040418 $ sudo python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/pi/Desktop/instabot040418/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/Desktop/instabot040418/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent

**Comment by spodZ** [comment]
Same with me I downloaded fake_user branch and master branch both have the same error

**Comment by spodZ** [comment]
Here's the fix I found going a little deeper on issues: `pip install fake_useragent`

**Comment by spodZ** [comment]
Well the error is stating you don't have fake_useragent module installed to install it you have to use `pip install fake_useragent` make sure you have python 3.6 installed and pip installer
