### ISSUE TITLE
Login error which leads to "Removing already liked medias..." loop

### ISSUE THREAD

**Issue by Corleanus** [instabot-py/instabot.py#1129]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
3

## Description

Type the description of your issue here.
04.04.2018_15:40 Trying to login as grigorije.jakisic@gmail.com...

04.04.2018_15:40 Login error! Check your login data!
04.04.2018_15:40 Removing already liked medias..
04.04.2018_15:40 Trying to unfollow #1: 
04.04.2018_15:40 Looks like there is nobody to unfollow.
04.04.2018_15:40 Removing already liked medias..
04.04.2018_15:40 Removing already liked medias..
04.04.2018_15:40 Removing already liked medias..

```
Include the contents of the error.log here (if applicable).
```

**Comment by Corleanus** [comment]
... Ofcourse I have checked the parametres! Thats why I posted this, because parametres are correct but the issue is still there!

**Comment by All3xJ** [comment]
same issue here... it doesn't work. I tried with several and different accounts, with correct credentials, but it fails.

**Comment by ChipWolf** [comment]
I'll try and replicate, if anyone can find the root cause, let me know.

**Comment by DavidUser** [comment]
Same here, the credentials are correct, running on local machine, but get suspicious log in attempt.
Some endpoint should was changed but still active getting suspicious log in.

**Comment by antkis** [comment]
Have the same problem if using email for the login, with the username works it.

**Comment by ChipWolf** [comment]
Yeah, it should be username and password.
As long as you don't change any of the default timings, you shouldn't have a problem.
I've seen this with people being too aggressive with the follow/like rates.

**Comment by noisyninjafeet** [comment]
I am having the same issue and I am being very conservative. I left all timings default. 600 likes (3 tags) 0 follow and 0 un-follow. I ran the bot for one day just liking the 3 tags then stopped it to add a fourth tag and now it no longer logs in without receiving the "suspicious log in attempt was this you?" on my mobile device. I have the 2 factor authentication off and If I select yes this was me and try to run the bot again it pops up again.

**Comment by VerinSC** [comment]
@ChipWolf I am getting the same error, even with default settings. I get a notification on Instagram saying there is a local log in attempt and the bot says 

"Login Error! Connection Error!"
"Removing already liked medias"
"Removing already liked medias"
"Removing already liked medias"
"Removing already liked medias"
"Removing already liked medias"

Also despite claiming not being able to log in, it appears it is unliking some photos which was odd. 

No 2FA, has been working fine for weeks, no changes made on my end. Good luck finding the problem :D

**Comment by ChipWolf** [comment]
It depends where you're running the bot. None of us are sure how the suspicious access attempt function works, but if you suddenly change behavior; it'll probably trip. As long as you're not running the bot remotely, you shouldn't see it too often.

I would probably start small and ramp up your numbers, I've seen issues (especially with new accounts) even with the default values.

**Comment by VerinSC** [comment]
@ChipWolf 

I've been running it on the same settings from my computer for the best part of a year now, only started getting these problems in the last couple of days. Nothing has been changed with the bot so I'd assume Instagram has changed something, the Intagram account also seems to be working fine

**Comment by instabot-master** [comment]
well I started to have these issues because probably I change my location quite often with my laoptop into remote places.

**Comment by VerinSC** [comment]
@instabot-master I use it from home, never move my computer and very rarely turn it off. As I said it's been fine for a long time before this week. Nothing changed on my end, just started being unable to log in

**Comment by Corleanus** [comment]
Hope the solution will pop-up soon!

**Comment by wn09xkd** [comment]
I run my bot on AWS lightsail server and have same issue. And can't login to instagram neither from chrome (from instance). So I think problem is related to network or IP address ....

**Comment by Idrisskh** [comment]
When you get the suspicious login, wait 24h and then try again. From what I have learned, here is the list of things that can cause the challenge :
- Trying to login with a VPS
- Trying to login with an IP related to another country
- Too many wrong password

After getting the suspicious login, waiting 24h before trying to login again has solved the problem in most of the case.

**Comment by KeshaFinkel** [comment]
Same problem, and also cannot login via browser on computer or phone.
Waited few days problem doesn't go.
But turning on VPN solved problem.
So it looks like ban of IP adress

**Comment by MiLeung** [comment]
I got this problem once I started getting prompted for "suspicious logins" in Mountain View on the Instagram mobile app and website (where my bot is hosted on GCP I think). The username and password are correct - it's just that instabot can't bypass the suspicious login prompt.

**Comment by MiLeung** [comment]
I got this problem once I started getting prompted for "suspicious logins" in Mountain View on the Instagram mobile app and website (where my bot is hosted on GCP I think). The username and password are correct.

**Comment by gonjumixproject** [comment]
Not really sure if that is the same issue but, I was getting "Removing already liked medias" error as well. I checked the error logs, there was a socket error. 

WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
..
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

I changed following code part from instabot.py ; 
fake_ua = UserAgent()  
to following;
fake_ua = UserAgent(verify_ssl=False) 

(https://github.com/hellysmile/fake-useragent/issues/53#ref-commit-9d7a967) 

and that actually solved my problem.. Not sure if this will be a permanent solution or not though..
