### ISSUE TITLE
Not work auto unfollow

### ISSUE THREAD

**Issue by itkos** [instabot-py/instabot.py#1138]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [ ] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows
## Python Version?
2 / 3
3
## Description

Type the description of your issue here.
Not work auto_unfollow
```
Include the contents of the error.log here (if applicable).

Traceback (most recent call last):
  File "D:\Project\instabot.py-master\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Project\instabot.py-master\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Project\instabot.py-master\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "D:\Project\instabot.py-master\src\instabot.py", line 357, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "C:\Program Files (x86)\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Conorbro** [comment]
Your version of the bot is out of date. Update and it'll work.

**Comment by itkos** [comment]
okey! thank you

2018-04-06 17:51 GMT+03:00 Conor Broderick <notifications@github.com>:
