### ISSUE TITLE
Unfollow mode causing an error

### ISSUE THREAD

**Issue by jrtderonde** [instabot-py/instabot.py#1145]
## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Window

## Python Version?
3

## Description

I tried to run mode 2 and 3 but both are causing the following error.

```
Include the contents of the error.log here (if applicable).

09.04.2018_11:53 Current Index = 42 of 61 medias

Traceback (most recent call last):
  File "example.py", line 97, in <module>
    unfollow_protocol(bot)
  File "C:\Users\<me>\Desktop\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "C:\Users\<me>\Desktop\instabot.py-master\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "C:\Users\<me>\Desktop\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\<me>\Desktop\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\<me>\Desktop\instabot.py-master\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
```

**Comment by Toonix** [comment]
I don't get any error but the bot is just logging out after first unfollow.

**Comment by ChipWolf** [comment]
Mode 0 is the only working mode currently

**Comment by lkemdiri** [comment]
Yes, this is still an issue! has anyone had any luck in resolving it?
