### ISSUE TITLE
Unfollow does not work!

### ISSUE THREAD

**Issue by dajul123** [instabot-py/instabot.py#1150]
#### Select one:
- [ X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10

## Python Version?
 3

## Description

The like module works but the unfollow does not.
```
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "C:\Users\MYUSer\Desktop\Instabot\src\instabot.py", line 357, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by dajul123** [comment]
This is the right thread (pls ignore my old one)

**Comment by ChipWolf** [comment]
We're only supporting mode 0 currently

**Comment by dajul123** [comment]
@ChipWolf I use mode 0

**Comment by dajul123** [comment]
these all normal settings, no special mod or something. (please stop closing my threads)
