### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by johannalc40** [instabot-py/instabot.py#1163]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MacOS High Sierra Version 10.13.3

## Python Version?
3

## Description

This is the error that I am getting. Can someone please help! Thanks

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/owner/Documents/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/owner/Documents/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/owner/Documents/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Owners-iMac:instabot.py-master Johanna$

**Comment by johannalc40** [comment]
Solved it.
As someone suggested:
For those who are running in mode 0 can do a temporarly fix by replacing line 300 from instabot.py

self.user_id = ui.get_user_id_by_login(self.user_login)

self.user_id = YOUR_USER_ID

if you dont know your user id you can get it from https://codeofaninja.com/tools/find-instagram-user-id
