### ISSUE TITLE
Instabot not working for me, i just stopped working?

### ISSUE THREAD

**Issue by Marten123123** [instabot-py/instabot.py#1168]
## Hosting
Local

#### Select one:
- [ ] Bug

### Operating System? (include version)
Windows

## Python Version?
3.6

## Description
I could run the bot perfectly up untill today, when i tried to run it this error shows after "python example.py" - which is when it starts logging in.

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\marti\Desktop\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\marti\Desktop\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\marti\Desktop\instabot.py-master\src\userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\marti\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Hope someone can help me

Kind regards
Martin

**Comment by andradjp** [comment]
I'm with same problem.

**Comment by Bl4ckFr0st** [comment]
Same problem

**Comment by ChipWolf** [comment]
Duplicate of #1153
