### ISSUE TITLE
Instabot user_blacklist error

### ISSUE THREAD

**Issue by sienika** [instabot-py/instabot.py#1190]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 10.13

## Python Version?
2.7

## Description

How do I specify user_blacklist correctly? Every time I put any username I get this:

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=[])
  File "/Users/annasienik/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.populate_user_blacklist()
  File "/Users/annasienik/Desktop/instabot.py-master/src/instabot.py", line 242, in populate_user_blacklist
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError

If I leave it blank the Instabot connects and starts liking instantly.

**Comment by nivong** [comment]
```
user_blacklist={'user1':'user2'},
```

**Comment by sienika** [comment]
Doesn't work.... The same error. Should I use instagram IDs or usernames?

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=[])
  File "/Users/***/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.populate_user_blacklist()
  File "/Users/***/Desktop/instabot.py-master/src/instabot.py", line 242, in populate_user_blacklist
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError

**Comment by matuella** [comment]
`ImportError: cannot import name JSONDecodeError`

"JSONDecodeError" was added after python 3.5 if I'm not mistaken.
Are you running on Python 2.7?
