### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by trapavellidon2x** [instabot-py/instabot.py#1211]
- [x] I have searched for other issues with the same problem. (including #1153)

- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 

## Python Version?
2 

## Description

Type the description of your issue here.

```
Traceback (most recent call last):
  File "example.py", line 53, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
  File "/Users/budstankz/Desktop/stinkisbotar/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/budstankz/Desktop/stinkisbotar/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/budstankz/Desktop/stinkisbotar/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by lebaratella** [comment]
I have the same problem

**Comment by igkmahesh** [comment]
i have the same issue

**Comment by ExoCode17** [comment]
I think it's the same for me..
`Traceback (most recent call last):
  File "C:\instabot.py-master\instabot.py\flygohr.py", line 54, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\instabot.py-master\instabot.py\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\instabot.py-master\instabot.py\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\instabot.py-master\instabot.py\src\userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\info\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\info\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\info\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

It's also happening to a friend of mine who sent me this screenshot:
![2018-04-18 08_38_39- 18 whatsapp](https://user-images.githubusercontent.com/13753044/38915510-4223014c-42e4-11e8-90df-2dfbabec6fb8.png)

**Comment by igkmahesh** [comment]
The issue is, the "info.text" is empty. Not sure how to fix it.

![image](https://user-images.githubusercontent.com/8609122/38915702-f6ddbe04-4327-11e8-8294-22c1d5f25782.png)

**Comment by igkmahesh** [comment]
i managed to fix this particular issue by doing below step. But not sure if it break later. At the moment it is working:

NOTE: I am not a python programmer, if anyone can fix this in a better way, please let us know.

Open the instabot.py file and go to around line 300 and hard code your instagram user name.

![image](https://user-images.githubusercontent.com/8609122/38916362-7720c186-432a-11e8-9bee-d68d2d4b87de.png)

**Comment by ValBerthe** [comment]
@igkmahesh it works. Apparently, the only purpose of this method is to log your user ID, so you can safely comment or erase that line.

**Comment by nellorocca** [comment]
Yes it works but it's not the best way to do it since the file instabot.py should be independent from your user id.

**Comment by oleharland** [comment]
Same issue also tried a few fixes before but they are raising more issues. Should be solved once.

**Comment by sagepierce** [comment]
not working for me

**Comment by CupCakeArmy** [comment]
Same here, running locally or on a server in docker.

Stack Trace:
```
instabot    | 18.04.2018_12:49 Instabot v1.2.0 started at 18.04.2018 12:49:
instabot    |
instabot    | 18.04.2018_12:49 Trying to login as xxxxxx...
instabot    |
instabot    | Traceback (most recent call last):
instabot    |   File "./app.py", line 8, in <module>
instabot    |     bot = InstaBot(**data)
instabot    |   File "/app/src/instabot.py", line 231, in __init__
instabot    |     self.login()
instabot    |   File "/app/src/instabot.py", line 300, in login
instabot    |     self.user_id = ui.get_user_id_by_login(self.user_login)
instabot    |   File "/app/src/userinfo.py", line 41, in get_user_id_by_login
instabot    |     all_data = json.loads(info.text)
instabot    |   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
instabot    |     return _default_decoder.decode(s)
instabot    |   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
instabot    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
instabot    |   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
instabot    |     raise JSONDecodeError("Expecting value", s, err.value) from None
instabot    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by budstankz** [comment]
anyone with a fix?

**Comment by budstankz** [comment]
anyone with a fix?

**Comment by budstankz** [comment]
i did the line 300 thing....

still get this Traceback (most recent call last):
  File "example.py", line 53, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
  File "/Users/budstankz/Desktop/stinkisbotar/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/budstankz/Desktop/stinkisbotar/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/budstankz/Desktop/stinkisbotar/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ajose19** [comment]
![captura de pantalla 2018-04-18 a la s 10 31 39 a m](https://user-images.githubusercontent.com/37116698/38938562-cb7f5e36-42f3-11e8-8824-c73076c72338.png)

**Comment by ajose19** [comment]
Logré solucionar este problema en particular haciendo el paso siguiente. Pero no estoy seguro de si se romperá más tarde. Por el momento está funcionando:

NOTA: No soy un programador de Python, si alguien puede arreglar esto de una mejor manera, por favor avísenos.

Abra el archivo instabot.py, vaya a la línea 300 y codifique el nombre de usuario de su instagram.

**Comment by ajose19** [comment]
![38916362-7720c186-432a-11e8-9bee-d68d2d4b87de](https://user-images.githubusercontent.com/37116698/38938619-f1f42222-42f3-11e8-8e37-fce5e3a629ef.png)

**Comment by sagepierce** [comment]
used fix by putting in user id in its numeric form worked for 10 minutes then insta shut down account completely, had to submit code, now insta is back up but I'm to scared to try again

**Comment by ajose19** [comment]
![captura de pantalla 2018-04-18 a la s 10 57 28 a m](https://user-images.githubusercontent.com/37116698/38940058-53c919d2-42f7-11e8-8e30-9f4092e4073a.png)

**Comment by ajose19** [comment]
ready!!!

**Comment by strivext** [comment]
@ajose19
Is it still working?

**Comment by strivext** [comment]
dont work.... fuck!!!!

**Comment by ajose19** [comment]
![captura de pantalla 2018-04-18 a la s 4 08 41 p m](https://user-images.githubusercontent.com/37116698/38955475-cbb1728e-4322-11e8-8d7c-209943e7e632.png)

**Comment by ajose19** [comment]
![captura de pantalla 2018-04-18 a la s 4 09 02 p m](https://user-images.githubusercontent.com/37116698/38955492-db83d09e-4322-11e8-8ba4-ccdcd216e43b.png)

**Comment by ajose19** [comment]
yes!!

**Comment by strivext** [comment]
@ajose19 Well, good luck. It does not work for me... :(

**Comment by ajose19** [comment]
![captura de pantalla 2018-04-18 a la s 4 16 26 p m](https://user-images.githubusercontent.com/37116698/38955878-e142cda4-4323-11e8-93e4-3259c2542d4f.png)

**Comment by ajose19** [comment]
work now!

**Comment by rugge89lau** [comment]
File "example.py", line 16, in <module>
    log_mod = 1)
  File "/Users/ruggero/Downloads/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/ruggero/Downloads/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/ruggero/Downloads/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mac-Pro-di-Ruggero:instabot.py-master ruggero$ 



so how can fix it?

**Comment by igkmahesh** [comment]
@rugge89lau you still have "**self.user_id = ui.get_user_id_by_login(self.user_login)**" in your instabot.py file. Please modify it to "**self.user_id = self.user_login**" 

so final code should be like this:

![image](https://user-images.githubusercontent.com/8609122/38961840-c9822c8e-43ad-11e8-8af6-3e11b9f1a533.png)

**Comment by rugge89lau** [comment]
it works, thank you!!

**Comment by wizardgandalf** [comment]
Ho to open instabot.py file?
He keeps saying instabot.py is a directory

**Comment by RPSPandora** [comment]
> Please modify it to "self.user_id = self.user_login"

it works, thank you!!

> Ho to open instabot.py file?

it's on **src** folder => src/instabot.py

**Comment by husligc** [comment]
Did the fix, but now the bot comments all of the comments on the same picture... Any idea how to fix this?

**Comment by javier2k2** [comment]
After change the line to"self.user_id = self.user_login"  I'm getting this error TabError: inconsistent use of tabs and spaces in indentation

**Comment by strivext** [comment]
OMG YESSSSSS work work work!!!!!  @igkmahesh  me hero :)

**Comment by andrewsegas** [comment]
Guys, here the get user info error is fixed
https://github.com/instabot-py/instabot.py/pull/1218

**Comment by andrewsegas** [comment]
you'll have problem with unfollow, i'm little bit busy, later i can fix it in instabot

**Comment by shashrvacai** [comment]
Maybe the prob has drifted a bit  .. I dont see the solution to  'No JSON object could be decoded' ..
also I tried the above solution about the .. It makes no difference in my error log.. it is consistent   - 


Traceback (most recent call last):
  File "code.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/cai/Documents/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/cai/Documents/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/cai/Documents/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
