### ISSUE TITLE
Failed to Login 

### ISSUE THREAD

**Issue by erictam96** [instabot-py/instabot.py#1216]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description

Type the description of your issue here.
I had follow the step from youtube, it will show trying to login as xxx, but after few seconds it prompt this error message
```
Include the contents of the error.log here (if applicable).
```
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "D:\Desktop\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "D:\Desktop\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "D:\Desktop\instabot.py-master\src\userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\erict\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\erict\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\erict\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kevin25** [comment]
The same issue for me 

> Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/homeassistant/.homeassistant/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/homeassistant/.homeassistant/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/homeassistant/.homeassistant/instabot.py/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by erictam96** [comment]
try this 
https://github.com/instabot-py/instabot.py/issues/1153

**Comment by erictam96** [comment]
i found this work for me  

For those who are running in mode 0 can do a temporarly fix by replacing line 300 from instabot.py

self.user_id = ui.get_user_id_by_login(self.user_login)

self.user_id = YOUR_USER_ID

if you dont know your user id you can get it from https://codeofaninja.com/tools/find-instagram-user-id

**Comment by andrewsegas** [comment]
Guys, here the get user info error is fixed
#1218

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
