### ISSUE TITLE
Bot starts up can't find media?

### ISSUE THREAD

**Issue by Therichiefleming** [instabot-py/instabot.py#1229]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MACos HighSierra 10.13.4

## Python Version?
Both

## Description

When I start up the bot, it logs me in successfully and likes 1 thing, then follows one person, then tries to do something else and gets caught up. Any suggestions? Here is my code:

```

python /Users/Richiemane/Desktop/instabot.py-master/example.py
Anonymous:~ Richiemane$ python /Users/Richiemane/Desktop/instabot.py-master/example.py
22.04.2018_12:27 Instabot v1.2.0 started at 22.04.2018 12:27:

22.04.2018_12:27 Trying to login as jdmbois...

22.04.2018_12:27 jdmbois login success!
22.04.2018_12:27 Get media id by tag: stance
22.04.2018_12:27 Removing already liked medias..
22.04.2018_12:27 Trying to like media: 1763234107310825928
22.04.2018_12:27 Liked: 1763234107310825928. Like #1.
22.04.2018_12:27 Trying to follow: 348389886
22.04.2018_12:27 Followed: 348389886 #1.
22.04.2018_12:27 jdmbois : Get media id on recent feed
 22.04.2018 12:27
22.04.2018_12:27 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
22.04.2018_12:28 jdmbois : Get media id on recent feed
 22.04.2018 12:28
22.04.2018_12:28 Except on get media!!
22.04.2018_12:28 ======> Get media id by Tag <======
22.04.2018_12:28 Get media by user success!
22.04.2018_12:28 Current Index = 28 of 61 medias
Traceback (most recent call last):
  File "/Users/Richiemane/Desktop/instabot.py-master/example.py", line 91, in <module>
    bot.new_auto_mod()
  File "/Users/Richiemane/Desktop/instabot.py-master/src/instabot.py", line 699, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/Users/Richiemane/Desktop/instabot.py-master/src/instabot.py", line 764, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/Users/Richiemane/Desktop/instabot.py-master/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/Users/Richiemane/Desktop/instabot.py-master/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/Users/Richiemane/Desktop/instabot.py-master/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/Users/Richiemane/Desktop/instabot.py-master/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/Users/Richiemane/Desktop/instabot.py-master/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
22.04.2018_12:28 Trying to unfollow: 348389886
22.04.2018_12:28 Unfollow: 348389886 #1 of 0.
22.04.2018_12:28 Pausing for 27 seconds... 1 of 0

```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
