### ISSUE TITLE
instabot Traceback (most recent call last):

### ISSUE THREAD

**Issue by NiPeters** [instabot-py/instabot.py#1236]
Traceback (most recent call last):
  File "C:\Users\NiPe\Downloads\instabot.py-master\example.py", line 53, in <module>
    unfollow_whitelist=[''])
  File "C:\Users\NiPe\Downloads\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\NiPe\Downloads\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\NiPe\Downloads\instabot.py-master\src\userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\NiPe\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\NiPe\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\NiPe\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Chukstart** [comment]
I have the same issue too...is there still no **solution**

**Comment by Chukstart** [comment]
If your running it in mode 0 you can do a temporary fix or so by replacing line 300 from insabot.py

- self.user_id = ui.get_user_id_login(self.user_login)

- self.user_id = YOUR_USER_ID
p.s you can get your user id from https://codeofaninja.com/tools/find-instagram-user-id

this solution was provided by Maty197 i just re-wrote it for you

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
