### ISSUE TITLE
name 'PROTOCOL_SSLv3' is not defined

### ISSUE THREAD

**Issue by mdrzn** [instabot-py/instabot.py#1237]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
Debian Jessie

## Python Version?
2.7

## Description

Type the description of your issue here.
Last time I started the bot was a couple weeks ago, it was working well, today I upgraded my Wheezy to Jessie, tried starting up the bot again, this happened:

```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/root/INSTAGRAM/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/root/INSTAGRAM/instabot.py/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/__init__.py", line 4, in <module>
    from fake_useragent.fake import FakeUserAgent, UserAgent  # noqa # isort:skip
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/fake.py", line 10, in <module>
    from fake_useragent.utils import load, load_cached, str_types, update
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 31, in <module>
    import gevent.socket
  File "/usr/lib/pymodules/python2.7/gevent/socket.py", line 788, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/usr/lib/pymodules/python2.7/gevent/ssl.py", line 422, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined
```

I'm using the same python version and everything from 30 minutes ago. Never had this issue before.

```
Include the contents of the error.log here (if applicable).
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
