### ISSUE TITLE
what's a fake_useragent anyway?? 

### ISSUE THREAD

**Issue by drovid** [instabot-py/instabot.py#1254]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [x ] Linux
- [ ] Android

## Python Version?
- [x ] 2.x
- [x ] 3.x

## Description of your issue

```
I keep getting the "no module named fake_useragent" error. And this happens on both Linux with python  2.7 and windows running python 3. Many others have the same issue but this one guy named chipwolf keeps closing every request mentioning it. What's happening? Is the project officially dead? why is this random chipwolf sabotaging any conversation taking place? ```


# Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="------------",
    password="--------",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")
```

**Comment by falconsmilie** [comment]
Running script on Raspberry Pi 3. I get this following error when running under Python 3.4.2. This error does not occur when run under python 2.7.9;

```Traceback (most recent call last):
  File "instaBotOne.py", line 6, in <module>
    from src import InstaBot
  File "/var/www/html/instagrambot/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/var/www/html/instagrambot/instabot.py/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named 'fake_useragent'


------------------
(program exited with code: 1)

**Comment by nivong** [comment]
@drovid why do you think there is an issue template? Please make use it and read what to do.

**Comment by drovid** [comment]
@nivong I did try to research and every time this issue is mentioned people just tell to install a pip fake useragent and chipwolf closes the issue

IT DOESN'T WORK

**Comment by falconsmilie** [comment]
@nivong so where's the link to the issue thread O.o

**Comment by drovid** [comment]
@falconsmilie because he's talking out of his ass. 

still haven't found solution by the way

**Comment by bodeezl** [comment]
@drovid did you install the requirements?

pip install -r requirements.txt

**Comment by Empty2k12** [comment]
Run
> pip3 install wheel
> pip3 install -r requirements.txt

**Comment by drovid** [comment]
@bodeezl @Empty2k12 gonna try that right now

**Comment by joby8** [comment]
I have got the same problem by the way. It sucks.

**Comment by bodeezl** [comment]
@drovid you need to be in the main directory where the requirements.txt is at when running that command.....

**Comment by drovid** [comment]
@bodeezl what do u mean main directory? I'm in ~/

**Comment by bodeezl** [comment]
@drovid what folder is the bot in, go to that folder, it should have example.py and requirements.txt in there, thats the main folder. if you dont have requirements.txt in the folder you are in the wrong place.
