### ISSUE TITLE
Crashes after trying to login

### ISSUE THREAD

**Issue by ill3r** [instabot-py/instabot.py#1272]
Hello everybody!
I am having an issue with the instabot. It opens up, tries to login and then crashes. any ideas? 

09.05.2018_18:20 Instabot v1.2.62 started at 09.05.2018 18:20:

09.05.2018_18:20 Trying to login as XXXX...

Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\Photo\BOT\instabot.pyV2-masterv2\instabot.pyV2-masterv2\example.py", line 44, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\DELL\Desktop\Photo\BOT\instabot.pyV2-masterv2\instabot.pyV2-masterv2\src\instabot.py", line 227, in __init__
    self.login()
  File "C:\Users\DELL\Desktop\Photo\BOT\instabot.pyV2-masterv2\instabot.pyV2-masterv2\src\instabot.py", line 296, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\DELL\Desktop\Photo\BOT\instabot.pyV2-masterv2\instabot.pyV2-masterv2\src\userinfo.py", line 44, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>>

**Comment by d1slact0r** [comment]
Please close your issue and reopen one with the correct templated filled in.

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
