### ISSUE TITLE
Bot stoped working after 1.2 minutes

### ISSUE THREAD

**Issue by raw-sun** [instabot-py/instabot.py#1279]
#### Select one:
 Bug

### Operating System? (include version)
Windows

## Python Version?
3.x

## Description of your issue

```
Bot is running successfully but only for 1 minute and in this 1-minute Bot unfollows one person and liked one post and after that, it stopped

Following error is showing:-

 16.05.2018 14:52
16.05.2018_14:52 Except on get media!!
16.05.2018_14:52 ======> Get media id by Tag <======
16.05.2018_14:53 Get media by user success!
16.05.2018_14:53 Current Index = 52 of 63 medias
Traceback (most recent call last):
  File "example.py", line 95, in <module>
    bot.new_auto_mod()
  File "C:\Users\ASUS\Desktop\instabot.py-master\src\instabot.py", line 700, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\ASUS\Desktop\instabot.py-master\src\instabot.py", line 765, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "C:\Users\ASUS\Desktop\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "C:\Users\ASUS\Desktop\instabot.py-master\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "C:\Users\ASUS\Desktop\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\ASUS\Desktop\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\ASUS\Desktop\instabot.py-master\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
16.05.2018_14:53 Trying to unfollow: 3282629734
16.05.2018_14:53 Unfollow: 3282629734 #1 of 0.
16.05.2018_14:53 Pausing for 25 seconds... 1 of 0
16.05.2018_14:53 Logout: likes - 0, follow - 0, unfollow - 1, comments - 0.
16.05.2018_14:53 Bot work time: 0:01:20.915469
16.05.2018_14:53 Logout success!


Can anybody tell me how can I fix this problem ??

**Comment by Empty2k12** [comment]
I think Instagram changed the API again, looks like the bot is trying to access some key (`KeyError: 'likes'`) in the response which was (re)moved. We need to wait a couple hours/days until someone figures out a solution.

**Comment by raw-sun** [comment]
it is a problem with everyone or it is just me ??

**Comment by reliefs** [comment]
everyone

**Comment by siddyyagno3** [comment]
any solution

**Comment by reliefs** [comment]
I fixed it, but only mode 1
https://github.com/reliefs/instabot.py

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
