### ISSUE TITLE
Can't seem to get this working!

### ISSUE THREAD

**Issue by sjuniorbrown** [instabot-py/instabot.py#1293]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
I can't seem to run the code when I put in all of my details I get this:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Junior\Documents\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Junior\Documents\instabot.py-master\src\instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "C:\Users\Junior\Documents\instabot.py-master\src\userinfo.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Hopefully you guys can help me out!
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by almaromr** [comment]
solved, thank you very much for the help

**Comment by QuinnGunter** [comment]
I am having the same issue. How did you solve this @almaromr?

**Comment by napolux** [comment]
Did you run: `pip install -r requirements.txt`???

**Comment by sjuniorbrown** [comment]
@napolux  I attempted this but it said:

pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pip install -r requirements.txt
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by sjuniorbrown** [comment]
@napolux I have installed the requirements but it is still giving me the same message. Do you have any idea on how to solve this issue?
