### ISSUE TITLE
Doesn't seem to be working 23.05.2018

### ISSUE THREAD

**Issue by Tigerkid142** [instabot-py/instabot.py#1294]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [x ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue
I am not really familiar with the current software or setup. The last time I used this instabot was in 2017 and it worked perfectly. I have now deleted all the content from back then and updated the software and code as instructed in the description. Any help would be greatly appreciated. 
```
Include the contents of the error.log here (if applicable). < \Downloads\instabot.py-master\instabot.py-master>python example.py
23.05.2018_23:38 Instabot v1.2.0 started at 23.05.2018 23:38:

23.05.2018_23:38 Trying to login as _______...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\_______\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\_______\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\_______\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\_______\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Robcis** [comment]
Same here. I get the same error when starting the bot. On top of it, Instagram locks me out as soon as I attempt to log in with Instabot saying that it detected suspicious activity.

**Comment by rugge89lau** [comment]
same here

**Comment by gbergna2009** [comment]
For me (WINDOWS) now it works with this solution: https://github.com/instabot-py/instabot.py/issues/1287

Doesn't work with MAC

**Comment by Buck86** [comment]
I re-downloaded and applied this fix https://github.com/instabot-py/instabot.py/pull/1292/files
Didnt work when I modified my already modified instabot.py

**Comment by Robcis** [comment]
I managed to fix it on my MacBook by updating Python to the newest version (3.6.5) and installed all of the requirements for the bot as well as well. Using pip3 and python3 commands in the terminal are essential. Version 2.7, that comes with Mac, somehow doesn't work.

**Comment by thecompix** [comment]
same here.

**Comment by Curtis777** [comment]
samer here....
My bot ran for weeks ... and i nedded to restart my pc and wanted to restart the bot and got this error

**Comment by marcinex** [comment]
I have the same issue ...

**Comment by dominobullo** [comment]
Same here...

**Comment by kreicmaneilze** [comment]
I am getting this same error. Anybody know how to fix this?

**Comment by unlimitedSAM** [comment]
Same issue on Linux.

Fixed with :
- Clone the repository again
- Apply the fix https://github.com/instabot-py/instabot.py/pull/1292/files

**Comment by AizenSousuke** [comment]
with unlimitenSAM's fix and reclone, only mode 0 works. Other mode gave an exception

**Comment by kreicmaneilze** [comment]
@unlimitedSAM Could you please explain how to apply this, I am having some troubles, would be great? :)

**Comment by unlimitedSAM** [comment]
@kreicmaneilze you must modify the file instabot.py on line 283 : 

**delete**       _self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})_
**ADD**        csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
**ADD**        self.s.headers.update({'X-CSRFToken': csrf_token})

**Comment by kreicmaneilze** [comment]
@unlimitedSAM Oh I just could not find the right file, found it! And how did you clone it? Just copied another instabot.py file and uploaded to the same folder or downloaded another zip from git? 🤔

**Comment by unlimitedSAM** [comment]
@kreicmaneilze I've cloned the entire repository to be sure to have a stable version

**Comment by kreicmaneilze** [comment]
@unlimitedSAM OMG it worked on MACBOOK! Thank you!
For those who are having the same issues my steps:
1. I got the GitHub Desktop / downloaded this repsitory
2. Cloned it
3. Changed the instagram.py files code starting from line 283 with the mentioned one above
4. Saved it and it launched Successfully 🙂 🤓

**Comment by thatazoreanguy** [comment]
I'm on Windows and applying the aforementioned [fix](https://github.com/instabot-py/instabot.py/pull/1292/files) after reinstalling the latest version of Python (as I write this, it's _3.6.5_) and downloading Instabot.py again fixed it. 😄 

#1292 👍

**Comment by rugge89lau** [comment]
what you mean with clone the repository? i've just modify the instabot.py line 283 and don't recognize the name "re"

**Comment by marcinex** [comment]
Try to do what @kreicmaneilze said. It must working. If not - You did sth wrong. Re should be imported at beginning of files.

**Comment by rugge89lau** [comment]
ok, but i don't get this points: 
1 I got the GitHub Desktop / downloaded this repsitory
2 Cloned it

**Comment by marcinex** [comment]
Simply delete all files (except this with configuration) and then just git clone repository or download files if You are using windows.

**Comment by rugge89lau** [comment]
it works. Thanks

**Comment by giulianoporro** [comment]
Do we have any solution for Mac users?

**Comment by mrm15** [comment]
@unlimitedSAM 

""           you must modify the file instabot.py on line 283 :

delete self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
ADD csrf_token = re.search('(?<="csrf_token":")\w+', r.text).group(0)
ADD self.s.headers.update({'X-CSRFToken': csrf_token})     ""


it worked.  thanks  alot

**Comment by kinggsidd** [comment]
@mrm15 I know this might sound a bit retarded, but what file do i change that in exactly? i keep getting this following error:



Traceback (most recent call last):
File "example.py", line 52, in 
unfollow_whitelist=['example_user_1', 'example_user_2'])
File "/Users/WineConverterMS/Desktop/instabot.py-master/src/instabot.py", line 232, in init
self.login()
File "/Users/WineConverterMS/Desktop/instabot.py-master/src/instabot.py", line 283, in login
self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 329, in getitem
return self._find_no_duplicates(name)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by kinggsidd** [comment]
@unlimitedSAM Without sounding a bit retarded could you elaborate which file etc please? I keep getting stuck on this error: i'm trying to do it on my mac/windows virtual machine but get this.



Traceback (most recent call last):
File "example.py", line 52, in 
unfollow_whitelist=['example_user_1', 'example_user_2'])
File "/Users/WineConverterMS/Desktop/instabot.py-master/src/instabot.py", line 232, in init
self.login()
File "/Users/WineConverterMS/Desktop/instabot.py-master/src/instabot.py", line 283, in login
self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 329, in getitem
return self._find_no_duplicates(name)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by kreicmaneilze** [comment]
@kinggsidd there is SRC folder in there you can find the file - instagram.py file

There you have to change the code to this:
https://github.com/instabot-py/instabot.py/pull/1292/files

**Comment by kinggsidd** [comment]
Okay now i'm getting this error. But i think its my fault i'm slightly confused that i have probably added the new code wrong, this is the error im getting;


Sidorels-MacBook-Pro:instabot.py SidKing$ python example.py

Traceback (most recent call last):

  File "example.py", line 6, in <module>

    from src import InstaBot

  File "/Users/SidKing/Desktop/instabot.py/src/__init__.py", line 1, in <module>

    from .instabot import InstaBot

  File "/Users/SidKing/Desktop/instabot.py/src/instabot.py", line 282

    r = self.s.get(self.url)

    ^

IndentationError: unexpected indent

Sidorels-MacBook-Pro:instabot.py SidKing$

Sorry about this! Hope im not being a bother!


________________________________

**Comment by twont** [comment]
Thanks @marcinex - forgot about that!

**Comment by twont** [comment]
@kinggsidd - there's some misalignment with the spaces at the start of your lines by the looks of it. You can overwrite them with spaces so that they were as they were - or alternatively re-download the instabot.py file

**Comment by kreicmaneilze** [comment]
Yeah, be carefull if you have some spaces in places where it is not needed. I had the same problem until I realized it!

**Comment by kinggsidd** [comment]
I think it’s because somebody offered a solution to replace a bit of code but I must of replaced it incorrectly! Thanks for the advice I’m going to give a shot

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
