### ISSUE TITLE
Errors cant connect properly 

### ISSUE THREAD

**Issue by FabWine** [instabot-py/instabot.py#1305]
Got this lines appearing - thanks a lot for your help

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/WineConverterMS/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/WineConverterMS/Desktop/instabot.py-master/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by olaims** [comment]
downloaded from 0 and I get this,

    from .instabot import InstaBot
  File "/home/pi/Desktop/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named 'fake_useragent'

**Comment by JohnsonHH** [comment]
@olaims You need to install the requirements.txt

pip install -r requirements.txt

**Comment by FabWine** [comment]
Done already - tried again - having the same lines

**Comment by sayuri399** [comment]
I download the requirements, still same error?

Any solution?

**Comment by FabWine** [comment]
Did some changes but now I'm having

File "/Users/TheMinion/Desktop/instabot.py-master/example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/TheMinion/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/TheMinion/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/TheMinion/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests

**Comment by kinggsidd** [comment]
@olaims If the command "Pip" doesn't work, try specifying which version of "Pip" you have so "Pip2" or "Pip3" the best thing to do is just update pip to the latest version using "Pip2" install --upgrade pip"
