### ISSUE TITLE
bot shuts down

### ISSUE THREAD

**Issue by kismet123** [instabot-py/instabot.py#1313]
When i run the bot it logs in and then there is a bunch of text that comes into the screen and then it shuts down.

I am not able to see what shows up or what the error could be before it shuts down.

any suggestions?

**Comment by olivierognn** [comment]
Yes, same problem here

**Comment by Francislume** [comment]
Yes, same problem here

**Comment by jjfriend** [comment]
use mode 0

**Comment by Francislume** [comment]
when I open the text editor in python it signals me an error:
  {
"resource": "/C:/Users/pc/Desktop/instabot.py-master/example.py",
"owner": "python",
"code": "F0002",
"severity": 8,
"message": "F0002: <class 'RuntimeError'>: generator raised StopIteration",
"source": "pylint",
"startLineNumber": 1,
"startColumn": 1,
"endLineNumber": 1,
"endColumn": 1
}
Can somebody help me? before it worked well.

**Comment by kismet123** [comment]
This error is occurring in mode 0

**Comment by Francislume** [comment]
Forgive, but like everyone else and in all of them I get the same. It closes as I open it. Could you explain to me what I should do?
08.06.2018_23:01 Trying to login as $$$$$$
Traceback (most recent call last):
  File "fran.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\pc\Desktop\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\pc\Desktop\instabot.py-master\src\instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by kinggsidd** [comment]
Hey francislume, that issues is to do with cookies, if you search the repository you should see the fix posted by someone, sorry I can’t give you the exact number of the fix as I am at work,

But look around for the cookies fix and apply it should work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Francislume** [comment]
thank you very much for your help. I found it and it's running again. thanks mate!

**Comment by twont** [comment]
@kismet123 @olivierognn  @Francislume 
Provided you're running on windows, you can drag scripts into cmd prompt, and can press enter to run them. 

If they ever bug out the script will just stop rather than the window closing, meaning you can see what caused the error.

**Comment by BrandonPrince** [comment]
Hi @Francislume Francislume. Would you please be able to assist me with the fix for this problem?
