### ISSUE TITLE
Cookie problems

### ISSUE THREAD

**Issue by brtzli** [instabot-py/instabot.py#1317]
Hello.
When I try to run the script this is what is showed.
I found out on the internet it's a cookie problem.
How could I solve this? Thanks.

Traceback (most recent call last):
  File "C:\Users\Luca\Desktop\instabot.py-master\example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Luca\Desktop\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\Luca\Desktop\instabot.py-master\src\instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Luca\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
>>>

**Comment by s1nn3r** [comment]
The same for me.

**Comment by kinggsidd** [comment]
Fix to this has already been applied, but double check.

After i applied the fix i got another 3 errors, so i'm a bit stuck myself.

**Comment by Eggwise** [comment]
Bug still occurs.
What was the fix?

**Comment by Eggwise** [comment]
https://github.com/instabot-py/instabot.py/pull/1292

This PR fixxes it

Merge! 👍

**Comment by mventer9** [comment]
Hi, i'm having same problem, followed the PR and still having the same problem...
![mk](https://user-images.githubusercontent.com/40006582/41064416-5f83b16c-69d3-11e8-8b95-760acc6cc821.png)
![python](https://user-images.githubusercontent.com/40006582/41064417-5fa31552-69d3-11e8-9b93-dd1389095797.png)

**Comment by errorerror0161** [comment]
this fixes it 
https://github.com/instabot-py/instabot.py/commit/ba0fe9e5f37cddc3a42fed66994102e6dbc39643
