### ISSUE TITLE
Bot can't login anymore, keep getting the same error message

### ISSUE THREAD

**Issue by 1993henkpiet** [instabot-py/instabot.py#1321]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

When trying to execute the bot after a Windows reboot it often doesn't work anymore. Usually redownloading the instabot and filling in my own data again fixes it, but this time I keep getting the same error message. Which is shown below.

Does anyone know how to fix this? It's driving me crazy to say the least. Hope somebody can help me out!

```

## Config

```
06.06.2018_23:53 Instabot v1.2.0 started at 06.06.2018 23:53:

06.06.2018_23:53 Trying to login as -my username-...

Traceback (most recent call last):
  File "C:\Downloads\instabot.py-master (6)\instabot.py-master\example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Downloads\instabot.py-master (6)\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Downloads\instabot.py-master (6)\instabot.py-master\src\instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\Henk\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Henk\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
>>> 
```

**Comment by andrste** [comment]
Have the same issue ...

**Comment by Bryanetchegaray** [comment]
Hi there ! Got the same issue, is the bot down ?

**Comment by andrste** [comment]
For some users it working ... I don't know what I am doing wrong. I installed & configured like in youtube video...

**Comment by kinggsidd** [comment]
Guys, that error has already been resolved take a look at the thread. Something to do with the cookies if I remember correctly!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kinggsidd** [comment]
If you keep persisting to receive error codes try uninstalling python 3 and install python 2.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andrste** [comment]
I tried with 3 and 2 versions of python nothing working...

**Comment by kinggsidd** [comment]
Guys look I know you might be new to this but you will find out the hard way that just posting for help usually doesn’t get you any.

The error you have posted has already been fixed and applied and I can confirm, I can’t tag you on the exact link of the fix as I am at work, but if you search the repository you should be able to find it. The most I can help you at the moment is that it’s a cookie issue so look for the cookie fix!

Hope that helps

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andrste** [comment]
@kinggsidd it works!!! thank you so much! 

Link for fix: https://github.com/instabot-py/instabot.py/pull/1292/commits/ba0fe9e5f37cddc3a42fed66994102e6dbc39643

**Comment by kinggsidd** [comment]
@andrste Was it the cookie fix just to confirm?

No problem! Sorry I couldn’t give you the link to it earlier I was at work and it’s hard for me to navigate it on my iPhone.

Post a screenshot of it working if you don’t mind :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andrste** [comment]
@kinggsidd Yup, you directed me to the right way! No problem thank you for your help! But after this issue fixed. I got another problem. It logs in but after that it shows error:

07.06.2018_18:54 Current Index = 15 of 70 medias
Traceback (most recent call last):
  File "example.py", line 94, in <module>
    bot.new_auto_mod()
  File "/Users/Username/Desktop/instabot.py-master/src/instabot.py", line 701, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/Users/Username/Desktop/instabot.py-master/src/instabot.py", line 766, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/Users/Username/Desktop/instabot.py-master/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/Users/Username/Desktop/instabot.py-master/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/Users/Username/Desktop/instabot.py-master/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/Users/Username/Desktop/instabot.py-master/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/Users/Username/Desktop/instabot.py-master/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'

**Comment by errorerror0161** [comment]
https://github.com/instabot-py/instabot.py/commit/ba0fe9e5f37cddc3a42fed66994102e6dbc39643
this worked for me
