### ISSUE TITLE
KeyError: 'likes' 

### ISSUE THREAD

**Issue by andrste** [instabot-py/instabot.py#1322]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

The issue is with mode = 2, Tried with mode = 0, all works perfect.

```
Username-MBP:instabot.py-master Username$ python2 example.py
07.06.2018_18:53 Instabot v1.2.0 started at 07.06.2018 18:53:

07.06.2018_18:53 Trying to login as ig_username...

07.06.2018_18:53 ig_username login success!
07.06.2018_18:53 Get media id by tag: beauty
07.06.2018_18:53 Removing already liked medias..
07.06.2018_18:53 Trying to like media: 1796561301750489001
07.06.2018_18:53 Liked: 1796561301750489001. Like #1.
07.06.2018_18:53 Trying to follow: 2541501372
07.06.2018_18:53 Followed: 2541501372 #1.
07.06.2018_18:53 ig_username : Get media id on recent feed 
 07.06.2018 18:53
07.06.2018_18:53 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
07.06.2018_18:54 ig_username : Get media id on recent feed 
 07.06.2018 18:54
07.06.2018_18:54 Except on get media!!
07.06.2018_18:54 ======> Get media id by Tag <======
07.06.2018_18:54 Get media by user success!
07.06.2018_18:54 Current Index = 15 of 70 medias
Traceback (most recent call last):
  File "example.py", line 94, in <module>
    bot.new_auto_mod()
  File "/Users/Username/Desktop/instabot.py-master/src/instabot.py", line 701, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/Users/Username/Desktop/instabot.py-master/src/instabot.py", line 766, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/Users/Username/Desktop/instabot.py-master/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/Users/Username/Desktop/instabot.py-master/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/Users/Username/Desktop/instabot.py-master/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/Users/Username/Desktop/instabot.py-master/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/Users/Username/Desktop/instabot.py-master/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
07.06.2018_18:54 Trying to unfollow: 2541501372
07.06.2018_18:54 Unfollow: 2541501372 #1 of 0.
07.06.2018_18:54 Pausing for 19 seconds... 1 of 0
07.06.2018_18:54 Logout: likes - 1, follow - 0, unfollow - 1, comments - 0.
07.06.2018_18:54 Bot work time: 0:01:10.340254
07.06.2018_18:54 Logout success!
```

## Config

```
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="username",
    password="password",
    like_per_day=800,
    comments_per_day=0,
    tag_list=['beauty'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=150,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=250,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")
```

**Comment by andrste** [comment]
This issus occurs when I use Mode = 2.

**Comment by jjfriend** [comment]
use mode 0, i find errors with mode 2

**Comment by aferook** [comment]
If you want hotfix and quick fix, it's in #1331

**Comment by SpaceSheepli** [comment]
Hey there. You should just replace the _instabot.py_ with this file: https://uploadfiles.io/iy1qb

**Comment by Conikalpha** [comment]
@SpaceSheepli can share the file again please?
i have the same error

**Comment by SpaceSheepli** [comment]
@Conikalpha Watch here: [](https://pastebin.com/psMz9ts8) But i don't know if it's the right one... Write me back if it doesen't work!

**Comment by kostasosfp** [comment]
have you fixed this issue?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
