### ISSUE TITLE
Several lines have errors to which i can not get around, STOCK EVERYTHING, I've only put in username and password. SEE ERROR CODE BELOW.

### ISSUE THREAD

**Issue by errorerror0161** [instabot-py/instabot.py#1327]
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue

```
Traceback (most recent call last):
  File "c:/Users/user/Downloads/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['k.n.t.m.l.n.'])
  File "c:\Users\user\Downloads\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "c:\Users\user\Downloads\instabot.py-master\src\instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

## Config

```
Complete stock configuration, only inputted username and password.
```

any help will be greatly appreciated.

**Comment by kinggsidd** [comment]
Hello bro, you seem to be having the same issue a lot of other people are, there is a fix for this and I can confirm it works.

You need to search the repository for the “cookies” or “token” fix. Find the cookies fix and apply it and it should work!

Let me know if you have any issues, also try python2 instead of python3 if you have it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by errorerror0161** [comment]
I'm glad you're helping man, where can I find the 'repository for the “cookies” or “token” fix'.

**Comment by errorerror0161** [comment]
https://github.com/instabot-py/instabot.py/commit/ba0fe9e5f37cddc3a42fed66994102e6dbc39643
this worked

**Comment by kinggsidd** [comment]
No problem brother I do what I can/know!

I think it’s number #1287 the fix. But I’m not 100% sure. I can’t check because I am at work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
