### ISSUE TITLE
Mode 5 error - 

### ISSUE THREAD

**Issue by jeo96x** [instabot-py/instabot.py#1338]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x? ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue

```
C:\Users\Jack\Desktop\insta>python example.py
11.06.2018_20:06 Instabot v1.2.0 started at 11.06.2018 20:06:

11.06.2018_20:06 Trying to login as user...

11.06.2018_20:06 user login success!
11.06.2018_20:06 user : Get media id on recent feed
 11.06.2018 20:06
11.06.2018_20:06 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
11.06.2018_20:06 user: Get media id on recent feed
 11.06.2018 20:06
11.06.2018_20:06 Except on get media!!
11.06.2018_20:07 ======> Get media id by Tag <======
11.06.2018_20:07 Get media by user success!
11.06.2018_20:07 Current Index = 0 of 49 medias
Traceback (most recent call last):
  File "example.py", line 108, in <module>
    unfollow_protocol(bot)
  File "C:\Users\Jack\Desktop\insta\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "C:\Users\Jack\Desktop\insta\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "C:\Users\Jack\Desktop\insta\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\Jack\Desktop\insta\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\Jack\Desktop\insta\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
11.06.2018_20:07 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
11.06.2018_20:07 Bot work time: 0:00:54.627883
11.06.2018_20:07 Logout success!


***user is my username***
another error on mode 0 which i think is similar that it cant find anyone to unfollow with over 500 followers on the account
## Config

```
Include the contents of your config here - standard config - just insterted the line of codes that needed replacing in instabot.py and added account name and password...

**Comment by Petronium37** [comment]
I have the same issue

**Comment by tayloriuss** [comment]
have the same problem. does anny one have a fix?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
