### ISSUE TITLE
11.June, not working (KeyError and so on)

### ISSUE THREAD

**Issue by Pleasehelpmee** [instabot-py/instabot.py#1339]
11.06.2018_22:02 Trying to login as ***...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/***/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/***/Desktop/instabot.py-master/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
***-MacBook-Pro:instabot.py-master ***$ 

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.6

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by jeo96x** [comment]
https://github.com/instabot-py/instabot.py/commit/ba0fe9e5f37cddc3a42fed66994102e6dbc39643 

try that

**Comment by Gradonsky** [comment]
I got the same error, @jeo96x the solution didn't worked :/

**Comment by Lefedyo** [comment]
Same problem

**Comment by jeo96x** [comment]
https://github.com/instabot-py/instabot.py/issues/1336 working apparently, im running mine after changing that line in instabot.py and it is working with no issue (only mode 0 is without issue)

**Comment by dzsniper707** [comment]
i dont know what's wrong with this bot every time we get a new error, i think the fixes doesn't work with everyone here, this what i got recently after i updated the instapy file

Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\instabot.py-master\example.py", line 52, in <modu
le>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\ADMIN\Desktop\instabot.py-master\src\instabot.py", line 226, in
 __init__
    self.login()
  File "C:\Users\ADMIN\Desktop\instabot.py-master\src\instabot.py", line 296, in
 login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\ADMIN\Desktop\instabot.py-master\src\userinfo.py", line 41, in
get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Python34\Lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\Lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\Lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

someone help ..

**Comment by focamonca** [comment]
I'm getting this error: http://prntscr.com/juig28
