### ISSUE TITLE
Bot stopt to fast

### ISSUE THREAD

**Issue by joost-heijden** [instabot-py/instabot.py#1342]
When i use the instabot, it stops very fast. Anyone knows why?

Traceback (most recent call last):
  File "example.py", line 68, in <module>
    bot.new_auto_mod()
  File "/Users/joost/Desktop/instabot.py-master/src/instabot.py", line 697, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/joost/Desktop/instabot.py-master/src/instabot.py", line 765, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "/Users/joost/Desktop/instabot.py-master/src/instabot.py", line 788, in check_exisiting_comment
    check_comment = self.s.get(url_check)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /p/Bj9hVMjjoCc/?__a=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x102e561d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
