### ISSUE TITLE
X-CSRFToken error

### ISSUE THREAD

**Issue by faughnn** [instabot-py/instabot.py#1351]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [x] 3.x

## Description of your issue

```
Getting this error when I try run the program. This was working for me fine a year ago. I have tried with python 2.7 and 3 on windows and RHEL7.3


18.06.2018_23:18 Instabot v1.2.0 started at 18.06.2018 23:18:

18.06.2018_23:18 Trying to login as xxxxxxxxxxxx...

Traceback (most recent call last):
  File "C:\Users\NF\Desktop\instabot.py-master\example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\NF\Desktop\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\NF\Desktop\instabot.py-master\src\instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\NF\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\NF\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

**Comment by informagico** [comment]
Instagram does not use anymore cookies like this, it store it in a script.
As a temporary workaround you need to change line 283 of src/instabot.py from
`self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})`
to
`csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})`

to make it work again.

**Comment by Gradonsky** [comment]
@informagico  still the same error :/
