### ISSUE TITLE
Bot not logging in mac osx KeyError: "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by Jonasipsen** [instabot-py/instabot.py#1358]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x ] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x ] 2.x
- [ ] 3.x

## Description of your issue
doesnt log in...
```
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/JonasIpsen/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/JonasIpsen/Desktop/instabot.py-master/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
Jonas-MBP:instabot.py-master JonasIpsen$ start
-bash: start: command not found
Jonas-MBP:instabot.py-master JonasIpsen$  < REPLACE THIS TEXT
```

## Config

```
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/JonasIpsen/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/JonasIpsen/Desktop/instabot.py-master/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
Jonas-MBP:instabot.py-master JonasIpsen$ start
-bash: start: command not found
Jonas-MBP:instabot.py-master JonasIpsen$ 
```

**Comment by errorerror0161** [comment]
I've had the same issue for a while now.
