### ISSUE TITLE
Bot shut down after trying to login

### ISSUE THREAD

**Issue by McSteroids** [instabot-py/instabot.py#1365]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by McSteroids** [comment]
Error.txt is empty

**Comment by McSteroids** [comment]
Any Help`?

**Comment by McSteroids** [comment]
C:\>C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\luxurybrandgang1312.py
Traceback (most recent call last):
  File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\luxurybrandgang1312.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\instabot.py", line 5, in <module>
    from .unfollow_protocol import unfollow_protocol
  File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\unfollow_protocol.py", line 7, in <module>
    from .follow_protocol import follow_protocol
  File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\follow_protocol.py", line 6, in <module>
    from .feed_scanner import feed_scanner
  File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\feed_scanner.py", line 6, in <module>
    from .likers_graber_protocol import likers_graber_protocol
  File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\likers_graber_protocol.py", line 8, in <module>
    from .user_feed import get_media_id_user_feed
  File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\user_feed.py", line 7, in <module>
    from .user_info import get_user_info
ImportError: cannot import name 'get_user_info'

**Comment by McSteroids** [comment]
Any help`?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
