### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by itsmariusm** [instabot-py/instabot.py#1366]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
KeyError: "name='csrftoken', domain=None, path=None"
```
Include the contents of the error.log here (if applicable). < 26.06.2018_13:24 Trying to login as username...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Marius Migles\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\Marius Migles\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\Marius Migles\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Marius Migles\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

## Config
Basic..just downloaded it.
```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < !/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="",
    password="",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by capttaddel** [comment]
also got the same problem

**Comment by kinggsidd** [comment]
same


________________________________

**Comment by rogribas** [comment]
same

**Comment by deanainsworth** [comment]
Me too...

**Comment by m24w24** [comment]
same

**Comment by damiafuentes** [comment]
same

**Comment by damiafuentes** [comment]
Just change the line 283 on instabot.py

`self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
`

for:

```
csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})
```

**Comment by deanainsworth** [comment]
Amazing, thank you, all working here!

**Comment by bwdmerlin** [comment]
Sorry if this is stupid but where do I find instabot.py? the only .py file I can see is the example.py but there I can´t find the line or code you refer to.

**Comment by bwdmerlin** [comment]
Here too, thanks!

**Comment by capttaddel** [comment]
still not working :/

**Comment by itsmariusm** [comment]
still not working... @damiafuentes

**Comment by itsmariusm** [comment]
After the edit: csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})


got this now:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Marius Migles\Downloads\instabot\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Marius Migles\Downloads\instabot\src\instabot.py", line 283
    csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)self.s.headers.update({'X-CSRFToken': csrf_token})
                                                                           ^
SyntaxError: invalid syntax

**Comment by damiafuentes** [comment]
@itsmariusm 

I wrote this:
```
csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})
```

You wrote this:
```
csrf_token = re.search('(?<="csrf_token":")\w+', r.text).group(0)self.s.headers.update({'X-CSRFToken': csrf_token})
```

My code is 2 lines, yours is 1 line.

**Comment by aekramer** [comment]
@damiafuentes I updated my lines to yours and the issue remained, I am wondering though because I have (as you said):
`self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})`
Replaced with your lines, but a few lines below that I also have
`self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
        self.csrftoken = login.cookies['csrftoken']`

This should be left alone?

To really get my annoyance levels up: This bot has been running fine for weeks, I just stopped it and wanted to put in different credentials of another account, and it did not work. (KeyError: "name='csrftoken', domain=None, path=None") now I did not edit any code, so my assumption would be if I changed back to the previous account it should still work. But it does not work for that account either now.
Why is this happening? It has ran fine for the past week and a half

**Comment by acollamat** [comment]
It doesn't work for me. Hope anyone can update the repo.

**Comment by Adriang71** [comment]
Yeap confirmed the solution.

**Comment by rugge89lau** [comment]
after fix of damiafuentes i got this error:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/ruggero/Downloads/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/ruggero/Downloads/instabot.py-master/src/instabot.py", line 288
    self.s.headers.update({'X-CSRFToken': csrf_token})
                                                     ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by alex-s435** [comment]
rugge89lau the same

**Comment by alex-s435** [comment]
@rugge89lau the same and was also on line 287 not 283
have you solve it???

**Comment by rugge89lau** [comment]
yes, just retry after a clean download :) and say: "was me" on instagram report
