### ISSUE TITLE
just downloaded as not used in a while and wont work

### ISSUE THREAD

**Issue by lgwjames** [instabot-py/instabot.py#1369]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ x] 2.x
- [ ] 3.x

## Description of your issue

installed requirements and when i run it wont load

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```
Traceback (most recent call last):
  File "/Users/Quad-Core/Desktop/instabot.py-master 4/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/Quad-Core/Desktop/instabot.py-master 4/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/Quad-Core/Desktop/instabot.py-master 4/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimabondz** [comment]
same problem here
anyone has a fix for this?
