### ISSUE TITLE
invalid sintax

### ISSUE THREAD

**Issue by irenecanorod** [instabot-py/instabot.py#1373]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
File "example.py" , line 53
    while True:
invalid sintax
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

its my first time on phyton i dont understand anything, i just had the problems with the unfollow whitelist and i read that i have to erase all the line now they told me that.

**Comment by irenecanorod** [comment]
Traceback (most recent call last):
  File "C:\Users\irene\Desktop\bot pyhton\instabot.py-master\example.py", line 52, in <module>
    unfollow_whitelist=[''])
  File "C:\Users\irene\Desktop\bot pyhton\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\irene\Desktop\bot pyhton\instabot.py-master\src\instabot.py", line 289, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "C:\Users\irene\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\irene\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

C:\Users\irene\Desktop\bot pyhton\instabot.py-master>

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
