### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None" and more errors

### ISSUE THREAD

**Issue by Petronium37** [instabot-py/instabot.py#1377]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue
I recieve the same error message and do not know what I should change. I have changed the user ID line and also the other where you add to new lines where "csrftoken" but it still won't work. What should I do? 

```
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/blank/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/blank/Desktop/instabot.py-master/src/instabot.py", line 289, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

## Config

```

```

**Comment by mooreg21** [comment]
I have the same problem. Did you get it fixed?

**Comment by Qualle1991** [comment]
Same here!

**Comment by robery567** [comment]
Replace line **183**
` self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})`

with this:
` csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})`

and use **mode = 0**

**Comment by Qualle1991** [comment]
Thank you, that helped.
It was line 283 btw ;)

**Comment by dieselp** [comment]
Got NameError: global name 're' is not defined :/

**Comment by kuzubov** [comment]
after editing i have new error:
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ink361.com', port=80): Max retries exceeded with url: / (C
aused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x00000000038D3668>: Failed
to establish a new connection: [Errno 11004] getaddrinfo failed',))

**Comment by pvcoelho** [comment]
Same error here and after editing got diferent error:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/pedro/bin/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pedro/bin/instabot.py-master/src/instabot.py", line 283
    csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0) self.s.headers.update({'X-CSRFToken': csrf_token})
                                                                            ^
SyntaxError: invalid syntax

**Comment by freaky1** [comment]
I changed like 283, but it now give me this: 

`Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\blank\Downloads\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\blank\Downloads\instabot.py-master\src\instabot.py", line 283
    csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0) self.s.headers.update({'X-CSRFToken': csrf_token})`

**Comment by robery567** [comment]
@freaky1 
see: 
`csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)`
`self.s.headers.update({'X-CSRFToken': csrf_token})`

**Comment by freaky1** [comment]
@robery567 ooh it's two lines! My stupid ass thought it was just one line - thank you so much man!

**Comment by alex-s435** [comment]
Hey robery567...
What is to do when I want to use mode 2?

**Comment by babakyfar** [comment]
new error after editing:  log in error, connection error

**Comment by manguszta** [comment]
3 of my 4 accounts are working perfectly with the fix, the 4th still has the same error, and password change didn't help either.

**Comment by NarijauskasMartynas** [comment]
still has this issue

**Comment by steffo93** [comment]
Bump, still having the issue if not using zero mode.

**Comment by psannino77** [comment]
> 3 of my 4 accounts are working perfectly with the fix, the 4th still has the same error, and password change didn't help either.

I have the some issue :(
