### ISSUE TITLE
Trying to run on Pythonanywhere then Errno 2 -> fakeuseragent -> Errno13

### ISSUE THREAD

**Issue by danifki** [instabot-py/instabot.py#1379]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
I've been running 6 bots on my pc (local network) and all of them starting to get the Not Liked: 400 error. I've tried changing User Agent and it doesnt work.
I had the idea to run on pythonanywhere but the following erros cant let me run. Any sugestions?

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
12:27 ~/instagram bot $ python example.py
python: can't open file 'example.py': [Errno 2] No such file or directory
12:27 ~/instagram bot $ python instabot.py-master/daniel.py
Traceback (most recent call last):
  File "instabot.py-master/daniel.py", line 6, in <module>
    from src import InstaBot
  File "/home/dfki/instagram bot/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/dfki/instagram bot/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
12:29 ~/instagram bot $ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
12:33 ~/instagram bot $ sudo pip install fake-useragent
sudo: unknown user: root
sudo: unable to initialize policy plugin
12:33 ~/instagram bot $ sudo pip install fake-useragent
sudo: unknown user: root
sudo: unable to initialize policy plugin
12:34 ~/instagram bot $ python instabot.py-master/daniel.py
Traceback (most recent call last):
  File "instabot.py-master/daniel.py", line 6, in <module>
    from src import InstaBot
  File "/home/dfki/instagram bot/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/dfki/instagram bot/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
12:34 ~/instagram bot $ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
12:35 ~/instagram bot $ pip install -r instabot.py-master/requirements.txt
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages (from -r instabot.py-master/requirements.txt (line 1))
Collecting fake-useragent (from -r instabot.py-master/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/19/78/942c4be64409dcb3ebdd5741e1b6cdc4d6153b16e9765bcecfb81547c7a1/fake-useragent-0.1.10.tar.gz
Building wheels for collected packages: fake-useragent
  Running setup.py bdist_wheel for fake-useragent ... done
  Stored in directory: /home/dfki/.cache/pip/wheels/19/59/cc/23bf58a5525ea47fadfe24c03a72a293cf79d6188a82401cf2
Successfully built fake-useragent
Installing collected packages: fake-useragent
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/fake_useragent'

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
