### ISSUE TITLE
ISSUE NEED HELP

### ISSUE THREAD

**Issue by McSteroids** [instabot-py/instabot.py#1380]
All time everything was working no since May this year i cannot start on Notebook and PC my Bot anymore. When i open in cmd.exe comes this. When i open normally shutdown window in not a second.

C:>C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\luxurybrandgang1312.py
Traceback (most recent call last):
File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\luxurybrandgang1312.py", line 6, in
from src import InstaBot
File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src_init_.py", line 1, in
from .instabot import InstaBot
File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\instabot.py", line 5, in
from .unfollow_protocol import unfollow_protocol
File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\unfollow_protocol.py", line 7, in
from .follow_protocol import follow_protocol
File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\follow_protocol.py", line 6, in
from .feed_scanner import feed_scanner
File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\feed_scanner.py", line 6, in
from .likers_graber_protocol import likers_graber_protocol
File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\likers_graber_protocol.py", line 8, in
from .user_feed import get_media_id_user_feed
File "C:\Users\Lupi\Dropbox\instabot.pyV2-masterv2\src\user_feed.py", line 7, in
from .user_info import get_user_info
ImportError: cannot import name 'get_user_info'

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
