### ISSUE TITLE
Error qpython

### ISSUE THREAD

**Issue by koeniig2** [instabot-py/instabot.py#1387]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
  I have searched for other issues with the same problem. (including #1153 )

Hosting
  Are you hosting the bot on a VPS or other Cloud hosting?
  If so; have you tried running the code on your local machine?

Select one:
  Bug
  Feature Request
• [ x] Technical Help
  Other

Operating System? (include version)
  MAC
  Windows
  Linux
  X Android

Python Version?
X  2.x
  3.x

-----------

py-master/example.py" && exit            <
02.07.2018_23:30 Instabot v1.2.0 started at 02.07.2018 23:30:

02.07.2018_23:30 Trying to login as

Traceback (most recent call last):
  File "/storage/emulated/0/qpython/scripts/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/storage/emulated/0/qpython/scripts/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/storage/emulated/0/qpython/scripts/instabot.py-master/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/requests-2.19.1-py2.7.egg/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/requests-2.19.1-py2.7.egg/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
1|dreamlte:/ $

☆ Requests and fake useragent is installed. I use qpython both 2 and v3. All default settings.

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/issues/1287
