### ISSUE TITLE
bot cant log in

### ISSUE THREAD

**Issue by DanPikus** [instabot-py/instabot.py#1395]
this is what it shows me when i write "example.py"
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\instabot.py-master\example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Lenovo\Desktop\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\Lenovo\Desktop\instabot.py-master\src\instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

i think it fails to login
Help pls

**Comment by chicboyband** [comment]
I have exactly the same problem. I also already tried to change the line 283 in the "instabot.py" file:

from:
self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
to:
csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0) 
self.s.headers.update({'X-CSRFToken': csrf_token})

I'm still getting the same error...

**Comment by magostinelli** [comment]
Hello,
i have the same problem, i tried to login on instagram via a webbrowser and it's working fine, without request me any questions.

**Comment by drms09** [comment]
This worked for me 
https://github.com/instabot-py/instabot.py/pull/1292/files

**Comment by kuzubov** [comment]
@dims09 that's fix only one problem. then its cant login and lock my account....

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
