### ISSUE TITLE
i can not use mode 5  i get this error

### ISSUE THREAD

**Issue by abderrahmaneMustapha** [instabot-py/instabot.py#1400]
xxxxxx user info list is empty!!! xxxxxxxxx
Traceback (most recent call last):
  File "example.py", line 101, in <module>
    unfollow_protocol(bot)
  File "/home/abderrahmane/Documents/instabot.py/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/home/abderrahmane/Documents/instabot.py/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/home/abderrahmane/Documents/instabot.py/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/home/abderrahmane/Documents/instabot.py/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/home/abderrahmane/Documents/instabot.py/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'

**Comment by mico** [comment]
same problem

**Comment by abderrahmaneMustapha** [comment]
im working maybe i can fix it

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`

**Comment by lea0923** [comment]
> im working maybe i can fix it

Could you fix it?
