### ISSUE TITLE
Suspicious login error

### ISSUE THREAD

**Issue by denigada** [instabot-py/instabot.py#1406]
I get this error when trying to use the bot
`Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/denizyazar/Desktop/new mac files/new mac files/documents/visual studio code projects/instagram bot/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/denizyazar/Desktop/new mac files/new mac files/documents/visual studio code projects/instagram bot/src/instabot.py", line 288, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"`

Seems like a lot of people are getting this error. I applied the fix, however, it doesnt work and everytime I try to start the bot. Instagram on my phone says there was a suspicious login. Even if I click "It was me" and start the bot again, it doesnt work

**Comment by danifki** [comment]
Same happening here. First time it happens, all account at once.

**Comment by danifki** [comment]
guys, i'm still getting this error... any clue?

**Comment by zokaicmoa** [comment]
Same here

**Comment by mariobock** [comment]
same here guys, any conclusion?

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
