### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by kyleheth** [instabot-py/instabot.py#1408]
I am trying to run my bot, I have down graded to python 2.7.14 because i was told it works better

14.07.2018_00:12 Trying to login as luxurioustravelx...

Traceback (most recent call last):
File "/Users/lachlananniehetherington/Desktop/instabot.py-master/example.py", line 52, in 
unfollow_whitelist=['example_user_1', 'example_user_2'])
File "/Users/lachlananniehetherington/Desktop/instabot.py-master/src/instabot.py", line 232, in init
self.login()
File "/Users/lachlananniehetherington/Desktop/instabot.py-master/src/instabot.py", line 301, in login
self.user_id = ui.get_user_id_by_login(self.user_login)
File "/Users/lachlananniehetherington/Desktop/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
all_data = json.loads(info.text)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/init.py", line 339, in loads
return _default_decoder.decode(s)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

This error keep poping up when i go to run instabot.py-master, came you please help me out. what do i have to do to produced

**Comment by kyleheth** [comment]
I am trying to run my bot, I have down graded to python 2.7.14 because i was told it works better

14.07.2018_00:12 Trying to login as luxurioustravelx...

Traceback (most recent call last):
  File "/Users/lachlananniehetherington/Desktop/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/lachlananniehetherington/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/lachlananniehetherington/Desktop/instabot.py-master/src/instabot.py", line 301, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/lachlananniehetherington/Desktop/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded


This error keep poping up when i go to run instabot.py-master, came you please help me out. what do i have to do to produced

**Comment by ugurozturk** [comment]
python 3 is better. Yet your issue template is not as it's supposed to be
