### ISSUE TITLE
I tried all the fixes, issue still presists 

### ISSUE THREAD

**Issue by Jessnoia** [instabot-py/instabot.py#1424]
root@ns334952:~/home/Bot/instabot.py-master# python example.py
19.07.2018_05:41 Instabot v1.2.0 started at 19.07.2018 05:41:

19.07.2018_05:41 Trying to login as user...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/root/home/Bot/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/root/home/Bot/instabot.py-master/src/instabot.py", line 285, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/usr/lib/python2.7/dist-packages/requests/cookies.py", line 276, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python2.7/dist-packages/requests/cookies.py", line 331, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
