### ISSUE TITLE
i cannot unfollow ac "  File "Desktop/instabot.py-master/src/instabot.py", line 700, in new_auto_mod     self.new_auto_mod_unfollow()

### ISSUE THREAD

**Issue by nagisan0215** [instabot-py/instabot.py#1428]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x ] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue

```
21.07.2018_08:50 Instabot v1.2.0 started at 21.07.2018 08:50:

21.07.2018_08:50 Trying to login as xxxx...

21.07.2018_08:50 xxxx login success!
21.07.2018_08:50 Get media id by tag: design
21.07.2018_08:50 Removing already liked medias..
21.07.2018_08:50 Trying to like media: 1xxx
21.07.2018_08:50 Liked: 1xxx. Like #1.
21.07.2018_08:50 xxxx: Get media id on recent feed 
 21.07.2018 08:50
21.07.2018_08:50 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
21.07.2018_08:51 xxxx : Get media id on recent feed 
 21.07.2018 08:51
21.07.2018_08:51 Except on get media!!
21.07.2018_08:51 ======> Get media id by Tag <======
21.07.2018_08:51 Get media by user success!
21.07.2018_08:51 Current Index = 12 of 51 medias
Traceback (most recent call last):
  File "example.py", line 86, in <module>
    bot.new_auto_mod()
  File "Desktop/instabot.py-master/src/instabot.py", line 700, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "Desktop/instabot.py-master/src/instabot.py", line 765, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "Desktop/instabot.py-master/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "Desktop/instabot.py-master/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "Desktop/instabot.py-master/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "Desktop/instabot.py-master/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "Desktop/instabot.py-master/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
21.07.2018_08:51 Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
21.07.2018_08:51 Bot work time: 0:00:52.568288
21.07.2018_08:51 Logout success!

```

## Config

```
I
bot = InstaBot(
    login="",
    password="",
    like_per_day=100,
    comments_per_day=0,
    tag_list=['design', 'designer'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=0,
    follow_time=0,
    unfollow_per_day=50,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "design"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[],
    unfollow_whitelist=[])
while True:
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
