### ISSUE TITLE
instabot.py: error in line 869, in auto_unfollow - key error 'Profile Page'

### ISSUE THREAD

**Issue by tuliosousa25** [instabot-py/instabot.py#1431]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
When I try to log in I receive that error. Last day that bot was working well then today this bug surfaced...
```
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on get_username_by_user_id
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 428, in get_username_by_user_id
    r = self.s.get(url_info, headers="")
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
ERROR:root:Except on follow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 639, in follow
    insert_username(self, user_id=user_id, username=username)
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\sql_updates.py", line 74, in insert_username
    VALUES('"+user_id+"','"+username+"','"+ str(now) +"')")
TypeError: can only concatenate str (not "bool") to str
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "D:\Imagens\Outro\The Guys Spot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
KeyError: 'ProfilePage'

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
login="username",
    password="passord",
    like_per_day=1000,
    comments_per_day=150,
    tag_list=['luxury', 'style', 'watchgeek', 'relogio', 'watchfreak', 'chrono', 'wriststyle', 'timegeeks', 'watches', 'watchesformen', 'menswear', 'mensfashion', 'fashion', 'menswatches', 'mensstyle', 'l:389983831'],
	tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=500,
    follow_time=35 * 60,
    unfollow_per_day=500,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
