### ISSUE TITLE
Please help.. 1 like then log out

### ISSUE THREAD

**Issue by KappaCrunch** [instabot-py/instabot.py#1440]
I'm not good at this at all. I set it up using an old youtube video and for what ever reason it is only liking one post and then logging out and shutting down.. Please help me find out what the issue is..

23.07.2018_18:43 dfw_evo_gsr login success!
23.07.2018_18:43 Get Media by tag: EVO
23.07.2018_18:43 Removing already liked medias..
23.07.2018_18:43 Trying to like media: 1830137078672691425
23.07.2018_18:43 Liked: 1830137078672691425. Like #1.
23.07.2018_18:43 dfw_evo_gsr : Get media id on recent feed
 23.07.2018 18:43
23.07.2018_18:43 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
23.07.2018_18:43 dfw_evo_gsr : Get media id on recent feed
 23.07.2018 18:43
23.07.2018_18:43 Except on get media!!
23.07.2018_18:44 ======> Get media id by Tag <======
23.07.2018_18:44 Get media by user success!
23.07.2018_18:44 Current Index = 28 of 70 medias
Traceback (most recent call last):
  File "c:/Users/Tyler/Desktop/instabot.py-master/example.py", line 94, in <module>
    bot.new_auto_mod()
  File "c:\Users\Tyler\Desktop\instabot.py-master\src\instabot.py", line 722, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "c:\Users\Tyler\Desktop\instabot.py-master\src\instabot.py", line 787, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "c:\Users\Tyler\Desktop\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "c:\Users\Tyler\Desktop\instabot.py-master\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "c:\Users\Tyler\Desktop\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "c:\Users\Tyler\Desktop\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "c:\Users\Tyler\Desktop\instabot.py-master\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
23.07.2018_18:44 Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
23.07.2018_18:44 Bot work time: 0:00:52.609890
23.07.2018_18:44 Logout success!

**Comment by KappaCrunch** [comment]
If you need more information or for me to show something else please let me know.

**Comment by y9y** [comment]
Do you have multiple Account with same Database ? So than it would logout always really quickly.

**Comment by worldsdream** [comment]
Same problem with mode 2

**Comment by kostasosfp** [comment]
same problem with all modes .... have you fixed that?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
