### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by boviestimul** [instabot-py/instabot.py#1442]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Ernius\Downloads\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Ernius\Downloads\instabot.py-master\src\instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "C:\Users\Ernius\Downloads\instabot.py-master\src\userinfo.py", line 32
    self.s = requests.Session()

IndentationError: expected an indented block
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
