### ISSUE TITLE
hangs on: found whitelist user, starting search again

### ISSUE THREAD

**Issue by rbrixel** [instabot-py/instabot.py#1447]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux - Raspberry Pi Zero W - Raspbian stretch lite - Version June 2018
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

Hello everybody!,

I get the bot running, but after a couple of time (approx. 30 minutes) it hangs on
"**found whitelist user, starting search again**". I've got the newest version of instabot-py

In the following log/config I anonymize all hashtags, usernames, etc.

```
Instagram bot v 1.2.0
[...]
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
25.07.2018_01:01 found whitelist user, starting search again
^CTraceback (most recent call last):
  File "example.py", line 93, in <module>
    bot.new_auto_mod()
  File "/home/pi/instabot.py/src/instabot.py", line 726, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/home/pi/instabot.py/src/instabot.py", line 787, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "/home/pi/instabot.py/src/instabot.py", line 843, in auto_unfollow
    username_row = get_username_random(self)
  File "/home/pi/instabot.py/src/sql_updates.py", line 109, in get_username_random
    username = self.follows_db_c.execute("SELECT * FROM usernames WHERE unfollow_count=0 ORDER BY RANDOM() LIMIT 1").fetchone()
KeyboardInterrupt
25.07.2018_01:01 Trying to unfollow: 36643
25.07.2018_01:02 Unfollow: 36643 #2 of 1.
25.07.2018_01:02 Pausing for 15 seconds... 2 of 1
25.07.2018_01:02 Logout: likes - 3, follow - 1, unfollow - 2, comments - 0.
25.07.2018_01:02 Bot work time: 6:07:29.384382
25.07.2018_01:02 Logout success!
```

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="username",
    password="password",
    start_at_h=8,
    start_at_m=0,
    end_at_h=23,
    end_at_m=0,
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['hashtag1', 'hashtag2', 'hashtag3', 'hashtag4'],
    tag_blacklist=['hashtag1', 'hashtag2'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
	    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['username', 'username','username','username',
    'username','username','username','username','username','username',
    'username','username','username','username','username','username',
    'username','username','username','username','username',
    'username','username','username','username','username','username','username',
    'username','username','username','username','username','username',
    'username','username','username','username','username','username',
    'username','username','username','username','username','username','username',
    'username','username','username','username','username','username','username',
    'username','username','username','username','username','username','username','username',
    'username','username','username','username','username','username','username',
    'username','username','username','username'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
