### ISSUE TITLE
instabot.py

### ISSUE THREAD

**Issue by NiPeters** [instabot-py/instabot.py#1465]
Traceback (most recent call last):
  File "C:\Users\NiPe\Downloads\instabot.py-master\example.py", line 53, in <module>
    unfollow_whitelist=[''])
  File "C:\Users\NiPe\Downloads\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\NiPe\Downloads\instabot.py-master\src\instabot.py", line 285, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\NiPe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\NiPe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by albqn** [comment]
The same problem please help

**Comment by jirkajirka** [comment]
Same here. Old fix doesn't work for me anymore

**Comment by DJRay57** [comment]
Me too, only last few days.

**Comment by antisocialmediamanager** [comment]
same issue here. is the bot getting flagged by insta?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
