### ISSUE TITLE
instabot logs in succesfully then logs out after 8sec of operation.

### ISSUE THREAD

**Issue by NikolasP98** [instabot-py/instabot.py#1469]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
I ran example.py (I named it **dankmomox.py** for reference). It runs for about 8sec and logs out. This is what the terminal spits out.

***NOTE: I've just recently downloaded this bot and these were the steps that I took:
--> Install python 3.7 (works), downloaded the instabot.py ZIP (vanilla) and extracted to DOWNLOADS, created a .bat file for startup (placed in shell:startup) [code: python "C:\_directory_\dankmomox.py"], added usr & pass, changed settings to my preferences (seen below) and got this feedback from the terminal:
```
06.08.2018_18:29 Trying to login as dank_momox...

06.08.2018_18:29 dank_momox login success!
06.08.2018_18:29 Account of user daquan was deleted or link is invalid
06.08.2018_18:29 Get Media by tag: f4f
06.08.2018_18:29 Removing already liked medias..
Traceback (most recent call last):
  File "C:\Users\nikol\Downloads\instabot.py-master\dankmomox.py", line 76, in <module>
    bot.new_auto_mod()
  File "C:\Users\nikol\Downloads\instabot.py-master\src\instabot.py", line 718, in new_auto_mod
    self.new_auto_mod_like()
  File "C:\Users\nikol\Downloads\instabot.py-master\src\instabot.py", line 746, in new_auto_mod_like
    if self.like_all_exist_media(media_size=1, delay=False):
  File "C:\Users\nikol\Downloads\instabot.py-master\src\instabot.py", line 481, in like_all_exist_media
    for blacklisted_user_name, blacklisted_user_id in self.user_blacklist.items(
AttributeError: 'set' object has no attribute 'items'
06.08.2018_18:29 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
06.08.2018_18:29 Bot work time: 0:00:08.871791
06.08.2018_18:29 Logout success!

C:\Users\nikol\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup>pause
Press any key to continue . . .
```

## Config (didn't copy modes since I did not edit the if statements below "mode = 0" (line 69)

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="user",
    password="pass",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute', 'meme', 'memes', 'funny', 'darkhumor', 'qualitymemes', 'funnymemes'],
    tag_blacklist=['rain', 'christian','christ'],
    user_blacklist={'daquan'},
    max_like_for_one_tag=150,
    follow_per_day=300,
    follow_time=2 * 60,
    unfollow_per_day=250,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
