### ISSUE TITLE
not liked 403

### ISSUE THREAD

**Issue by kelijay** [instabot-py/instabot.py#1497]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
bot worked fine for 3 days but now repeating this line and not getting passed it
Not liked: 403

20.08.2018_22:41 Not liked: 403
20.08.2018_22:41 Trying to like media: 1850071407950737771
20.08.2018_22:41 Not liked: 403
20.08.2018_22:41 Trying to like media: 1850039825546515074
20.08.2018_22:41 Not liked: 403
20.08.2018_22:41 Trying to like media: 1850038724617774527
20.08.2018_22:41 Not liked: 403
20.08.2018_22:41 Trying to like media: 1849850369832946251
20.08.2018_22:41 Not liked: 403
20.08.2018_22:41 Trying to like media: 1849847170209409091
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
ERROR:root:Logout error!
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xx\Downloads\instabot.py-master\src\instabot.py", line 325, in logout
    logout = self.s.post(self.url_logout, data=logout_post)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 644, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 644, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 222, in resolve_redirects
    **adapter_kwargs
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
ERROR:root:Except on like!
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xx\Downloads\instabot.py-master\src\instabot.py", line 592, in like
    like = self.s.post(url_likes)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt


## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by json144** [comment]
been having the same issue as well since this morning.  Please assist!

**Comment by jarosenthal** [comment]
#1498

**Comment by kelijay** [comment]
thank you very much @jarosenthal
