### ISSUE TITLE
NameError: name 'bot' is not defined

### ISSUE THREAD

**Issue by ianong113** [instabot-py/instabot.py#1506]
Traceback (most recent call last):
  File "example.py", line 35, in <module>
    unfollow_whitelist=[bot])
NameError: name 'bot' is not defined

How to fix this? Everytime I run my python example.py then I get this issue, if I make it blank. unfollow_whitelist=[] , it will prompt another issue as shown below.

  File "example.py", line 35, in <module>
    unfollow_whitelist=[])
  File "C:\Users\user\Downloads\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\user\Downloads\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\user\Downloads\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

NoneType has no attribute... hmm.. how to fix this? Thanks

**Comment by ieatchoppers** [comment]
same, likebot was working just fine for the past month or so and all of a sudden I run into this error for all my accounts. I even tried re-downloading the src but still produces the same result. Anyone with experience on this?

**Comment by ianong113** [comment]
Solution found.
Replaced userinfo.py
Line 42 by this

json_info = json.loads(re.search(r'>window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))

Then it works. Thank you
