### ISSUE TITLE
Mode 5 doesn't work

### ISSUE THREAD

**Issue by fedex03** [instabot-py/instabot.py#1521]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

```
Hi there, 

I tried to start the bot in mode 5 to start the unfollow but I receive back this error:


xxxxxxx user info list is empty!!! xxxxxxxxx
Traceback (most recent call last):
  File "instabot_script.py", line 113, in <module>
    unfollow_protocol(bot)
  File "/home/user/script/instabot/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/home/user/script/instabot/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/home/user/script/instabot/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/home/user/script/instabot/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/home/user/script/instabot/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'

This is the errors.log
INFO:user:user login success!
INFO:user:user : Get media id on recent feed
 23.08.2018 13:08
INFO:user:Except on get media!!
INFO:user:user : Get media id on recent feed
 23.08.2018 13:09
INFO:user:Except on get media!!
INFO:user:======> Get media id by Tag <======
INFO:user:Get media by user success!
INFO:user:Current Index = 64 of 71 medias
INFO:user:Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
INFO:user:Bot work time: 0:00:49.242980
INFO:user:Logout success!

What does it means? 
In the script folder I have the follows_db.

Thanks in advance.
Federico

```

## Config

```
start_at_h=6,
start_at_m=10,
end_at_h=23,
end_at_m=55,
like_per_day=1000,
media_min_like=20,
comments_per_day=0,
tag_list=['xxx', 'xxx', 'xxx', 'xxx'],
tag_blacklist=[],
user_blacklist={},
max_like_for_one_tag=150,
follow_per_day=500,
follow_time=5 * 60 * 60,
unfollow_per_day=500,
unfollow_break_min=15,
unfollow_break_max=30,
log_mod=1
```

**Comment by LopesX** [comment]
Some here

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
