### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by jhaycheese** [instabot-py/instabot.py#1531]
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/root/Desktop/instabot.py/src/instabot.py", line 234, in __init__
    self.login()
  File "/root/Desktop/instabot.py/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/root/Desktop/instabot.py/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I need help pls

**Comment by K2X** [comment]
Same issue here! Anyone found any solutions??

**Comment by erikpi** [comment]
Try this https://github.com/instabot-py/instabot.py/pull/1503

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
