### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by qaranjik** [instabot-py/instabot.py#1532]
Hi, How can I fix this error?

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\scripts\instabot_arzansaraye.gharanjik\example.py", line 134, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Administrator\Desktop\scripts\instabot_arzansaraye.gharanjik\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\Administrator\Desktop\scripts\instabot_arzansaraye.gharanjik\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Administrator\Desktop\scripts\instabot_arzansaraye.gharanjik\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Yeshasvitvs** [comment]
https://github.com/instabot-py/instabot.py/issues/1522
FYI: Check the previous issues before opening a new one. I think you can close this

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
