### ISSUE TITLE
Login error - Traceback (most recent call last):   File "example.py", line 52, in <module>     unfollow_whitelist=['example_user_1', 'example_user_2'])   File "/Users/admin/Desktop/instabot.py-master/src/instabot.py", line 234, in __init__     self.login()   File "/Users/admin/Desktop/instabot.py-master/src/instabot.py", line 303, in login     self.user_id = ui.get_user_id_by_login(self.user_login)   File "/Users/admin/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login     json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}') AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by chris3341** [instabot-py/instabot.py#1540]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [YES] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [NO] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [YES] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [YES] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [YES] 3.x

## Description of your issue  
not logging in throwing back errors

```
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/admin/Desktop/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/Users/admin/Desktop/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/admin/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
```

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="",
    password="",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute', 'l:212999109'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong 

mode!")
```

**Comment by MOzil10** [comment]
Having the same issue, hoping someone can help asap!

**Comment by bnjmn** [comment]
Check out this PR https://github.com/instabot-py/instabot.py/pull/1525
It should help you fix your issue

**Comment by matthewwoodard** [comment]
Thanks @bnjmn - that fixed it for me!

**Comment by MediaGod** [comment]
@matthewwoodard How did you Manage to Find the Fix? I am Extremely Confused

**Comment by bnjmn** [comment]
@MediaGod (and anyone else wondering), since it seems unlikely that the fix will get merged into the repo anytime soon try this...

Go to `src/userinfo.py` and change line 42 like so:

```diff
-        json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
+        json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
```

(replace the red text with the green text) 😃

**Comment by MediaGod** [comment]
Hey Ben, this is what i have for line 42 
 id_user = all_data['graphql']['user']['id']

**Comment by MediaGod** [comment]
Okay, so my Userinfo.py File was different because I Edited it and Added a New code to fix an error I believe it was I was told to this by the video I was going off of on YouTube the channel's/ Person name is James Buzzard Anyways I recuperated the Old Userinfo. Py file and Now my Line 42 is 

  json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)

I Now replaced the Red text with the GREEN TEXT 
and am going back to the Example. Py File to run Python in the Terminal and it's still giving me the TRACEBACK ERROR

**Comment by MediaGod** [comment]
@bnjmn

**Comment by icedevil2001** [comment]
Also having the same issue here! 
I pulled the repo today (2018-08-29) and everything left unchanged in the example.py other then uname and pwd.   

Using a MacOS with python 3.7 inside of a conda env

Error mgs:

```
29.08.2018_17:23 Instabot v1.2.0 started at 29.08.2018 17:23:

29.08.2018_17:23 Trying to login as ######...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist= [ ])
  File "/Users/####/git/instabot.py/src/instabot.py", line 234, in __init__
    self.login()
  File "/Users/####/git/instabot.py/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/####/git/instabot.py/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Serhiy23** [comment]
@bnjmn Thank you mate!!! That fixed my bot!!!

**Comment by MediaGod** [comment]
@bnjmn So Fixed it :) 

Once I get login success!

(Date and Time) {MY ACCOUNT NAME}  login success!
(Date and Time) Account of user  was deleted or link is invalid
(Date and Time) Get Media by tag: Positive
(Date and Time) Removing already liked medias..

Traceback (most recent call last):
The Lines it's telling me us 94,718,746,481 

Then after that Traceback it tells me 

Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
Bot work time: 0:00:13.149259
Logout success!

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
