### ISSUE TITLE
I am getting logged out after only working for like a minute or less

### ISSUE THREAD

**Issue by heateavs** [instabot-py/instabot.py#1549]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\HEAT> & python c:/Users/HEAT/Desktop/instabot.py-master/example.py
28.08.2018_13:44 Instabot v1.2.0 started at 28.08.2018 13:44:

28.08.2018_13:44 Trying to login as heatservices...

28.08.2018_13:44 heatservices login success!
28.08.2018_13:44 Get Media by tag: mixtapes
28.08.2018_13:44 Removing already liked medias..
28.08.2018_13:44 Trying to like media: 1856136945661345219
28.08.2018_13:44 Liked: 1856136945661345219. Like #1.
28.08.2018_13:44 Trying to follow: 224659718
28.08.2018_13:44 Followed: 224659718 #1.
28.08.2018_13:44 heatservices : Get media id on recent feed
 28.08.2018 13:44
28.08.2018_13:44 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
28.08.2018_13:44 heatservices : Get media id on recent feed
 28.08.2018 13:44
28.08.2018_13:44 Except on get media!!
28.08.2018_13:45 ======> Get media id by Tag <======
28.08.2018_13:45 Get media by user success!
28.08.2018_13:45 Current Index = 3 of 69 medias
Traceback (most recent call last):
  File "c:/Users/HEAT/Desktop/instabot.py-master/example.py", line 90, in <module>
    bot.new_auto_mod()
  File "c:\Users\HEAT\Desktop\instabot.py-master\src\instabot.py", line 721, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "c:\Users\HEAT\Desktop\instabot.py-master\src\instabot.py", line 786, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "c:\Users\HEAT\Desktop\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "c:\Users\HEAT\Desktop\instabot.py-master\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "c:\Users\HEAT\Desktop\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "c:\Users\HEAT\Desktop\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "c:\Users\HEAT\Desktop\instabot.py-master\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
28.08.2018_13:45 Trying to unfollow: 224659718
28.08.2018_13:45 Unfollow: 224659718 #1 of 0.
28.08.2018_13:45 Pausing for 22 seconds... 1 of 0
28.08.2018_13:45 Logout: likes - 1, follow - 0, unfollow - 1, comments - 0.
28.08.2018_13:45 Bot work time: 0:01:18.401653
28.08.2018_13:45 Logout success!
```

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="username",
    password="password",
    like_per_day=2000,
    comments_per_day=300,
    tag_list=['mixtapecomingsoon','mixtapeotw','mixtapeontheway','sendbeats','rap','rappers','rapartist','rapping','soundcloudrapper','hiphop','hiphopartist','freestylerap','raplife','hiphoplife','realrap','hiphophead','newrap','recordingartist','newmusicalert','rapvideos','hotnewhiphop','rapradar','allhiphop','mixtape','hiphopculture','mymixtapez','mixtapes','unsignedheat','rapmusic','hiphopmusic','indiehiphop','undergroundhiphop','indierap','undergroundrap','rapvideo','hiphopvideo','spinrilla','Rapper','unsignedrapper','upcomingrapper','datpiffmixtapes'],
    tag_blacklist=['producer','production','beatstars','traktrain','hiphopproducer','rapproducer','trapproducer','buybeats','nofreebeats','flstudio','fruityloops','ableton','trapbeats','airbit','drumkit','drumkits','hotgirl','nsfw','cellphone'],
    user_blacklist={},
    max_like_for_one_tag=24,
    follow_per_day=300,
    follow_time=2 * 60,
    unfollow_per_day=250,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["what's"],
                  ["up", "good"],
                  ["i'm"],
                  ["a"],
                  ["producer."],
                  ["Dm"],
                  ["me"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags','producer','nsfw','nsfw','production','beatmaker','beats','produced'],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by heateavs** [comment]
i had originally started this for a different issue, but i fixed that. now this is my current issue.

**Comment by steffo93** [comment]
Same here.

**Comment by cooolforce** [comment]
i am having the same problem

**Comment by tayloriuss** [comment]
have the same problem

**Comment by justindustries1** [comment]
Same

**Comment by Moondog360** [comment]
I have been trying all sorts of fix and nothing has been helpful. Have been scouring for help for about 42hours now.

**Comment by museshashin** [comment]
If I change the inputs
follow_per_day=0,
unfollow_per_day=0,

the script runs - otherwise I also have the problem that it logs out of IG after about 0:01:16 

any ideas?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
