### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by Stefamen23** [instabot-py/instabot.py#1562]
S:\Users\stefa\Downloads\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "S:\Users\stefa\Downloads\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "S:\Users\stefa\Downloads\instabot.py-master\src\instabot.py", line 285
    r = self.s.get(self.url)
    ^
IndentationError: unexpected indent

**Comment by Stefamen23** [comment]
pls help me

**Comment by KyleTrimpe** [comment]
Getting the same problem.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
