### ISSUE TITLE
DatabaseError: database disk image is malformed PLEASE HELP ME!

### ISSUE THREAD

**Issue by rugge89lau** [instabot-py/instabot.py#1613]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
HELP please, since 1 month I have this problem!
can you help me???

Traceback (most recent call last):
  File "example.py", line 16, in <module>
    log_mod = 1)
  File "/Users/ruggero/Downloads/instabot.py-master/src/instabot.py", line 162, in __init__
    check_and_update(self)
  File "/Users/ruggero/Downloads/instabot.py-master/src/sql_updates.py", line 7, in check_and_update
    self.follows_db_c.execute("CREATE TABLE IF NOT EXISTS usernames (username varchar(300))")
sqlite3.DatabaseError: database disk image is malformed
Mac-Pro-di-Ruggero:instabot.py-master ruggero$ 
```

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
               like_per_day=2000,
               media_max_like=50,
               tag_list = ['minimal', 'learnminimalism', 'rsa_minimal', 'jj_minimal', 'minimal_experience', 'minimal_masters', 'transfer_visions', 'mindtheminimal','minimal_perfection','haveboatwilltravel','liveaboardlife','sailingstagram','sailinglife','folkscenery','folkgood','pioneeradventures','mountainadventures','welivetoexplore','roamtheplanet','fiftyshades_of_nature','nature_perfection','ig_mountains','folkcreative','folkvibe'],
               log_mod = 1)
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by LopesX** [comment]
Local machine ?
you try use original file example.py only change username and password https://github.com/instabot-py/instabot.py/blob/master/example.py

try too using python 2.7
i use windows local python 2.7 works fine

**Comment by rugge89lau** [comment]
solved just deleted the db file.......................

**Comment by LopesX** [comment]
If works good, please close the issue

**Comment by goochi1** [comment]
did that and got Traceback (most recent call last):
  File "/var/task/lambda.py", line 53, in lambda_handler
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/var/task/src/instabot.py", line 164, in __init__
    self.follows_db = sqlite3.connect(database_name, timeout=0, isolation_level=None)
OperationalError: unable to open database file

**Comment by LopesX** [comment]
@goochi1 try delete your db file if not work please open a new issue
