### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by gumdropsteve** [instabot-py/instabot.py#1619]
When attempting to run:

C:\Users\USER\Downloads\GetHub\instabot.py-master\instabot.py-master>**python example.py**
25.09.2018_03:11 Instabot v1.2.0 started at 25.09.2018 03:11:

25.09.2018_03:11 Trying to login as 'username'...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\USER\Downloads\GetHub\instabot.py-master\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\USER\Downloads\GetHub\instabot.py-master\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\USER\Downloads\GetHub\instabot.py-master\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

C:\Users\USER\Downloads\GetHub\instabot.py-master\instabot.py-master>

**Comment by neospeed83** [comment]
open the link.
Find the file under src folder.
Replace the line in Red with one in green. (line42)

https://github.com/instabot-py/instabot.py/commit/806e09414f73a461bdb81fd6d4fc2e1e34a54ef8

**Comment by neospeed83** [comment]
After that follow https://github.com/instabot-py/instabot.py/commit/9f6a2840083f56a855ab700022b10a97bd50aac1 to fix the Not Liked 403 error
