### ISSUE TITLE
Bot stop working after 1 minute (With error)

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [instabot-py/instabot.py#1625]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
 So, The bot start working and after 1 minutes it's logout
```
26.09.2018_16:44 Instabot v1.2.0 started at 26.09.2018 16:44:

26.09.2018_16:44 Trying to login as falshanson...

26.09.2018_16:44 falshanson login success!
26.09.2018_16:44 Get Media by location: 212999109
26.09.2018_16:44 Removing already liked medias..
26.09.2018_16:44 Trying to like media: 1876976474101914285
26.09.2018_16:44 Liked: 1876976474101914285. Like #1.
26.09.2018_16:44 Trying to follow: 17076199
26.09.2018_16:44 Followed: 17076199 #1.
26.09.2018_16:44 falshanson : Get media id on recent feed
 26.09.2018 16:44
26.09.2018_16:44 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
26.09.2018_16:44 falshanson : Get media id on recent feed
 26.09.2018 16:44
26.09.2018_16:44 Except on get media!!
26.09.2018_16:45 ======> Get media id by Tag <======
26.09.2018_16:45 Get media by user success!
26.09.2018_16:45 Current Index = 56 of 68 medias
Traceback (most recent call last):
  File "C:\Users\Tom\Desktop\instabot.py-master\example.py", line 94, in <module>
    bot.new_auto_mod()
  File "C:\Users\Tom\Desktop\instabot.py-master\src\instabot.py", line 722, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\Tom\Desktop\instabot.py-master\src\instabot.py", line 787, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "C:\Users\Tom\Desktop\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "C:\Users\Tom\Desktop\instabot.py-master\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "C:\Users\Tom\Desktop\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\Tom\Desktop\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\Tom\Desktop\instabot.py-master\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
26.09.2018_16:45 Trying to unfollow: 17076199
26.09.2018_16:45 Unfollow: 17076199 #1 of 0.
26.09.2018_16:45 Pausing for 30 seconds... 1 of 0
26.09.2018_16:45 Logout: likes - 1, follow - 0, unfollow - 1, comments - 0.
26.09.2018_16:45 Bot work time: 0:01:27.526940
26.09.2018_16:45 Logout success! < REPLACE THIS TEXT
```

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="falshanson",
    password="AnUnknownPassword",
    like_per_day=1000,
    comments_per_day=50,
    tag_list=['follow4follow', 'f4f', 'cute', 'l:212999109'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['ntdevs', 'tomaveclevdsl'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by TomAvecLeVdsl** [comment]
PS: Now it's seams to work

**Comment by Lahirutech** [comment]
same here

**Comment by LopesX** [comment]
Try on python 2.7 if works fine close the issue please

**Comment by blackavec** [comment]
@TomAvecLeVdsl @Lahirutech @LopesX 
i'm not really sure if this is the right change but it works for me, although on mode 5, it doesn't unfollow anyone.
`likers_protocol.py`
```python
def likers_protocol(self):
    if len(self.media_by_user) > 0:
        # You have media_id to like:
        self.current_index = random.randint(0, len(self.media_by_user) - 1)

        media = self.media_by_user[self.current_index]

        if hasattr(media, "likes"):
            log_string = "Current Index = %i of %i medias, total likes: %i" % (self.current_index, len(self.media_by_user), media["likes"]["count"])

            if media["likes"]["count"] >= 10 and media["likes"]["count"] < 100:
                get_user_id_post_page(self, media["code"])
                username_checker(self)
        else:
            log_string = "Current Index = %i of %i medias, total likes: %i" % (self.current_index, len(self.media_by_user), media["node"]["edge_media_preview_like"]["count"])

            if media["node"]["edge_media_preview_like"]["count"] >= 10 and media["node"]["edge_media_preview_like"]["count"] < 100:
                get_user_id_post_page(self, media["node"]["shortcode"])
                username_checker(self)

        self.write_log(log_string)

        del self.media_by_user[self.current_index]
```

i'm wan't sure if media still has the attribute of `likes` or it only happens on certain medias, but i left it there just in case.
i'll make PR if this is something we can rely on. it also tested on PYTHON 3.7.0

PS: i'm not a python focused engineer

**Comment by Lahirutech** [comment]
After changing that on mode 2 it seems that bot just does likes only. Not Following Any one. Do changed the src.follw_protocol.py file also
