### ISSUE TITLE
Bot not starting, error in multiple files

### ISSUE THREAD

**Issue by Rinarikato** [instabot-py/instabot.py#1632]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows 7 x64
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
bot not starting with the following errors

Traceback (most recent call last):
  File "A:\instabot.py-master\msan.py", line 6, in <module>
    from src import InstaBot
  File "A:\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "A:\instabot.py-master\src\instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "A:\instabot.py-master\src\userinfo.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). #!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="",
    password="",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['bodybuilding', 'bodybuilder', 'academia', 'l:32376255','treino','fitgirl'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=1,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags','ganha'
    ],
    unfollow_whitelist=['mdiazsalvatore', 'fernandosardinha', 'amandinhagriebel', 'danny_ribeiro', 'jhulianisabelle', 'acordemotivado', 
                        'psicologiareal', 'viviwinklerwellness', 'leyla_ortegaa', 'goticside', 'marombazueiro', 'bodybuildingemotivacao',
                        'vazafrango', 'bulkingoficial', 'eva_andressa', '_julianaalves_', 'manualdohomem', 'renatagodio', 'leticiabuffonn',
                        'isapecini', 'chapolinbodybuilder', 'laispollly', 'andrey_ruas', 'monstrosemusas', 'marombeiratop', 'corpodemonstro',
                        'worldbodybuilder', 'isaac.reboucas', 'treinamento_feminino', 'semdor_semgloria', 'homermaromba', '_emagrecendo.juntos',
                        'fibradaporra', 'ab_bodybuilding', 'velhorico', 'mafiabboficial', 'lumacordeiro_', 'pernalongamaromba', 'bbg_watermelon',
                        'vick23m', 'jakeline_souzaaa', 'bewrappy', '3vsnutrition', 'andrelly.sabattyni', 'lucasvpaula', 'veronica_saeki',
                        'marombasincerooficial', 'mesadesupino', 'playmateiryna', 'maxtitaniumsuplementos', 'megastoresuplemento',
                        'regatas_super_cavadas', 'neonutrioficial', 'blackskullusa', 'fisiopharma', 'newnutritionbrasil', 'iridiumlabsbrasil',
                        'arnoldnutrition', 'gsnsuplementos', 'probioticaoficial', 'growthsupplements', 'dragonpharmabrasil', 'poweroficial',
                        'midwaylabs', 'darknessnation', 'newmillensuplementos', 'athleticanutrition', 'integralmedica', 'bodyactionoficial', 'nadaapanda',
                        'fabianeteixeirasilva', 'semprenatural', 'academia_milgrau', 'segredotestosterona', 'bizonmystyle', 'goku_ferrero',
                        'thatah_yhorrane', 'receitasdadi', 'receitasdicasfit', 'sardinha_sincero', 'tresde10', 'frangodeacademia', 'gokubodybuilder',
                        'papavince', 'moldadasaferro', 'marombaprojeto', 'culinarianinja', 'vittagold', 'fitnessmagazinebrasil', 'garotada.capa',
                        'babicotrim', 'motivabuilder', 'ataldevic', 'joao_dos_veneno', 'mrmatusalem', 'santamaromba', 'seucorpofit', 'lalberto74',
                        'marombarealista', 'fitness_freak.empire', 'atitude.maromba', 'sucessoprogramado', 'joaodosveneno', 'picapaumaromba', 'teamurso',
                        'blackenedamericanwhiskey', 'glaufcoelho', 'magrelasarada', 'fitlife_instag', 'bodysuperation', 'memesbuilder',
                        'caesegatos_oficial', 'memesdamarombaoficial', 'jehnutrifit', 'bonecadeferro.barbiedeferro', 'mendessnathalia', 'princesamaromba',
                        'carol_lima404', 'bambamoficial', 'alissawhitegluz', 'james.hetfield', 'renan4fitclub', 'lionschulz', 'patyfit_', 'bina.buck',
                        'tali_moreno', 'arnoldoficial', 'mikevitielloc', 'vida_anabolica', 'fefranco', 'musclemotivation', 'larsulrich', 'kirkhammett',
                        'treinofocadobr', 'manu.almeidag', 'bianca_ruiva', 'jujusalimeni', 'phenriquefdeoliveira', 'mirandanauane', 'rafaneres',
                        'nossokantinho', 'raphaizumi', 'liih_rodriguess', 'dweslord', 'fran.mirandaa', 'cauelz', 'lucas_silva_92', 'tharge',
                        'jaque.ferre', 'gu45ft', 'ribeiro.dcalan91', 'tassiaoliveirab', 'tsannossauro', 'palomac968', 'diegomal', 'sgt_bulldog',
                        'deoartmoraes', 'umsabadoqualquer', 'l_vilkler', 'samuraililo', 'douglastropiano', 'maary_padilha', 'natalia_yagamii', 'mitasuna1', 'van.rogue', 'nana_k_d', 'dehtoscano', 'samanthasuellen', 'erica_migpaiva', 'psycho_andie', 'missopyon' ])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by Rinarikato** [comment]
solved installing requests, but now I'm having issues with unfollowing like this:

INFO:rinarikato:Trying to unfollow #1: 
INFO:rinarikato:Getting user info : alver0.lifts
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "A:\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
INFO:rinarikato:Trying to unfollow: 7983166655
