### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by niklashaukenfrers** [instabot-py/instabot.py#1633]
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

```
ValueError: No JSON object could be decoded
```

## Config

```
Traceback (most recent call last):
  File "/Users/NAME/Desktop/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['the_casual_one', 'stefaniehaukenfers'])
  File "/Users/NAME/Desktop/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/Users/NAME/Desktop/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/NAME/Desktop/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by ColeShelly** [comment]
Same Here..

**Comment by ColeShelly** [comment]
Try using Python 3

**Comment by LopesX** [comment]
Teste with my fork: https://github.com/LopesX/instabot.py
