### ISSUE TITLE
Attempts login. Doesn't run. Traceback (most recent call last)

### ISSUE THREAD

**Issue by meggiejenny** [instabot-py/instabot.py#1635]
When attempting to run, I only get the following message:

02.10.2018_13:57 Trying to login as [mylogininfo]...

Traceback (most recent call last):
  File "c:/Users/me/Desktop/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\Users\me\Desktop\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "c:\Users\me\Desktop\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "c:\Users\me\Desktop\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
PS C:\Users\me>

**Comment by hackthefap** [comment]
Same happened to me.

**Comment by hackthefap** [comment]
v@v:~/InstagramBot/instabot.py$ python example.py 
03.10.2018_12:03 Instabot v1.2.0 started at 03.10.2018 12:03:

03.10.2018_12:03 Trying to login as droneandtimelapse...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/v/InstagramBot/instabot.py/src/instabot.py", line 234, in __init__
    self.login()
  File "/home/v/InstagramBot/instabot.py/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/v/InstagramBot/instabot.py/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
v@v:~/InstagramBot/instabot.py$

**Comment by hackthefap** [comment]
meggiejenny
just open userinfo.py in a text editor and change line 42
SOLVED

    downland the last instabot.py
    Change src/userinfo.py Line 42
    json_info = json.loads(re.search(r'>window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))

**Comment by clickandwatch** [comment]
Worked for me, thanks
