### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by kixiro** [instabot-py/instabot.py#1640]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

```
Traceback (most recent call last):
  File "/home/web/src/instabot.py/src/instabot.py", line 380, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
INFO:toxa742:Get Media by tag: #algorithms
```

## Config

```
bot = InstaBot(
    login="xxx",
    password="xxx",
    like_per_day=1000,
    tag_list=['#coding', '#python', '#algorithms', '#skill', '#vim', '#bash'],
    max_like_for_one_tag=50,
    log_mod=1)
```

**Comment by kixiro** [comment]
Oxxxx... tags not contained '#'
