### ISSUE TITLE
Im getting an error, line 56?

### ISSUE THREAD

**Issue by P2PMartin** [instabot-py/instabot.py#1650]
Hi. When i try to run the example.py i get this message:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DK\P2P\example.py", line 56, in <module>
    unfollow_whitelist=[])
  File "C:\Users\Administrator\Desktop\DK\P2P\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\Administrator\Desktop\DK\P2P\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Administrator\Desktop\DK\P2P\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

Do anyone know how i can get this bot running?

**Comment by som-m** [comment]
https://github.com/instabot-py/instabot.py/commit/806e09414f73a461bdb81fd6d4fc2e1e34a54ef8

replace line 42 with the code in green

**Comment by P2PMartin** [comment]
Thank you so much! But it dont understand it, can you explain what this means?😊
