### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by vikomte** [instabot-py/instabot.py#1653]
09.10.2018_12:49 Instabot v1.2.0 started at 09.10.2018 12:49:

09.10.2018_12:49 Trying to login as example_user...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/me/INSTA/new_instab/src/instabot.py", line 234, in __init__
    self.login()
  File "/Users/me/INSTA/new_instab/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/me/INSTA/new_instab/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by vikomte** [comment]
My instabot was working before the insta update few month ago
