### ISSUE TITLE
Traceback (most recent call last): & AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Sniggii** [instabot-py/instabot.py#1669]
Error:
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\nikob\Desktop\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\nikob\Desktop\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\nikob\Desktop\instabot.py-master\src\userinfo.py", line 355, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by rajdeepbharati** [comment]
I am also having the same error.

**Comment by 5ergi0** [comment]
Same for me. But the error in userninfo.py in my case is in line 42 not in line 355.

**Comment by 5ergi0** [comment]
I fixed my issue changing src/userinfo.py line 42 to below.

`json_info = json.loads(re.search('{"activity.+gatekeepers', info.text, re.DOTALL).group(0)+'":""}')`

I don't know if this will work with you. I think you have ''json_info'' in line 355 and not in line 42 like me. Wish you luck!

**Comment by 5ergi0** [comment]
Actually our issue is solved in [#1509](https://github.com/instabot-py/instabot.py/issues/1509#issuecomment-414965794).
Just open this file that you can find in your instabot.py-master folder with a text editor for code like ''sublime text'' and replace line 42 with that code. Hope this helps you.

**Comment by rajdeepbharati** [comment]
Yes it is solved now. Thank you for sharing the solution!

**Comment by json144** [comment]
This is the error I keep getting, please help:

Traceback (most recent call last):
  File "c:/Users/Jean/Desktop/instabot.py-master 1/example2.py", line 58, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\instabot.py", line 234, in __init__
    self.login()
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\instabot.py", line 304, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\userinfo.py", line 41, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
