### ISSUE TITLE
Fake user agent broke again

### ISSUE THREAD

**Issue by koeniig2** [instabot-py/instabot.py#1695]
/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/scripts/instabot.py-master/example.py" && exit
py-master/example.py" && exit            <
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/scripts/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/storage/emulated/0/qpython/scripts/instabot.py-master/src/instabot.py", line 165, in __init__
    fake_ua = UserAgent()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.10-py2.7.egg/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.10-py2.7.egg/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.10-py2.7.egg/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.10-py2.7.egg/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.10-py2.7.egg/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.10-py2.7.egg/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
1|dreamlte:/ $

Every few weeks my bot stop working cause of this error

**Comment by ronecharles** [comment]
yep, same here.

**Comment by ronecharles** [comment]
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by koeniig2** [comment]
Anyone????

**Comment by ronecharles** [comment]
pip install -U fake-useragent

its work for me.

**Comment by koeniig2** [comment]
@ronecharles 

ython.qpy/files/bin/qpypi.py" && exit    <
Input pip commands, ie: pip install {module} OR pip help
-->pip install -U fake-useragent
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/bin/pip", line 4, in <module>
    from pkg_resources import load_entry_point
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==9.0.3
-->

**Comment by koeniig2** [comment]
@SchillerPaul 

ython.qpy/files/bin/qpypi.py" && exit    <
Input pip commands, ie: pip install {module} OR pip help
-->pip install -U fake-useragent
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/bin/pip", line 4, in <module>
    from pkg_resources import load_entry_point
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==9.0.3
-->

**Comment by koeniig2** [comment]
Can someone help?

**Comment by b4ckbre4ker** [comment]
same issue, cant find this solution.

**Comment by koeniig2** [comment]
Help us please

**Comment by joe6ar** [comment]
pip install -U fake-useragent --user

Worked for me

**Comment by b4ckbre4ker** [comment]
> pip install -U fake-useragent --user
> 
> Worked for me

just placing this in command?

**Comment by joe6ar** [comment]
> > pip install -U fake-useragent --user
> > Worked for me
> 
> just placing this in command?

I'm using macOS Terminal, opened new shell, first command 'pip install -U fake-useragent --user'
After receiving 'Successfully installed fake-useragent-0.1.11' just launch and run instabot as before
If this doesn't work I can't really help as my knowledge is limited!

**Comment by b4ckbre4ker** [comment]
> > > pip install -U fake-useragent --user
> > > Worked for me
> > 
> > 
> > just placing this in command?
> 
> I'm using macOS Terminal, opened new shell, first command 'pip install -U fake-useragent --user'
> After receiving 'Successfully installed fake-useragent-0.1.11' just launch and run instabot as before
> If this doesn't work I can't really help as my knowledge is limited!

thanks, seemed to work, just instead of pasting pip install i had to do pip3.7 install
some others might be needing to do same... thanks again!

**Comment by koeniig2** [comment]
@b4ckbre4ker /data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/data/user/0/org.qpython.qpy/files/bin/qpypi.py" && exit
ython.qpy/files/bin/qpypi.py" && exit    <
Input pip commands, ie: pip install {module} OR pip help
-->pip3.7 install -U fake-useragent --user
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/bin/pip", line 4, in <module>
    from pkg_resources import load_entry_point
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==9.0.3
-->

----I use qpython
----i tried type in the command (pip3.7 install) and this error above comes
---- can you explain how exactly you type in the pip? I dont really understand where else to type it in qpython on android

**Comment by koeniig2** [comment]
@b4ckbre4ker i did, but when i start the script it says

raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
1|dreamlte:/ $

**Comment by b4ckbre4ker** [comment]
I’m not sure with android and qpython. I’m in Mac and using python3.7

**Comment by koeniig2** [comment]
Can someone help with qpython

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
