### ISSUE TITLE
unfollow mode2 

### ISSUE THREAD

**Issue by ar8001** [instabot-py/instabot.py#1704]
Any idea why unfollow doesn't work?

01.11.2018_16:46 Current Index = 34 of 71 medias
Traceback (most recent call last):
  File "2bot.py", line 97, in <module>
    bot.new_auto_mod()
  File "/home/pi/instagrambot/ibot2/src/instabot.py", line 722, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/home/pi/instagrambot/ibot2/src/instabot.py", line 787, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/home/pi/instagrambot/ibot2/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/home/pi/instagrambot/ibot2/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/home/pi/instagrambot/ibot2/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/home/pi/instagrambot/ibot2/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/home/pi/instagrambot/ibot2/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
01.11.2018_16:46 Trying to unfollow: 2521997823

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
