### ISSUE TITLE
Instabot - NameError: global name 'id_user' is not defined

### ISSUE THREAD

**Issue by rfrecka** [instabot-py/instabot.py#1707]
I'm sure this is something incredibly simple I missed but here is the readout I've gotten from python upon attempting login:

02.11.2018_01:41 Instabot v1.2.0 started at 02.11.2018 01:41:

02.11.2018_01:41 Trying to login as REDACTED...

Traceback (most recent call last):
  File "custom.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/REDACTED/Desktop/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/home/REDACTED/Desktop/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/REDACTED/Desktop/instabot.py-master/src/userinfo.py", line 43, in get_user_id_by_login
    return id_user
NameError: global name 'id_user' is not defined

First time on GitHub, just trying to tinker with python and didn't find this specific issue solved in my searches.

Any input would be greatly appreciated, thanks in advance!

**Comment by JonDowes** [comment]
I think Instabot is down. Alot of people are having this issue and the last update was like 7 months ago

**Comment by rfrecka** [comment]
> I think Instabot is down. Alot of people are having this issue and the last update was like 7 months ago

I've read several people on these forums using the example.py template as late as September 28, 2018 with success. Perhaps they modified it but I am assuming their must be a workaround. Hoping someone has encountered this issue before, it is a good point that the bot template hasn't been updated for a period.

**Comment by sourstripe** [comment]
I am having a kind of similar issue

Traceback (most recent call last):
  File "example.py", line 55, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\xxx\Desktop\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\xxx\Desktop\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\xxx\Desktop\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by alanifotis** [comment]
i am having the same problem i hope anyone more experienced can help us

root@xxxx-Ubuntu:/home/xxxx/Downloads/instabot.py-master# python2 example.py
04.11.2018_19:11 Instabot v1.2.0 started at 04.11.2018 19:11:

04.11.2018_19:11 Trying to login as xxxx...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/xxxx/Downloads/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/home/xxxx/Downloads/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/xxxx/Downloads/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by alanifotis** [comment]
i 

> I have searched for other issues with the same problem. (including #1153)
> 
> Hosting
> No VPS or cloud hosting.
> Ran code locally, below errors described.
> Select one:
> Technical Help
> Operating System?
> Linux (Ubuntu 18.04.1 LTS)
> Python Version?
> 3.6.6
> Description of your issue
> Immediately following a login attempt I am barred from connection, no actions taken by bot.
> Config
> I'm sure this is something incredibly simple I missed but here is the readout I've gotten from python upon attempting login:
> 
> 02.11.2018_01:41 Instabot v1.2.0 started at 02.11.2018 01:41:
> 
> 02.11.2018_01:41 Trying to login as REDACTED...
> 
> Traceback (most recent call last):
> File "custom.py", line 52, in 
> unfollow_whitelist=['example_user_1', 'example_user_2'])
> File "/home/REDACTED/Desktop/instabot.py-master/src/instabot.py", line 234, in **init**
> self.login()
> File "/home/REDACTED/Desktop/instabot.py-master/src/instabot.py", line 303, in login
> self.user_id = ui.get_user_id_by_login(self.user_login)
> File "/home/REDACTED/Desktop/instabot.py-master/src/userinfo.py", line 43, in get_user_id_by_login
> return id_user
> NameError: global name 'id_user' is not defined
> 
> First time on GitHub, just trying to tinker with python and didn't find this specific issue solved in my searches.
> 
> Any input would be greatly appreciated, thanks in advance!

you should start from the beginning
first command 
pip3 install -r requirements.txt

second command
sudo python3 example.py

if you get this error after that:

root@xxxx-Ubuntu:/home/xxxx/Downloads/instabot.py-master# python2 example.py
04.11.2018_19:11 Instabot v1.2.0 started at 04.11.2018 19:11:

04.11.2018_19:11 Trying to login as xxxx...

Traceback (most recent call last):
File "example.py", line 52, in 
unfollow_whitelist=['example_user_1', 'example_user_2'])
File "/home/xxxx/Downloads/instabot.py-master/src/instabot.py", line 234, in init
self.login()
File "/home/xxxx/Downloads/instabot.py-master/src/instabot.py", line 303, in login
self.user_id = ui.get_user_id_by_login(self.user_login)
File "/home/xxxx/Downloads/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

you should find the file named userinfo.py
and the line 42 from: json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}') to json_info = json.loads(re.search('{"activity_counts.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
and it will work like a charm 
at least it did for me

**Comment by sourstripe** [comment]
> 
> 
> i
> 
> > I have searched for other issues with the same problem. (including #1153)
> > Hosting
> > No VPS or cloud hosting.
> > Ran code locally, below errors described.
> > Select one:
> > Technical Help
> > Operating System?
> > Linux (Ubuntu 18.04.1 LTS)
> > Python Version?
> > 3.6.6
> > Description of your issue
> > Immediately following a login attempt I am barred from connection, no actions taken by bot.
> > Config
> > I'm sure this is something incredibly simple I missed but here is the readout I've gotten from python upon attempting login:
> > 02.11.2018_01:41 Instabot v1.2.0 started at 02.11.2018 01:41:
> > 02.11.2018_01:41 Trying to login as REDACTED...
> > Traceback (most recent call last):
> > File "custom.py", line 52, in
> > unfollow_whitelist=['example_user_1', 'example_user_2'])
> > File "/home/REDACTED/Desktop/instabot.py-master/src/instabot.py", line 234, in **init**
> > self.login()
> > File "/home/REDACTED/Desktop/instabot.py-master/src/instabot.py", line 303, in login
> > self.user_id = ui.get_user_id_by_login(self.user_login)
> > File "/home/REDACTED/Desktop/instabot.py-master/src/userinfo.py", line 43, in get_user_id_by_login
> > return id_user
> > NameError: global name 'id_user' is not defined
> > First time on GitHub, just trying to tinker with python and didn't find this specific issue solved in my searches.
> > Any input would be greatly appreciated, thanks in advance!
> 
> you should start from the beginning
> first command
> pip3 install -r requirements.txt
> 
> second command
> sudo python3 example.py
> 
> if you get this error after that:
> 
> root@xxxx-Ubuntu:/home/xxxx/Downloads/instabot.py-master# python2 example.py
> 04.11.2018_19:11 Instabot v1.2.0 started at 04.11.2018 19:11:
> 
> 04.11.2018_19:11 Trying to login as xxxx...
> 
> Traceback (most recent call last):
> File "example.py", line 52, in
> unfollow_whitelist=['example_user_1', 'example_user_2'])
> File "/home/xxxx/Downloads/instabot.py-master/src/instabot.py", line 234, in init
> self.login()
> File "/home/xxxx/Downloads/instabot.py-master/src/instabot.py", line 303, in login
> self.user_id = ui.get_user_id_by_login(self.user_login)
> File "/home/xxxx/Downloads/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
> json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
> AttributeError: 'NoneType' object has no attribute 'group'
> 
> you should find the file named userinfo.py
> and the line 42 from: json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}') to json_info = json.loads(re.search('{"activity_counts.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
> and it will work like a charm
> at least it did for me

That did the trick for me too! Genius. Thank you!

**Comment by santiarizam** [comment]
Hello,

> i
> 
> > I have searched for other issues with the same problem. (including #1153)
> > Hosting
> > No VPS or cloud hosting.
> > Ran code locally, below errors described.
> > Select one:
> > Technical Help
> > Operating System?
> > Linux (Ubuntu 18.04.1 LTS)
> > Python Version?
> > 3.6.6
> > Description of your issue
> > Immediately following a login attempt I am barred from connection, no actions taken by bot.
> > Config
> > I'm sure this is something incredibly simple I missed but here is the readout I've gotten from python upon attempting login:
> > 02.11.2018_01:41 Instabot v1.2.0 started at 02.11.2018 01:41:
> > 02.11.2018_01:41 Trying to login as REDACTED...
> > Traceback (most recent call last):
> > File "custom.py", line 52, in
> > unfollow_whitelist=['example_user_1', 'example_user_2'])
> > File "/home/REDACTED/Desktop/instabot.py-master/src/instabot.py", line 234, in **init**
> > self.login()
> > File "/home/REDACTED/Desktop/instabot.py-master/src/instabot.py", line 303, in login
> > self.user_id = ui.get_user_id_by_login(self.user_login)
> > File "/home/REDACTED/Desktop/instabot.py-master/src/userinfo.py", line 43, in get_user_id_by_login
> > return id_user
> > NameError: global name 'id_user' is not defined
> > First time on GitHub, just trying to tinker with python and didn't find this specific issue solved in my searches.
> > Any input would be greatly appreciated, thanks in advance!
> 
> you should start from the beginning
> first command
> pip3 install -r requirements.txt
> 
> second command
> sudo python3 example.py
> 
> if you get this error after that:
> 
> root@xxxx-Ubuntu:/home/xxxx/Downloads/instabot.py-master# python2 example.py
> 04.11.2018_19:11 Instabot v1.2.0 started at 04.11.2018 19:11:
> 
> 04.11.2018_19:11 Trying to login as xxxx...
> 
> Traceback (most recent call last):
> File "example.py", line 52, in
> unfollow_whitelist=['example_user_1', 'example_user_2'])
> File "/home/xxxx/Downloads/instabot.py-master/src/instabot.py", line 234, in init
> self.login()
> File "/home/xxxx/Downloads/instabot.py-master/src/instabot.py", line 303, in login
> self.user_id = ui.get_user_id_by_login(self.user_login)
> File "/home/xxxx/Downloads/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
> json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
> AttributeError: 'NoneType' object has no attribute 'group'
> 
> you should find the file named userinfo.py
> and the line 42 from: json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}') to json_info = json.loads(re.search('{"activity_counts.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
> and it will work like a charm
> at least it did for me

Hey,

I did that of sudo pynthon3 example.py  and then asked me for a password:
Like this: I try to type my instagram pw but didn't work. I'm in a mac computer
xxxxx-MacBook:instabot.py-master xxxxx$ sudo pynthon3 example.py
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:

**Comment by TheNazareen** [comment]
hi !!
he didn't work for me :-(

C:\Users\Le_Nazareen\Documents\instabot\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Le_Nazareen\Documents\instabot\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Le_Nazareen\Documents\instabot\instabot.py-master\src\instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "C:\Users\Le_Nazareen\Documents\instabot\instabot.py-master\src\userinfo.py", line 44
    return id_user
    ^
IndentationError: unexpected indent

please help
