### ISSUE TITLE
Problems with logging in

### ISSUE THREAD

**Issue by limboy95** [instabot-py/instabot.py#1716]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue
Please I continously get this error anyone an idea about solving line 233 288 of instabot and 328 399 for requests cookies?
```
ITraceback (most recent call last):
  File "C:\Users\LenovoX200\Desktop\instabot.py-master\photography.py", line 49, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\LenovoX200\Desktop\instabot.py-master\src\instabot.py", line 233, in __init__
    self.login()
  File "C:\Users\LenovoX200\Desktop\instabot.py-master\src\instabot.py", line 288, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "C:\Users\LenovoX200\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\LenovoX200\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
