### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Gabro89r** [instabot-py/instabot.py#1717]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [NO] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [X] 2.7.10
- [] 3.x

## Description of your issue

```
$ python /XXX/XXX/Desktop/instabot.py-master/example.py
Traceback (most recent call last):
  File "/XXX/XXX/Desktop/instabot.py-master/example.py", line 6, in <module>
    from src import InstaBot
  File "/XXX/XXX/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/XXX/XXX/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/XXX/XXX/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests

**Comment by ofekch** [comment]
you need to install the module requests,
if you have pip, run this command in cmd:
pip install requests

**Comment by Gabro89r** [comment]
> you need to install the module requests,
> if you have pip, run this command in cmd:
> pip install requests

I did it, but now says:

Traceback (most recent call last):
  File "/XXX/XXX/Desktop/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/XXX/XXX/Desktop/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/XXX/XXX/Desktop/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/XXX/XXX/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

anyone know what does it mean?

**Comment by Gabro89r** [comment]
Traceback (most recent call last):
  File "/XXX/XXX/XXX/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['XXX', 'sony', 'apple', 'n26', 'satispay', 'hypeapp', 'ig_europe', '_igeuropa', 'ig_italia', 'sonyalpha'])
  File "/XXX/XXX/XXX/instabot.py-master/src/instabot.py", line 234, in init
    self.login()
  File "/XXX/XXX/XXX/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/XXX/XXX/XXX/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity_.+(}(?=.*</script>))', info.text).group(0))
AttributeError: 'NoneType' object has no attribute 'group'


I got this issue now. Can someone help me??

**Comment by TheNazareen** [comment]
Hi everybody !
i have the same issue than you Gabro89r ! i do not understand where is the problem. Is there anyone who can help us please

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/pull/1732
