### ISSUE TITLE
KeyError: Likes

### ISSUE THREAD

**Issue by Gabro89r** [instabot-py/instabot.py#1724]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [X] 2.7.15.
- [ ] 3.x

## Description of your issue

```
I've got this issues on mode 2. After 1min it logs out:

09.11.2018_10:26 XXXXXXXXX login success!
09.11.2018_10:26 Get Media by tag: viaggiare
09.11.2018_10:26 Removing already liked medias..
09.11.2018_10:26 Trying to like media: 1908706610152548645
09.11.2018_10:26 Liked: 1908706610152548645. Like #1.
09.11.2018_10:26 Trying to follow: 8595121375
09.11.2018_10:26 Followed: 8595121375 #1.
09.11.2018_10:26 XXXXXXXXXXXX : Get media id on recent feed
 09.11.2018 10:26
09.11.2018_10:26 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
09.11.2018_10:26 XXXXXXXXXXXX : Get media id on recent feed
 09.11.2018 10:26
09.11.2018_10:26 Except on get media!!
09.11.2018_10:27 ======> Get media id by Tag <======
09.11.2018_10:27 Get media by user success!
09.11.2018_10:27 Current Index = 57 of 70 medias
Traceback (most recent call last):
  File "/XXX/XXX/YY/instabot.py-master/example.py", line 94, in <module>
    bot.new_auto_mod()
  File "/XXX/XXX/YY/instabot.py-master/src/instabot.py", line 722, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/XXX/XXX/YY/instabot.py-master/src/instabot.py", line 787, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/XXX/XXX/YY/instabot.py-master/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/XXX/XXX/YY/instabot.py-master/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/XXX/XXX/YY/instabot.py-master/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/XXX/XXX/YY/instabot.py-master/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/XXX/XXX/YY/instabot.py-master/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
09.11.2018_10:27 Trying to unfollow: 8595121375
09.11.2018_10:27 Unfollow: 8595121375 #1 of 0.
09.11.2018_10:27 Pausing for 30 seconds... 1 of 0
09.11.2018_10:27 Logout: likes - 1, follow - 0, unfollow - 1, comments - 0.
09.11.2018_10:27 Bot work time: 0:01:34.948046
09.11.2018_10:27 Logout success!

```
config
```

#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="XXXX",
    password="YYYYY!",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['viaggiare', 'viaggiando', 'italia', 'igitalia', 'igeurope', 'europa'],
    tag_blacklist=['hotgirl'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")
```

```

**Comment by yakuzy** [comment]
I had exact the same issue and this one was the solution for me: https://github.com/instabot-py/instabot.py/blob/191c960aa78068a96d64e4ac0f9948e73bbd72d4/src/likers_protocol.py

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
