### ISSUE TITLE
Likes one photo then logs out! Please assist!

### ISSUE THREAD

**Issue by xmeggsx** [instabot-py/instabot.py#1738]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [x] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
I have the bot running, but every time it logs in it only follows one person and likes only one photo. I have gone through countless other q/a concerning the same issue, but I can't figure out how to fix this. It only stays logged in for a couple seconds, and this is the only account I am using with this program. I am running this through visual studio code installed on my computer.
```
C:\Users\m>"c:\Users\m\Desktop\instabot.py-master REVISED\instabot.py-master\example.py"
13.11.2018_16:44 Instabot v1.2.0 started at 13.11.2018 16:44:

13.11.2018_16:44 Trying to login as myusernamehiddenfromchat...

13.11.2018_16:45 myusernamehiddenfromchat login success!
13.11.2018_16:45 Get Media by tag: fairseason
13.11.2018_16:45 Removing already liked medias..
13.11.2018_16:45 Trying to like media: 1911968297765335312
13.11.2018_16:45 Liked: 1911968297765335312. Like #1.
13.11.2018_16:45 Keep calm - It's your own profile ;)
13.11.2018_16:45 myusernamehiddenfromchat : Get media id on recent feed
 13.11.2018 16:45
13.11.2018_16:45 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
13.11.2018_16:46 myusernamehiddenfromchat : Get media id on recent feed
 13.11.2018 16:46
13.11.2018_16:46 Except on get media!!
13.11.2018_16:46 ======> Get media id by Tag <======
13.11.2018_16:46 Get media by user success!
13.11.2018_16:46 Current Index = 25 of 67 medias
Traceback (most recent call last):
  File "C:\Users\m\Desktop\instabot.py-master REVISED\instabot.py-master\example.py", line 94, in <module>
    bot.new_auto_mod()
  File "C:\Users\m\Desktop\instabot.py-master REVISED\instabot.py-master\src\instabot.py", line 732, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\m\Desktop\instabot.py-master REVISED\instabot.py-master\src\instabot.py", line 797, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "C:\Users\m\Desktop\instabot.py-master REVISED\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "C:\Users\m\Desktop\instabot.py-master REVISED\instabot.py-master\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "C:\Users\m\Desktop\instabot.py-master REVISED\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\m\Desktop\instabot.py-master REVISED\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\m\Desktop\instabot.py-master REVISED\instabot.py-master\src\likers_protocol.py", line 18, in likers_protocol
    likes_count = get_likes_count(self)
NameError: name 'get_likes_count' is not defined
13.11.2018_16:46 Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
13.11.2018_16:46 Bot work time: 0:01:58.442579
13.11.2018_16:46 Logout success!.
```

## Config

```#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="usernamehiddenfromchat",
    password="passwordhiddenfromchat",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=[ 'fair', 'fairground', 'fallfashion', 'shetravels', 'groovy', 'coffeeshopvibes', 'l:212999109'],
    tag_blacklist=['sexy', 'hot', 'cute', 'beautiful' , 'steamy', 'gorgeous', 'babe', 'sex',],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=2 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['johnmayer'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")


```

**Comment by Brcalvo** [comment]
The same issue here. Mode 0 works well, but if I try to use model 2, I get the same error.

**Comment by Brcalvo** [comment]
> same error. try mode 0

Yes, mode 0 works well, but I want to use mode 2 to be sure I don´t unfollow anyone who follows me!

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
