### ISSUE TITLE
Instabot - Error on trying to login - 1st Configuration

### ISSUE THREAD

**Issue by axbstreet** [instabot-py/instabot.py#1766]
## Hosting
Python - Local machine

#### Select one:
- [X] Technical Help

### Operating System? (include version)
- [X ] Windows

## Python Version?
- [X] 3.7.1

## Description of your issue

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\abphf16.DESKTOP-2DKHBB3\Downloads\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\abphf16.DESKTOP-2DKHBB3\Downloads\instabot.py-master\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\abphf16.DESKTOP-2DKHBB3\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\abphf16.DESKTOP-2DKHBB3\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

## Config

#!/usr/bin/env python
 -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="username",
    password="password",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['streetlife_mag', 'streetscenemag', 'streetleaks', 'ig_streets', 'zonestreet', 'worldstreetfeature', 'streethubchallenge', 'world_street_photographers', 'street_perfection', 'human_streetphoto', 'streetfeat', 'best_streetview', 'streets_focus_on', 'beststreets', 'streets_oftheworld', 'capturestreets', 'worldstreetphotography', 'streetizm', 'streets_storytelling', 'eyeshotmag', 'fstopmagazine', 'observecollective', 'yallersStreet', 'wearethestreets', 'timeless_Streets', 'hsp_new_talent', 'fivesixmag', 'storyofthestreet', 'worldstreetfeature'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

**Comment by tbela9111** [comment]
same problem

**Comment by sezerc** [comment]
same problem please help

**Comment by bennibenny** [comment]
it won't be fixed

**Comment by mistermagon** [comment]
why won't it be fixed?

**Comment by axbstreet** [comment]
can someone suggest us, at least, an old stable version with a functioning code?

**Comment by anchelote** [comment]
Replace line 287 in instabot.py
self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})

with this:
csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})

This worked for me

**Comment by Nadastique** [comment]
> Replace line 287 in instabot.py
> self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
> 
> with this:
> csrf_token = re.search('(?<="csrf_token":")\w+', r.text).group(0)
> self.s.headers.update({'X-CSRFToken': csrf_token})
> 
> This worked for me

and 2 days later, it comes back...
`Traceback (most recent call last):
  File "****.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/******/Pictures/igbot/src/instabot.py", line 236, in __init__
    self.login()
  File "/Users/******/Pictures/igbot/src/instabot.py", line 292, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"`

**Comment by pablo3600** [comment]
which folder or file is modified line 278 in example.py? I only see up to 111 line or is another file please someone explain it a little more detailed. it works a week ago well the instabot and from one day to the next throws me this problem.


Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\casapc\Downloads\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\casapc\Downloads\instabot.py-master\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

C:\Users\casapc\Downloads\instabot.py-master>

**Comment by pablo3600** [comment]
modify the file instabot.py line 287 and I throw the following error.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\casapc\Downloads\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\casapc\Downloads\instabot.py-master\src\instabot.py", line 287, in login
    csrf_token = re.search ('(? <= "csrf_token": ") \ w +', r.text) .group (0)
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\re.py", line 183, in search
    return _compile(pattern, flags).search(string)
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 806, in _parse
    len(char) + 1)
re.error: unknown extension ?  at position 1

C:\Users\casapc\Downloads\instabot.py-master>

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



Instabot worked well for me a week ago, I stopped using it for a few days and when I went back to using it the error that it gives me is this.


Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\casapc\Downloads\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\casapc\Downloads\instabot.py-master\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\casapc\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

C:\Users\casapc\Downloads\instabot.py-master>


any help please. hopefully among all we found a solution, I see that I'm not the only one who happens this  thanks

**Comment by pablo3600** [comment]
What desperation with instabot does not work for me in any way please someone to help us.

Does anyone know why this has stopped working or is it due?

I just worked hard 2 weeks I stopped using it a few days and I already jumped errors without modifying anything from any file

Really, it's crap.

**Comment by pablo3600** [comment]
I had the same error you mentioned.
I made the change in line 287 and for one hour it worked but 


he stopped and threw the following error







  File "example.py", line 94, in <module>
    bot.new_auto_mod()
  File "C:\Users\casapc\Downloads\instabot.py-master\src\instabot.py", line 733, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\casapc\Downloads\instabot.py-master\src\instabot.py", line 798, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "C:\Users\casapc\Downloads\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "C:\Users\casapc\Downloads\instabot.py-master\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "C:\Users\casapc\Downloads\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\casapc\Downloads\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\casapc\Downloads\instabot.py-master\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
08.12.2018_13:36 Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
08.12.2018_13:36 Bot work time: 0:00:57.476414
08.12.2018_13:36 Logout success!





----------    someone who can help instabot work well

**Comment by alex-s435** [comment]
Same here

**Comment by pablo3600** [comment]
When starting instabot, it launches the same problem that the partner mentioned at the beginning.

change line 287, if I leave it as it was, it also throws me an error.

that solution to change line 287 only works for a few hours


this is the error



09.12.2018_11:57 Trying to login as walterMVM...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\walter\Downloads\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\ walter\Downloads\instabot.py-master\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\ walter\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\ walter\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
