### ISSUE TITLE
error to run

### ISSUE THREAD

**Issue by SudnerKrush** [instabot-py/instabot.py#1767]
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\SK\Desktop\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\SK\Desktop\instabot.py-master\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\SK\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\SK\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by mistermagon** [comment]
same for me

**Comment by mohamad171** [comment]
read this comment
[issue](https://github.com/instabot-py/instabot.py/issues/1366#issuecomment-400852889
)
solved it

**Comment by mistermagon** [comment]
Didn't solve it, it brings up a new error

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/xxx/Desktop/instabot.py-master/src/instabot.py", line 236, in __init__
    self.login()
  File "/Users/xxx/Desktop/instabot.py-master/src/instabot.py", line 292, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
xxx-MBP:instabot.py-master xxx$

**Comment by axbstreet** [comment]
After modifying the code mohamad171 was talking about, I got another error.

C:\Users\abphf16.DESKTOP-2DKHBB3\Downloads\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\abphf16.DESKTOP-2DKHBB3\Downloads\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\abphf16.DESKTOP-2DKHBB3\Downloads\instabot.py-master\src\instabot.py", line 289
    time.sleep(5 * random.random())
    ^
IndentationError: unexpected indent

**Comment by bennibenny** [comment]
I've got the same error!

**Comment by sezerc** [comment]
> read this comment
> [issue](https://github.com/instabot-py/instabot.py/issues/1366#issuecomment-400852889)
> solved it

you didnt solved it dude
we all get

Traceback (most recent call last):
File "example.py", line 52, in 
unfollow_whitelist=['example_user_1', 'example_user_2'])
File "/Users/xxx/Desktop/instabot.py-master/src/instabot.py", line 236, in init
self.login()
File "/Users/xxx/Desktop/instabot.py-master/src/instabot.py", line 292, in login
self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
File "/Library/Python/2.7/site-packages/requests/cookies.py", line 328, in getitem
return self._find_no_duplicates(name)
File "/Library/Python/2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
xxx-MBP:instabot.py-master xxx$

**Comment by joaoleite20** [comment]
no solution? is this code dead?

**Comment by manguszta** [comment]
Solved for 3 accounts, not solved for 1 account.

**Comment by mistermagon** [comment]
manguszta, no hard feelings but it seems like you can't even count.
Anyone here is a computer genius and can solve this?

**Comment by manguszta** [comment]
> manguszta, no hard feelings but it seems like you can't even count.
> Anyone here is a computer genius and can solve this?

I'm talking about my accounts, genius.

**Comment by iLeGiTiMx** [comment]
Same here on just one Account. I always get the login verification, and when i press "That was me", the some comes again when I start the bot.. Same 'csrftoken' error then

**Comment by tombraider74** [comment]
Same for me, after running some hours, i need to activate insta on my mobile via verification code.

**Comment by rugge89lau** [comment]
> Same here on just one Account. I always get the login verification, and when i press "That was me", the some comes again when I start the bot.. Same 'csrftoken' error then

yes same here :(  I starting to think that instagram can recognize the bot

**Comment by Conikalpha** [comment]
> Didn't solve it, it brings up a new error
> 
> Traceback (most recent call last):
> File "example.py", line 52, in 
> unfollow_whitelist=['example_user_1', 'example_user_2'])
> File "/Users/xxx/Desktop/instabot.py-master/src/instabot.py", line 236, in **init**
> self.login()
> File "/Users/xxx/Desktop/instabot.py-master/src/instabot.py", line 292, in login
> self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
> File "/Library/Python/2.7/site-packages/requests/cookies.py", line 328, in **getitem**
> return self._find_no_duplicates(name)
> File "/Library/Python/2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
> raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
> KeyError: "name='csrftoken', domain=None, path=None"
> xxx-MBP:instabot.py-master xxx$
same here

**Comment by mistermagon** [comment]
After trying not to login for more than 24 hours it works again... but i get the feeling it won't last forever

**Comment by rugge89lau** [comment]
> After trying not to login for more than 24 hours it works again... but i get the feeling it won't last forever

yes, me too...

**Comment by manguszta** [comment]
My 4th account works too.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
