### ISSUE TITLE
ImportError: cannot import name 'get_user_info' from 'src.user_info'

### ISSUE THREAD

**Issue by MartinGagaleski** [instabot-py/instabot.py#1769]
PS C:\Users\Martin\AppData\Roaming\Python\Python37\Scripts> & python c:/Users/Martin/Desktop/instabot.py-master/example.py
Traceback (most recent call last):
  File "c:/Users/Martin/Desktop/instabot.py-master/example.py", line 6, in <module>
    from src import InstaBot
  File "c:\Users\Martin\Desktop\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "c:\Users\Martin\Desktop\instabot.py-master\src\instabot.py", line 5, in <module>
    from .unfollow_protocol import unfollow_protocol
  File "c:\Users\Martin\Desktop\instabot.py-master\src\unfollow_protocol.py", line 7, in <module>
    from .follow_protocol import follow_protocol
  File "c:\Users\Martin\Desktop\instabot.py-master\src\follow_protocol.py", line 6, in <module>
    from .feed_scanner import feed_scanner
  File "c:\Users\Martin\Desktop\instabot.py-master\src\feed_scanner.py", line 6, in <module>
    from .likers_graber_protocol import likers_graber_protocol
  File "c:\Users\Martin\Desktop\instabot.py-master\src\likers_graber_protocol.py", line 8, in <module>
    from .user_feed import get_media_id_user_feed
  File "c:\Users\Martin\Desktop\instabot.py-master\src\user_feed.py", line 7, in <module>
    from .user_info import get_user_info
ImportError: cannot import name 'get_user_info' from 'src.user_info' (c:\Users\Martin\Desktop\instabot.py-master\src\user_info.py)
PS C:\Users\Martin\AppData\Roaming\Python\Python37\Scripts>

**Comment by RCPalStudent** [comment]
Having the same issue.  I run it on Visual Studio Code but I get a box that pops up that says:

"Linter pylint is not installed."

then when I try to install it it says 

"There is no Pip installer available in the selected environment."

Not sure if this has anything to do with the issue we are having but wanted to put that out there.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
