### ISSUE TITLE
Fake useragent not working?

### ISSUE THREAD

**Issue by koeniig2** [instabot-py/instabot.py#1771]
I have this error, someone know whats going on here? I am using qpython on android

/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/scripts/instabot.py-master/example.py" && exit
py-master/example.py" && exit            <
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/scripts/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/storage/emulated/0/qpython/scripts/instabot.py-master/src/instabot.py", line 167, in __init__
    fake_ua = UserAgent()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
1|dreamlte:/ $

**Comment by ChaseEmeryDavis** [comment]
yeah me too but mine is a bit more simple I think:
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src.instabot import InstaBot
  File "/Users/***************/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/***************/Desktop/instabot.py-master/src/instabot.py", line 22, in <module>
    from .fake_useragent import UserAgent
ImportError: No module named fake_useragent

they are write there is no module named fake_useragent, so what module do they mean then?

**Comment by koeniig2** [comment]
an help?

**Comment by gwest123** [comment]
Same issue here.

**Comment by koeniig2** [comment]
Any help?

**Comment by koeniig2** [comment]
Help

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
