### ISSUE TITLE
Cant get it working. Getting some errors.  

### ISSUE THREAD

**Issue by HyronNotEZ** [instabot-py/instabot.py#1804]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < I always get this error and i don't get what i should fix. 

I also don't want to follow and unfollow so i set it to 0. 

C:\Users\dumit\Desktop\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 43, in <module>
    unfollow_whitelist=[])
  File "C:\Users\dumit\Desktop\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\dumit\Desktop\instabot.py-master\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < bot = InstaBot(
    login="XXXXXXXXX",
    password="XXXXXXXXXX",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute', 'ulm', 'l:222859765'],
    tag_blacklist=[],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=0,
    follow_time=0,
    unfollow_per_day=0,
    unfollow_break_min=0,
    unfollow_break_max=0,
    log_mod=1,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=[])
```

**Comment by iLeGiTiMx** [comment]
Same with some accounts. Login authentication loop

**Comment by gincarbone** [comment]
Same problem ... still not resolved :(

**Comment by goochi1** [comment]
haveing same issue

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
