### ISSUE TITLE
Suspicious login 

### ISSUE THREAD

**Issue by michaelosten** [instabot-py/instabot.py#1830]
Getting the following today as well as "Suspicious Login" notification on the iPhone app.

18.12.2018_14:09 Instabot v1.2.0 started at 18.12.2018 14:09:

18.12.2018_14:09 Trying to login as **********...

18.12.2018_14:09 Login error! Connection error!
18.12.2018_14:09 Removing already liked medias..
18.12.2018_14:09 Trying to unfollow #1: 
18.12.2018_14:09 Looks like there is nobody to unfollow.
18.12.2018_14:09 Removing already liked medias..
^CTraceback (most recent call last):
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "/root/INSTAGRAM/12-10-2018/instabot.py/src/instabot.py", line 737, in new_auto_mod
    time.sleep(3)
KeyboardInterrupt

**Comment by arifkaisarn** [comment]
instagram send me email about suspicion attempt, are you get it too ?, 
still have no clue how to fix it.

**Comment by JD2719** [comment]
Same issue here. Ive tried everything so far, no luck.

**Comment by marcusagm** [comment]
See the pull request #1788 
Duplicate of #1812

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks

**Comment by afaque24** [comment]
Hi fool you are Instagrm platform they know you are using bots fool...
