### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by mbe9477** [instabot-py/instabot.py#1831]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue
**Can't login anymore. I searched the open issues but could not find the matching solution for my case.
Hope that anybody can help me.... :(** 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/marcus/Desktop/instabot.py-U/src/instabot.py", line 208, in __init__
    fake_ua = UserAgent()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

## Config

```

```

**Comment by dimisdas** [comment]
pip install certifi

**Comment by mbe9477** [comment]
@dimisdas 
That didn't work

> Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (2018.1.18)

**Comment by dimisdas** [comment]
Seems like you’re running python3, try pip3 instead.

**Comment by therealcalle** [comment]
same here doesn't work. I tried every pip3 install --upgrade Instaloader/fake_useragent/certifi but nothing...

**Comment by mbe9477** [comment]
@dimisdas 
Did not help, too :(
What's the problem here?

> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/marcus/Desktop/instabot.py-U/src/instabot.py", line 208, in __init__
    fake_ua = UserAgent()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by dimisdas** [comment]
I assume from the paths that you're using macOS.

Try going to `cd /Applications/Python\ 3.7/` and run `Install\ Certificates.command`. It seems like a problem with python not using the same CA certificates from the operating system. 

I cannot reproduce your errors. I have installed python3 through [Homebrew](https://brew.sh) using `brew install python3`

**Comment by mbe9477** [comment]
@dimisdas Thanks for your help!
The command `./Install\ Certificates.command` worked for me. (thx to google)
Now bot logged in successfully... I'll see tomorrow if there is any other issue!

**Comment by mbe9477** [comment]
@dimisdas 
It worked fine for about 5 hours. 
Then I got these errors.... Could you help me again to solve this please?

The unfollow is strange because I've set this in examply.py
` unfollow_per_day=1,`
running ` mode = 0`


> Traceback (most recent call last):
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "/Users/marcus/Desktop/instabot.py-U/src/instabot.py", line 847, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/marcus/Desktop/instabot.py-U/src/instabot.py", line 930, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "/Users/marcus/Desktop/instabot.py-U/src/instabot.py", line 955, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
20.12.2018_03:03 Trying to unfollow: 3284101991
20.12.2018_03:03 Unfollow: 3284101991 #1 of 15.
20.12.2018_03:03 Pausing for 29 seconds... 1 of 15
20.12.2018_03:04 Trying to unfollow: 6450689210
20.12.2018_03:04 Unfollow: 6450689210 #2 of 15.
20.12.2018_03:04 Pausing for 27 seconds... 2 of 15
20.12.2018_03:04 Trying to unfollow: 629489688
20.12.2018_03:04 Unfollow: 629489688 #3 of 15.
20.12.2018_03:04 Pausing for 19 seconds... 3 of 15
20.12.2018_03:04 Trying to unfollow: 605398408
20.12.2018_03:05 Unfollow: 605398408 #4 of 15.
20.12.2018_03:05 Pausing for 20 seconds... 4 of 15
20.12.2018_03:05 Trying to unfollow: 180609209
20.12.2018_03:05 Unfollow: 180609209 #5 of 15.
20.12.2018_03:05 Pausing for 15 seconds... 5 of 15
20.12.2018_03:05 Trying to unfollow: 1580759373
20.12.2018_03:05 Slow Down - Pausing for 5 minutes so we don't get banned!
20.12.2018_03:10 Still no good :( Skipping and pausing for another 5 minutes
20.12.2018_03:15 Pausing for 15 seconds... 5 of 15
20.12.2018_03:15 Trying to unfollow: 6173857818
20.12.2018_03:15 Slow Down - Pausing for 5 minutes so we don't get banned!
20.12.2018_03:20 Still no good :( Skipping and pausing for another 5 minutes
20.12.2018_03:25 Pausing for 15 seconds... 5 of 15
20.12.2018_03:26 Trying to unfollow: 223273143
20.12.2018_03:26 Slow Down - Pausing for 5 minutes so we don't get banned!
20.12.2018_03:31 Still no good :( Skipping and pausing for another 5 minutes
20.12.2018_03:36 Pausing for 17 seconds... 5 of 15
20.12.2018_03:36 Trying to unfollow: 5531004747
20.12.2018_03:36 Slow Down - Pausing for 5 minutes so we don't get banned!
20.12.2018_03:41 Still no good :( Skipping and pausing for another 5 minutes
20.12.2018_03:46 Pausing for 29 seconds... 5 of 15
20.12.2018_03:46 Trying to unfollow: 6911495147
20.12.2018_03:46 Slow Down - Pausing for 5 minutes so we don't get banned!
20.12.2018_03:51 Still no good :( Skipping and pausing for another 5 minutes
20.12.2018_03:56 Pausing for 28 seconds... 5 of 15
20.12.2018_03:57 Trying to unfollow: 1999732460
20.12.2018_03:57 Slow Down - Pausing for 5 minutes so we don't get banned!
20.12.2018_04:02 Still no good :( Skipping and pausing for another 5 minutes
20.12.2018_04:07 Pausing for 25 seconds... 5 of 15
20.12.2018_04:07 Trying to unfollow: 1528865816
20.12.2018_04:07 Slow Down - Pausing for 5 minutes so we don't get banned!
20.12.2018_04:12 Still no good :( Skipping and pausing for another 5 minutes
20.12.2018_04:17 Pausing for 24 seconds... 5 of 15
20.12.2018_04:18 Trying to unfollow: 8378346298
20.12.2018_04:18 Slow Down - Pausing for 5 minutes so we don't get banned!
20.12.2018_04:23 Still no good :( Skipping and pausing for another 5 minutes
20.12.2018_04:28 Pausing for 24 seconds... 5 of 15
20.12.2018_04:28 Trying to unfollow: 8895167743
20.12.2018_04:28 Slow Down - Pausing for 5 minutes so we don't get banned!
20.12.2018_04:33 Still no good :( Skipping and pausing for another 5 minutes
20.12.2018_04:38 Pausing for 26 seconds... 5 of 15
20.12.2018_04:39 Logout: likes - 98, follow - 15, unfollow - 5, comments - 43.
20.12.2018_04:39 Bot work time: 5:05:36.178359
20.12.2018_04:39 Logout success!

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
