### ISSUE TITLE
unknown new issue

### ISSUE THREAD

**Issue by naasiri** [instabot-py/instabot.py#1835]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux Ubuntu 18.04
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
I am running Linux Ubuntu 18.04 and python 3.
I haven't changed anything except the Username and Password for my account.

```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/ceoadmin/Downloads/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/ceoadmin/Downloads/instabot.py-master/src/instabot.py", line 24, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

```

## Config

It is the default..I haven't changed anything except the Username and Password as in the Linux tutorial provided.
 
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login=" ",
    password=" ",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute', 'l:212999109'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],

```

**Comment by waynoedm** [comment]
It's looking for 'fake_useragent'.

**Comment by Alexyoe** [comment]
install requirements.txt `pip3 install -r requirements.txt`

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
