### ISSUE TITLE
get_username_by_user_id

### ISSUE THREAD

**Issue by workproduct** [instabot-py/instabot.py#1836]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue

Erroring on fresh install

```
ERROR:root:Except on get_username_by_user_id
Traceback (most recent call last):
  File "E:\_DS\instabot.py\src\instabot.py", line 436, in get_username_by_user_id
    all_data = json.loads(r.text)
  File "C:\Users\workproduct\Anaconda3\envs\py37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\workproduct\Anaconda3\envs\py37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\workproduct\Anaconda3\envs\py37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:root:Except on follow!
```

## Config

```
    login="",
    password="",
    like_per_day=523,
    comments_per_day=0,
    tag_list=['3d','c4d','cgsociety','maxon','design','redshift','CGI','maya','vj','videoart','motiongraphics','adobe','photoshop','psychedelic','houdini','everyday','beeple','filmmaker','otoy','xparticles','octanerender'],
    tag_blacklist=['rain', 'thunderstorm','nsfw'],
    user_blacklist={},
    max_like_for_one_tag=20,
    follow_per_day=150,
    follow_time=1 * 53,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=1,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
```

**Comment by abnerrizzi** [comment]
I am having the same here:

```
ERROR:root:Except on get_username_by_user_id
Traceback (most recent call last):
  File "/home/support/.local/lib/python3.6/site-packages/instabot_py/instabot.py", line 762, in get_username_by_user_id
    profile = instaloader.Profile.from_id(self.instaload.context, user_id)
  File "/home/support/.local/lib/python3.6/site-packages/instaloader/structures.py", line 409, in from_id
    rhx_gis=context.root_rhx_gis)['data']['user']
  File "/home/support/.local/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 507, in root_rhx_gis
    self._root_rhx_gis = self.get_json('', {})['rhx_gis']
KeyError: 'rhx_gis'

```
