### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by fab976** [instabot-py/instabot.py#1838]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue
Hey :)
No Matter what I do, I always get this Traceback error, which I can`t fix on my own. I found a fix like one year ago, but it doesn`t work anymore. I tried every recent fix I found for this Bot, but it didn`t work.
```
Traceback (most recent call last):
  File "Bot.py", line 44, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\FixTets\instabot.py-master (1)\instabot.py-master\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\FixTets\instabot.py-master (1)\instabot.py-master\src\instabot.py", line 289, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"```

Thank you for any help!

**Comment by Alexyoe** [comment]
Have you tried #1788 ? That should fix the csrftoken issue.

**Comment by fab976** [comment]
Yes I did, even checked again the new updated Fix, but still doesn`t work :/ Unfortunately. But thank you for the answer.

**Comment by Candy11kid** [comment]
You Need To Replace instabot.py + userinfo.py 

with this files  ___ http://dapalan.com/3HJi ___ http://dapalan.com/3HR0

**Comment by Candy11kid** [comment]
Hope It Works :)

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
