### ISSUE TITLE
fake user agent in python

### ISSUE THREAD

**Issue by meggiejenny** [instabot-py/instabot.py#1851]
I'm at a loss. Not sure what changed, but I am now receiving this error when trying to log into Python. If someone more clever than myself could help, I would appreciate it. 

PS C:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\concat-map\example> & python c:/Users/me/Desktop/instabot.py-master/example.py
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\utils.py", line 67, in get
    context=context,
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\utils.py", line 67, in get
    context=context,
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/me/Desktop/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\Users\me\Desktop\instabot.py-master\src\instabot.py", line 165, in __init__
    fake_ua = UserAgent()
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\fake.py", line 69, in __init__
    self.load()
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fake_useragent\utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
PS C:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\concat-map\example>

**Comment by rets85** [comment]
Same issue. Started for no apparent reason a few days ago.

**Comment by rsummers23** [comment]
I'm getting the same fake user agent error...Help?

File "/Users/RichieSummers/Desktop/instabot.py-master/src/instabot.py", line 167, in __init__
    fake_ua = UserAgent()
  File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by gwest123** [comment]
Any solutions?

**Comment by bvttle** [comment]
> I'm getting the same fake user agent error...Help?
> 
> File "/Users/RichieSummers/Desktop/instabot.py-master/src/instabot.py", line 167, in **init**
> fake_ua = UserAgent()
> File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 69, in **init**
> self.load()
> File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 78, in load
> verify_ssl=self.verify_ssl,
> File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
> update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
> File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 245, in update
> write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
> File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 189, in load
> verify_ssl=verify_ssl,
> File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 84, in get
> raise FakeUserAgentError('Maximum amount of retries reached')
> fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

Same issue as @rsummers23 here

**Comment by jpmalley** [comment]
Fixed my issue regarding "fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached" by advice from another thread: https://github.com/instabot-py/instabot.py/issues/1829#issuecomment-448297873

> Had the same problem today. Updating the fake_useragent package fixed it.
>
> Open a new terminal window and run (assuming you use pip):
> `pip install fake_useragent --upgrade`
>
> Make sure to restart your shell that is running the bot and then reload your instabot.py.
> Hope that helps!

@rsummers23 @bvttle

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
