### ISSUE TITLE
example.py

### ISSUE THREAD

**Issue by Gx0st** [instabot-py/instabot.py#1854]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- x I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- x If so; have you tried running the code on your local machine? Yes.

#### Select one:
- [ ] Bug
- [ ] Feature Request
- x Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- x Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- x 3.x

## Description of your issue - Example. py

```
Include the contents of the error.log here (if applicable). Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\-> cd desktop/coding
PS C:\Users\-\desktop\coding> cd instabot.py-master
PS C:\Users\-\desktop\coding\instabot.py-master> pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\-\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: fake-useragent in c:\users\-\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (0.1.11)
Requirement already satisfied: instaloader in c:\users\-\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 3)) (4.2)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\-\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\-\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\-\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\-\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (2.8)
PS C:\Users\-\desktop\coding\instabot.py-master> python example.py
26.12.2018_21:12 Checking for updates...
26.12.2018_21:12 You are running the latest stable version
26.12.2018_21:12 Instabot v1.2.0/3 started at 26.12.2018 21:12:
26.12.2018_21:12 Trying to login as -...
26.12.2018_21:13 - login success!

26.12.2018_21:13 Get Media by tag: creative
26.12.2018_21:13 Removing already liked medias..
26.12.2018_21:13 Trying to like media: 1943368193426894107
26.12.2018_21:13 Liked: 1943368193426894107. Like #1.
26.12.2018_21:13 Trying to follow: 7572814964
26.12.2018_21:13 Followed: 7572814964 #1.
26.12.2018_21:13     >>>Waiting for database to populate before unfollowing (progress 1/20)
                        (Will try to populate using recent feed)
26.12.2018_21:13 - : Get media id on recent feed
26.12.2018_21:13 Media in recent feed = 12
26.12.2018_21:13 Inserted user lydia_sweets94 from recent feed
Traceback (most recent call last):
  File "example.py", line 94, in <module>
    bot.new_auto_mod()
  File "C:\Users\-\desktop\coding\instabot.py-master\src\instabot.py", line 855, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\-\desktop\coding\instabot.py-master\src\instabot.py", line 936, in new_auto_mod_unfollow
    self.populate_from_feed()
  File "C:\Users\-\desktop\coding\instabot.py-master\src\instabot.py", line 920, in populate_from_feed
    feed_username = mediafeed_user["node"]["owner"]["username"]
KeyError: 'owner'
26.12.2018_21:13 Trying to unfollow: 7572814964
26.12.2018_21:13 Unfollow: 7572814964 #1 of 1.
26.12.2018_21:13 Pausing for 25 seconds... 1 of 1
26.12.2018_21:13 Logout: likes - 1, follow - 1, unfollow - 1, comments - 0.
26.12.2018_21:13 Bot work time: 0:01:10.620107
26.12.2018_21:13 Logout success!
PS C:\Users\-\desktop\coding\instabot.py-master>
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by darkroker** [comment]
how to update instabot to the last version ?

**Comment by Pitti1981** [comment]
same Problem here...don't know what's wrong...i'm operating on Linux / Raspi

**Comment by jrndope** [comment]
Same error here: KeyError: 'owner', Let me know if there is an update

**Comment by pablo3600** [comment]
better take and do it yourself because for the results that will give you the bot that continually throws errors lose time and the same would have gotten yourself doing your follow unfollow with your finger the bot is a crap if not with time you will give me the reason over normalmene the people who follow the basis of hagstags are users to make bulk as they neither interact with your content or are from countries that the same for the purpose you want do not serve you more than to fatten your list of followers, over there are people that is so stupid that they will just accept the request and it does not start to follow you

**Comment by zeus72** [comment]
Unfortunately seeing the same issue (just installed today):

fhem@fhem:~/instabot.py-master$ python3 example.py
04.01.2019_01:22 Checking for updates...
04.01.2019_01:22 You are running the latest stable version
04.01.2019_01:22 Instabot v1.2.0/3 started at 04.01.2019 01:22:
04.01.2019_01:22 Trying to login as xxxxxxxxxxxxxxxx...
04.01.2019_01:22 xxxxxxxxxxx login success!

04.01.2019_01:22 Get Media by tag: f4f
04.01.2019_01:22 Removing already liked medias..
04.01.2019_01:22 Trying to like media: 1949020523239295120
04.01.2019_01:23 Liked: 1949020523239295120. Like #1.
04.01.2019_01:23 Trying to follow: 7415969485
04.01.2019_01:23 Followed: 7415969485 #1.
04.01.2019_01:23     >>>Waiting for database to populate before unfollowing (progress 3/20)
                        (Will try to populate using recent feed)
04.01.2019_01:23 ampheus72 : Get media id on recent feed
04.01.2019_01:23 Media in recent feed = 11
Traceback (most recent call last):
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "/home/fhem/instabot.py-master/src/instabot.py", line 868, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/home/fhem/instabot.py-master/src/instabot.py", line 954, in new_auto_mod_unfollow
    self.populate_from_feed()
  File "/home/fhem/instabot.py-master/src/instabot.py", line 938, in populate_from_feed
    feed_username = mediafeed_user["node"]["owner"]["username"]
KeyError: 'owner'
04.01.2019_01:23 Trying to unfollow: 7415969485
04.01.2019_01:23 Unfollow: 7415969485 #1 of 1.
04.01.2019_01:23 Pausing for 61 seconds... 1 of 1
04.01.2019_01:24 Logout: likes - 1, follow - 1, unfollow - 1, comments - 0.
04.01.2019_01:24 Bot work time: 0:01:34.773477
04.01.2019_01:24 Logout success!

**Comment by EyezGlazed** [comment]
Same error here. 

`python example.py
06.01.2019_01:54 Checking for updates...
06.01.2019_01:54 You are running the latest stable version
06.01.2019_01:54 Instabot v1.2.0/3 started at 06.01.2019 01:54:
06.01.2019_01:54 Trying to login as myusername...
06.01.2019_01:54 myusername login success!

06.01.2019_01:54 Get Media by tag: blackandwhitephotography
06.01.2019_01:54 Removing already liked medias..
06.01.2019_01:54 Trying to like media: 1950485796310258626
06.01.2019_01:54 Liked: 1950485796310258626. Like #1.
06.01.2019_01:54 Trying to follow: 6630540970
06.01.2019_01:54 Followed: 6630540970 #1.
06.01.2019_01:54     >>>Waiting for database to populate before unfollowing (progress 3/20)
                        (Will try to populate using recent feed)
06.01.2019_01:54 myusername : Get media id on recent feed
06.01.2019_01:54 Media in recent feed = 12
Traceback (most recent call last):
  File "example.py", line 118, in <module>
    bot.new_auto_mod()
  File "C:\Users\myusername\Documents\Programmering\py\instabot.py-master\src\instabot.py", line 868, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\myusername\Documents\Programmering\py\instabot.py-master\src\instabot.py", line 954, in new_auto_mod_unfollow
    self.populate_from_feed()
  File "C:\Users\myusername\Documents\Programmering\py\instabot.py-master\src\instabot.py", line 938, in populate_from_feed
    feed_username = mediafeed_user["node"]["owner"]["username"]
KeyError: 'owner'
06.01.2019_01:54 Trying to unfollow: 6630540970
06.01.2019_01:54 Unfollow: 6630540970 #1 of 1.
06.01.2019_01:54 Pausing for 17 seconds... 1 of 1
06.01.2019_01:55 Logout: likes - 1, follow - 1, unfollow - 1, comments - 0.
06.01.2019_01:55 Bot work time: 0:00:49.811805
06.01.2019_01:55 Logout success!`

**Comment by EyezGlazed** [comment]
Update: 

I couldn't stop wondering about the following line:
```06.01.2019_01:54 >>>Waiting for database to populate before unfollowing (progress 3/20)```

..so I kept running "python example.py" and the number got higher. The time after it had reached "19/20", it started to work! Result:

```
python example.py
06.01.2019_03:00 Checking for updates...
06.01.2019_03:00 You are running the latest stable version
06.01.2019_03:00 Instabot v1.2.0/3 started at 06.01.2019 03:00:
06.01.2019_03:00 Trying to login as myusername...
06.01.2019_03:01 myusername login success!

06.01.2019_03:01 Get Media by tag: blackandwhitephotography
06.01.2019_03:01 Removing already liked medias..
06.01.2019_03:01 Trying to like media: 1950519479809545734
06.01.2019_03:01 Liked: 1950519479809545734. Like #1.
06.01.2019_03:01 Trying to follow: 8978173022
06.01.2019_03:01 Followed: 8978173022 #1.
06.01.2019_03:01 Trying to unfollow #1:
06.01.2019_03:01 found whitelist user, starting search again
06.01.2019_03:01 found whitelist user, starting search again
06.01.2019_03:01 found whitelist user, starting search again
06.01.2019_03:01 found whitelist user, starting search again
06.01.2019_03:01 Getting user info : felixferdi
06.01.2019_03:01 Checking user info..
06.01.2019_03:01 Follower : 288
06.01.2019_03:01 Following : 696
06.01.2019_03:01 Media : 470
06.01.2019_03:01    >>>This is probably Fake account
06.01.2019_03:01    >>>This user is active
06.01.2019_03:01    >>>This account is NOT following you
06.01.2019_03:01    >>>You are following this account
06.01.2019_03:01 felixferdi
06.01.2019_03:01 Unfollowed: 243331872 #1.
06.01.2019_03:02 Trying to like media: 1950517800411653412
06.01.2019_03:02 Liked: 1950517800411653412. Like #2.
```

So, just keep running it until your list is full, and it should continue to do its job without logging in.. or give you another error to troubleshoot if there are more errors in your setup (haha)!

**Comment by Ce0tOS** [comment]
> @zeus72 @jrndope @Gx0st @Pitti1981
> 
> Update:
> 
> I couldn't stop wondering about the following line:
> `06.01.2019_01:54 >>>Waiting for database to populate before unfollowing (progress 3/20)`
> 
> ..so I kept running "python example.py" and the number got higher (almost) each time. The time after it had reached "19/20", it started to work! Result:
> 
> ```python
> 06.01.2019_03:00 Checking for updates...
> 06.01.2019_03:00 You are running the latest stable version
> 06.01.2019_03:00 Instabot v1.2.0/3 started at 06.01.2019 03:00:
> 06.01.2019_03:00 Trying to login as myusername...
> 06.01.2019_03:01 myusername login success!
> 
> 06.01.2019_03:01 Get Media by tag: blackandwhitephotography
> 06.01.2019_03:01 Removing already liked medias..
> 06.01.2019_03:01 Trying to like media: 1950519479809545734
> 06.01.2019_03:01 Liked: 1950519479809545734. Like #1.
> 06.01.2019_03:01 Trying to follow: 8978173022
> 06.01.2019_03:01 Followed: 8978173022 #1.
> 06.01.2019_03:01 Trying to unfollow #1:
> 06.01.2019_03:01 found whitelist user, starting search again
> 06.01.2019_03:01 found whitelist user, starting search again
> 06.01.2019_03:01 found whitelist user, starting search again
> 06.01.2019_03:01 found whitelist user, starting search again
> 06.01.2019_03:01 Getting user info : felixferdi
> 06.01.2019_03:01 Checking user info..
> 06.01.2019_03:01 Follower : 288
> 06.01.2019_03:01 Following : 696
> 06.01.2019_03:01 Media : 470
> 06.01.2019_03:01    >>>This is probably Fake account
> 06.01.2019_03:01    >>>This user is active
> 06.01.2019_03:01    >>>This account is NOT following you
> 06.01.2019_03:01    >>>You are following this account
> 06.01.2019_03:01 felixferdi
> 06.01.2019_03:01 Unfollowed: 243331872 #1.
> 06.01.2019_03:02 Trying to like media: 1950517800411653412
> 06.01.2019_03:02 Liked: 1950517800411653412. Like #2.
> ```
> 
> So, just keep running it until your list is full, and it should continue to do its job without logging out (or give you another error to troubleshoot if there are more errors in your setup (haha))!

YOU ARE THE BEST

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
