### ISSUE TITLE
Something is wrong with Instagram! Please try again later - Instabot

### ISSUE THREAD

**Issue by murlikanne** [instabot-py/instabot.py#1891]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ Y] Bug 
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ Y] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [Y ] 3.x

## Description of your issue

I've downloaded the updated version of Instabot, it throws an error "Something is wrong with Instagram! Please try again later"

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```
12.01.2019_23:18 Checking for updates...
12.01.2019_23:18 You are running the latest stable version
12.01.2019_23:18 Instabot v1.2.1/0 started at 12.01.2019 23:18:
12.01.2019_23:18 Trying to login as username...
12.01.2019_23:18 Something is wrong with Instagram! Please try again later...
12.01.2019_23:18 Error => Sorry, there was a problem with your request.
12.01.2019_23:18 Exit Program... GoodBye
## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < #!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="",
    password="",
    like_per_day=500,
    comments_per_day=500,
    tag_list=['',],
    tag_blacklist=[],
    user_blacklist={},
    max_like_for_one_tag= 2,
    follow_per_day=500,
    follow_time= 48*60*60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[['@globalpoetcult, you should feature this profile!'],],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=['bymepoetry','herheartpoetry','untwine.me','artlixir'],
    unfollow_whitelist=[])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by DarkSuniuM** [comment]
> Sorry, there was a problem with your request.

 This is what Instagram returns while we request to login

[![image-2019-01-13-00-42-07.png](https://i.postimg.cc/g0xWgN9G/image-2019-01-13-00-42-07.png)](https://postimg.cc/qtHSRcMF)

And this is what bot would see if it was a user,

We're thinking maybe it's a rate limit that Instagram applies on accounts!

Can you do something?

1. Try with other another account
2. Change this account's password and try again

Let us know what happens, Thanks

**Comment by murlikanne** [comment]
I changed the password on the current account (Recently created one comparing to the second account I tested logging in with)

Here's the error after I updated the password
 Also "13.01.2019_03:27 Found session file username.session" - This line automatically showed up

Log:

13.01.2019_03:27 Checking for updates...
13.01.2019_03:27 You are running the latest stable version
13.01.2019_03:27 Instabot v1.2.1/0 started at 13.01.2019 03:27:
13.01.2019_03:27 Found session file username.session
Traceback (most recent call last):
  File "run.py", line 224, in <module>
    session_file=usrconfig+'.session')
  File "C:\Users\DELL\Music\5\src\instabot.py", line 291, in __init__
    self.login()
  File "C:\Users\DELL\Music\5\src\instabot.py", line 455, in login
    self.csrftoken = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

===================================================

I tested the script with the second account (about an year old, Instagram doesn't push verification ID on this account for some reason), It continues to throw challenge verification

log:

13.01.2019_03:27 Checking for updates...
13.01.2019_03:27 You are running the latest stable version
13.01.2019_03:27 Instabot v1.2.1/0 started at 13.01.2019 03:27:
13.01.2019_03:27 Trying to login as username...
13.01.2019_03:27 Challenge required at https://instagram.com/challenge/5552102349/O1ewCVkIis/
Challenge Required.

**Comment by DarkSuniuM** [comment]
Oh no, Please delete the session, since u changed the password it can't use the same sessions I guess

**Comment by Silentguard** [comment]
Same here. Managed to log in once with challenge right after password change.
