### ISSUE TITLE
instabot installation issue

### ISSUE THREAD

**Issue by channelblackri** [instabot-py/instabot.py#1917]
I've watched the tutorial and and tried my best to follow instructuions but I got the following issue:

I require to execute in my terminal: pip install -r requirements.txt

Maverix$ pip install -r requirements.txt
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.12.4)
Requirement already satisfied: fake-useragent in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (0.1.10)
Collecting instaloader (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/86/be/95b14652bc85ce9c43da508d2d63954a736aa22ffedfb8b9cbed4d752a12/instaloader-2.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Instaloader requires Python >= 3.5.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cr/42sv2y2n4xvg21t9xlq35vcw0000gn/T/pip-install-Zrka3N/instaloader/
Georges-Air:bot6.1 Maverix$ 

I can't install the requirements. 

At the end it sasy  " Instaloader requires Python >= 3.5. " downloaded and installed Python 3.5 -3.7 

Maverix$ python3 --version
Python 3.6.1

Maverix$ python --version
Python 2.7.13

So do I need to update my Python version? 

Then I tried ro run example.py and this happens: 

Maverix$ **python3 example.py**

One or more required modules are missing.
 Would you like to try install them automatically? (yes/no): **yes**
Modules in requirements.txt installed successfuly. Loading...

Error installing modules. Please make sure you have installed the latest version of pip.
 You can install manually using requirements.txt
Traceback (most recent call last):
  File "/Users/Maverix/Desktop/Bot6/bot6.1/src/instabot.py", line 27, in <module>
    globals()[modname] = importlib.import_module(modname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/__init__.py", line 16, in <module>
    from .instaloader import Instaloader
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloader.py", line 18, in <module>
    from .instaloadercontext import InstaloaderContext
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 17, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/Maverix/Desktop/Bot6/bot6.1/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/Maverix/Desktop/Bot6/bot6.1/src/instabot.py", line 40, in <module>
    globals()[modname] = importlib.import_module(modname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/__init__.py", line 16, in <module>
    from .instaloader import Instaloader
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloader.py", line 18, in <module>
    from .instaloadercontext import InstaloaderContext
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 17, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
Georges-Air:bot6.1 Maverix$ 

At the beginning it says install the latest version of pip, which I did update:
Maverix$ pip --version
pip 18.1 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip (python 2.7)
Georges-Air:bot6.1 Maverix$ 

Iam very confused about this.. maybe Somebody has a Idea how to make it run..

**Comment by dimisdas** [comment]
Use pip3 instead of pip when installing requirements.

I'm going to close this since the issue template is missing. Please edit your post or submit another issue properly. Thanks!
