### ISSUE TITLE
Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

### ISSUE THREAD

**Issue by sollyman** [instabot-py/instabot.py#1942]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32```

#### Pip Version?
```
pip 19.0.1
```

#### Description of your issue

```
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=== RESTART: C:\Users\Administrator\Documents\GitHub\InstaPy\quickstart.py ===

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-01-28 13:18:22] [habdology]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

...............................................................
INFO [2019-01-28 13:18:32] [habdology]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-01-28 13:18:32] [habdology]  Saving account progress...

INFO [2019-01-28 13:18:39] [habdology]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 2406 users & had 500 FOLLOWERS
[Session lasted 24.13 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-01-28 13:18:39] [habdology]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2019-01-28 13:18:39] [habdology]  Tag [1/27]
INFO [2019-01-28 13:18:39] [habdology]  --> b'health'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000165BCD110B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\quickstart.py", line 35, in <module>
    session.follow_by_tags(['health', 'fitness', 'fit', 'socialsteeze', 'fitnessmodel', 'fitnessaddict', 'fitspo', 'workout', 'bodybuilding', 'cardio', 'gym', 'train', 'training', 'healthy', 'instahealth', 'healthychoices', 'active', 'strong', 'motivation', 'instagood', 'determination', 'lifestyle', 'diet', 'getfit', 'cleaneating', 'eatclean', 'exercise'], amount=10)
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\instapy\instapy.py", line 4043, in follow_by_tags
    self.logger)
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\instapy\like_util.py", line 233, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\instapy\util.py", line 1006, in web_address_navigator
    current_url = get_current_url(browser)
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\instapy\util.py", line 1516, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\request.py", line 72, in request
    **urlopen_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=51512): Max retries exceeded with url: /session/3151a62795a95d93371cefa7584c8d5f/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000165BCD110B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
>>> 
```

#### Config

```
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'habdology'
insta_password = 'youcantseeme'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 585),
                               peak_comments=(21, 182),
                                peak_follows=(48, None),
                                 peak_unfollows=(35, 402),
                                  peak_server_calls=(None, 4700))
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    # activity
session.follow_by_tags(['health', 'fitness', 'fit', 'socialsteeze', 'fitnessmodel', 'fitnessaddict', 'fitspo', 'workout', 'bodybuilding', 'cardio', 'gym', 'train', 'training', 'healthy', 'instahealth', 'healthychoices', 'active', 'strong', 'motivation', 'instagood', 'determination', 'lifestyle', 'diet', 'getfit', 'cleaneating', 'eatclean', 'exercise'], amount=10)
session.set_do_comment(enabled=True, percentage=25)
session.set_comments(['Awesome', 'Really Cool', 'I like your stuff'])
session.like_by_tags(['health', 'fitness', 'fit', 'socialsteeze', 'fitnessmodel', 'fitnessaddict', 'fitspo', 'workout', 'bodybuilding', 'cardio', 'gym', 'train', 'training', 'healthy', 'instahealth', 'healthychoices', 'active', 'strong', 'motivation', 'instagood', 'determination', 'lifestyle', 'diet', 'getfit', 'cleaneating', 'eatclean', 'exercise'], amount=10)
session.unfollow_users(amount=40, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=450)

```
the account login successfully but when trying to search for tags ,it gives me this error. I'm using AWS micro instance "Windows 2019"

**Comment by dimisdas** [comment]
This is not instabot.
