### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by pedrille** [instabot-py/instabot.py#1982]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.5
```

#### Pip Version?
```
pip 19.0.2 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip (python 3.6)
```

#### Description of your issue

I've been using the bot for several month without major problems. Every time it crashed i could find the solution looking for similar issues or checking the recent commit ...  But this time i can't figure out why it's not working. Can you guys help me understand whats going wrong ?
Thanks in advance and thks for your amazing job an support  

```
Last login: Thu Feb 14 18:17:13 on ttys001
pierres-macbook-pro:~ pierrechanut$ cd desktop
pierres-macbook-pro:desktop pierrechanut$ cd bot new
pierres-macbook-pro:bot pierrechanut$ cd instabot.py-master
pierres-macbook-pro:instabot.py-master pierrechanut$ python3 example.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 45, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/pierrechanut/Desktop/bot/instabot.py-master/src/instabot.py", line 163, in __init__
    fake_ua = UserAgent(verify_ssl=False, use_cache_server=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 178, in load
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
pierres-macbook-pro:instabot.py-master pierrechanut$ 

```

#### Config

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="xxx",  # Enter username (lowercase). Do not enter email!
    password="xxx",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=["veloancien", "vintagebicycle", "fixie", "velovintage", "nantestattoo", "velosanciens", "singlespeed" ,"anjouvelovintage", "ecoresponsable", "zerodechet", "levoyageanantes", "transfertnantes", "machinesdelile", "ecologie", "recyclage", "nantes"],
    tag_blacklist=["nsfw", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=300,
    unlike_per_day=0,
    unfollow_recent_feed=True,  # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        [
            "propre",
            "nice",
            "niiice",
            "niiiiiiiice",
            "cool",
            "grave cool",
            "sympa",
            "sweet",
            "GREAT",
            "wow",
            "grave cool",
            "very cool",
            "validé ✔️",
            "beautiful",
            "vraiment cool",
            "vraiment sympa",
            "on aime !",
            "j'adore",
            "bien cool",
            "yessssss",
            "excellent",
        ],
        ["...", ".......", " !", " ..!", "...!", " !!", " !!!" ],
        [" 💯", " 🙌", " 👏", " 💛", " 😍", " 😎", " 🆒", " 😉", " 🤩", " ☺️", " 😻", " 😺", " 🖐️", " 👌", " ✌️", " 🤟", " 🤘", " 🤙", " 👍", " ✊", " 👊", " 🤜", " 💪"],
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        "second",
        "stuff",
        "art",
        "project",
        "love",
        "life",
        "food",
        "blog",
        "free",
        "keren",
        "photo",
        "graphy",
        "indo",
        "travel",
        "art",
        "shop",
        "store",
        "sex",
        "toko",
        "jual",
        "online",
        "murah",
        "jam",
        "kaos",
        "case",
        "baju",
        "fashion",
        "corp",
        "tas",
        "butik",
        "grosir",
        "karpet",
        "sosis",
        "salon",
        "skin",
        "care",
        "cloth",
        "tech",
        "rental",
        "kamera",
        "beauty",
        "express",
        "kredit",
        "collection",
        "impor",
        "preloved",
        "follow",
        "follower",
        "gain",
        ".id",
        "_id",
        "bags",
    ],
    unfollow_whitelist=["segopora", "bikemania.shop", "jacovangass", "ciro.bikes", "fraaistaal", "lowride.customgarage", "bicyclemods", "vintage.space", "cattelan_cycles", "letourdefrance", "cannondaleroad", "giantbicycles", "rideshimano", "lookcycle", "maviccycling", "uci_cycling", "bianchibicycles", "premiumcycling", "colnagoworld", "campagnolosrl", "52x42", "velovintagebikes", "cycloretro", "sofoot", "_dirty_cycles_", "jeni_carli", "chaohuili", "maltabikepl", "designbike_bednar", "lesbaroudeurs_", "shavaracing", "le_bonbon_nantes", "tronicdrive", "commencalbikes", "luisbikeshop", "customvintagebicycles", "singlespeedfrance", "le_poupoupidou_atelier", "cycles_panache", "myskyisblue_", "suit_barberlounge", "lebarbierdesainttugal", "steelcoffeeshop", "cafemericourt", "cafeloustic", "kbcoffeeroastersparis", "fragmentsparis", "coutumecafe", "cafeoberkampf", "cafesbelleville", "holybellycafe", "tenbelles", "lepelotoncafe", "lecycliste", "free_color_fc_", "_pinionfix", "biciclofficinarestauro", "jamesdbuzzard", "marius_tattoo_shop", "berserkers_tattoos", "halloween_tattoo_lyon", "allan_leal", "fullmoontattoo", "remybtattoo", "mattcurzon", "traditionalartist", "gakuo55golf", "thepeugeotguys", "dupne.kolo", "velopeedi", "eroicacycles", "caesarnfrank_", "spitalwerkstatt", "martinvdakker", "italcorsabicycles", "bicibavarese", "supreme_style_mates", "richlifecycle", "nicerideroadbikes", "abikes_andersbergh", "yesterdays_bike_project", "cycleclassicmagazin", "gradeisgood", "pete.howard.1023", "historicbicycles", "sicutcycles", "velodepoque", "iwob_italian_way_of_bike", "vintagecykel", "archivio.fotografico.tiralento", "wricycles_bicycles", "grandis.tank", "temili_design", "mikeradenbaugh", "switchbike_bornemann_giessen", "ucsanremo", "juvevintage95", "davidribault_mediaproduction", "singlespeededinburgh", "pvsako_outdoor", "veloshop.co.uk", "eddymerckxbikes", "velos_do_marco", "insidethekerf", "rogergarage_custombikes", "favusshonan", "timelessmod", "ap_adi79", "retrocicloantigas", "luisoficialsport", "cyclingbeast", "wheelaxx", "jaumedelavila", "classiccyclists", "vintage_velo04", "rust_to_ride", "massimo_framebuilder", "bikesonthebrain", "marcelocycles", "vintagevelos", "friendlybicycle", "helyettcycles", "velovintage_brussels", "reidbikes", "stringartbytom", "peugeotcycles", "vintage_bikes_torino", "sustainablebikes", "taliaferro_cylery", "northercycles", "buy_cycles", "vintagebikesclub", "thompsonbicycles", "coolosjulios", "velo_heaven", "ironandwalnut", "coppa_cobram", "martinforet_com", "uli_bet", "velo_renaissance", "insta.bicycle", "freddiegrubb", "cyclefox", "cremecycles", "velovintageparis", "eroica.cc", "biciclettavintage", "bellaciaobiciclette", "cyclescostin", "ridenjs", "velorigolo", "lachouetteparis", "larouille.paris", "la.bouclee", "velostation_lorient", "soho_vintage_bikes", "mon_cycliste", "rihscycle", "henry_yih", "lechoppedu2roues", "velocontainer", "refab_by_labecaneajules", "scbikeschile", "ergo_au", "bricklanebikesclothing", "ronacustomcycle", "velovintage_paris", "espritcycles", "biclounedaumesnil", "ateliertak", "jourdevelo", "paul.bijsterbosch", "cnkbikepolo", "ciclicromati", "storybikes", "elbicycles", "mycyclick", "no85atelier", "camille_slh", "kick_my_pan", "futuro_cycles", "velovintage18", "lacleapaulette", "poclovic", "oden_france", "pedale_paris", "retrocyclo", "cyclesanciens", "dynmcyclerepairs", "cyclesmanivelle", "cyclesgrandbois", "cyclescattin", "selles_ideale", "belleroue", "dmdjpcycles", "steelframeyyc", "steels_real", "bikeground_garage", "deadratscycles", "biciclasic", "labicyclettedegraham", "rustines_official", "bergkoenig_gstaad", "crumbworks.co", "ruthworkssf", "hunqaloosa", "clermont_velo_vintage", "taborsaddles", "vintagecycles_byclem", "velomuseum", "enroue.libre", "cycle_shops", "pipronouncedaspie", "rouetinenantes", "cycles_tempete", "cyclablerouen", "monsieurpignonmadameguidon", "cycles_dautry", "santasworkshopcycle", "cyclesalexsinger", "nantesbikesolutions", "ritabikes", "localcustomspain", "roadartpics", "larecycletterie", "neo_bike_restoration", "la.cyclerie.cafe", "inkwells", "damiansuomi", "bicyclemagazine", "spray.bike", "recycle_and_bicycle", "s2pbikes", "biciclettedepoca", "steelechtbikes", "feathercycles", "horsecycles", "paul_viner", "londonbikeandbeergroup", "corsacorsa", "vintagebikesparis", "vintage_luxury_bicycles", "lionbellworks", "cycledproject", "turific_handmade", "bicycle_factory", "spokemag", "the_light_blue", "nycsteelponies", "warsawcycling", "vamper.cc", "steelmaniak", "lovelybicycle", "templecycles", "ridewithwolves", "vulcanbicycleworks", "repetecycles", "oldfieldcycles", "fixedandfree", "athens_custom_bicycles", "crustbikes", "kpcyclery", "itsnotabikeshop", "caletticycles", "regroup_coffeeandbicycles", "bicycle_nomad", "cylub", "madaboutcycling", "arterocycles", "jamesjiggyg_photography", "roulezvintage", "cannibalecycle", "kubosgarage", "bicyclebespokery", "becycleservice", "barkingbikes", "christophe_bike", "classicretrocycles", "kj84workshop", "old_biker59", "velogak", "juricustoms", "atelier_1817", "carlitos_bike_cusago", "cyclesfp", "italianvintagebikes", "fahrradservicelembike", "msebike", "rebelriderbikes", "vertetvelo", "gokhankutluer", "shimanobikenyc", "bicycle.club", "headbadge", "jengreenheadbadges", "hizokucycles", "millfieldvelo", "cf_cycles", "bikeemblems", "retro_classic_cyclist", "wrapbars4getcars", "vintagebikesnparts", "unveloauplafond", "thefrenchbicyclette", "bricklanebikes", "velo_orange", "reynolds.531", "vintagefahren", "mistervelo_vintage_bikes", "exclusivevintagebikes", "cicliberlinetta", "ciclicorsaclassico", "vintageofbikes", "life_on_vintage_wheels", "chromovelato", "love_bikes_mind", "artbicycles", "labicicletteria_vintage", "nsbraybrook", "oldcycleslausanne", "cyclesvintagesauvergne", "backyard_bicycles", "restombikes", "lesmainsauxcocottes", "steelbikes_", "vintagespeedbicycles", "berthoud_cycles", "brooksengland", "genuinecycles", "lesvelosdebenfo", "steelvintagelatvia", "qstom_bike", "vintageveloberlin", "velovintage.poitiers", "hoj_art", "anjouvelovintage", "labicycletterie", "la_bicyclette", "steelvintagebikes", "vintageroadbikes", "monsieurvelo", "pedraulitau", "bikesplease"],
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 9, # Hour you want the bot to start
    # start_at_m = 10, # Minute you want the bot to start, in this example 9:10 (am).
)

bot.mainloop()

```

**Comment by pedrille** [comment]
I found the issue .. needed to re instal requirements.txt ..
