### ISSUE TITLE
Comment Generator Won't Update Words

### ISSUE THREAD

**Issue by accpb99** [instabot-py/instabot.py#2092]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```3.7.3
Include here the response of 'python --version' or 'python3 --version'
```Python 3.7.3

#### Pip Version?
```19.0.3
Include here the response of 'pip --version' or 'pip3 --version'
```pip 19.0.3 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)


#### Description of your issue

```The bot continues to post comments with the default words that the original example.py file came with, ex. this, is, glorious, beautiful, magnificent, lovely, etc. I changed all of them, saved the file, uninstalled and reinstalled python, restarted terminal, but nothing seems to work.
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="USERNAME",  # Enter username (lowercase). Do not enter email!
    password="PASSWORD",
    like_per_day=1000,
    comments_per_day=30,
    tag_list=["art", "artist," "illustration", "painting", "music", "painting", "drawing", ],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=70,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=300,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        ["This is incredible", "This is amazing!", "This is dope. Nice work", "Love this.", "Awesome stuff", "Nice job!!", "Beautiful!", "This is outstanding", "Absolutely insane work. Keep it up", "So cool!", "This is so cool!", "Awesome piece!", "This is really great", "So pretty!!", "This is so fascinating. I love it!", "Stunning piece!", "Wonderful job on this. Keep up the good work :)", "Ahh this is brilliant!", "Incredible stuff you got here.", "How are you so talented??",
        "Love your work so much!!", "Wow you're an amazing artist", "Wow.", "WOW this is so sick", "Sick", "Nice stuff!", "Really cool art"],
        ["🙌", "👏", 😍"]
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        "second",
        "stuff",
        "project",
        "love",
        "life",
        "food",
        "blog",
        "free",
        "keren",
        "indo",
        "travel",
        "shop",
        "store",
        "sex",
        "toko",
        "jual",
        "online",
        "murah",
        "jam",
        "kaos",
        "case",
        "baju",
        "fashion",
        "corp",
        "tas",
        "butik",
        "grosir",
        "karpet",
        "sosis",
        "salon",
        "skin",
        "care",
        "cloth",
        "tech",
        "rental",
        "kamera",
        "beauty",
        "express",
        "kredit",
        "collection",
        "impor",
        "preloved",
        "follow",
        "follower",
        "gain",
        ".id",
        "_id",
        "bags",
    ],
    unfollow_whitelist=["example_user_1", "example_user_2"],
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 9, # Hour you want the bot to start
    # start_at_m = 10, # Minute you want the bot to start, in this example 9:10 (am).
)

bot.mainloop()
```

**Comment by dimisdas** [comment]
How exactly are you running the bot? Which command are you using? Thanks

**Comment by joaocpereiraa** [comment]
My problem on comment bot:

Traceback (most recent call last):
  File "C:\Users\joaoc\Downloads\instabot\iamcoment.py", line 68, in <module>
    bot.new_auto_mod()
  File "C:\Users\joaoc\Downloads\instabot\src\instabot.py", line 707, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\joaoc\Downloads\instabot\src\instabot.py", line 775, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "C:\Users\joaoc\Downloads\instabot\src\instabot.py", line 806, in check_exisiting_comment
    comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_comment']['edges'])
KeyError: 'edge_media_to_comment'
>>>

**Comment by joaocpereiraa** [comment]
why you delete my commentt? :s @instabot
