### ISSUE TITLE
empty range for randrange

### ISSUE THREAD

**Issue by marcellindwurm** [instabot-py/instabot.py#2124]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version? 

python 3.7.3

#### Description of your issue
I cant fix this stupid error :-(
Cant find any help with this problem.. maybe you guys can give me the right way to fix!
```
Here the Protocol:

     ______Starting bot_____
29.04.2019_21:24 Checking for updates...
29.04.2019_21:24 You are running the latest stable version
29.04.2019_21:24 Instabot v1.2.5/0 started at 29.04.2019 21:24:
29.04.2019_21:24 Found session file gymwars_athlet.session
29.04.2019_21:24 gymwars_athlet login success!

29.04.2019_21:24 Saving cookies to session file gymwars_athlet.session
29.04.2019_21:24 Get Media by tag: instagood
Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 397, in main
    bot.new_auto_mod()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 1035, in new_auto_mod
    self.mainloop()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 1054, in mainloop
    1, self.max_like_for_one_tag
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)

Above is the error after login :-(

**Comment by dimisdas** [comment]
Hey,

Would you kindly post the contents of example.py or config.ini ?

**Comment by mathiasleroy** [comment]
+1

     ______Starting bot_____
2019-09-05 12:25:54,064 - InstaBot - INFO - Checking for updates...
2019-09-05 12:25:54,219 - InstaBot - INFO - You are running the latest stable version
2019-09-05 12:25:54,219 - InstaBot - INFO - Instabot v1.2.6/0 started at 05.09.2019 12:25:
2019-09-05 12:25:54,220 - InstaBot - INFO - Found session file yyyy.session
2019-09-05 12:25:56,875 - InstaBot - INFO - yyyy login success!
2019-09-05 12:25:56,876 - InstaBot - INFO - Saving cookies to session file yyyy.session
2019-09-05 12:25:56,876 - InstaBot - DEBUG - Get Media by tag: cinema
Traceback (most recent call last):
  File "/home/xxx/.local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/home/xxx/.local/lib/python3.7/site-packages/instabot_py/__main__.py", line 395, in main
    bot.mainloop()
  File "/home/xxx/.local/lib/python3.7/site-packages/instabot_py/instabot.py", line 796, in mainloop
    1, self.max_like_for_one_tag
  File "/usr/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)
