### ISSUE TITLE
'Follower' object does not support indexing

### ISSUE THREAD

**Issue by guztavoalves** [instabot-py/instabot.py#2136]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.7
```

#### Pip Version?
```
pip 19.1.1 from /usr/lib/python3.6/dist-packages/pip (python 3.6)
```

#### Description of your issue

```
InstaBot - DEBUG - Trying to unfollow #1:
Traceback (most recent call last):
  File "bot_c_1.py", line 280, in <module>
    bot.mainloop()
  File "/insta/instabot.py/instabot_py/instabot.py", line 823, in mainloop
    self.new_auto_mod_unfollow()
  File "/insta/instabot.py/instabot_py/instabot.py", line 1017, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "/insta/instabot.py/instabot_py/instabot.py", line 1160, in auto_unfollow
    current_id = username_row[0]
TypeError: 'Follower' object does not support indexing
```

#### Config

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
 
import os
import time
import sys

from instabot_py import InstaBot

bot = InstaBot(
    login="",  
    password="",
	database_name="",
	session_file="",
    like_per_day=10,
    comments_per_day=320,
    tag_list=[	
		'l:213163910',
		'l:216598942',
		'l:247340952',			
		'l:213163910',	
		'l:213088533',	
		'l:213287181',	
		'l:213255513',	
		'l:213428557',		
		'brasil',	
		'amor',	
		'lookdodia',	
		'bemmenininha',	
		'partiu',	
		'deontem',		
		'meamo',	
		'boasemana',	
		'boanoite',	
		'bomdia',	
		'boatarde',	
		'tardelinda',	
		'dialindo',	
		'noite',
		'deagora',	
		'dehoje',
		'frase',
		'direita',
		'galera',	
		'eu',	
		'amando',			
		'estilo',			
		'moda',			
		'linda',			
		'maravilhosa',			
		'fome',			
		'tocomfome',			
		'matandoafome',			
		'meuprato',			
		'passeio',			
		'passeando',			
		'turistando',			
		'viajando',			
		'curtindo',			
		'amomuito',		
		'fotododia',			
		'selfiedodia',			
		'felicidade',			
		'meuestilo',			
		'festa',			
		'cozinhando',			
		'amores',			
		'saopaulo',			
		'tbf',			
		'tbt❤️',			
		'emoção'
	],
    tag_blacklist=[
		"follow",
		"like4like",
		"compre",
		"loja",
		"sorteio",
		"promocao",
		"look",
		"vestidos",
		"visite",
		"fotooficial",
		"fotoficial",
		"participe"
	],     
    max_like_for_one_tag=2,
	media_max_like=100,
	media_min_like=10,
    follow_per_day=350,
    follow_time=1 * 24 * 60,
	follow_time_enabled=True,
    unfollow_per_day=283,
    unlike_per_day=0,
    unfollow_recent_feed=False,
	unfollow_not_following=True,
	unfollow_inactive=True,
	unfollow_probably_fake=True,
	unfollow_selebgram=True,
    time_till_unlike=4 * 24 * 60 * 60, 
    unfollow_break_min=65,
    unfollow_break_max=300,
    user_max_follow=5000,
    user_min_follow=200,
    log_mod=0,
    proxy=sys.argv[1],
    comment_list=[
    [
			"Gostei, ",
			"Show, ",
			"Mas que ",
			"Mas q ",
			"Ei, ",
			"Wow ",
			"Que "
	  ],
    [
			"foto",
			"imagem",
			"post",
			"registro",
			"click"
	  ],
    [
			"legal",
			"👉 top",
			"👉 demais ",
			"show",
			"top",
			"bacana",
			"#best"
	  ],
    [
            " =)",
            " *-* ",
            " 👍 ",
            " 😀 ",
            " @username@",
            " @username@",
            " @username@",
            " @username@",
            " @username@",
            " @username@",
            " 😄 ",
     ],
     [
      ".",
      "!",
      " o/ ",
      " ",
      "!!!"
      ]
      ],
    unwanted_username_list=[
        "second",
        "stuff",
        "art",
        "project",
        "love",
        "life",
        "food",
        "blog",
        "free"
    ],
    user_blacklist={}
)

bot.mainloop()

```

**Comment by elchacho14** [comment]
I have de same problem. Can be this error caused by an incorrect configuration?

**Comment by mcliquid** [comment]
I get a similar error. Same trace.

```
2019-05-10 07:01:37,025 - InstaBot - DEBUG - username : Get media id on recent feed
2019-05-10 07:01:37,954 - InstaBot - DEBUG - Media in recent feed = 12
2019-05-10 07:01:37,969 - InstaBot - DEBUG - Trying to unfollow #1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/instabot_py/__main__.py", line 395, in <module>
    bot.mainloop()
  File "/instabot_py/instabot.py", line 823, in mainloop
    self.new_auto_mod_unfollow()
  File "/instabot_py/instabot.py", line 1017, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "/instabot_py/instabot.py", line 1160, in auto_unfollow
    current_id = username_row[0]
TypeError: 'Follower' object is not subscriptable
```

I have currently set the bot to "unfollow_everyone = True" in the config. When I delete the line, the bot works, but it keeps coming: 
```
2019-05-10 06:30:26,486 - InstaBot - DEBUG - Trying to unfollow #1:
2019-05-10 06:30:26,486 - InstaBot - DEBUG - Looks like there is nobody to unfollow.
```

**Comment by guztavoalves** [comment]
I had disable this unfollow feature and that's working fine for me. But this is bad  =/

**Comment by shriram-k** [comment]
Found a solution to this problem. In line 1160, replace with these lines,
```
current_id = username_row.id
current_user = username_row.username
unfollow_count = username_row.unfollow_count
```
