### ISSUE TITLE
Proxy error: OSError: Tunnel connection failed

### ISSUE THREAD

**Issue by Martypary** [instabot-py/instabot.py#2144]
#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.2
```

#### Pip Version?
```
pip 19.1
```

#### Description of your issue

```

Sorry I am an noob, but I don't know what to do. 
The proxy has always worked but since 1 week ago it is no longer working. I have already bought a new proxy, but it doesn't work either. I buy my proxies at proxy6.net (IPv4 Proxy)

My other account without proxy just works.

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\urllib3\connection.py", line 308, in connect
    self._tunnel()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 407 Proxy Authentication Required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Administrator/Desktop/instabot1.db/example1.py", line 122, in <module>
    unfollow_whitelist=["example_user_1", "example_user_2"],
  File "c:\Users\Administrator\Desktop\instabot1.db\instabot_py\instabot.py", line 196, in __init__
    self.login()
  File "c:\Users\Administrator\Desktop\instabot1.db\instabot_py\instabot.py", line 429, in login
    r = self.s.get("https://www.instagram.com/")
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by
ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by yurilaaziz** [comment]
@dimisdas 
Maybe we need to catch this exception related to Proxy feature (authentication failed )
and print an appropriate message 
what do you think?

**Comment by Martypary** [comment]
so is there a solution? @dimisdas Thanks

**Comment by dimisdas** [comment]
Your proxy setup is wrong. The server is saying that authentication failed, presumably because you did not supply the correct username or password in the URI.

**Comment by Martypary** [comment]
I have checked the password and proxy well. I entered everything as always in the instagram bot. Has nothing changed at the proxy settings since the last update?

**Comment by chandrakanth527** [comment]
The easiest way i found to fix is to replace the below line in instabot.py

proxies = {"http": f"http://{proxy}", "https": f"http://{proxy}"}
with this
proxies = {'http://': proxy, 'https://': proxy}

**Comment by Martypary** [comment]
Thanks @chandrakanth527 , but it still doesn't work. Maybe I entered it incorrectly:

![Naamloos](https://user-images.githubusercontent.com/39266285/58548681-124f9500-820a-11e9-908c-f6c06bf5903c.png)

**Comment by nickgryg** [comment]
This is very outdated issue. Please use instabot-py version 0.5.20 or later.
