### ISSUE TITLE
KeyError: 'owner' - InstaBot - WARNING - Notice: could not populate from recent feed

### ISSUE THREAD

**Issue by farbraum** [instabot-py/instabot.py#2145]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.2

```

#### Pip Version?
```
pip 19.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

```

#### Description of your issue

From time to time the bot gives this error:
```
InstaBot - ERROR - 'owner'
Traceback (most recent call last):
  File "/home/pi/instabot/instabot.py/instabot_py/instabot.py", line 968, in populate_from_feed
    feed_username = mediafeed_user["node"]["owner"]["username"]
KeyError: 'owner'
```
I've searched the on the whole web, but I didn't find a solution or a description that sounds like mine. I am using the latest Firmware on an Respberry Pi 3+ Instabot is the only job of the Pi. The InstaBot runs since 24 hours. No interruption, but this error.
Any Ideas?

**Comment by e-mete** [comment]
I have the same issue.

`2019-06-13 23:14:10,359 - InstaBot - WARNING - Except on get_media!
2019-06-13 23:14:10,360 - InstaBot - ERROR - get_media_id_by_tag
Traceback (most recent call last):
  File "C:\...\instabot_py\inst
abot.py", line 526, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "C:\Python3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-13 23:14:10,373 - InstaBot - DEBUG - Could not remove media
2019-06-13 23:14:11,375 - InstaBot - DEBUG - Get Media by tag: successmotivation

2019-06-13 23:14:17,446 - InstaBot - DEBUG - Trying to like media: 2065577753763
162254, https://www.instagram.com/p/ByqaAXtAKiO/
2019-06-13 23:14:18,151 - InstaBot - INFO - Liked: 2065577753763162254. Like #2
https://www.instagram.com/p/ByqaAXtAKiO/.
2019-06-13 23:14:23,174 - InstaBot - DEBUG - > Waiting for database to populate
before unfollowing (progress 1 /20)
2019-06-13 23:14:23,175 - InstaBot - DEBUG - Will try to populate using recent f
eed
2019-06-13 23:14:23,176 - InstaBot - DEBUG - username: Get media id o
n recent feed
2019-06-13 23:14:24,028 - InstaBot - DEBUG - Media in recent feed = 10
2019-06-13 23:14:24,038 - InstaBot - WARNING - Notice: could not populate from r
ecent feed
2019-06-13 23:14:24,039 - InstaBot - ERROR - 'owner'
Traceback (most recent call last):
  File "C:\....\instabot_py\inst
abot.py", line 968, in populate_from_feed
    feed_username = mediafeed_user["node"]["owner"]["username"]
KeyError: 'owner'
2019-06-13 23:15:23,083 - InstaBot - DEBUG - Get Media by tag: cyclingmotivation

`

**Comment by leadzteam** [comment]
have the same problem

**Comment by northtree** [comment]
@yurilaaziz Could I know the progress on this bug? I cloned and run from `example.py` and have the same issue. 

My env: 
- Python 3.7.3
- pip 19.1.1
- OS X

**Comment by umitkumbul** [comment]
same problem here :S

**Comment by specialteam** [comment]
i runned example.py and I also have this problem
    feed_username = mediafeed_user["node"]["owner"]["username"]
dear creator please fix it

**Comment by azor0** [comment]
Probably Instagram changed their API. If this is not fixed tomorrow, I will investigate

**Comment by ruslan-baichurin** [comment]
any update?

**Comment by AbdulBariKhan** [comment]
All is good now thank you

**Comment by vekMaster** [comment]
Here I have this problem, any suggest to solve it?
Thanks in advance

**Comment by tarikbahar** [comment]
I have the same problem too.

```
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\instabot_py\instabot.py", line 1000, in populate_from_feed
    feed_username = mediafeed_user["node"]["owner"]["username"]
KeyError: 'owner'
```

**Comment by chenr1** [comment]
Any solution to this? I'm having the same issue unfortunately ...

**Comment by Data0Face** [comment]
I have the same problem over this issue.

**Comment by mtrinh27** [comment]
Still having this issue as well.

**Comment by JattHer01** [comment]
Same issue as from my side also no solutions
