### ISSUE TITLE
Error while making POST to http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage

### ISSUE THREAD

**Issue by gernest123** [instabot-py/instabot.py#2146]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.7.3

#### Pip Version?
PIP 19.1.1

#### Description of your issue
Errors on startup of example.py
Error while making POST to http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage
```
C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\config42\handlers\files\yaml.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(f)
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
Error while making POST to http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage                      Traceback (most recent call last):
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_handler\handlers.py", line 61, in request
    response.raise_for_status()
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage
2019-05-11 13:06:48,885 - InstaBot - INFO - Checking for updates...
Error while making POST to http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage                      Traceback (most recent call last):
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_handler\handlers.py", line 61, in request
    response.raise_for_status()
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage
2019-05-11 13:06:50,683 - InstaBot - INFO - You are running the latest stable version
Error while making POST to http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage                      Traceback (most recent call last):
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_handler\handlers.py", line 61, in request
    response.raise_for_status()
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage
2019-05-11 13:06:51,533 - InstaBot - INFO - Instabot v1.2.5/0 started at 11.05.2019 13:06:
Error while making POST to http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage                      Traceback (most recent call last):                                                                            File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_handler\handlers.py", line 61, in request
    response.raise_for_status()
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)                                                          requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage
2019-05-11 13:06:52,270 - InstaBot - INFO - Found session file iconspiracies.session
Error while making POST to http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage
Traceback (most recent call last):
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram_handler\handlers.py", line 61, in request
    response.raise_for_status()
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)                                                          requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://botapi.antrekod.ru/botTELEGRAM_BOT_TOKEN/sendMessage
2019-05-11 13:06:54,928 - InstaBot - INFO - iconspiracies login success!```

#### Config
bot = InstaBot(
    login="xxxxxxxx",  # Enter username (lowercase). Do not enter email!
    password="xxxxxxxx",
    like_per_day=1000,
    comments_per_day=300,
    tag_list=["conspiracytheories", "conspiracytheory", "UFO", "cryptids"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=100,
    follow_per_day=0,
    follow_time=0,
    unfollow_per_day=0,
    unlike_per_day=0,
    unfollow_recent_feed=False,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=0,  # 3 days
    unfollow_break_min=0,
    unfollow_break_max=0,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
```
```

**Comment by yurilaaziz** [comment]
You need to create a telegram bot before. I am writing an article as guidance. 
This issue is for me :D

**Comment by dimisdas** [comment]
@yurilaaziz Let me know if I can post it on the Wiki and link it from README
