### ISSUE TITLE
Can't unfollow people -  'Follower' object is not subscriptable

### ISSUE THREAD

**Issue by ShubhamPandeyy** [instabot-py/instabot.py#2147]
Already tried to replace string in instabot/instabot.py in line 1160, it didnt helped me.
Facing this issue after updating the bot, it was running fine before the update.
(new to github, Sorry if I did any mistake)
Help Please.

`InstaBot - DEBUG - Trying to unfollow #1:
Traceback (most recent call last):
  File "example.py", line 124, in <module>
    bot.mainloop()
  File "/data/data/com.termux/files/home/instabot.py/instabot_py/instabot.py", line 823, in mainloop
    self.new_auto_mod_unfollow()
  File "/data/data/com.termux/files/home/instabot.py/instabot_py/instabot.py", line 1017, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "/data/data/com.termux/files/home/instabot.py/instabot_py/instabot.py", line 1160, in auto_unfollow
    current_id = username_row[0]
TypeError: 'Follower' object is not subscriptable
$`

**Comment by yurilaaziz** [comment]
A fix has been merged. please update your repo
