### ISSUE TITLE
No module named 'config42'

### ISSUE THREAD

**Issue by jonparro** [instabot-py/instabot.py#2148]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
3.7.3
```

#### Description of your issue
After try to start the bot I have this issue...
```
C:\Users\Jon\Downloads\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "C:\Users\Jon\Downloads\instabot.py-master\instabot_py\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Jon\Downloads\instabot.py-master\instabot_py\instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "C:\Users\Jon\Downloads\instabot.py-master\instabot_py\config.py", line 4, in <module>
    from config42 import ConfigManager
ModuleNotFoundError: No module named 'config42'
```

**Comment by yurilaaziz** [comment]
don't forget to install dependencies 
`pip install -e . `

Please update your repo before typing the given command 
`git pull`

cc @dimisdas

**Comment by jonparro** [comment]
@yurilaaziz Sorry, I don't know how to install depencies. How may i do it?

**Comment by dimisdas** [comment]
White in the project's root directory, run this command `pip install -e .`

**Comment by jonparro** [comment]
@dimisdas Ok, I did it.

>`C:\Users\Jon\Downloads\instabot.py-master>pip install -e .
Obtaining file:///C:/Users/Jon/Downloads/instabot.py-master
Requirement already satisfied: fake-useragent==0.1.11 in c:\users\jon\appdata\local\programs\python\python37-32\lib\site-packages (from instabot-py==0.4.7) (0.1.11)
Requirement already satisfied: instaloader==4.2.1 in c:\users\jon\appdata\local\programs\python\python37-32\lib\site-packages (from instabot-py==0.4.7) (4.2.1)
Requirement already satisfied: requests==2.21.0 in c:\users\jon\appdata\local\programs\python\python37-32\lib\site-packages (from instabot-py==0.4.7) (2.21.0)
Requirement already satisfied: blessings==1.7.0 in c:\users\jon\appdata\local\programs\python\python37-32\lib\site-packages (from instabot-py==0.4.7) (1.7)
Collecting config42==0.3.1 (from instabot-py==0.4.7)
  Downloading https://files.pythonhosted.org/packages/b3/eb/42825e0bcc0611b0690a672072a9b76130c75977e766226667ef14c9e7f4/config42-0.3.1-py3-none-any.whl
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jon\appdata\local\programs\python\python37-32\lib\site-packages (from requests==2.21.0->instabot-py==0.4.7) (2019.3.9)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\jon\appdata\local\programs\python\python37-32\lib\site-packages (from requests==2.21.0->instabot-py==0.4.7) (1.24.3)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\jon\appdata\local\programs\python\python37-32\lib\site-packages (from requests==2.21.0->instabot-py==0.4.7) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\jon\appdata\local\programs\python\python37-32\lib\site-packages (from requests==2.21.0->instabot-py==0.4.7) (3.0.4)
Requirement already satisfied: six in c:\users\jon\appdata\local\programs\python\python37-32\lib\site-packages (from blessings==1.7.0->instabot-py==0.4.7) (1.12.0)
Installing collected packages: config42, instabot-py
  Found existing installation: instabot-py 0.4.7
    Uninstalling instabot-py-0.4.7:
      Successfully uninstalled instabot-py-0.4.7
  Running setup.py develop for instabot-py
Successfully installed config42-0.3.1 instabot-py`


### After that I tried:

>`C:\Users\Jon\Downloads\instabot.py-master>python example.py
Traceback (most recent call last):
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\config42\handlers\files\yaml.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "C:\Users\Jon\Downloads\instabot.py-master\instabot_py\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Jon\Downloads\instabot.py-master\instabot_py\instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "C:\Users\Jon\Downloads\instabot.py-master\instabot_py\config.py", line 24, in <module>
    config.set_many(ConfigManager(path=config_path.replace('//', '/')).as_dict())
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\config42\config_manager.py", line 20, in __init__
    self.handler = handler(**handler_kwargs)
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\config42\handlers\files\__init__.py", line 12, in __new__
    from .yaml import YamlHandler as Handler
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\config42\handlers\files\yaml.py", line 4, in <module>
    raise ImportError("files.Yaml handler requires 'PyYAML' package\n"
ImportError: files.Yaml handler requires 'PyYAML' package
Install it with 'pip install pyyaml'

C:\Users\Jon\Downloads\instabot.py-master>pip install pyyaml
Collecting pyyaml
  Downloading https://files.pythonhosted.org/packages/a2/50/d42aa0b14fd7b04d287fa739c16e49d9eb79d364a6aa0c5df6ecdeef3dd4/PyYAML-5.1-cp37-cp37m-win32.whl (195kB)
     |████████████████████████████████| 204kB 3.3MB/s
Installing collected packages: pyyaml
Successfully installed pyyaml-5.1`


### And After I tried again:

`C:\Users\Jon\Downloads\instabot.py-master>python example.py
C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\config42\handlers\files\yaml.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(f)
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
Traceback (most recent call last):
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\logging\config.py", line 383, in resolve
    found = self.importer(used)
ModuleNotFoundError: No module named 'telegram_handler'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\logging\config.py", line 562, in configure
    handler = self.configure_handler(handlers[name])
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\logging\config.py", line 712, in configure_handler
    klass = self.resolve(cname)
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\logging\config.py", line 396, in resolve
    raise v
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\logging\config.py", line 383, in resolve
    found = self.importer(used)
ValueError: Cannot resolve 'telegram_handler.TelegramHandler': No module named 'telegram_handler'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "C:\Users\Jon\Downloads\instabot.py-master\instabot_py\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Jon\Downloads\instabot.py-master\instabot_py\instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "C:\Users\Jon\Downloads\instabot.py-master\instabot_py\config.py", line 43, in <module>
    logging.config.dictConfig(config.get("logging"))
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\logging\config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Users\Jon\AppData\Local\Programs\Python\Python37-32\lib\logging\config.py", line 570, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'telegram'`

**Comment by yurilaaziz** [comment]
@dimisdas  should we uncomment telegram handler in the sample configuration?

**Comment by dimisdas** [comment]
@yurilaaziz I think that would be wise. I’ve had people get confused on Telegram group as well.

I’m on the road (mobile). Will do it tomorrow, or accept it as PR, whichever comes first. 

OP: you need to edit the config and under handlers remove telegram

**Comment by dwohl12** [comment]
hey guys  I cant get my Instagram bot to run when I try I get this error  

  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "/home/nextstoptravelsaccessory/instabot.py/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/nextstoptravelsaccessory/instabot.py/instabot_py/instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "/home/nextstoptravelsaccessory/instabot.py/instabot_py/config.py", line 4, in <module>
    from config42 import ConfigManager
ModuleNotFoundError: No module named 'config42'


I tried to run pip install -e but then i get this 

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...
-e option requires an argument

any suggestions?

**Comment by sebisnotyourhomie** [comment]
i am having the same issue but im on a mac, is there a solution for me? i have python 3.7.3

**Comment by iamsilvia** [comment]
Updated today.. bot doesn't work anymore. Any solutions?

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/config42/handlers/files/yaml.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 6, in <module>
    from instabot_py.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "/usr/local/lib/python3.7/site-packages/instabot_py/config.py", line 24, in <module>
    config.set_many(ConfigManager(path=config_path.replace('//', '/')).as_dict())
  File "/usr/local/lib/python3.7/site-packages/config42/config_manager.py", line 20, in __init__
    self.handler = handler(**handler_kwargs)
  File "/usr/local/lib/python3.7/site-packages/config42/handlers/files/__init__.py", line 12, in __new__
    from .yaml import YamlHandler as Handler
  File "/usr/local/lib/python3.7/site-packages/config42/handlers/files/yaml.py", line 4, in <module>
    raise ImportError("files.Yaml handler requires 'PyYAML' package\n"
ImportError: files.Yaml handler requires 'PyYAML' package
Install it with 'pip install pyyaml'

**Comment by Jangojack14** [comment]
I just fix it by updating the pip !!!  
In my case i installed python 3.6 and 3.7 so i run : sudo pip3.6 install pyyaml and sudo pip3.7 install pyyaml.       And it fix my problem !! Hope it help you...

**Comment by jianxinzhou123** [comment]
Also got a ModuleNotFoundError: No module named 'config42' error on Mac.
