### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe.

### ISSUE THREAD

**Issue by uzairnz** [instabot-py/instabot.py#2175]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.1.1 from c:\users\uzair\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < UZAIR@DESKTOP-IU23J75 MINGW64 /c/Dev/Bots/Test/instabot.py (master)
$ python nabeha.py
C:\Users\***\AppData\Local\Programs\Python\Python37-32\lib\site-packages\config42\handlers\files\yaml.py:13: YAMLLault Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(f)
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
2019-05-22 15:34:48,219 - InstaBot - INFO - Checking for updates...
2019-05-22 15:34:50,081 - InstaBot - INFO - You are running the latest stable version
2019-05-22 15:34:50,081 - InstaBot - INFO - Instabot v1.2.5/0 started at 22.05.2019 15:34:
2019-05-22 15:34:50,081 - InstaBot - INFO - Found session file nabe_ehaa.session
2019-05-22 15:34:52,369 - InstaBot - INFO - nabe_ehaa login success!

2019-05-22 15:34:52,369 - InstaBot - INFO - Saving cookies to session file nabe_ehaa.session
2019-05-22 15:34:52,385 - InstaBot - DEBUG - Get Media by tag: creative_pakistan
2019-05-22 15:34:54,053 - InstaBot - DEBUG - Trying to like media: 2049347090909003648, https://www.instagram.com/p/
2019-05-22 15:34:54,871 - InstaBot - INFO - Liked: 2049347090909003648. Like #1 https://www.instagram.com/p/BxwvlI_H
2019-05-22 15:34:54,874 - InstaBot - DEBUG - Trying to follow: 1986130309
ERROR:root:Except on get_username_by_user_id
Traceback (most recent call last):
  File "C:\Dev\Bots\Test\instabot.py\instabot_py\instabot.py", line 554, in get_username_by_user_id
    profile = instaloader.Profile.from_id(self.instaload.context, user_id)
  File "C:\Users\UZAIR\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instaloader\structures.py", line
    rhx_gis=context.root_rhx_gis)['data']['user']
  File "C:\Users\UZAIR\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instaloader\instaloadercontext.py
    self._root_rhx_gis = self.get_json('', {})['rhx_gis']
KeyError: 'rhx_gis'
2019-05-22 15:34:57,912 - InstaBot - INFO - Followed: https://www.instagram.com/False/ #1.
INFO:InstaBot:Followed: https://www.instagram.com/False/ #1.
2019-05-22 15:34:58,416 - InstaBot - INFO - Trying to comment: 2049344140568156684
                 https://www.instagram.com/p/Bxwu6NRF9oM/
INFO:InstaBot:Trying to comment: 2049344140568156684
                 https://www.instagram.com/p/Bxwu6NRF9oM/
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\UZAIR\AppData\Local\Programs\Python\Python37-32\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\UZAIR\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f64c' in position 75: character maps to <undefined
Call stack:
  File "nabeha.py", line 149, in <module>
    bot.mainloop()
  File "C:\Dev\Bots\Test\instabot.py\instabot_py\instabot.py", line 825, in mainloop
    self.new_auto_mod_comments()
  File "C:\Dev\Bots\Test\instabot.py\instabot_py\instabot.py", line 1040, in new_auto_mod_comments
    self.comment(self.media_by_tag[0]["node"]["id"], comment_text)
  File "C:\Dev\Bots\Test\instabot.py\instabot_py\instabot.py", line 749, in comment
    self.logger.info(log_string)
Message: 'Write: This picture looks good \U0001f64c. #1.'
Arguments: ()
INFO:InstaBot:Write: This picture looks good \U0001f64c. #1.
2019-05-22 15:35:01,178 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:02,179 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:03,180 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:04,193 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:05,204 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:06,211 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:07,212 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:08,226 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:09,226 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:10,240 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:11,240 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:12,245 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:13,260 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:14,261 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:15,263 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:16,268 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:17,268 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:18,272 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:18,272 - InstaBot - DEBUG - > Waiting for database to populate before unfollowing (progress 1 /20)
DEBUG:InstaBot:> Waiting for database to populate before unfollowing (progress 1 /20)
2019-05-22 15:35:18,272 - InstaBot - DEBUG - Will try to populate using recent feed
DEBUG:InstaBot:Will try to populate using recent feed
2019-05-22 15:35:18,272 - InstaBot - DEBUG - nabe_ehaa : Get media id on recent feed
DEBUG:InstaBot:nabe_ehaa : Get media id on recent feed
2019-05-22 15:35:19,368 - InstaBot - DEBUG - Media in recent feed = 12
DEBUG:InstaBot:Media in recent feed = 12
2019-05-22 15:35:19,384 - InstaBot - DEBUG - Inserted user wis_art_photographie from recent feed
DEBUG:InstaBot:Inserted user wis_art_photographie from recent feed
2019-05-22 15:35:19,400 - InstaBot - DEBUG - Inserted user malasdemao from recent feed
DEBUG:InstaBot:Inserted user malasdemao from recent feed
2019-05-22 15:35:19,431 - InstaBot - DEBUG - Inserted user thevancouver_visionary from recent feed
DEBUG:InstaBot:Inserted user thevancouver_visionary from recent feed
2019-05-22 15:35:19,446 - InstaBot - DEBUG - Inserted user noar.raw from recent feed
DEBUG:InstaBot:Inserted user noar.raw from recent feed
2019-05-22 15:35:19,462 - InstaBot - DEBUG - Inserted user oyeshowbiz from recent feed
DEBUG:InstaBot:Inserted user oyeshowbiz from recent feed
2019-05-22 15:35:19,493 - InstaBot - DEBUG - Inserted user pokemongorome from recent feed
DEBUG:InstaBot:Inserted user pokemongorome from recent feed
2019-05-22 15:35:19,509 - InstaBot - DEBUG - Inserted user aao_hassa from recent feed
DEBUG:InstaBot:Inserted user aao_hassa from recent feed
2019-05-22 15:35:20,510 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:21,513 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:22,515 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:23,528 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:24,532 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:25,532 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:26,547 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:27,553 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:28,562 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:29,573 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:30,575 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:31,581 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:32,588 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:33,591 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:34,599 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-22 15:35:34,599 - InstaBot - INFO - Exit Program... GoodBye
INFO:InstaBot:Exit Program... GoodBye

![Screenshot (8)](https://user-images.githubusercontent.com/18249670/58169157-825d9880-7ca9-11e9-835e-30f3ed934bfa.png)
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < #!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="nabe_ehaa",  # Enter username (lowercase). Do not enter email!
    password="***************",
    like_per_day=753,
    comments_per_day=96,
    database_name = "nabe_ehaa.db",
    tag_list=["l:216064306", "l:224526487", "l:219790614"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=35,
    follow_per_day=996,
    follow_time=1 * 24 * 60 * 60, # 1 day
    unfollow_per_day=881,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=1 * 24 * 60 * 60,  # 1 day
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    unfollow_selebgram=True,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot"],
        ["is", "looks", "is really"],
        [
            "great",
            "super",
            "good",
            "amazing",
        ],
        [".", "🙌", "... 👏", "!", "! 😍", "😎"],
    ],
    unwanted_username_list=[
        "second",
        "stuff",
    ],
    unfollow_whitelist=["example_user_1", "example_user_2"],
    
)

bot.mainloop()

```

**Comment by uzairnz** [comment]
Same problem on my VPS running Linux. I tested it on windows environment and I got the same issue. This is after I cloned new repository. My other VPS is running old version of instabot without any problem.

**Comment by marcosenno88** [comment]
same here

**Comment by husligc** [comment]
@uzairnz do you guys know why the old version is changing hashtags with each comment? any fix? that was the only reason I downloaded the new one.

**Comment by uzairnz** [comment]
> @uzairnz do you guys know why the old version is changing hashtags with each comment? any fix? that was the only reason I downloaded the new one.

I was having problems with unfollow.

**Comment by uzairnz** [comment]
> @uzairnz do you guys know why the old version is changing hashtags with each comment? any fix? that was the only reason I downloaded the new one.

Yes! I just noticed the same issue. But its changing hashtag after every alteration. And certainly after comment.

**Comment by husligc** [comment]
> > @uzairnz do you guys know why the old version is changing hashtags with each comment? any fix? that was the only reason I downloaded the new one.
> 
> Yes! I just noticed the same issue. But its changing hashtag after every alteration. And certainly after comment.

Any idea how to fix that? besides changing to a single hashtag? @dimisdas

**Comment by uzairnz** [comment]
![image](https://user-images.githubusercontent.com/18249670/58284665-87633a80-7dc4-11e9-9309-a7de61f6577b.png)

**Comment by marcosenno88** [comment]
Has anyone managed to fix this problem?

**Comment by uzairnz** [comment]
No

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dimisdas** [comment]
Please upgrade via pip. This was an error with Instaloader, because instagram changed parts of their page. The guys over the project have fixed it in their latest version.

@uzairnz your screenshot suggests you are using an older version. Could you please try to reinstall? thanks!

**Comment by mrallanodreman** [comment]
i just install the latest versión of this repo and im having the same problem
