### ISSUE TITLE
Unfollow/follow not working, KeyError: rhx_gis

### ISSUE THREAD

**Issue by michelgawron** [instabot-py/instabot.py#2196]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (Raspberry Pi - Raspbian)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.2
```

#### Pip Version?
```
pip 18.1
```

#### Description of your issue

```
2019-06-02 12:53:23,322 - InstaBot - DEBUG - Trying to follow: 253539345
DEBUG:InstaBot:Trying to follow: 253539345
ERROR:root:Except on get_username_by_user_id
Traceback (most recent call last):
  File "/home/pi/Bureau/new_bot_ophe/instabot.py/instabot_py/instabot.py", line 560, in get_username_by_user_id
    profile = instaloader.Profile.from_id(self.instaload.context, user_id)
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 460, in from_id
    rhx_gis=context.root_rhx_gis)['data']['user']
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 533, in root_rhx_gis
    self._root_rhx_gis = self.get_json('', {})['rhx_gis']
KeyError: 'rhx_gis'
2019-06-02 12:53:29,582 - InstaBot - INFO - Followed: https://www.instagram.com/False/ #4.
INFO:InstaBot:Followed: https://www.instagram.com/False/ #4.
```

#### Config

```
bot = InstaBot(
    login="#####",  # Enter username (lowercase). Do not enter email!
    password="#####",
    like_per_day=1700,
    comments_per_day=300,
    tag_list=['travelphotography', 'rooftop', 'tourisme', 'vacances', 'landscape', 'paysage', 'blogueuse', 'blogueur',
              'lifestyle', 'healthy', 'fitnessmotivation', 'maquillage', 'blogging', 'traveler', 'tatouage', 'worldtraveler',
              'skyline', 'makeuponfleek', 'erasmus', 'sunset', 'motivation', 'girltraveler', 'makeup', 'instatraveling',
              'travelblogger', 'travelholic', 'travelgram', 'fashionblogger', 'lifestyleblogger', 'voyageuse',
              'blogvoyage'],
    tag_blacklist=[],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=450,
    follow_time=1 * 48,
    unfollow_per_day=600,
    unlike_per_day=0,
    unfollow_recent_feed=False,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=12,
    unfollow_break_max=27,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot"],
        ["is", "looks", "is 👉", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "🙌", "... 👏", "!", "! 😍", "😎"],
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[],
    unfollow_whitelist=[],
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 9, # Hour you want the bot to start
    # start_at_m = 10, # Minute you want the bot to start, in this example 9:10 (am).
)

```

Seems like the following function is broken - tries to follow an account, gets the KeyError exception, catches it and follows the account:  https://www.instagram.com/False.

Also seems to break down the unfollowing bot as the database file is populated with wrong values.

**Comment by dimisdas** [comment]
This is the bazillion time it’s been asked. You need to update Instabot and all its dependencies via pip. Instagram changed parts of their code, older versions are not supported.
