### ISSUE TITLE
ImportError: files.Yaml handler requires 'PyYAML' package 

### ISSUE THREAD

**Issue by relfv43** [instabot-py/instabot.py#2201]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
'python3 --version'
Include here the response of 'python --version' or 'python3 --version'
`Python 3.7.3`

#### Pip Version?
`pip3 --version`
Include here the response of 'pip --version' or 'pip3 --version'
`pip 19.1.1`

#### Description of your issue
File import error 
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
`
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/config42/handlers/files/yaml.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "/Users/j.a./Desktop/instabot.py-master/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/j.a./Desktop/instabot.py-master/instabot_py/instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "/Users/j.a./Desktop/instabot.py-master/instabot_py/config.py", line 24, in <module>
    config.set_many(ConfigManager(path=config_path.replace('//', '/')).as_dict())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/config42/config_manager.py", line 20, in __init__
    self.handler = handler(**handler_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/config42/handlers/files/__init__.py", line 12, in __new__
    from .yaml import YamlHandler as Handler
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/config42/handlers/files/yaml.py", line 4, in <module>
    raise ImportError("files.Yaml handler requires 'PyYAML' package\n"
ImportError: files.Yaml handler requires 'PyYAML' package
Install it with 'pip install pyyaml'`

**Comment by abhidp** [comment]
depending on your system, please try the following. You may also need to use `sudo` infront of these commands depending on how your permission is setup. 
`pip3.7 install pyyaml` , `pip3 install pyyaml`

**Comment by relfv43** [comment]
Error: couldn’t find a version that satisfies the requirement pyyam1

**Comment by relfv43** [comment]
Got thank you

**Comment by relfv43** [comment]
Thank you

**Comment by bayilyas** [comment]
install version 5.1 not latest one
`pip3 install pyyaml==5.1`

**Comment by yurilaaziz** [comment]
Fixed in newer releases
