### ISSUE TITLE
error while running the bot

### ISSUE THREAD

**Issue by saurabhkanswal** [instabot-py/instabot.py#2207]
OS: windows 

```
C:\Users\HP\Desktop\bot\instabot.py>python -m instabot_py
Traceback (most recent call last):
  File "C:\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\HP\Desktop\bot\instabot.py\instabot_py\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\HP\Desktop\bot\instabot.py\instabot_py\instabot.py", line 19, in <module>
    import instaloader
ModuleNotFoundError: No module named 'instaloader'
```

**Comment by selene-y** [comment]
@dimisdas hi, how do you fix this issue, I meet this issue today, please help, thakns

**Comment by hanbogdan1** [comment]
@selene-y 

Don't skip the install step

`python3 -m pip install instabot-py`

or 

`python3 -m pip install instabot-py --no-cache-dir --upgrade
pip3 install instabot-py --no-cache-dir --upgrade`
