### ISSUE TITLE
ModuleNotFoundError: No module named 'config42' with dependencies failed to be installed

### ISSUE THREAD

**Issue by jianxinzhou123** [instabot-py/instabot.py#2218]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.3
```

#### Pip Version?
```
pip 19.1.1
```

#### Description of your issue

```
When running the program, the following errors ensued:
`Traceback (most recent call last):
  File "/Users/x/Desktop/A&RIGA/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/x/Desktop/A&RIGA/instabot_py/instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "/Users/x/Desktop/A&RIGA/instabot_py/config.py", line 4, in <module>
    from config42 import ConfigManager
ModuleNotFoundError: No module named 'config42'````

And when I try to install more dependencies under the REQUIREMENTS folder, namely, base.txt, I get the following error:

Installing collected packages: PyYAML
  Found existing installation: PyYAML 3.13
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

```

#### Config

```
like_per_day = 700
comments_per_day = 350
max_like_for_one_tag = 100
follow_per_day = 700
follow_time = 3600
unfollow_per_day = 700
unfollow_break_min = 1
unfollow_break_max = 1
comment_list = [["yo, this", "lol the", "wtf your", "damn, this"], ["shot", "post", "pic"], ["is", "looks", "feels", "was"], ["lit lmao", "lit lol", "great dude", "kinda good lmao", "good lol", "very good dude", "good dude", "wow haha", "cool dude", "GREAT", "quite magnificent lol", "magical", "very cool haha", "stylish man", "beautiful indeed", "so beautiful", "so stylish", "so professional", "lovely haha", "so lovely lol", "very lovely man", "glorious haha", "insanely good wtf", "so glorious", "damn glorious", "damn adorable lol", "damn excellent wow", "amazing lol"], [". do u think u could come to my page as well?", ".. maybe u could give a comment on my ig too?", "... welcome to visit my page as well", "! u think u could give a check out to my ig as well?", "!!", "!!! could you maybe check me out too?"]]
tag_list = ["follow4follow", "songwriting", "followme", "instagood", "photography", "music", "taylorswift", "happy", "arianagrande", "instalifo", "likemypics", "kitties", "puppies", "coding", "food", "usa", "scene", "scenery", "pictures", "Kpop", "dance", "instadaily", "nature", "entertainment", "style", "smile", "love", "countrymusic", "photooftheday", "follow", "follow4follow", "like4like", "fashion", "beautiful", "happy", "cute", "tbt", "picoftheday", "me", "selfie", "summer", "art", "instadaily", "friends", "leagueoflegends", "musiccover", "likeme", "fun", "kawaii", "Japan", "tech", "beauty"]
```

**Comment by jfinly** [comment]
Same issue with the newest version, the old version works well.

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
