### ISSUE TITLE
Config Invalid interpolation syntax

### ISSUE THREAD

**Issue by weewey** [instabot-py/instabot.py#2224]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.1.1
```

#### Description of your issue

First running `instabot-py`, after entering password with special characters. 

```

INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
Traceback (most recent call last):
  File "/Users/yewweechua/.virtualenvs/instabot/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/Users/yewweechua/.virtualenvs/instabot/lib/python3.7/site-packages/instabot_py/__main__.py", line 392, in main
    configdict = interactive()
  File "/Users/yewweechua/.virtualenvs/instabot/lib/python3.7/site-packages/instabot_py/__main__.py", line 316, in interactive
    setupinteractive(config, config_location)
  File "/Users/yewweechua/.virtualenvs/instabot/lib/python3.7/site-packages/instabot_py/__main__.py", line 262, in setupinteractive
    config[confusername][setting] = str(confvar)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1256, in __setitem__
    return self._parser.set(self._name, key, value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1198, in set
    super().set(section, option, value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 893, in set
    value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 402, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in '&m*w@k6X%JMd' at position 8

```

Don't worry. I have changed my password. :)

**Comment by yurilaaziz** [comment]
please move to YAML Configuration in new versions
