### ISSUE TITLE
How to run instabot.py

### ISSUE THREAD

**Issue by vincent41** [instabot-py/instabot.py#2259]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```
Python 3.7.3

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 18.1

#### Description of your issue
How can i run a Code? If i run instabot-py
or python3 -m instabot_py 
i get an error on 
Raspberry Pi 3 Model B Rev 1.2
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:44 BST 2019 armv7l GNU/Linux
pi@raspberrypi:~ $ cat /etc/debian_version
10.0
```
Include the contents of the error.log here (if applicable). pi@raspberrypi:~ $ instabot-py
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/config42/handlers/files/yaml.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/instabot-py", line 6, in <module>
    from instabot_py.__main__ import main
  File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/config.py", line 24, in <module>
    config.set_many(ConfigManager(path=config_path.replace('//', '/')).as_dict())
  File "/home/pi/.local/lib/python3.7/site-packages/config42/config_manager.py", line 20, in __init__
    self.handler = handler(**handler_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/config42/handlers/files/__init__.py", line 12, in __new__
    from .yaml import YamlHandler as Handler
  File "/home/pi/.local/lib/python3.7/site-packages/config42/handlers/files/yaml.py", line 4, in <module>
    raise ImportError("files.Yaml handler requires 'PyYAML' package\n"
ImportError: files.Yaml handler requires 'PyYAML' package
Install it with 'pip install pyyaml'

```

#### Config
i dont see any config file after install "python3 -m pip install instabot-py"

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by ticevi** [comment]
Check the last line of the error message. 
You have to install another package.
pip install pyyaml

**Comment by vincent41** [comment]
thank you!
