### ISSUE TITLE
Bug " in get_media_id_by_tag     all_data = json.loads(r.text) " 

### ISSUE THREAD

**Issue by mrallanodreman** [instabot-py/instabot.py#2260]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
C:\Users\Allan>python --version
Python 3.7.3
```

#### Pip Version?
```
pip 19.1.1 from c:\users\allan\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)
```

#### Description of your issue

```
Microsoft Windows [Versión 10.0.18362.175]
(c) 2019 Microsoft Corporation. Todos los derechos reservados.


1313C:\Userss\Alllan\smartigg\grillee>python example.py
INFO : instabot_py.config:Setting configuration from instabot.config.yml : OK
2019-06-29 23:31:23,407 - InstaBot - INFO - Checking for updates...
2019-06-29 23:31:24,199 - InstaBot - INFO - You are running the latest stable version
2019-06-29 23:31:24,200 - InstaBot - INFO - Instabot v1.2.6/0 started at 29.06.2019 23:31:
2019-06-29 23:31:24,200 - InstaBot - INFO - Trying to login as radiogrilleburger...
2019-06-29 23:31:35,032 - InstaBot - INFO - radiogrilleburger login success!

2019-06-29 23:31:35,033 - InstaBot - INFO - Saving cookies to session file radiogrilleburger.session
2019-06-29 23:31:35,042 - InstaBot - INFO - Get Media by location: 214664036
2019-06-29 23:31:36,455 - InstaBot - DEBUG - Trying to like media: 2077430978973180021, https://www.instagram.
com/p/BzUhHf7FqB1/
2019-06-29 23:31:37,254 - InstaBot - INFO - Liked: 2077430978973180021. Like #1 https://www.instagram.com/p/Bz
UhHf7FqB1/.
2019-06-29 23:31:37,258 - InstaBot - DEBUG - Trying to follow: 2020231585
2019-06-29 23:31:40,885 - InstaBot - INFO - Followed: https://www.instagram.com/ferjose56/ #1.
2019-06-29 23:31:54,061 - InstaBot - DEBUG - > Waiting for database to populate before unfollowing (progress 1
3 /20)
2019-06-29 23:31:54,061 - InstaBot - DEBUG - Will try to populate using recent feed
2019-06-29 23:31:54,063 - InstaBot - DEBUG - radiogrilleburger : Get media id on recent feed
2019-06-29 23:31:54,931 - InstaBot - DEBUG - Media in recent feed = 12
2019-06-29 23:31:55,148 - InstaBot - DEBUG - Inserted user kamilatrujillo97 from recent feed
2019-06-29 23:31:55,304 - InstaBot - DEBUG - Inserted user lalolares1964 from recent feed
2019-06-29 23:31:55,463 - InstaBot - DEBUG - Inserted user fernanda.cordova.946954 from recent feed
2019-06-29 23:31:55,620 - InstaBot - DEBUG - Inserted user darielgram28 from recent feed
2019-06-29 23:31:55,779 - InstaBot - DEBUG - Inserted user andrees0395 from recent feed
2019-06-29 23:31:55,948 - InstaBot - DEBUG - Inserted user neglitoo_gonzalez from recent feed
2019-06-29 23:31:56,103 - InstaBot - DEBUG - Inserted user nathaliaconded from recent feed
2019-06-29 23:32:01,112 - InstaBot - DEBUG - Trying to like media: 2077410738336349315, https://www.instagram.
com/p/BzUcg9XHryD/
2019-06-29 23:32:01,789 - InstaBot - INFO - Liked: 2077410738336349315. Like #2 https://www.instagram.com/p/Bz
Ucg9XHryD/.
2019-06-29 23:32:06,792 - InstaBot - DEBUG - Get Media by tag: cuencaecuador
2019-06-29 23:32:26,877 - InstaBot - DEBUG - Trying to like media: 2077323590932694633, https://www.instagram.
com/p/BzUIszBFQZp/
2019-06-29 23:32:27,538 - InstaBot - INFO - Liked: 2077323590932694633. Like #3 https://www.instagram.com/p/Bz
UIszBFQZp/.
2019-06-29 23:32:53,566 - InstaBot - DEBUG - Trying to like media: 2077248415615500095, https://www.instagram.
com/p/BzT3m2jAT8_/
2019-06-29 23:32:54,230 - InstaBot - INFO - Liked: 2077248415615500095. Like #4 https://www.instagram.com/p/Bz
T3m2jAT8_/.
2019-06-29 23:33:15,240 - InstaBot - INFO - Get Media by location:  721468954640594
2019-06-29 23:33:15,535 - InstaBot - WARNING - Except on get_media!
2019-06-29 23:33:15,537 - InstaBot - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Allan\smartig\grille\instabot_py\instabot.py", line 508, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "C:\Users\Allan\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Allan\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Allan\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-06-29 23:33:15,546 - InstaBot - DEBUG - Could not remove media
2019-06-29 23:33:16,547 - InstaBot - DEBUG - Get Media by tag: cuencacity
2019-06-29 23:33:18,486 - InstaBot - DEBUG - Trying to like media: 2077414581031174723, https://www.instagram.
com/p/BzUdY4JlIJD/
2019-06-29 23:33:19,085 - InstaBot - INFO - Liked: 2077414581031174723. Like #5 https://www.instagram.com/p/Bz
UdY4JlIJD/.
2019-06-29 23:33:45,100 - InstaBot - DEBUG - Trying to like media: 2076290811402990365, https://www.instagram.
com/p/BzQd34IFTMd/
2019-06-29 23:33:45,507 - InstaBot - INFO - Liked: 2076290811402990365. Like #6 https://www.instagram.com/p/Bz
Qd34IFTMd/.
2019-06-29 23:34:12,526 - InstaBot - DEBUG - Trying to like media: 2075407426303981685, https://www.instagram.
com/p/BzNVA7pDnh1/
2019-06-29 23:34:12,897 - InstaBot - INFO - Liked: 2075407426303981685. Like #7 https://www.instagram.com/p/Bz
NVA7pDnh1/.
2019-06-29 23:34:24,904 - InstaBot - INFO - Get Media by location: 129521297641770
2019-06-29 23:34:34,301 - InstaBot - DEBUG - radiogrilleburger : Get media id on recent feed
2019-06-29 23:34:35,211 - InstaBot - DEBUG - Media in recent feed = 12
2019-06-29 23:34:35,243 - InstaBot - DEBUG - Trying to unfollow #1:
2019-06-29 23:34:35,245 - InstaBot - DEBUG - Looks like there is nobody to unfollow.
2019-06-29 23:34:37,248 - InstaBot - DEBUG - Trying to like media: 2077349036743269941, https://www.instagram.
com/p/BzUOfFRlR41/
2019-06-29 23:34:37,967 - InstaBot - INFO - Liked: 2077349036743269941. Like #8 https://www.instagram.com/p/Bz
UOfFRlR41/.< REPLACE THIS TEXT
```

#### Config

```
from instabot_py import InstaBot

bot = InstaBot(
    login="xxxxxx",  # Enter username (lowercase). Do not enter email!
    password="xxxxxxxx",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=["l:214664036", "l:12xx9764xxxx70", "l: 7214689xx594", "l:275250xxx96388", "l:59xxxx4", "cuxxxxxxx", "cxxxxxxxxxr", "xxxxx"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=300,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot"],
        ["is", "looks", "is 👉", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "🙌", "... 👏", "!", "! 😍", "😎"],
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        "second",
        "stuff",
        "art",
        "project",
        "love",
        "life",
        "food",
        "blog",
        "free",
        "keren",
        "photo",
        "graphy",
        "indo",
        "travel",
        "art",
        "shop",
        "store",
        "sex",
        "toko",
        "jual",
        "online",
        "murah",
        "jam",
        "kaos",
        "case",
        "baju",
        "fashion",
        "corp",
        "tas",
        "butik",
        "grosir",
        "karpet",
        "sosis",
        "salon",
        "skin",
        "care",
        "cloth",
        "tech",
        "rental",
        "kamera",
        "beauty",
        "express",
        "kredit",
        "collection",
        "impor",
        "preloved",
        "follow",
        "follower",
        "gain",
        ".id",
        "_id",
        "bags",
    ],
    unfollow_whitelist=["example_user_1", "example_user_2"],
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 9, # Hour you want the bot to start
    # start_at_m = 10, # Minute you want the bot to start, in this example 9:10 (am).
)

bot.mainloop()

```

keep working 

Like
Follow

Task Stoped
Unfollow

**Comment by yurilaaziz** [comment]
Thank you for your interest. 
I will work on it 
the JSON load method is not secured

**Comment by nachovoss** [comment]
![Captura33](https://user-images.githubusercontent.com/38444147/60914480-e7854180-a289-11e9-9993-b30eabd85669.PNG)

I'm still getting this error

**Comment by mrb0098** [comment]
i have the same problem in ubuntu :(

**Comment by NuLL3rr0r** [comment]
Same problem on the latest Debian.

**Comment by mrb0098** [comment]
i change :
all_data = json.loads(r.text)
to
all_data =r.json()

**Comment by NuLL3rr0r** [comment]
@mrb0098  thanks for your workaround, but I still get the same results:

```
2019-07-25 10:40:37,541 - InstaBot - WARNING - Except on get_media!
2019-07-25 10:40:37,541 - InstaBot - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 517, in get_media_id_by_tag
    all_data = r.json()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-07-25 10:40:37,545 - InstaBot - DEBUG - Could not remove media
^C2019-07-25 10:40:38,545 - InstaBot - INFO - Exit Program... GoodBye
```

**Comment by mrb0098** [comment]
If this problem is related to tags
I suggest you use the under line instead of the space
ex : 
best_friend :ok: 
best friend :no_entry:

**Comment by NuLL3rr0r** [comment]
I guess, intabot.py getting banned by Instagram somehow. Last night it worked, liked some posts, followed some people and it stopped working. I tried to remove the session file as suggested by others. But, I received this error afterward. I receive the login notification from Instagram by email:

```
We Noticed a New Login,
 
We noticed a login from a device you don't usually use.
 
 
 
Linux · Firefox · Unknown location
 
July 25 at 3:40 AM (PDT)
 
If this was you, you can safely disregard this email. If this wasn't you, you can secure your account here.
 
Learn more about keeping your account secure.
```

I guess Instagram wants confirmation and won't send the json.

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
