### ISSUE TITLE
Background on this error at: http://sqlalche.me/e/e3q8)

### ISSUE THREAD

**Issue by vdemir** [instabot-py/instabot.py#2270]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: medias.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example.py", line 130, in <module>
    bot.mainloop() 
  File "/usr/lib/python3.6/site-packages/instabot_py/instabot.py", line 798, in mainloop
    self.remove_already_liked()
  File "/usr/lib/python3.6/site-packages/instabot_py/instabot.py", line 829, in remove_already_liked
    media_id=self.media_by_tag[x]["node"]["id"]
  File "/usr/lib/python3.6/site-packages/instabot_py/persistence/sql.py", line 43, in check_already_liked
    .filter(Media.id == media_id) \
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3250, in one_or_none
    ret = list(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3323, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3348, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: medias.id
[SQL: SELECT medias.id AS medias_id, medias.created AS medias_created, medias.status AS medias_status, medias.code AS medias_code 
FROM medias 
WHERE medias.id = ?]
[parameters: ('2081259975367214757',)]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by Rick1998** [comment]
Same here!

**Comment by phewit** [comment]
I've it too

**Comment by stylesuxx** [comment]
Moving the db for my user worked around this issue.

**Comment by Rick1998** [comment]
> Moving the db for my user worked around this issue.

thanks man that really works!

**Comment by phewit** [comment]
> Moving the db for my user worked around this issue.

It worked for me!

**Comment by nemoback** [comment]
moving is not an option, I would like to unfollow and unlike, if I move this then it will not be unfollowed or unliked. how to fix currect db ? so it will work with new version of instabot-py ?

**Comment by ilMagnifico** [comment]
Same problem.

**Comment by iammoez** [comment]
> Moving the db for my user worked around this issue.

could you please explain how to do that , am not professional in Coding .. thank u btw

**Comment by ovaixalee** [comment]
The error seems pretty clear, the db driver is unable to open the sqlite file. Look at the connection URL and make sure it points to the location where your database is. Also make sure the database is created and has been populated with all its tables
