### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by davidslagorsky** [instabot-py/instabot.py#2292]
Hey guys, please help. I've had this issue for the past couple of days. Can't run it on my PC. 

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
python 3.7.0
```

#### Pip Version?
```
for some reason won't let me check. i get the same error as i get when running my example.py
```

#### Description of your issue

```
C:\Users\Games\Documents\instabot.py-master\instabot.py-master>py example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Games\Documents\instabot.py-master\instabot.py-master\src\__ini
t__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Games\Documents\instabot.py-master\instabot.py-master\src\insta
bot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "C:\Users\Games\Documents\instabot.py-master\instabot.py-master\src\useri
nfo.py", line 5, in <module>
    import requests
  File "C:\Users\Games\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\requests\__init__.py", line 112, in <module>
    from . import utils
  File "C:\Users\Games\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\Games\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\Games\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\requests\compat.py", line 60, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
OSError: [Errno 9] Bad file descriptor

```

#### Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="-",
    password="-",
    like_per_day=1800,
    comments_per_day=30,
    tag_list=["newmusic","newhiphop"'],
    tag_blacklist=['igpromo','nsfw'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["litt","firee","yea","nice"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'sex', 'toko', 'jual', 'online', 'murah', 'kaos',
        'case', 'baju', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by mrhili** [comment]
me to

**Comment by thecatextremist** [comment]
I have been having this same problem as well...
Can somebody please help us. I am quite the advanced python user and even I can't figure this out.
I know that it has something to do with sockets however,

**Comment by davidslagorsky** [comment]
Just adding, My mac works fine with the bot. I'm wondering what's wrong.

**Comment by yurilaaziz** [comment]
Please update, your version is deprecated

**Comment by davidslagorsky** [comment]
> Please update, your version is deprecated

I did now. still getting the exact same error even after running the 

> python3 -m pip install instabot-py

command

**Comment by mrhili** [comment]
The problem is with python

**Comment by Tahmeed156** [comment]
@mrhili what might be the problem?
I got this error in a different project, not even using this library.
I tried installing and reinstalling python but still getting the error.
What can I try?

**Comment by mrhili** [comment]
I talked with them here:

https://github.com/pypa/pip/issues/6711

**Comment by Tahmeed156** [comment]
@mrhili So what's the workaround for this?
I know other developers who has their pip in working mode with Windows build 1903.
Is the only way to install a different version of windows or is there any way I can solve this problem?
(Even a shitty method with a temporary fix will do for now)

**Comment by pradyunsg** [comment]
Try reinstalling Python?

**Comment by mrhili** [comment]
Brothers , @Tahmeed156  i discovered something , there is a virus who bloking pip to work correctly, try install the latest version of malwarebytes , for me after scaning i got everything work correctly
