### ISSUE TITLE
ValueError: empty range for randrange() (1,1, 0)

### ISSUE THREAD

**Issue by danielcharrua** [instabot-py/instabot.py#2297]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS 10.14.5
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

#### Description of your issue
I have first created the config file and the second time I have executed the script I get the error 
ValueError: empty range for randrange() (1,1, 0)
```
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
     Loading settings for ****!
     Config: /Users/****/Documents/Web/instagram/instabot.config.ini 
     (Tip: Log in directly by running 'instabot-py ****')'

     ______Starting bot_____
2019-07-16 13:46:35,859 - InstaBot - INFO - Checking for updates...
2019-07-16 13:46:36,380 - InstaBot - INFO - You are running the latest stable version
2019-07-16 13:46:36,380 - InstaBot - INFO - Instabot v1.2.6/0 started at 16.07.2019 13:46:
2019-07-16 13:46:36,381 - InstaBot - INFO - Found session file ****.session
2019-07-16 13:46:38,567 - InstaBot - INFO - **** login success!

2019-07-16 13:46:38,567 - InstaBot - INFO - Saving cookies to session file ****.session
2019-07-16 13:46:38,568 - InstaBot - DEBUG - Get Media by tag: negocios
Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 395, in main
    bot.mainloop()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 796, in mainloop
    1, self.max_like_for_one_tag
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)
```

#### Config

```
[DEFAULT]
username = none
password = none
like_per_day = 709
comments_per_day = 31
max_like_for_one_tag = 36
follow_per_day = 260
follow_time = 36000
unfollow_per_day = 247
unfollow_break_min = 3
unfollow_break_max = 17
log_mod = 0
proxy = 
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
comment_list = [["this", "the", "your"], ["photo", "picture", "pic", "shot", "snapshot"], ["is", "looks", "feels", "is really"], ["great", "super", "good", "very good", "good", "wow", "WOW", "cool", "GREAT", "magnificent", "magical", "very cool", "stylish", "beautiful", "so beautiful", "so stylish", "so professional", "lovely", "so lovely", "very lovely", "glorious", "so glorious", "very glorious", "adorable", "excellent", "amazing"], [".", "..", "...", "!", "!!", "!!!"]]
tag_list = ["follow4follow", "f4f", "cute", "l:212999109"]
tag_blacklist = ["rain", "thunderstorm"]
unwanted_username_list = ["second", "stuff", "art", "project", "love", "life", "food", "blog", "free", "keren", "photo", "graphy", "indo", "travel", "art", "shop", "store", "sex", "toko", "jual", "online", "murah", "jam", "kaos", "case", "baju", "fashion", "corp", "tas", "butik", "grosir", "karpet", "sosis", "salon", "skin", "care", "cloth", "tech", "rental", "kamera", "beauty", "express", "kredit", "collection", "impor", "preloved", "follow", "follower", "gain", ".id", "_id", "bags"]
unfollow_whitelist = ["example_user_1", "example_user_2"]

[****]
username = ****
password = ****
like_per_day = 50
comments_per_day = 0
max_like_for_one_tag = 0
follow_per_day = 20
follow_time = 172800
unfollow_per_day = 20
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
tag_list = ["diseñoweb", "coruña", "vigo", "galicia", "negocios", "marketing"]

```

**Comment by danielcharrua** [comment]
The issue was having `max_like_for_one_tag = 0`, changed the value to 10 and the bot started working.
