### ISSUE TITLE
Issue - failed to establish connection with github for updates

### ISSUE THREAD

**Issue by parthshiras** [instabot-py/instabot.py#2312]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ X] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ X] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.4
```

#### Pip Version?
```
pip 19.0.3
```

#### Description of your issue

```
Unable to establish connection and update
```

#### Config

```
     ______Starting bot_____
2019-07-26 10:23:53,581 - InstaBot - INFO - Checking for updates...
2019-07-26 10:24:14,637 - InstaBot - WARNING - Could not check for updates
2019-07-26 10:24:14,637 - InstaBot - ERROR - HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /instabot-py/instabot.py/raw/master/version.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x06FF24F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Traceback (most recent call last):
  File "c:\users\ke536ed\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "c:\users\ke536ed\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "c:\users\ke536ed\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
