### ISSUE TITLE
Challenge required - Entered code is wrong, Try again later!

### ISSUE THREAD

**Issue by stachyc** [instabot-py/instabot.py#2333]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?

Python 3.6.8

#### Pip Version?

pip 9.0.1 from /opt/ig-boot-yaml/venv/lib/python3.6/site-packages (python 3.6)

#### Description of your issue

2019-08-04 22:02:17,270 - user - Persistence - DEBUG - Init SQL Perisitence sqlite:///user.db
2019-08-04 22:02:17,311 - user - InstaBot - INFO - Instabot v0.5.4 started at 04.08.2019 22:02:
2019-08-04 22:02:17,312 - user - InstaBot - INFO - Trying to login as user...
2019-08-04 22:02:23,919 - user - InstaBot - DEBUG - Login request succeeded 
2019-08-04 22:02:23,919 - user - InstaBot - WARNING - Something wrong with login
2019-08-04 22:02:23,919 - user - InstaBot - DEBUG - {"message": "checkpoint_required", "checkpoint_url": "/challenge/4052374111/5EiCG0RIvQ/", "lock": false, "status": "fail"}
2019-08-04 22:02:23,919 - user - InstaBot - ERROR - "name='csrftoken', domain=None, path=None"
Traceback (most recent call last):
  File "/opt/ig-boot-yaml/venv/lib/python3.6/site-packages/instabot_py/instabot.py", line 319, in login
    self.csrftoken = login.cookies["csrftoken"]
  File "/opt/ig-boot-yaml/venv/lib/python3.6/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/opt/ig-boot-yaml/venv/lib/python3.6/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
2019-08-04 22:02:23,921 - user - InstaBot - INFO - Challenge required at https://instagram.com/challenge/4052374111/5EiCG0RIvQ/
Challenge Required.

Enter the code sent to your mail/phone: 246891
2019-08-04 22:02:57,171 - user - InstaBot - INFO - Entered code is wrong, Try again later!
2019-08-04 22:02:57,174 - user - InstaBot - INFO - Exit from loop GoodBye

#### Config
login : "XXXXX"
password : "XXXXXX"
debug: 1
follow_time: 604800
like_per_day: 709
comments_per_day: 31
max_like_for_one_tag: 36
follow_per_day: 260
follow_time: 36000
unfollow_per_day: 247
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false

**Comment by macd2** [comment]
the problem is this:
https://github.com/instabot-py/instabot.py/issues/2217#issuecomment-518031710

**Comment by yurilaaziz** [comment]
Are you receiving the code via SMS ? 
if yes, I am working on it

**Comment by stachyc** [comment]
yes , I receive email with code.

**Comment by ph94** [comment]
I've got the same problem yesterday. The code was not accepted, cos in the app poped up the window with the question "Were this your device?". I pressed yes, had to change the password and could log in with the bot afterwards.

**Comment by shae128** [comment]
I have the same issue, I receive the code via email but anytime I enter it the bot says:
Entered code is wrong, Try again later!

**Comment by iammoez** [comment]
i have the same issue (

**Comment by stachyc** [comment]
quick solution: try to switch from personal to bussines account and back or drom bussines to personal and back.This helped me.

**Comment by iammoez** [comment]
Ayt thank you very much mate , i will check out and let you know if i have
any questions , I appreciate it

**Comment by iammoez** [comment]
i still have this issue when i try to run the bot!

You didn't provide your Instagram login & password or you didn't specify
the configuration file

Try again :


   instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD

   instabot-py -c your-config.yml

You can export and modify the default configuration by typing the command
below

    instabot-py --dump





i used the command (instabot-py --dump ) , but it showed all the default
cong. What i can do now

**Comment by PranavSanghvi** [comment]
Has anyone found a solution?

**Comment by Programmierus** [comment]
Have same issue most likely because of insta being asking if that was me or not... Solutions?

**Comment by Th3BiSh0p** [comment]
Same issue here. Just installed the bot but it won't start because of that challenge issue.

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
