### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by arielgithub** [instabot-py/instabot.py#2336]
Any solution?

Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 252, in main
    bot.mainloop()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 750, in mainloop
    max_tag_like_count = random.randint(1, self.max_like_for_one_tag)
  File "/usr/local/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
TypeError: can only concatenate str (not "int") to str

**Comment by dracount** [comment]
same here

**Comment by topMbb** [comment]
how to fix it

**Comment by yurilaaziz** [comment]
please use the yaml configuration file, 
please removes quotes from numbers. 
please update
