### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by arielgithub** [instabot-py/instabot.py#2337]
Any Solution?

Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 252, in main
    bot.mainloop()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 756, in mainloop
    self.new_auto_mod_unfollow()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 899, in new_auto_mod_unfollow
    user = self.persistence.get_username_to_unfollow_random()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/persistence/sql.py", line 95, in get_username_to_unfollow_random
    if self.bot.follow_time > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by yurilaaziz** [comment]
please use the yaml configuration file
