### ISSUE TITLE
Conection error?

### ISSUE THREAD

**Issue by mrallanodreman** [instabot-py/instabot.py#2344]
2019-08-07 13:20:45,356 - mr.polemic - InstaBot - DEBUG - Trying to like media: id: 2105375148145410478, url: https://www.instagram.com/p/B03y4rgJIGu/
ERROR:root:('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/data/data/com.termux/files/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/data/data/com.termux/files/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/data/data/com.termux/files/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/data/data/com.termux/files/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/data/data/com.termux/files/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/data/data/com.termux/files/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/data/data/com.termux/files/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/data/data/com.termux/files/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/data/data/com.termux/files/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/data/data/com.termux/files/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/data/data/com.termux/files/usr/lib/python3.7/ssl.py", line 1071, in recv_into

I change the user agent to my device app-inbrowser user agent  and now afther the firts like the bot send me this

**Comment by mcarlock1** [comment]
is your error similar to the error im getting ?

2019-08-07 14:59:22,906 -  - InstaBot - INFO - Could not like media: id: 2105358880627349062, url: https://www.instagram.com/p/B03vL9MgdZG/. Reason: {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}

**Comment by mrallanodreman** [comment]
No bro

**Comment by mrallanodreman** [comment]
Close this error, was fixed with arrows

**Comment by parihacker** [comment]
What?
