### ISSUE TITLE
instabot v0.5.7 - sqlite3.IntegrityError: UNIQUE constraint failed: medias.id

### ISSUE THREAD

**Issue by fedex03** [instabot-py/instabot.py#2345]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [X] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Linux raspi4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
```

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.4
```

#### Pip Version?
```
pip 19.2.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

#### Instabot Version?
```
Installed version 0.5.7
```

#### How you use the instabot
- [X] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Today I updated my Instabot and after that I receive this error:
`
  2019-08-08 10:38:04,527 - userInsta - InstaBot - INFO - Trying to comment: xxxxx
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: medias.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 303, in main
    bot.mainloop()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 757, in mainloop
    self.new_auto_mod_comments(media)
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 1034, in new_auto_mod_comments
    self.persistence.insert_media(media["node"]["id"], "Error")
  File "/usr/local/lib/python3.7/site-packages/instabot_py/persistence/sql.py", line 66, in insert_media
    self._session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 493, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2458, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2596, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2556, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1066, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: medias.id
[SQL: INSERT INTO medias (id, created, status, code) VALUES (?, ?, ?, ?)]
[parameters: ('2105851246201283980', '2019-08-08 10:38:04.846781', 'Error', None)]
(Background on this error at: http://sqlalche.me/e/gkpj)

`

Before the update the bot works very well!

How I can solve this issue?

Thanks for your time and your great job with instabot!

```

#### Config

```
login : "user"
password : "pwd"
follow_time: 172800
like_per_day: 709
comments_per_day: 31
max_like_for_one_tag: 36
follow_per_day: 260
follow_time: 36000
unfollow_per_day: 247
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
```

**Comment by abourtnik** [comment]
Hello,

How do you resolve this issue ? I have the same error when I started my bot today.

**Comment by iammoez** [comment]
same issue with me (

**Comment by cyberthingsforgeeks** [comment]
same
