### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]

### ISSUE THREAD

**Issue by djmarcosban** [instabot-py/instabot.py#2350]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
2019-08-09 10:49:20,572 - InstaBot - DEBUG - Trying to follow: 30565546
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
ERROR:root:Except on get_username_by_user_id
Traceback (most recent call last):
  File "c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloadercontext.py", line 373, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloadercontext.py", line 373, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloadercontext.py", line 373, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\instabot.py", line 550, in get_username_by_user_id
    profile = instaloader.Profile.from_id(self.instaload.context, user_id)
  File "c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\structures.py", line 496, in from_id
    rhx_gis=context.root_rhx_gis)['data']['user']
  File "c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloadercontext.py", line 436, in graphql_query
    session=tmpsession)
  File "c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloadercontext.py", line 399, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloadercontext.py", line 399, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloadercontext.py", line 392, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 403.
2019-08-09 10:49:26,741 - InstaBot - INFO - Followed: https://www.instagram.com/False/ #1.
INFO:InstaBot:Followed: https://www.instagram.com/False/ #1.
```

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.4
```

#### Pip Version?
```
pip 19.1.1
```

#### Instabot Version?
```
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
default config
```

**Comment by boxfriend** [comment]
I have been receiving this error as well. It seems settings follow_per_day to 0 gets it to work as it only happens when attempting to follow another user

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
