### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by JesuTinto** [instabot-py/instabot.py#2372]
aaron@love:~/Downloads/instabot.py-master$ instabot-py -c sample.conf
Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 11, in <module>
    load_entry_point('instabot-py==0.5.9', 'console_scripts', 'instabot-py')()
  File "/usr/local/lib/python3.7/dist-packages/instabot_py-0.5.9-py3.7.egg/instabot_py/__main__.py", line 274, in main
  File "/usr/local/lib/python3.7/dist-packages/config42/config_manager.py", line 29, in __init__
    self.handler = self.load_handler(**handler_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/config42/config_manager.py", line 60, in load_handler
    return handler(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/config42/handlers/file.py", line 22, in __new__
    return Handler(path=path, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'schema'

**Comment by nickgryg** [comment]
This is very outdated issue. Please use the latest version of instabot.
