### ISSUE TITLE
Traceback (most recent call last) - json.decoder.JSONDecodeError: Unterminated string starting - Random error occuring suddenly

### ISSUE THREAD

**Issue by marcularis04** [instabot-py/instabot.py#2374]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Raspberry Pi - Raspbian
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 18.1 from /home/pi/venv/lib/python3.7/site-packages/pip (python 3.7)
```

#### Instabot Version?
```
Installed version 0.5.9
```
#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue
I get this error randomly, while the bot is running:
```
Traceback (most recent call last):                           
 File "/ home/pi/venv/bin/instabot-py", line 10, in <module> sys.exit(main())  File "/home/pi/venv/lib/python3.7/site-packages/ instabot_py/__main__.py", line 304, in main    bot.mainloop()  File "/home/pi/venv/lib/python3.7/site-packages/ instabot_py/instabot.py", line 762, in mainloop    self.new_auto_mod_comments(media)  File "/home/pi/venv/lib/python3.7/sitepackages/instabot_py/instabot.py", line 1030, in new_auto_mod_comments    if self.iteration_ready("comments") and self.verify_media_before_comment(media):  File "/home/pi/venv/lib/python3.7/sitepackages/instabot_py/instabot.py", line 1082, in verify_media_before_comment    all_data = json.loads(raw_data)["entry_data"] ["PostPage"][0]  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads    return _default_decoder.decode(s)  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode    obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2590 (char 2589)

  File "/home/pi/venv/lib/python3.7/site-packages/instabot_py/__main__.py", line 304, in main
    bot.mainloop()
  File "/home/pi/venv/lib/python3.7/site-packages/instabot_py/instabot.py", line 762, in mainloop
    self.new_auto_mod_comments(media)
  File "/home/pi/venv/lib/python3.7/site-packages/instabot_py/instabot.py", line 1030, in new_auto_mod_comments
    if self.iteration_ready("comments") and self.verify_media_before_comment(media):
  File "/home/pi/venv/lib/python3.7/site-packages/instabot_py/instabot.py", line 1082, in verify_media_before_comment
    all_data = json.loads(raw_data)["entry_data"]["PostPage"][0]
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2563 (char 2562)
```
It's the same format always, just the line numbers differ. It just appears randomly, while the bot is running REALLY well. Then, Instabot stops working. After the error, I can restart Instabot, run it for 3-4 hours, then when I return at the SSH terminal, it shows me this error. Sometimes, this error appears immediately after running. It's the same always, only the line numbers differ. I have installed the latest Instabot with this tutorial:

```
#Install python3-venv to create virtual env
# In Ubuntu, install it using apt
sudo apt install python3-venv 
# Create a virtual env 
python3 -m venv venv 
source venv/bin/activate
pip install instabot-py
instabot-py --version
```
The source is `https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a`
```
#### Config
login : "myusername"
password : "mypassword"
accept_language: en-US,en;q=0.5
ban_sleep_time: 10800
comment_list:
- (my comments)
comments_per_day: 24
comments_per_run: '{{comments_per_day}}'
database:
  connection_string: sqlite:///{{database.path}}
  path: '{{login}}.db'
  type: sql
debug: 0
dump_configuration: false
end_at_h: 21
end_at_m: 45
error_400_to_ban: 3
follow_per_day: 30
follow_per_run: 30
follow_time: 18000
follow_time_enabled: true
like_per_day: 30
like_per_run: 30
list_of_ua:
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.6.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.7.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.5.01003)
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/5.0 (Windows NT 5.1; rv:13.0) Gecko/20100101 Firefox/13.0.1
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko/20100101 Firefox/11.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.0.3705)
- Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727;
  .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
- Opera/9.80 (Windows NT 5.1; U; en) Presto/2.10.289 Version/12.01
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)
- Mozilla/5.0 (Windows NT 5.1; rv:5.0.1) Gecko/20100101 Firefox/5.0.1
- Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/5.02
- Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.112
  Safari/535.1
- Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition
  [en]
log_mod: 0
logging:
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s - {{login}} - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
  loggers:
    InstaBot:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
    Persistence:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
  root:
    level: INFO
  version: 1
max_like_for_one_tag: 11
media_max_like: 150
media_min_like: 0
session_file: '{{login}}.session'
start_at_h: 9
start_at_m: 30
tag_list:
- (my list)
time_till_unlike: 0
unfollow_break_max: 75
unfollow_break_min: 50
unfollow_everyone: false
unfollow_inactive: true
unfollow_not_following: true
unfollow_per_day: 30
unfollow_per_run: 30
unfollow_probably_fake: true
unfollow_recent_feed: false
unfollow_selebgram: false
unlike_per_day: 0
unlike_per_run: 0
user_max_follow: 0
user_min_follow: 0
window_check_every: 300
```

**Comment by iamklaus** [comment]
Same for me.

**Comment by marcularis04** [comment]
Have you found the solution? I have to keep my SSH open all day to restart instabot when this error occurs

**Comment by dragonito** [comment]
> Have you found the solution? I have to keep my SSH open all day to restart instabot when this error occurs

I´m using nohub like this

```
nohup python3 -m instabot_py -c username.config.yml &
```

Errors are loged to nohub.log

**Comment by marcularis04** [comment]
I'll give it a try. For now, I tried reinstalling and upgrading anything I could. Now it's running, but maybe after 2-3 hours it'll give me this error. I'll keep you informed

**Comment by martygriffin** [comment]
+1

**Comment by pihomeserver** [comment]
The nohup will only allow to close the session and keep the bot running. Unfortunatly it does not restart the bot in case of a crash ...

**Comment by pihomeserver** [comment]
@marcularis04 any feedback ?

**Comment by pihomeserver** [comment]
As it seems that the parsing of the JSON reply does not seems correct i added some traces in the program. Let's now wait for a crash ....

**Comment by nickgryg** [comment]
It is very outdated issue. If you still have it, please use instabot-py version 0.5.20 or later.
