### ISSUE TITLE
Login Issue (traceback)

### ISSUE THREAD

**Issue by Slayboo** [instabot-py/instabot.py#2381]
19.08.2019_11:41 Checking for updates...
19.08.2019_11:41 > UPDATE AVAILABLE Please update Instabot 'python3 -m pip install instabot-py --upgrade'
19.08.2019_11:41 Instabot v1.2.5/0 started at 19.08.2019 11:41:
19.08.2019_11:41 Trying to login as fatal.interest.gg...
Traceback (most recent call last):
  File "c:\users\clint\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\clint\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\clint\AppData\Local\Programs\Python\Python37-32\Scripts\instabot-py.exe\__main__.py", line 9, in <module>
  File "c:\users\clint\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\__main__.py", line 395, in main
    bot = InstaBot(**configdict)
  File "c:\users\clint\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\instabot.py", line 365, in __init__
    self.login()
  File "c:\users\clint\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\instabot.py", line 589, in login
    self.user_id = self.get_user_id_by_username(self.user_login)
  File "c:\users\clint\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\instabot.py", line 395, in get_user_id_by_username
    id_user = json_info["entry_data"]["ProfilePage"][0]["graphql"]["user"]["id"]
KeyError: 

> 'graphql'

**Comment by parthshiras** [comment]
Same issue. Upgraded the bot still running into the same problem.

**Comment by Slayboo** [comment]
I have updated the bot, also.  Hopefully theres a fix soon. works on my other Instagram account, so very confused.

**Comment by parthshiras** [comment]
Same here. Bot works fine with other accounts, but gives the following issue - 

id_user = json_info["entry_data"]["ProfilePage"][0]["graphql"]["user"]["id"]
KeyError: 'graphql'

**Comment by H00kahMan** [comment]
I had the same problem, solved by deleting the .session file and re-logging in with 'challenge required' code, and shortly after Insta detected and warned me to change my password.

**Comment by Slayboo** [comment]
> I had the same problem, solved by deleting the .session file and re-logging in with 'challenge required' code, and shortly after Insta detected and warned me to change my password.

Did not work for me, I get an email directly after I start the bot everytime saying unknown browser then it shuts bot off with above error

**Comment by Andy2903** [comment]
same error here

**Comment by IsaackHazaell** [comment]
Same error, someone knows the solution?

**Comment by dsmh** [comment]
I have 7 accounts running (some of them with the blocking issue) but with one account I'm unable to login with the following error log: 
```
2019-08-20 11:21:02,923 - santiagopizarrov - Persistence - DEBUG - Init SQL Perisitence sqlite:///santiagopizarrov.db
2019-08-20 11:21:03,017 - santiagopizarrov - InstaBot - INFO - Instabot v0.5.9 started at 20.08.2019 11:21:
2019-08-20 11:21:03,021 - santiagopizarrov - InstaBot - INFO - Trying to login as santiagopizarrov...
2019-08-20 11:21:08,282 - santiagopizarrov - InstaBot - DEBUG - Login request succeeded 
Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 294, in main
    bot = InstaBot(config=config)
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 214, in __init__
    self.login()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 425, in login
    self.user_id = self.get_user_id_by_username(self.user_login)
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 230, in get_user_id_by_username
    id_user = json_info["entry_data"]["ProfilePage"][0]["graphql"]["user"]["id"]
KeyError: 'graphql'
```

**Comment by canpoyrazoglu** [comment]
Yup, same. I have 3 accounts, one with this problem, and I can't find any session file too.

**Comment by Slayboo** [comment]
no fix?

**Comment by daggerire** [comment]
Very same issue.
Clearing Session File did not help, Adding and removing two factor did not work.

**Comment by parthshiras** [comment]
I switched to a personal account from the creator account type and now there is a new error ->

```
InstaBot - ERROR - Something is wrong with Instagram! Please try again later...
2019-08-22 22:53:32,576 - InstaBot - ERROR - Error =>Sorry, there was a problem with your request.
2019-08-22 22:53:32,577 - InstaBot - INFO - Exit Program... GoodBye
```

**Comment by Shreyasdbz** [comment]
This is because Instagram flags your account as suspicious. So you have to manually confirm it was you.

**Comment by Slayboo** [comment]
how do I do that

**Comment by daggerire** [comment]
> 
> 
> This is because Instagram flags your account as suspicious. So you have to manually confirm it was you.

I have tried this, and tried changing vpn locations and reconfirming  but issue is still the same

**Comment by parthshiras** [comment]
Still no fix..

**Comment by nickblitz** [comment]
Same error here. Also this is my first time trying to login with this version and no session file has yet been created.

**Comment by jezsmith720** [comment]
Still same error

**Comment by nickgryg** [comment]
It is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
