### ISSUE TITLE
Bot fails after commenting

### ISSUE THREAD

**Issue by craigslong** [instabot-py/instabot.py#2385]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
3.73
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [x ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
After logging in, bot likes and follows, then tries to comment and shuts down with error.
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\engine\default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: medias.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\Scripts\instabot-py.exe\__main__.py", line 9, in <module>
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\__main__.py", line 304, in main
    bot.mainloop()
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\instabot.py", line 762, in mainloop
    self.new_auto_mod_comments(media)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\instabot.py", line 1039, in new_auto_mod_comments
    self.persistence.insert_media(media["node"]["id"], "Error")
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\persistence\sql.py", line 66, in insert_media
    self._session.commit()
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\session.py", line 1026, in commit
    self.transaction.commit()
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\session.py", line 493, in commit
    self._prepare_impl()
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\session.py", line 472, in _prepare_impl
    self.session.flush()
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\session.py", line 2458, in flush
    self._flush(objects)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\session.py", line 2596, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\session.py", line 2556, in _flush
    flush_context.execute()
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    insert,
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\orm\persistence.py", line 1066, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sqlalchemy\engine\default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: medias.id
[SQL: INSERT INTO medias (id, created, status, code) VALUES (?, ?, ?, ?)]
[parameters: ('2114989189400413577', '2019-08-20 18:22:52.754780', 'Error', None)]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by spud-dog** [comment]
I have the same issue. Bot comments on one or two posts then stops working. Have changed comments to simple ascii text but this still doesn't improve situation

**Comment by srikanthvavilala** [comment]
Hi, can someone help me how to add the hashtags and locations in tag_list in configuration file,my config file looks like this,the bot is working fine for 1hour later on it is getting stopped with the below error.
Traceback (most recent call last):
  File "c:\users\srikanth vavilala\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\srikanth vavilala\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Srikanth Vavilala\AppData\Local\Programs\Python\Python37\Scripts\instabot-py.exe\__main__.py", line 9, in <module>
  File "c:\users\srikanth vavilala\appdata\local\programs\python\python37\lib\site-packages\instabot\__main__.py", line 345, in main
    bot.run()
  File "c:\users\srikanth vavilala\appdata\local\programs\python\python37\lib\site-packages\instabot\bot.py", line 740, in run
    self.new_auto_mod_comments(media)
  File "c:\users\srikanth vavilala\appdata\local\programs\python\python37\lib\site-packages\instabot\bot.py", line 1008, in new_auto_mod_comments
    if self.iteration_ready("comments") and self.verify_media_before_comment(media):
  File "c:\users\srikanth vavilala\appdata\local\programs\python\python37\lib\site-packages\instabot\bot.py", line 1060, in verify_media_before_comment
    all_data = json.loads(raw_data)["entry_data"]["PostPage"][0]
  File "c:\users\srikanth vavilala\appdata\local\programs\python\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\srikanth vavilala\appdata\local\programs\python\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\srikanth vavilala\appdata\local\programs\python\python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 6674 (char 6673)

**Comment by mariyagcv** [comment]
Still having same issue with the latest version of the bot

**Comment by nickgryg** [comment]
What is the last version of the bot? Please provide the error output here.

**Comment by mariyagcv** [comment]
bot version: Instabot v0.7.9
pip: pip 20.0.2 
python: Python 3.8.2
using bot with: instabot-py


```
2020-04-09 09:43:14,377 - usrname - InstaBot - INFO - Trying to comment 2283225607701792917, url: https://www.instagram.com/p/B-vpZfZJAiV/
Traceback (most recent call last):
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: medias.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\usrname\AppData\Local\Programs\Python\Python38\Scripts\instabot-py.exe\__main__.py", line 7, in <module>
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\instabot_py\__main__.py", line 372, in main
    bot.mainloop()
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\instabot_py\instabot.py", line 840, in mainloop
    self.new_auto_mod_comments(media)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\instabot_py\instabot.py", line 1220, in new_auto_mod_comments
    self.persistence.insert_media(media['node']['id'], 'Error')
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\instabot_py\persistence\sql.py", line 66, in insert_media
    self._session.commit()
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\session.py", line 1027, in commit
    self.transaction.commit()
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\session.py", line 494, in commit
    self._prepare_impl()
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\session.py", line 473, in _prepare_impl
    self.session.flush()
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\session.py", line 2470, in flush
    self._flush(objects)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\session.py", line 2568, in _flush
    flush_context.execute()
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "c:\users\usrname\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: medias.id
[SQL: INSERT INTO medias (id, created, status, code) VALUES (?, ?, ?, ?)]
[parameters: ('2283225607701792917', '2020-04-09 09:43:15.089958', 'Error', None)]
(Background on this error at: http://sqlalche.me/e/gkpj)`
```
