### ISSUE TITLE
ERROR - "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by CharlsBags** [instabot-py/instabot.py#2388]
Hi, 

I have a brand new server, just compiled, installed services, pip, pyhton etc.. and instabot_py is  running
I can run instabot_py simultaneously using screen. On 2 profile everything is ok
on third I've got this error. This is a business profile.
User / Password are OK
I tried to run only this bot (stopping others 2), same error....

===================

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 
#1153 
#1287 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
Brand new Ubuntu 18.04 server ed.

```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [x] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
Linux hostname 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.6.8

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```
Instabot v0.5.9

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [x] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

user@hostname:~$ python3 -m instabot_py -c my_insta_profile.yml
2019-08-22 14:57:01,016 - my_insta_profile - Persistence - DEBUG - Init SQL Perisitence sqlite:///my_insta_profile.db
2019-08-22 14:57:01,123 - my_insta_profile - InstaBot - INFO - Instabot v0.5.9 started at 22.08.2019 14:57:
2019-08-22 14:57:01,126 - my_insta_profile - InstaBot - INFO - Trying to login as my_insta_profile...
2019-08-22 14:57:05,053 - my_insta_profile - InstaBot - DEBUG - Login request succeeded
2019-08-22 14:57:05,054 - my_insta_profile - InstaBot - WARNING - Something wrong with login
2019-08-22 14:57:05,055 - my_insta_profile - InstaBot - DEBUG - {"authenticated": false, "user": true, "status": "ok"}
2019-08-22 14:57:05,055 - my_insta_profile - InstaBot - ERROR - "name='csrftoken', domain=None, path=None"
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/instabot_py/instabot.py", line 319, in login
    self.csrftoken = login.cookies["csrftoken"]
  File "/home/user/.local/lib/python3.6/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/user/.local/lib/python3.6/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
2019-08-22 14:57:05,062 - my_insta_profile - InstaBot - ERROR - Login error! Check your login data!
2019-08-22 14:57:05,063 - my_insta_profile - InstaBot - INFO - Exit from loop GoodBye

#### Config

defauld by dump, changed username & password and tags.

**Comment by nickgryg** [comment]
It is very outdated issue. If you still have it, please use version 0.5.20 or later.
