### ISSUE TITLE
error expecting value

### ISSUE THREAD

**Issue by dilox123** [instabot-py/instabot.py#2389]
i used instabot-py --login --password
after about 40m, it says me that
019-08-22 15:46:42,530 - meme_mondiali_mercantili - InstaBot - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/instabot_py-0.5.9-py3.7.egg/instabot_py/instabot.py", line 500, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/dilox/.local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/instabot_py-0.5.9-py3.7.egg/instabot_py/__main__.py", line 314, in main
  File "/usr/local/lib/python3.7/dist-packages/instabot_py-0.5.9-py3.7.egg/instabot_py/instabot.py", line 751, in mainloop
TypeError: object of type 'NoneType' has no len()

**Comment by pihomeserver** [comment]
Same than #2374

**Comment by nickgryg** [comment]
This issue is very outdated. If you still have it, just update instabot-py to the latest version.
