### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2646 (char 2645)

### ISSUE THREAD

**Issue by bijanzd** [instabot-py/instabot.py#2390]
**evertime i use bot for commenting after 3 or 4 comment this error disappear !**

2019-08-22 22:18:14,275 - username - InstaBot - DEBUG - Retrieved 72 medias
2019-08-22 22:18:14,309 - username - InstaBot - DEBUG - Select 1 medias to process. Increase max_like_for_one_tag value for more processing medias 
Traceback (most recent call last):
  File "/usr/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/instabot_py/__main__.py", line 304, in main
    bot.mainloop()
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 762, in mainloop
    self.new_auto_mod_comments(media)
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 1030, in new_auto_mod_comments
    if self.iteration_ready("comments") and self.verify_media_before_comment(media):
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 1082, in verify_media_before_comment
    all_data = json.loads(raw_data)["entry_data"]["PostPage"][0]
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2646 (char 2645)

**thanks for your help !**

**Comment by Pitti1981** [comment]
me too...same issue after a random count of comments... :-(

**Comment by bijanzd** [comment]
nice support !
