### ISSUE TITLE
Json decode error on verify_media_before_comment

### ISSUE THREAD

**Issue by neok** [instabot-py/instabot.py#2415]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

#### Instabot Version?
```
Installed version 0.5.9
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Traceback (most recent call last):

  File "/usr/local/bin/instabot-py", line 11, in <module>

    load_entry_point('instabot-py==0.5.9', 'console_scripts', 'instabot-py')()

  File "/usr/local/lib/python3.7/site-packages/instabot_py-0.5.9-py3.7.egg/instabot_py/__main__.py", line 314, in main

  File "/usr/local/lib/python3.7/site-packages/instabot_py-0.5.9-py3.7.egg/instabot_py/instabot.py", line 764, in mainloop

  File "/usr/local/lib/python3.7/site-packages/instabot_py-0.5.9-py3.7.egg/instabot_py/instabot.py", line 1032, in new_auto_mod_comments

  File "/usr/local/lib/python3.7/site-packages/instabot_py-0.5.9-py3.7.egg/instabot_py/instabot.py", line 1084, in verify_media_before_comment

  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads

    return _default_decoder.decode(s)

  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode

    obj, end = self.scan_once(s, idx)

json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 19424 (char 19423)
```

**Comment by nickgryg** [comment]
Please update instabot to the latest version by performing ```python3 -m pip install --no-cache-dir --upgrade git+https://github.com/instabot-py/instabot.py``` and check if you still have above issue.
