### ISSUE TITLE
Matching error

### ISSUE THREAD

**Issue by TheLarry27** [instabot-py/instabot.py#2427]
Traceback (most recent call last):
  File "D:\Desktop\instapy-quickstart-master\quickstart.py", line 18, in <module>
    multi_logs=True)
  File "C:\Users\Vincent von Berg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\Vincent von Berg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Vincent von Berg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Vincent von Berg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Vincent von Berg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Vincent von Berg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Vincent von Berg\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by nickgryg** [comment]
What's this? It doesn't look like instabot at all.
