### ISSUE TITLE
instabot-py shows this after it signs in.

### ISSUE THREAD

**Issue by gavinmicks** [instabot-py/instabot.py#2436]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [no] Are you hosting the bot on a VPS or other Cloud hosting?
- [no] Are you running the code on your phone
- [n/a] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.3
```

#### Pip Version?
```
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

```

#### Instabot Version?
```
 Could not find user in settings. Would you like to add now? (yes/no):
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue
Shows this:
     ______Starting bot_____
2019-10-19 19:57:23,914 - InstaBot - INFO - Checking for updates...
2019-10-19 19:57:24,405 - InstaBot - INFO - You are running the latest stablersion
2019-10-19 19:57:24,405 - InstaBot - INFO - Instabot v1.2.6/0 started at 19.1019 19:57:
2019-10-19 19:57:24,408 - InstaBot - INFO - Trying to login as edgymemez.ig..
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/__main__.py",ne 399, in <module>
    main()
  File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/__main__.py",ne 394, in main
    bot = InstaBot(**configdict)
  File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/instabot.py",ne 202, in __init__
    self.login()
  File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/instabot.py",ne 443, in login
    self.user_id = self.get_user_id_by_username(self.user_login)
  File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/instabot.py",ne 246, in get_user_id_by_username
    id_user = json_info["entry_data"]["ProfilePage"][0]["graphql"]["user"]["i
KeyError: 'graphql'

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Could not find user in settings. Would you like to add now? (yes/no): 

```

**Comment by elmissouri16** [comment]
I think problem-related to instaloader module try updated to latest version

**Comment by cyberthingsforgeeks** [comment]
same problem KeyError: 'graphql'

**Comment by elmissouri16** [comment]
error is related to instaloader module try updated to the latest version and see if  solve the problem for you

**Comment by nickgryg** [comment]
Version 0.5.20 was released yesterday. Above issue should been fixed in it.
