### ISSUE TITLE
i very tired with whis problem > anyone please help me .

### ISSUE THREAD

**Issue by mongkol2222** [instabot-py/instabot.py#2437]
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "/root/Desktop/hack/instabot.py-master/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/root/Desktop/hack/instabot.py-master/instabot_py/instabot.py", line 19, in <module>
    import instaloader
ModuleNotFoundError: No module named 'instaloader'

**Comment by elmissouri16** [comment]
you have to install the missing module  
if you have pip installed , run this command: pip install instaloader
