### ISSUE TITLE
Help wanted questions

### ISSUE THREAD

**Issue by polaroi8d** [instabot-py/instabot.py#245]
There is tons of pointless issues, so I decide to open an issue for the dumb questions. Feel free to ask here. BUT First please read the README.md file.

**Comment by marianssen** [comment]
I'm completely new to Python, and I'm trying to get this script working, but without any luck. Could you please suggest what I'm doing wrong?

```
cd '/Users/marianrehak/Downloads/instabot.py-master/src/' && '/usr/local/bin/pythonw'  '/Users/marianrehak/Downloads/instabot.py-master/src/instabot.py'  && echo Exit status: $? && exit 1
Marians-MacBook-Pro:~ marianrehak$ cd '/Users/marianrehak/Downloads/instabot.py-master/src/' && '/usr/local/bin/pythonw'  '/Users/marianrehak/Downloads/instabot.py-master/src/instabot.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/marianrehak/Downloads/instabot.py-master/src/instabot.py", line 4, in <module>
    from userinfo import UserInfo
  File "/Users/marianrehak/Downloads/instabot.py-master/src/userinfo.py", line 4, in <module>
    import requests
ImportError: No module named requests
Marians-MacBook-Pro:src marianrehak$ 
```

I'm using Python 3.5.2 on OS X.

**Comment by virginsince1997** [comment]
$ sudo pip install requests

**Comment by alexcheninfo** [comment]
My bot is following and un-following the same users. So, my accounts are getting banned from Instagram. Can someone give me a sample code explaining how to automatically backlist un-followed users?

(I have a JavaScript background, so I'm a bit lost here.)

I appreciate any help.

**Comment by Faykai** [comment]
Hi Guys,
I saw somewhere here around that someone talked about liking by location by adding "l:12345678",
to the TagList .
First, I can't find it anymore here.
Second, somebody know if it's works and how to run this option ?

It'll help a lot to some people who are running this code for branding .

TIA !

**Comment by kemong** [comment]
Hy @alexcheninfo !
First question would be. why do you keep follow and unfollow the same person, again and again and again? 
If you use mode 0 (zero) you have to MAKE SURE that the tag you are using are popular tags.
If there are only small people around the globe who use that tags, the photos on the tag feed is never been updated for a long time, you like the first photo on the tag feed now, you follow the owner, next you unfollow him, two days later no-one upload a photo using that tag, so your bot like the first photo on the tag feed again, the same photo on the day one.

You (till now) can't dig deep to more than 24 photos on tag feed. So, even if you check the tag #applepie (for example) and you can see that there are 123.245 photos uploaded using the tag, your bot will only get 24 recent photos uploaded using #applepie. If this recent photos never updated (eg: no-one else on this planet using the tag anymore) you will follow the same person again and again.

First you check the tag, search using instagram app by your tag, check it periodically, if in ten minutes interval the photos just stay the same, then the problem is you are choosing non-popular tags.

If you use popular tags, and the photo on the tag feed updated very fast, i'll back with the solution later.

**Comment by virginsince1997** [comment]
Sorry
Seems your missing a module requests
To install type
$ pip install requests

**Comment by virginsince1997** [comment]
Use python 2.7

**Comment by meeser93** [comment]
Virgin is right, try using 2.7. Some modules are not supported in 3 if I'm not mistaken.

**Comment by TTAAEELL** [comment]
I'm still getting error with latest version: Couldn't find caption.
Running on both python 2.7 and qpython on android.

Any solutions?

**Comment by rachteo** [comment]
Sorry, stupid question, but with the new modes, people I actually _want_ to follow keep getting unfollowed, even in mode 0, which if I'm understanding correctly is the default mode. The older version used to only unfollow users which the bot had followed and leave the rest of my Following list alone. Am I missing something in editing the example.py file?

**Comment by TTAAEELL** [comment]
new error

`Traceback (most recent call last):
  File "C:\instabot\example.py", line 74, in <module>
    bot.new_auto_mod()
  File "C:\instabot\src\instabot.py", line 519, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\instabot\src\instabot.py", line 572, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "C:\instabot\src\instabot.py", line 601, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Trying to unfollow: 1681776433
Unfollow: 1681776433 #19 of 31.
Pausing for 22 seconds... 19 of 31
Logout: likes - 58, follow - 31, unfollow - 19, comments - 30.
Bot work time: 1:27:39.845000
Logout success!
Exception KeyError: KeyError(80632,) in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored`

**Comment by drewhga** [comment]
Sorry but at the moment the seems to be no answer for this error. It occurs
when an account with either 0 following or followers is met..... It might
be a long shot but try handling the exception.

except ValueError:

**Comment by saveasex** [comment]
Traceback (most recent call last):
File "C:\Program Files\instabot.py-master\example.py", line 27, in <module>
proxy='',)
File "C:\Program Files\instabot.py-master\src\instabot.py", line 185, in init
self.populate_user_blacklist()
File "C:\Program Files\instabot.py-master\src\instabot.py", line 197, in populate_user_blacklist
self.user_blacklist[user]=id_user
TypeError: 'set' object does not support item assignment

**Comment by saveasex** [comment]
Traceback (most recent call last):
File "C:\Program Files\instabot.py-master\example.py", line 27, in <module>
proxy='',)
File "C:\Program Files\instabot.py-master\src\instabot.py", line 185, in init
self.populate_user_blacklist()
File "C:\Program Files\instabot.py-master\src\instabot.py", line 197, in populate_user_blacklist
self.user_blacklist[user]=id_user
TypeError: 'set' object does not support item assignment

**Comment by ierogliph** [comment]
Hi. Sometimes i see this errors:

`Couldn't find caption - not liking
Trying to follow: 2033305148
Followed: 2033305148 #1.
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Get media id by tag: art
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Trying to like media: 1376656274485278459
Liked: 1376656274485278459. Like #1.
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Get media id by tag: vscobest
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Trying to like media: 1376656705659788353
Liked: 1376656705659788353. Like #2.
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
`

**Comment by antoniotrento** [comment]
Using on CENT OS python 2.7 and works well.
How to install python search it on digital ocean community
to install pip used this https://www.youtube.com/watch?v=3m9HERsGeKM here a video
Check your file.py conf to have a good configuration

**Comment by antoniotrento** [comment]
## Issue using CENTOS with phyton 2.7

for the third consecutive time, these days, the bot did logout from instagram and forces me to restart it, does anyone know help me solve the problem? I wish I could make it go 24/7 without having to stand by every time

Error:

> Pausing for 29 seconds... 14 of 22
Logout: likes - 103, follow - 22, unfollow - 14, comments - 21.
Bot work time: 5:00:58.585044
Logout success!
Exception KeyError: KeyError(140693750376256,) in <module 'threading' from '/usr/lib64/python2.7/threading.pyc'> ignored
[root@localhost instabot.py-master]#

**Comment by penguinsarepeopletoo** [comment]
I'm having the same issue as @ierogliph

**Comment by TTAAEELL** [comment]
@penguinsarepeopletoo This error is completely gone in latest version.

**Comment by penguinsarepeopletoo** [comment]
@TTAAEELL I am using the latest version.

**Comment by Sergekuz** [comment]
@penguinsarepeopletoo did you fix ti? I tried removing try/except block, and still doesn't work.

**Comment by tiagokotryk** [comment]
can the bot follow someone's followers?

**Comment by penguinsarepeopletoo** [comment]
@Sergekuz No, still having the same issue

**Comment by tiagokotryk** [comment]
that's bad. do you know about a bot that can do this? I only know about the paid ones.

**Comment by 179skr** [comment]
Does this bot write who the bot followed in a txt file? I wanted to use the feature which unfollows anyone who hasnt followed back but instead of it being in a list i wanted the bot to read it from a txt file. Whats the best way to do this?

**Comment by jpalmer505** [comment]
I have python 2.7.13 in a virtual machine running Ubuntu. I have ran $ pip install request several times yet I keep receiving the: No module named request error.... Any suggestions?? 


  File "/home/ares/Desktop/instabot.py-master/src/instabot.py", line 4, in <module>
    from userinfo import UserInfo
  File "/home/ares/Desktop/instabot.py-master/src/userinfo.py", line 4, in <module>
    import requests
ImportError: No module named requests

**Comment by tiagokotryk** [comment]
@jpalmer505 what is the link for this virtual machine you're using? I'd like to try

**Comment by jpalmer505** [comment]
I'm using VirtualBox with Ubuntu 16.04, Currently trying out a virtualenv within it running python 2.7.10. Hopefully that will work.

**Comment by jpalmer505** [comment]
In case anyone runs into the same issue... I installed ubuntu 15.10 wily w/ python 2.7.10 and finally got it to run.

**Comment by polaroi8d** [comment]
@jpalmer505 it good the hear

**Comment by 179skr** [comment]
Sorry but whats the point of this issue if all questions here are simply being ignored.

**Comment by virginsince1997** [comment]
Join the group on telegram...

**Comment by 179skr** [comment]
Could you send me a link please thank you 😊

**Comment by Lobsang26** [comment]
Hi.
Is it possible to make bot unfollow (for example) 30 users which I want to unfollow and after this, follow them back, make 20 minute break and repeat the process again, and again and again for like few hours?
I've tried to do something with follow and unfollow protocols and changing values in example.py but as a newbie in programming I mostly read the code and edit few things which ended up with errors.
