### ISSUE TITLE
NEED HELP?

### ISSUE THREAD

**Issue by willtbrown** [instabot-py/instabot.py#2456]
______Starting bot_____
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\Scripts\instabot-py.exe\__main__.py", line 9, in <module>
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\__main__.py", line 394, in main
    bot = InstaBot(**configdict)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 60, in __init__
    self.persistence = PersistenceManager(config.get("database"))
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\persistence\manager.py", line 10, in __new__
    from instabot_py.persistence.sql import Persistence
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\persistence\sql.py", line 3, in <module>
    from sqlalchemy import Column, Integer, String, DateTime
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 331, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

Keep getting this back as a traceback. Is there something I am missing?

**Comment by nickgryg** [comment]
Please try to use instabot with Python 3.6 or 3.7 for now. We'll see how to fix this issue for Python 3.8 some time later.

**Comment by nickgryg** [comment]
Duplicate to #2446
