### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ishandutta2007** [instabot-py/instabot.py#2463]
```
ishandutta2007@MacBook-Pro:~/Documents/Projects/instabot.py$ instabot-py --ignore-updates
2019-11-23 21:27:12,334 - youyou - Persistence - DEBUG - Init SQL Perisitence sqlite:///youyou.db
2019-11-23 21:27:12,368 - youyou - InstaBot - INFO - Instabot v0.5.9 started at 23.11.2019 21:27:
2019-11-23 21:27:12,368 - youyou - InstaBot - INFO - Found session file youyou.session
Traceback (most recent call last):
  File "/Users/ishandutta2007/.pyenv/versions/3.7.0/bin/instabot-py", line 11, in <module>
    load_entry_point('instabot-py==0.5.9', 'console_scripts', 'instabot-py')()
  File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/instabot_py/__main__.py", line 299, in main
    bot = InstaBot(config=config)
  File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/instabot_py/instabot.py", line 221, in __init__
    self.login()
  File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/instabot_py/instabot.py", line 427, in login
    self.csrftoken = re.search('(?<="csrf_token":")\w+', r.text).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
You have new mail in /var/mail/ishandutta2007

```

**Comment by meestaShin** [comment]
The developers have stopped working on this for a while now. It doesn't work. They announced it.

**Comment by nickgryg** [comment]
@ishandutta2007, it seems your session file is no longer acceptable. Please try to delete it and start bot again.

**Comment by martygriffin** [comment]
+1

**Comment by bartiiz** [comment]
same here

**Comment by Nadastique** [comment]
samehere

**Comment by bijanzd** [comment]
Same issue...

**Comment by nickgryg** [comment]
What's the bot version? What's the full error output after you deleted sessions file?

**Comment by ishandutta2007** [comment]
> 2019-11-23 21:27:12,368 - youyou - InstaBot - INFO - Instabot v0.5.9 started at 23.11.2019 21:27:

It says v0.5.9

**Comment by nickgryg** [comment]
Ah, yes, my bad. Please try to use the latest one: 0.5.19. Version 0.5.9 had a lot of bugs.

**Comment by ishandutta2007** [comment]
upgraded to 0.5.19, it worked fine until we restart and it tries with old session file.
Here is the error log:

> ishandutta2007@MacBook-Pro:~/Documents/Projects/instabot.py$ instabot-py --ignore-updates
> Using 'instabot.config.yml' as a configuration, add '-c your-config.yml' if you want to use your config file
> 2019-12-19 10:10:26,698 - ishandutta2007_insta - Persistence - DEBUG - Init SQL Perisitence sqlite:///ishandutta2007_insta.db
> 2019-12-19 10:10:26,741 - ishandutta2007_insta - InstaBot - INFO - Instabot v0.5.19 started at 19.12.2019 10:10:
> 2019-12-19 10:10:26,742 - ishandutta2007_insta - InstaBot - DEBUG - User agent 'Opera/9.80 (Windows NT 5.1; U; en) Presto/2.10.289 Version/12.01' is used
> 2019-12-19 10:10:26,743 - ishandutta2007_insta - InstaBot - INFO - Found session file ishandutta2007_insta.session
> 2019-12-19 10:10:43,223 - ishandutta2007_insta - InstaBot - INFO - ishandutta2007 has logged in successfully!
> 2019-12-19 10:10:43,223 - ishandutta2007_insta - InstaBot - INFO - Saving cookies to session file ishandutta2007_insta.session
> 2019-12-19 10:10:59,901 - ishandutta2007_insta - InstaBot - DEBUG - Getting media by tag: car
> 2019-12-19 10:11:09,023 - ishandutta2007_insta - InstaBot - DEBUG - Retrieved 64 medias
> 2019-12-19 10:11:09,138 - ishandutta2007_insta - InstaBot - DEBUG - Selected 9 medias to process. Increase max_like_for_one_tag value for more processing medias 
> 2019-12-19 10:11:13,700 - ishandutta2007_insta - InstaBot - DEBUG - Trying to like media #1: id: 2202096434157708935, url: https://www.instagram.com/p/B6PawonH-aH/
> 2019-12-19 10:11:13,700 - ishandutta2007_insta - InstaBot - DEBUG - Will not like this media: number of likes 1 does not meet media_min_like requirements
> 2019-12-19 10:11:19,151 - ishandutta2007_insta - InstaBot - DEBUG - Trying to follow user #1: id: 5765335419, username: mod016
> 2019-12-19 10:11:21,159 - ishandutta2007_insta - InstaBot - INFO - Followed user #1: username: mod016, url: https://www.instagram.com/mod016/
> 2019-12-19 10:11:22,659 - ishandutta2007_insta - InstaBot - DEBUG - Trying to unfollow user #1: olapankratova
> 2019-12-19 10:11:27,089 - ishandutta2007_insta - InstaBot - DEBUG - User olapankratova has: 500 followers, 373 followings, 277 medias
> 2019-12-19 10:11:27,089 - ishandutta2007_insta - InstaBot - DEBUG -     > Unfollowing olapankratova: the user is not following you
> 2019-12-19 10:11:28,678 - ishandutta2007_insta - InstaBot - INFO - Unfollowed user #1: username: olapankratova, url: https://www.instagram.com/olapankratova/
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/bin/instabot-py", line 11, in <module>
>     load_entry_point('instabot-py==0.5.19', 'console_scripts', 'instabot-py')()
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/instabot_py/__main__.py", line 359, in main
>     bot.mainloop()
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/instabot_py/instabot.py", line 821, in mainloop
>     self.new_auto_mod_comments(media)
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/instabot_py/instabot.py", line 1175, in new_auto_mod_comments
>     self.verify_media_before_comment(media):
>   File "/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/instabot_py/instabot.py", line 1227, in verify_media_before_comment
>     re.DOTALL).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'
>

**Comment by bijanzd** [comment]
Same issue after update !!!

**Comment by Nadastique** [comment]
Traceback (most recent call last):
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/__main__.py", line 363, in <module>
    main()
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/__main__.py", line 359, in main
    bot.mainloop()
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/instabot.py", line 821, in mainloop
    self.new_auto_mod_comments(media)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/instabot.py", line 1175, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/instabot.py", line 1227, in verify_media_before_comment
    re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by martygriffin** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/instabot_py/__main__.py", line 363, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/instabot_py/__main__.py", line 359, in main
    bot.mainloop()
  File "/usr/local/lib/python3.6/site-packages/instabot_py/instabot.py", line 815, in mainloop
    self.new_auto_mod_comments(media)
  File "/usr/local/lib/python3.6/site-packages/instabot_py/instabot.py", line 1169, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "/usr/local/lib/python3.6/site-packages/instabot_py/instabot.py", line 1221, in verify_media_before_comment
    re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by bijanzd** [comment]
Nice Update !!!

**Comment by nickgryg** [comment]
Please update instabot to the master branch version and try to use it:
```
python3 -m pip install git+https://github.com/instabot-py/instabot.py
```

**Comment by bijanzd** [comment]
@nickgryg New error after update !

Traceback (most recent call last):
  File "/usr/bin/instabot-py", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/instabot_py/__main__.py", line 359, in main
    bot.mainloop()
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 815, in mainloop
    self.new_auto_mod_comments(media)
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 1169, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 1222, in verify_media_before_comment
    all_data = json.loads(raw_data)["entry_data"]["PostPage"][0]
KeyError: 'entry_data'

**Comment by nickgryg** [comment]
We don't have this code in master branch.
Could you try to upgrade your instabot with this:
```
python3 -m pip install --no-cache-dir --upgrade git+https://github.com/instabot-py/instabot.py
```

**Comment by bijanzd** [comment]
@nickgryg Thank you bro ! work like charm ...

**Comment by xibix-fp** [comment]
Partial same problem here as well, even after upgrade to the latest version.

Installed version 0.5.19

`2019-12-21 02:24:45,912 - XXXXXXX - InstaBot - DEBUG - Login request succeeded
Traceback (most recent call last):
  File "C:\Python37\Scripts\instabot-py-script.py", line 11, in <module>
    load_entry_point('instabot-py==0.5.19', 'console_scripts', 'instabot-py')()
  File "C:\Python37\lib\site-packages\instabot_py\__main__.py", line 345, in main
    bot = InstaBot(config=config)
  File "C:\Python37\lib\site-packages\instabot_py\instabot.py", line 237, in __init__
    self.login()
  File "C:\Python37\lib\site-packages\instabot_py\instabot.py", line 449, in login
    self.user_id = self.get_user_id_by_username(self.user_login)
  File "C:\Python37\lib\site-packages\instabot_py\instabot.py", line 250, in get_user_id_by_username
    "window._sharedData = (.*?);</script>", info.text, re.DOTALL
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by martygriffin** [comment]
Using the code in the master branch, this is fixed! Bot no longer will crash.

**Comment by ishandutta2007** [comment]
@nickgryg My point is can we create a configuration to auto-recreate session file if it's failing, every time debugging a deleting session file doesn't seem to be a scalable solution. Let me know if something like that is already and I might have missed it.

**Comment by ishandutta2007** [comment]
> What's the bot version? What's the full error output after you deleted sessions file?

@nickgryg My point is can we create a configuration to auto-recreate new session file if it's failing, every time investigation and then deleting session file doesn't seem to be a scalable solution. Let me know if something like that is already and I might have missed it.

**Comment by nickgryg** [comment]
Version 0.5.20 was released yesterday. I refactored login function. Now if your session file is stale, it will be deleted automatically.
