### ISSUE TITLE
UnboundLocalError: local variable 'resp' referenced before assignment

### ISSUE THREAD

**Issue by yosmelvin** [instabot-py/instabot.py#2471]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
3.7.3
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
pip 19.3.1
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
0.5.14
```

#### How you use the instabot
- [*] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
    main()
  File "/var/www/instabot.py/instabot_py/__main__.py", line 314, in main
    bot.mainloop()
  File "/var/www/instabot.py/instabot_py/instabot.py", line 811, in mainloop
    self.new_auto_mod_comments(media)
  File "/var/www/instabot.py/instabot_py/instabot.py", line 1115, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "/var/www/instabot.py/instabot_py/instabot.py", line 1157, in verify_media_before_comment
    self.logger.warning(f"Could not comment media {media_code}, url: "
UnboundLocalError: local variable 'resp' referenced before assignment


===========================

status code: 400. Reason: {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_unfollow/", "status": "fail"}
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/www/instabot.py/instabot_py/__main__.py", line 318, in <module>
    main()
  File "/var/www/instabot.py/instabot_py/__main__.py", line 314, in main
    bot.mainloop()
  File "/var/www/instabot.py/instabot_py/instabot.py", line 803, in mainloop
    self.new_auto_mod_comments(media)
  File "/var/www/instabot.py/instabot_py/instabot.py", line 1156, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "/var/www/instabot.py/instabot_py/instabot.py", line 1212, in verify_media_before_comment
    re.DOTALL).group(1)


```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
accept_language: en-US,en;q=0.5
ban_sleep_time: 10800
comment_list:
- - this
  - the
  - your
- - photo
  - picture
  - pic
  - shot
  - snapshot
- - is
  - looks
  - feels
  - is really
- - great
  - super
  - good
  - very good
  - good
  - wow
  - WOW
  - cool
  - GREAT
  - magnificent
  - magical
  - very cool
  - stylish
  - beautiful
  - so beautiful
  - so stylish
  - so professional
  - lovely
  - so lovely
  - very lovely
  - glorious
  - so glorious
  - very glorious
  - adorable
  - excellent
  - amazing
- - .
  - ..
  - '...'
  - '!'
  - '!!'
  - '!!!'
comments_per_day: 31
comments_per_run: '{{comments_per_day}}'
config:
  file: config.yml
database:
  connection_string: sqlite:///{{database.path}}
  path: '{{login}}.db'
  type: sql
debug: 0
end_at_h: 23
end_at_m: 59
error_400_to_ban: 3
follow_attempts: 10
follow_per_day: 260
follow_per_run: '{{follow_per_day}}'
follow_time: 36000
follow_time_enabled: true
like_per_day: 709
like_per_run: '{{like_per_day}}'
list_of_ua:
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.6.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.7.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.5.01003)
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/5.0 (Windows NT 5.1; rv:13.0) Gecko/20100101 Firefox/13.0.1
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko/20100101 Firefox/11.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.0.3705)
- Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727;
  .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
- Opera/9.80 (Windows NT 5.1; U; en) Presto/2.10.289 Version/12.01
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)
- Mozilla/5.0 (Windows NT 5.1; rv:5.0.1) Gecko/20100101 Firefox/5.0.1
- Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/5.02
- Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.112
  Safari/535.1
- Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition
  [en]
log_mod: 0
logging:
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s - {{login}} - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
  loggers:
    InstaBot:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
    Persistence:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
  root:
    level: INFO
  version: 1
login: ******
max_like_for_one_tag: 36
media_max_like: 150
media_min_like: 10
password:****
proxies: {}
session_file: '{{login}}.session'
start_at_h: 0
start_at_m: 0
tag_blacklist: []
tag_list:
- acoustic
- riffwars
- guitarists
- talented
- acousticcover
- guitar
- musically
time_till_unlike: 259200
unfollow_break_max: 17
unfollow_break_min: 3
unfollow_everyone: false
unfollow_inactive: true
unfollow_not_following: true
unfollow_per_day: 247
unfollow_per_run: '{{unfollow_per_day}}'
unfollow_probably_fake: true
unfollow_recent_feed: false
unfollow_selebgram: false
unfollow_whitelist: []
unlike_per_day: 0
unlike_per_run: '{{unlike_per_day}}'
unwanted_username_list: []
user_blacklist: {}
user_max_follow: 0
user_min_follow: 0
window_check_every: 300

```

**Comment by nickgryg** [comment]
According to the error log you are blocked by Instagram. But I'm going to change code a little to properly handle such kind of errors.
