### ISSUE TITLE
Bot can't comment / verify media before comment

### ISSUE THREAD

**Issue by bartiiz** [instabot-py/instabot.py#2473]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

Local on Raspberry Pi Model 3B+ 
Variable IP-Adress

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.7.3

#### Pip Version?
pip 19.3.1 from /home/pi/.local/lib/python3.7/site-packages/pip (python 3.7)

#### Instabot Version?
Installed version 0.5.14

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

I have this problem even I use no emojis for comment, I can write comments in the App and in the web browser, so I'm not banned. My bot wrote 2 comments and then displays always this error, so I need to deactivate comment function if I want to use this bot.

```
2019-12-04 14:01:08,264 - REMOVED- InstaBot - DEBUG - Trying to like media: id: REMOVED, url: https://www.instagram.com/p/REMOVED/
2019-12-04 14:01:09,173 - REMOVED- InstaBot - INFO - Liked media #5: id: REMOVED, url: https://www.instagram.com/p/REMOVED/
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/__main__.py", line 318, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/__main__.py", line 314, in main
    bot.mainloop()
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 811, in mainloop
    self.new_auto_mod_comments(media)
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 1115, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 1171, in verify_media_before_comment
    re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```

#### Config

---
login : "REMOVED"
password : "REMOVED"
debug: 0
log_mod: 1
follow_time: 604800
like_per_day: 240
comments_per_day: 100
max_like_for_one_tag: 80
follow_per_day: 240
follow_time: 36000
unfollow_per_day: 240
unfollow_break_min: 15
unfollow_break_max: 30
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
tag_list: ["REMOVED", "REMOVED", "REMOVED", "REMOVED", "REMOVED", "REMOVED", "REMOVED"]
comment_list: [
        ["❤️", "💎"],
    ]
logging.handlers.telegram:
  level: INFO
  class: telegram_handler.TelegramHandler
  token: REMOVED
  chat_id: REMOVED
logging.loggers.InstaBot.handlers:
  - telegram
  - console

I have this problem even I use no emojis for comment, I can wirte comments manuel, so I'm not banned. My bot wrote 2 comments and than displays always this error, so I need to deaktivate comment function if I want to use my bot.

**Comment by nickgryg** [comment]
What's the bot version?

**Comment by nickgryg** [comment]
Please try to update instabot to the latest version and check if you still have this issue.

**Comment by nickgryg** [comment]
@bartiiz Please update instabot to the master branch version and try to use it:
```
python3 -m pip install git+https://github.com/instabot-py/instabot.py
```

**Comment by nickgryg** [comment]
Version 0.5.20 has been just released. This version should fix above issue.
