### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by bijanzd** [instabot-py/instabot.py#2488]
Traceback (most recent call last):
  File "/usr/bin/instabot-py", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/instabot_py/__main__.py", line 359, in main
    bot.mainloop()
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 815, in mainloop
    self.new_auto_mod_comments(media)
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 1169, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 1221, in verify_media_before_comment
    re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**whats this in new version and how fix that ?**

**Comment by Nadastique** [comment]
#2463

**Comment by nickgryg** [comment]
@Nadastique you mentioned another issue, not the same one

**Comment by bijanzd** [comment]
@Nadastique My issue is different bro  !
this error after upgrade to new version !

**Comment by nickgryg** [comment]
@bijanzd Please update instabot to the master branch version and try to use it:
```
python3 -m pip install git+https://github.com/instabot-py/instabot.py
```

**Comment by bijanzd** [comment]
**@nickgryg New error after update !**

Traceback (most recent call last):
  File "/usr/bin/instabot-py", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/instabot_py/__main__.py", line 359, in main
    bot.mainloop()
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 815, in mainloop
    self.new_auto_mod_comments(media)
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 1169, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 1222, in verify_media_before_comment
    all_data = json.loads(raw_data)["entry_data"]["PostPage"][0]
KeyError: 'entry_data'

**Comment by nickgryg** [comment]
We don't have this code in master branch.
Could you try to upgrade your instabot with this:
```
python3 -m pip install --no-cache-dir --upgrade git+https://github.com/instabot-py/instabot.py
```

**Comment by bijanzd** [comment]
@nickgryg Thank you bro ! work like charm ...

**Comment by bijanzd** [comment]
@nickgryg Thank you bro ! work like charm ...

**Comment by damagezwk** [comment]
Your solution did not work for me... 
python3 -m pip install --no-cache-dir --upgrade git+https://github.com/instabot-py/instabot.py
Successfully updated and still get same error.

**Comment by nickgryg** [comment]
So, please provide me a full error output.

**Comment by damagezwk** [comment]
I submitted a bug #2491

**Comment by nickgryg** [comment]
Why, if it is duplicate for this one?

**Comment by damagezwk** [comment]
The duplicate one was not up when I submitted.  I am sorry

**Comment by damagezwk** [comment]
> 
> 
> So, please provide me a full error output.

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Scripts\instabot-py-script.py", line 11, in <module>
    load_entry_point('instabot-py==0.5.19', 'console_scripts', 'instabot-py')()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instabot_py\__main__.py", line 345, in main
    bot = InstaBot(config=config)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instabot_py\instabot.py", line 237, in __init__
    self.login()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instabot_py\instabot.py", line 449, in login
    self.user_id = self.get_user_id_by_username(self.user_login)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instabot_py\instabot.py", line 249, in get_user_id_by_username
    re.search(
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by nickgryg** [comment]
And this log output is about another function: get_user_id_by_username, not a verify_media_before_comment, which is described in this issue.

**Comment by damagezwk** [comment]
> 
> 
> And this log output is about another function: get_user_id_by_username, not a verify_media_before_comment, which is described in this issue.

I am sorry I am new to this.  How do I fix?

**Comment by nickgryg** [comment]
Version 0.5.20 has been just released. This version should fix an issue with "get_user_id_by_username" function.
