### ISSUE TITLE
sqlalchemy.exc.IntegrityError

### ISSUE THREAD

**Issue by Nadastique** [instabot-py/instabot.py#2490]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```3.7
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```
Traceback (most recent call last):
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: medias.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/__main__.py", line 363, in <module>
    main()
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/__main__.py", line 359, in main
    bot.mainloop()
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/instabot.py", line 821, in mainloop
    self.new_auto_mod_comments(media)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/instabot.py", line 1185, in new_auto_mod_comments
    self.persistence.insert_media(media['node']['id'], 'Error')
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/instabot_py/persistence/sql.py", line 66, in insert_media
    self._session.commit()
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/junyu/anaconda3/envs/4duz/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: medias.id
[SQL: INSERT INTO medias (id, created, status, code) VALUES (?, ?, ?, ?)]
[parameters: ('2203299900299669659', '2019-12-20 22:14:27.710084', 'Error', None)]
(Background on this error at: http://sqlalche.me/e/gkpj)
#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by nickgryg** [comment]
This issue is very outdated. It should have been fixed many releases ago. Please update `instabot-py` to the latest version and check if this issue still exists.
