### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by nizarganteng** [instabot-py/instabot.py#2491]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [x] Windows 10
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
2019-12-21 21:47:20,671 - myinstagramusername - InstaBot - DEBUG - Will not like this media: number of likes 0 does not meet media_min_like requirements
Traceback (most recent call last):
  File "c:\users\nizar\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nizar\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\Scripts\instabot-py.exe\__main__.py", line 7, in <module>
  File "c:\users\nizar\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\__main__.py", line 359, in main
    bot.mainloop()
  File "c:\users\nizar\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 815, in mainloop
    self.new_auto_mod_comments(media)
  File "c:\users\nizar\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 1169, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "c:\users\nizar\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 1219, in verify_media_before_comment
    raw_data = re.search(
AttributeError: 'NoneType' object has no attribute 'group'
```

#### Config

```
---
login: "myusername"
password: "mypassword"

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"

tag_list: ["ceramah", "videoislam", "fotoislam", "ustadadihidayat", "ustadzadihidayat", "ustadabdulsomad", "ustadzabdulsomad", "ustadkhalid", "ustadkhalidbasalamah", "indonesia", "pemudahijrah", "hijrahfest"]
tag_blacklist: ["sex", "porno", "shop", "jual", "bokep", "porn", "telanjang"]

like_per_day: 0
max_like_for_one_tag: 50
media_min_like: 10
media_max_like: 5000
follow_per_day: 0

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 1000
comment_list: [
        ["Halo"],
        ["..", "...", "....", "....."],
        [",salam kenal ,boleh minta tolong? ,Tolong ==> FOLLOW : @ <== Akan Selalu memberikan : SHOLAWAT , INFORMASI ISLAM , CERAMAH ISLAM , KAJIAN ISLAM , ILMU AGAMA ISLAM"],
        ["..", "...", "....", "....."],
        ["*AUTO COMMENT"],
    ]


```

**Comment by nickgryg** [comment]
Duplicate to #2488
