### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by damagezwk** [instabot-py/instabot.py#2492]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
``` local machine

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
``` 3.8.1
Include here the response of 'python --version' or 'python3 --version'
```
3.8.1
#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```pip 19.2.3

#### Instabot Version?
```0.5.19
Include here the response of 'instabot-py --version'
```
0.5.19
#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

``` AttributeError: 'NoneType' object has no attribute 'group'
Include the contents of the error.log here (if applicable). < Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Scripts\instabot-py-script.py", line 11, in <module>
    load_entry_point('instabot-py==0.5.19', 'console_scripts', 'instabot-py')()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instabot_py\__main__.py", line 345, in main
    bot = InstaBot(config=config)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instabot_py\instabot.py", line 237, in __init__
    self.login()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instabot_py\instabot.py", line 449, in login
    self.user_id = self.get_user_id_by_username(self.user_login)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instabot_py\instabot.py", line 249, in get_user_id_by_username
    re.search(
AttributeError: 'NoneType' object has no attribute 'group'
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < ---
login: ""
password: ""

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["cute", "follow4follow", "f4f"]
tag_blacklist: ["sex", "porno"]

like_per_day: 196
max_like_for_one_tag: 36
media_min_like: 20
media_max_like: 200
like_followers_per_run: 0

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 156
follow_time: 259200
follow_attempts: 10
user_min_follow: 200
user_max_follow: 2200

unfollow_per_day: 199
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 0
comment_list: [
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ]


```

**Comment by danielpettifer** [comment]
I'm getting the same error as above. I also notice that I can't access the feeds for the logins i'm using @ instagram.com/my_user_login

Potentially instagram is down for personal feeds or my ip has been flagged for misuse

**Comment by nickgryg** [comment]
Version 0.5.20 has been just released. This version should fix above issue.
