### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KatzeMau** [instabot-py/instabot.py#2495]
2019-12-23 11:07:11,375 - 2706.ryuu - InstaBot - DEBUG - Trying to follow user #18: id: 23689364996, username: smuffisz
2019-12-23 11:07:20,091 - 2706.ryuu - InstaBot - DEBUG - Trying to follow user #18: id: 10185131135, username: sebnemstayle
2019-12-23 11:07:30,306 - 2706.ryuu - InstaBot - DEBUG - Getting media by tag: dog
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 294, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1822, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.7/http/client.py", line 447, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/__main__.py", line 359, in main
    bot.mainloop()
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 800, in mainloop
    medias = self.get_medias()
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 531, in get_medias
    medias_raw = self.get_media_id_by_tag(tag)
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 515, in get_media_id_by_tag
    r = self.s.get(url_tag)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
root@raspberrypi:/home/pi/Desktop# 
root@raspberrypi:/home/pi/Desktop#    
root@raspberrypi:/home/pi/Desktop# 
root@raspberrypi:/home/pi/Desktop# 
root@raspberrypi:/home/pi/Desktop#

**Comment by nickgryg** [comment]
This error is just about poor Internet connection. Please make sure your computer/mobile has stable Internet connection.

**Comment by dnsandmann** [comment]
Hey Guys, 
I'm having the same problem on a Raspberry Pi with ethernet connection. What could possibly disturbt the Pi's internet connection? I thought ethernet ist stable.
