### ISSUE TITLE
UnboundLocalError: local variable 'resp' referenced before assignment

### ISSUE THREAD

**Issue by nizarganteng** [instabot-py/instabot.py#2501]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Traceback (most recent call last):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x04AC14C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /p/B6oRib0Hnpa/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04AC14C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 1223, in verify_media_before_comment
    resp = self.s.get(url_check)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /p/B6oRib0Hnpa/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04AC14C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\Scripts\instabot-py-script.py", line 11, in <module>
    load_entry_point('instabot-py==0.5.20', 'console_scripts', 'instabot-py')()
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\__main__.py", line 359, in main
    bot.mainloop()
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 825, in mainloop
    self.new_auto_mod_comments(media)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 1187, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 1225, in verify_media_before_comment
    self.logger.warning(f"Could not comment media {media_code}, url: "
UnboundLocalError: local variable 'resp' referenced before assignment
```

#### Config

```
login: "myusername"
password: "mypassword"

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"

tag_list: ["ceramah", "videoislam", "fotoislam", "ustadadihidayat", "ustadzadihidayat", "ustadabdulsomad", "ustadzabdulsomad", "ustadkhalid", "ustadkhalidbasalamah", "indonesia", "pemudahijrah", "hijrahfest"]
tag_blacklist: ["sex", "porno", "shop", "jual", "bokep", "porn", "telanjang"]

like_per_day: 0
follow_per_day: 0
unfollow_per_run: 0

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 500
comment_list: [
        ["mytext"],
        ["..", "...", "....", "....."],
        ["my text"],
        ["..", "...", "....", "....."],
        ["*AUTO COMMENT"],
    ]
```

**Comment by nizarganteng** [comment]
That error because my instagram account get comment banned....

if you want ,please add text on thats error ,so everyone know he account get comment banned

**Comment by nickgryg** [comment]
Duplicate to #2471

**Comment by nizarganteng** [comment]
On this post i just telling you that error because the account getting comment banned ,and in other account i not get comment banned ,but get the same error...



Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 


#### Description of your issue

```
Traceback (most recent call last):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 752, in read_chunked
    self._update_chunk_length()
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 682, in _update_chunk_length
    line = self._fp.fp.readline()
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 560, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 781, in read_chunked
    self._original_response.close()
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 1223, in verify_media_before_comment
    resp = self.s.get(url_check)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 686, in send
    r.content
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\Scripts\instabot-py-script.py", line 11, in <module>
    load_entry_point('instabot-py==0.5.20', 'console_scripts', 'instabot-py')()
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\__main__.py", line 359, in main
    bot.mainloop()
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 825, in mainloop
    self.new_auto_mod_comments(media)
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 1187, in new_auto_mod_comments
    self.verify_media_before_comment(media):
  File "C:\Users\NIZaR\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 1225, in verify_media_before_comment
    self.logger.warning(f"Could not comment media {media_code}, url: "
UnboundLocalError: local variable 'resp' referenced before assignment
```

#### Config

```
login: "myusername"
password: "mypassword"

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"

tag_list: ["ceramah", "videoislam", "fotoislam", "ustadadihidayat", "ustadzadihidayat", "ustadabdulsomad", "ustadzabdulsomad", "ustadkhalid", "ustadkhalidbasalamah", "indonesia", "pemudahijrah", "hijrahfest"]
tag_blacklist: ["sex", "porno", "shop", "jual", "bokep", "porn", "telanjang"]
user_blacklist: {"username"}

like_per_day: 0
follow_per_day: 0
unfollow_per_run: 0

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 100
comment_list: [
        ["Halo"],
        ["..", "...", "....", "....."],
        ["my text"],
        ["..", "...", "....", "....."],
        ["*A,UT.O COMM.EN.T"],
    ]
```
