### ISSUE TITLE
verify_media_before_comment -> 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by TheGurus** [instabot-py/instabot.py#2511]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
It is running on my laptop with anaconda env and the instabot version is the one from the master branch of GitHub
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [x] Linux (Ubuntu 18.04 LTS)
- [ ] Android (include terminal)

```
Linux gurus-dev 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.5
```

#### Pip Version?
```
pip 19.3.1
```

#### Instabot Version?
```
Installed version 0.5.21, installed from master branch on GitHub
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
The bot is not able to comment:

Jan 06 09:52:58 gurus-dev instabot-py[21287]: Traceback (most recent call last):
Jan 06 09:52:58 gurus-dev instabot-py[21287]:   File "/home/gurus/projects/social/instagram/instabot.py/instabot_py/instabot.py", line 1240, in verify_media_before_comment
Jan 06 09:52:58 gurus-dev instabot-py[21287]:     resp.text, re.DOTALL).group(1)
Jan 06 09:52:58 gurus-dev instabot-py[21287]: AttributeError: 'NoneType' object has no attribute 'group'
```

#### Config

```
accept_language: en-US,en;q=0.5
ban_sleep_time: 10800
comment_list:
- - this
  - the
  - your
- - photo
  - picture
  - pic
  - shot
  - snapshot
- - is
  - looks
  - feels
  - is really
- - great
  - super
  - good
  - very good
  - good
  - wow
  - WOW
  - cool
  - GREAT
  - magnificent
  - magical
  - very cool
  - stylish
  - beautiful
  - so beautiful
  - so stylish
  - so professional
  - lovely
  - so lovely
  - very lovely
  - glorious
  - so glorious
  - very glorious
  - adorable
  - excellent
  - amazing
- - .
  - ..
  - '...'
  - '!'
  - '!!'
  - '!!!'
comments_per_day: 20
comments_per_run: '{{comments_per_day}}'
config:
  file: projects/social/instagram/pedro.config.yml
database:
  connection_string: sqlite:///{{database.path}}
  path: '{{login}}.db'
  type: sql
debug: 0
end_at_h: 21
end_at_m: 0
error_400_to_ban: 3
follow_attempts: 10
follow_per_day: 156
follow_per_run: 25
follow_time: 259200
follow_time_enabled: true
like_followers_per_run: 0
like_per_day: 296
like_per_run: 100
list_of_ua:
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.6.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.7.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.5.01003)
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/5.0 (Windows NT 5.1; rv:13.0) Gecko/20100101 Firefox/13.0.1
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko/20100101 Firefox/11.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.0.3705)
- Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727;
  .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
- Opera/9.80 (Windows NT 5.1; U; en) Presto/2.10.289 Version/12.01
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)
- Mozilla/5.0 (Windows NT 5.1; rv:5.0.1) Gecko/20100101 Firefox/5.0.1
- Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/5.02
- Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.112
  Safari/535.1
- Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition
  [en]
log_mod: 0
logging:
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s - {{login}} - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
  loggers:
    InstaBot:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
    Persistence:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
  root:
    level: INFO
  version: 1
max_like_for_one_tag: 25
media_max_like: 100
media_min_like: 3
proxies: {}
session_file: '{{login}}.session'
start_at_h: 7
start_at_m: 0
tag_blacklist: []
tag_list:
- datascience
- artificialintelligence
- machinelearning
time_till_unlike: 259200
unfollow_break_max: 20
unfollow_break_min: 5
unfollow_everyone: false
unfollow_inactive: true
unfollow_not_following: true
unfollow_per_day: 15
unfollow_per_run: '{{unfollow_per_day}}'
unfollow_probably_fake: true
unfollow_recent_feed: false
unfollow_selebgram: false
unfollow_whitelist: []
unlike_per_day: 0
unlike_per_run: 0
unwanted_username_list:
- free
- travel
- shop
- store
- sex
- online
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
user_blacklist: {}
user_max_follow: 2000
user_min_follow: 50
window_check_every: 300

```

**Comment by iamklaus** [comment]
+1

**Comment by nickgryg** [comment]
@TheGurus The fix for your bug was implemented two versions before. It seems like your code wasn't properly updated. I suggest you to delete `instabot-py` and install it again:
```
# python3 -m pip uninstall instabot-py
# python3 -m pip install instabot-py
```

**Comment by mrlzla** [comment]
Still error

**Comment by dirtyrick007** [comment]
File "c:\users\lenovo\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 1238, in verify_media_before_comment
    raw_data = re.search(
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dirtyrick007** [comment]
Still having this too.

**Comment by telemmaite** [comment]
same error.

**Comment by iEddy19** [comment]
same here

**Comment by nickgryg** [comment]
Instead of just writing "same here", please tell me what's version of `instabot-py` you use?

**Comment by iEddy19** [comment]
Hello. Sorry yes. I just downloaded the current version via python3 -m pip install instabot-py and python3 -m pip install git+https://github.com/instabot-py/instabot.py and got the same error for both cases. Version.txt is 1559201997.

Thank you

**Comment by nickgryg** [comment]
Please post your error output here.

**Comment by iEddy19** [comment]
Sure,
I get this error:
2020-02-12 19:19:43,170 - InstaBot - ERROR - 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 1257, in verify_media_before_comment
    resp.text, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by nickgryg** [comment]
Version 0.5.26 has been just released. Function verify_media_before_comment` was refactored in this release. @iEddy19 please upgrade `instabot-py` to version 0.5.26 and check if issue is still there.

**Comment by iEddy19** [comment]
Thank you very much. Seems like its now a different error. After I check IG I realized I got blocked for one week :/.
I got InstaBot - WARNING - Could not comment media  and then the whole print out of the <html>...</html>

**Comment by nickgryg** [comment]
What was the `status code:` in the error message?
