### ISSUE TITLE
get_media_id_by_tag   -  all_data = json.loads(r.text)

### ISSUE THREAD

**Issue by Mmalherbe** [instabot-py/instabot.py#2516]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI Buster ( latest version)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
Linux raspberrypi 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux

```
#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.9.0a1
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
pip 19.3.1 from /home/pi/.virtualenvs/instabot/lib/python3.9/site-packages/pip (python 3.9)
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'

(instabot) pi@raspberrypi:~ $ instabot-py --version
Installed version 0.5.21
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py ( Changed the default config with my credentials etc). 
- [ ] example.py (Deprecated, please install newer version) 
- [x] python instabot_py

#### Description of your issue

```
ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/instabot/lib/python3.9/site-packages/instabot_py/instabot.py", line 527, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "/usr/local/lib/python3.9/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

#### Config

```
Default config file, with only some tags added and my credentials.

```

**Comment by nickgryg** [comment]
The bot works fine on Python version 3.6 - 3.8. Version 3.9 hasn't been tested yet. So, as a temporary solution, just downgrade your Python version to 3.8 or 3.7.

**Comment by dankismylifestyle** [comment]
I have exactly the same problem on python 3.6. For me, the bot is trying every tag in my taglist but fails to get media every time. I guess its Insta blocking the bot from accessing the account but thats just a guess from someone who has no clue about how this bot works. Does anyone else has a solution?

**Comment by u0xpsec** [comment]
if IG keep blocking the bot, comment the user_agent flag on config file so the bot will pick one randomly from a list and remove session file. works for me every time. im working on a way to make the bot do that automatically.

**Comment by dankismylifestyle** [comment]
didnt change anything :(

**Comment by nickgryg** [comment]
Please upgrade instabot-py to version 0.5.22 and provide your config file to check if it's bug or just incorrect configuration.

**Comment by dankismylifestyle** [comment]
nvm got it working now. I dragged the bot over from my laptop to my pc via dropbox and that kinda messed things up, after reinstalling like 5 times it worked
