### ISSUE TITLE
instabot.py and Middle East character.

### ISSUE THREAD

**Issue by hack3rcon** [instabot-py/instabot.py#2521]
Hello Instabot-py Team,
I tried to use the Instabot-py with Middle East characters in the "tag_list" option, but I got below error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/instabot_py/instabot.py", line 527, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
Can  Instabot-py support UTF-8?

Thank you.

**Comment by hack3rcon** [comment]
Any idea?

**Comment by nickgryg** [comment]
Please fill issue template when you create issues. We cannot help you if we know nothing about your setup: instabot-py version, OS you use, configuration etc.
