### ISSUE TITLE
Error random.py... Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by xuser99** [instabot-py/instabot.py#2524]
The instabot don't work and give me this error:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/instabot-py", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/instabot_py/__main__.py", line 371, in main
    bot.mainloop()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/instabot_py/instabot.py", line 798, in mainloop
    medias = self.get_medias()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/instabot_py/instabot.py", line 540, in get_medias
    tag = random.choice(self.tag_list)
  File "/data/data/com.termux/files/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

**Comment by xuser99** [comment]
I use the instabot with termux on android,
I don't know the problem and i'm not very well with putho i'm used to use other languages, someone can help me?

**Comment by u0xpsec** [comment]
can you post your configuration file? make sure you remove username and password

**Comment by xuser99** [comment]
I don't know why but after 7 days the problem has disappeared, thank u same for the help, goodbye
