### ISSUE TITLE
bot crashing after having retrieved media

### ISSUE THREAD

**Issue by Pencilhead12** [instabot-py/instabot.py#2527]
Hi all,
I'm frustrated with this issue which I can't manage to get around. Every time I start up the bot, it doesn't get past the media retrieving stage; not once has it worked. Any ideas?

P.S. I have replaced my username with "username" for privacy reasons, and it's running on Mac.

..
..
..

instabot-py
Using 'instabot.config.yml' as a configuration, add '-c your-config.yml' if you want to use your config file
2020-01-29 22:55:12,483 - username - Persistence - DEBUG - Init SQL Perisitence sqlite:///username.db
2020-01-29 22:55:12,556 - username - InstaBot - INFO - Instabot v0.5.21 started at 29.01.2020 22:55:
2020-01-29 22:55:12,556 - username - InstaBot - DEBUG - User agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0' is used
2020-01-29 22:55:12,556 - username - InstaBot - INFO - Found session file username.session
2020-01-29 22:55:16,176 - username - InstaBot - INFO - username has logged in successfully!
2020-01-29 22:55:16,176 - username - InstaBot - INFO - Saving cookies to the session file username.session
2020-01-29 22:55:30,196 - username - InstaBot - DEBUG - Getting media by tag: blackandwhite
2020-01-29 22:55:32,232 - username - InstaBot - DEBUG - Retrieved 69 medias
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Library/Python/3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: medias.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.7/site-packages/instabot_py/__main__.py", line 371, in main
    bot.mainloop()
  File "/Library/Python/3.7/site-packages/instabot_py/instabot.py", line 798, in mainloop
    medias = self.get_medias()
  File "/Library/Python/3.7/site-packages/instabot_py/instabot.py", line 544, in get_medias
    medias = self.remove_already_liked_medias(medias_raw)[
  File "/Library/Python/3.7/site-packages/instabot_py/instabot.py", line 831, in remove_already_liked_medias
    return [media for media in medias if not
  File "/Library/Python/3.7/site-packages/instabot_py/instabot.py", line 833, in <listcomp>
    media_id=media['node']['id'])]
  File "/Library/Python/3.7/site-packages/instabot_py/persistence/sql.py", line 46, in check_already_liked
    .filter(Media.id == media_id) \
  File "/Library/Python/3.7/site-packages/sqlalchemy/orm/query.py", line 3294, in one_or_none
    ret = list(self)
  File "/Library/Python/3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/Library/Python/3.7/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Library/Python/3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/Library/Python/3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Library/Python/3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/Library/Python/3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/Library/Python/3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Library/Python/3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Library/Python/3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Library/Python/3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Library/Python/3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: medias.id
[SQL: SELECT medias.id AS medias_id, medias.created AS medias_created, medias.status AS medias_status, medias.code AS medias_code 
FROM medias 
WHERE medias.id = ?]
[parameters: ('2232031482226366608',)]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by NuniTelo** [comment]
hi, this looks like a problem with database. 
can you execute this in your database shell ?

SELECT medias.id AS medias_id, medias.created AS medias_created, medias.status AS medias_status, medias.code AS medias_code
FROM medias


check if it's returning something or not (Based on your error I doubt). So I think maybe the tables have not created on the database and the bot it's trying to access them.

**Comment by Pencilhead12** [comment]
Hi @NuniTelo thanks for the prompt reply. I'm not sure how to execute this in my database shell... I'm very new to programming, could you please run me through the procedure?
Thanks! ^_^

Also, do you recommend instabot.py? Have you had any issues with Instagram's bot detection? I'd personally rather stick to just liking and commenting, not following or unfollowing... how many likes and comments per day would you recommend I stick between?

**Comment by u0xpsec** [comment]
@Pencilhead12 just remove the DB and bot will create another on next run
