### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Jostino** [instabot-py/instabot.py#2529]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
RASPBERRY PI 3+
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Linux rasp2igbot 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.3.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
```

#### Instabot Version?
```
Installed version 0.5.21
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
2020-01-30 16:50:54,717 - xxxxxxxxx - InstaBot - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 527, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/__main__.py", line 371, in main
    bot.mainloop()
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 798, in mainloop
    medias = self.get_medias()
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 542, in get_medias
    self.logger.debug(f"Retrieved {len(medias_raw)} medias")
TypeError: object of type 'NoneType' has no len()

```

#### Config

```
debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["nature", "follow4follow", "f4f", "landscape", "firstpost"]
tag_blacklist: ["sex", "porno"]

like_per_day: 196
max_like_for_one_tag: 36
media_min_like: 20
media_max_like: 200
like_followers_per_run: 0

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 156
follow_time: 259200
follow_attempts: 10
user_min_follow: 200
user_max_follow: 2200

unfollow_per_day: 199
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 0
comment_list: [
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ]

```

**Comment by claude-eric-steiner** [comment]
same problem here.

On Windows Python 3.8.1
The bot works for some time, then trows this error after:
"DEBUG - Getting media by tag"

**Comment by Luismi74** [comment]
same problem here: 
`2020-02-06 16:32:44,732 - luisphotogram - InstaBot - DEBUG - Getting media by tag: #portraitfestival
2020-02-06 16:32:44,895 - luisphotogram - InstaBot - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\users\luis\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 527, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "c:\users\luis\appdata\local\programs\python\python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\users\luis\appdata\local\programs\python\python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\luis\appdata\local\programs\python\python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\users\luis\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\luis\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\luis\AppData\Local\Programs\Python\Python38-32\Scripts\instabot-py.exe\__main__.py", line 7, in <module>
  File "c:\users\luis\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\__main__.py", line 371, in main
    bot.mainloop()
  File "c:\users\luis\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 798, in mainloop
    medias = self.get_medias()
  File "c:\users\luis\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 542, in get_medias
    self.logger.debug(f"Retrieved {len(medias_raw)} medias")
TypeError: object of type 'NoneType' has no len()`

**Comment by claude-eric-steiner** [comment]
I figured out what causes this issue (at least in my case). 

It tries to lookup a nonexisting hashtag (had a tippo in the hashtag name).

Anyway, this kind of error should be excepted and handled accordingly, or at least given a correct error message...
