### ISSUE TITLE
new python error;

### ISSUE THREAD

**Issue by JesuTinto** [instabot-py/instabot.py#2530]
Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 11, in <module>
    load_entry_point('instabot-py===devel', 'console_scripts', 'instabot-py')()
  File "/usr/local/lib/python3.7/site-packages/instabot_py-devel-py3.7.egg/instabot_py/__main__.py", line 371, in main
    bot.mainloop()
  File "/usr/local/lib/python3.7/site-packages/instabot_py-devel-py3.7.egg/instabot_py/instabot.py", line 798, in mainloop
    medias = self.get_medias()
  File "/usr/local/lib/python3.7/site-packages/instabot_py-devel-py3.7.egg/instabot_py/instabot.py", line 543, in get_medias
    max_tag_like_count = random.randint(1, self.max_like_for_one_tag)
  File "/usr/local/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/local/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)

**Comment by u0xpsec** [comment]
Set the  like_per_run: 0 but leave the max_like_for_one_tag flag anything other than 0

**Comment by nickgryg** [comment]
Please fill issue template when you create issues. We cannot help you if we know nothing about your setup: instabot-py version, OS, configuration etc.
