### ISSUE TITLE
Error codes while launching

### ISSUE THREAD

**Issue by thehackedone** [instabot-py/instabot.py#2541]
I've been using this bot for quite awhile now no issues, suddenly I cannot login. I updated the bot and am getting the same issue seemingly.

Traceback (most recent call last):
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Soul\AppData\Local\Programs\Python\Python36-32\Scripts\instabot-py.exe\__main__.py", line 9, in <module>
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\site-packages\instabot_py\__main__.py", line 395, in main
    bot = InstaBot(**configdict)
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\site-packages\instabot_py\instabot.py", line 365, in __init__
    self.login()
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\site-packages\instabot_py\instabot.py", line 589, in login
    self.user_id = self.get_user_id_by_username(self.user_login)
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\site-packages\instabot_py\instabot.py", line 392, in get_user_id_by_username
    "window._sharedData = (.*?);</script>", info.text, re.DOTALL
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by nickgryg** [comment]
Above error output shows that you are running `instabot-py` not the latest version 0.5.23. Function `get_user_id_by_username` is on line [246](https://github.com/instabot-py/instabot.py/blob/master/instabot_py/instabot.py#L246.) now, not 392, like it is shown in error message.

The issue you have was fixed in previous releases.

Please update `instabot-py` to the latest version and provide an error log if it is still there.

**Comment by RomanKosyii** [comment]
@nickgryg after update im getting this error here
![image](https://user-images.githubusercontent.com/43781324/74340449-96ed3e00-4dae-11ea-95ba-7af018c2a86c.png)

**Comment by nickgryg** [comment]
@RomanKosyii your issue is duplicate to #2510 and it will be fixed soon.

**Comment by RomanKosyii** [comment]
@nickgryg okay, thanks, great

**Comment by thehackedone** [comment]
I just updated it, downloaded the latest build, when was it fixed?

**Comment by nickgryg** [comment]
This issue was fixed in version [0.5.20](https://github.com/instabot-py/instabot.py/commit/1e0d755b7f353680d25a535f1ce75369f99f6111) on December 24th in 2019 year.
