### ISSUE TITLE
Error with telegram conf : dictionary doesn't specify a version

### ISSUE THREAD

**Issue by rwanch** [instabot-py/instabot.py#2577]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ x] PI4
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Im hosting the script on a Pi4 under buster lite
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ x] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Linux xxxx 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
'python --version' -> Python 2.7.16
'python3 --version' -> Python 3.7.3
```

#### Pip Version?
```
'pip --version' -> pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)
'pip3 --version' -> pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```

#### Instabot Version?
```
Installed version 0.7.1
```

#### How you use the instabot
- [ x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
The instabotworks just fine so far, I am able to run it either way with a instabot-py -c my-configfile.yml  and a systemctl service.
The issue is I am trying to use a telegram bot to get the information from the current running process.
I have added  the following lines to my yml conf as described in the documentation, and other places on the net

logging.handlers.telegram:
  level: INFO
  formatter: telegram
  class: telegram_handler.TelegramHandler
  token: REPLACED
  chat_id: -REPLACED

logging.loggers.InstaBot.handlers:
  - telegram
  - console

And I am getting the following error

> pi@xxxx:~/bot $ instabot-py -c instabot.config.yml
> Traceback (most recent call last):
>   File "/home/pi/.local/bin/instabot-py", line 10, in <module>
>     sys.exit(main())
>   File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/__main__.py", line 313, in main
>     configure_logging(config)
>   File "/home/pi/.local/lib/python3.7/site-packages/instabot_py/__main__.py", line 263, in configure_logging
>     logging.config.dictConfig(config.get("logging"))
>   File "/usr/lib/python3.7/logging/config.py", line 799, in dictConfig
>     dictConfigClass(config).configure()
>   File "/usr/lib/python3.7/logging/config.py", line 495, in configure
>     raise ValueError("dictionary doesn't specify a version")
> ValueError: dictionary doesn't specify a version

```

#### Config

```
pi@xxxx:~/bot $ cat instabot.config.yml 
---
login: "REPLACED"
password: "REPLACED!"

debug: 1
logging.handlers.telegram:
  level: INFO
  formatter: telegram
  class: telegram_handler.TelegramHandler
  token: REPLACED
  chat_id: REPLACED

logging.loggers.InstaBot.handlers:
  - telegram
  - console

log_mod: 1
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"

tag_list: ["momentwide", "follow4follow", "f4f"]
tag_blacklist: ["sex", "porno"]

like_per_day: 196
max_like_for_one_tag: 15
media_min_like: 2
media_max_like: 200
like_followers_per_run: 30

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 20
follow_time: 259200
follow_attempts: 5
user_min_follow: 200
user_max_follow: 1500

unfollow_per_day: 1
unfollow_break_min: 15
unfollow_break_max: 50
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "shop", "store", "sex", "online"]
comments_per_day: 10
comment_list: [
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ]
```

**Comment by nickgryg** [comment]
Sorry, it's duplicate to #2346 

Cheers!
