### ISSUE TITLE
Problem since last update

### ISSUE THREAD

**Issue by TheNazareen** [instabot-py/instabot.py#2588]
hello since the last update, i have this message. i do not understand some things with this bots. but yesterday it was working pretty fine. could you please help me, i'm a Dev. beginner!!

Instabot V 7.6

Traceback (most recent call last):
File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
return run_code(code, main_globals, None,
File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "instabot_py_main.py", line 375, in
main()
File "instabot_py_main.py", line 371, in main
bot.mainloop()
File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 794, in mainloop
medias = self.get_medias()
File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 521, in get_medias
max_tag_like_count = random.randint(1, self.max_like_for_one_tag)
File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\random.py", line 248, in randint
return self.randrange(a, b+1)
File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\random.py", line 226, in randrange
raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1, 1, 0)

**Comment by lumiyo** [comment]
same here

**Comment by nickgryg** [comment]
Please fill issue template when you create issues. We cannot help you if we know nothing about your setup: instabot-py version, configuration etc.

**Comment by TheNazareen** [comment]
sorry @nickgryg  i have opened another issue with all the informations you need to help us !! thank you very much
