### ISSUE TITLE
issues since update 7.7 and 7.8

### ISSUE THREAD

**Issue by TheNazareen** [instabot-py/instabot.py#2592]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [X ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [X ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [ ] I am using Python 3.8 

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```instabot 7.8
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [X ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
C:\Users\shabi\Documents\instabot.py-master\instabot.py-master>py instabot_py
Using 'instabot.config.yml' as a configuration, add '-c your-config.yml' if you want to use your config file
2020-04-08 13:36:22,854 - XXXX- Persistence - DEBUG - Init SQL Perisitence sqlite:///uman_project.db
2020-04-08 13:36:22,885 - XXXX- InstaBot - INFO - Instabot v0.7.8 started at 2020-Apr-08 13:36:22
2020-04-08 13:36:22,885 - XXXX- InstaBot - DEBUG - User agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0' is used
2020-04-08 13:36:22,885 - XXXX- InstaBot - INFO - Found session file XXXXX.session
2020-04-08 13:36:24,853 - XXXX- InstaBot - INFO - XXXXXXXX has logged in successfully!
2020-04-08 13:36:24,853 - XXXXX- InstaBot - INFO - Saving cookies to the session file XXXXX.session
2020-04-08 13:36:40,434 - XXXXX- InstaBot - DEBUG - Getting media by tag: instagood
2020-04-08 13:36:42,508 - XXXXX- InstaBot - DEBUG - Retrieved 70 medias
Traceback (most recent call last):
  File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "instabot_py\__main__.py", line 375, in <module>
    main()
  File "instabot_py\__main__.py", line 371, in main
    bot.mainloop()
  File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 813, in mainloop
    medias = self.get_medias()
  File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot_py\instabot.py", line 540, in get_medias
    max_tag_like_count = random.randint(1, self.max_like_for_one_tag)
  File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "C:\Users\shabi\AppData\Local\Programs\Python\Python38-32\lib\random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1, 1, 0)
```

#### Config

```
---
login: "XXXXX"
password: "XXXXX"

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["spring", "follow4follow", "f4f", "montpellier", "followback", "backpack", "instagood", "backpackers", "nopainnogain"]
tag_blacklist: ["sex", "porno", "cute"]

like_per_day: 50
max_like_for_one_tag: 0
media_min_like: 20
media_max_like: 0
like_followers_per_run: 0

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 250
follow_time: 259200
follow_attempts: 10
user_min_follow: 100
user_max_follow: 0

unfollow_per_day: 200
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 50
comment_list: [
        ["your"],
        ["photo", "picture", "pic", "feed"],
        ["is", "looks", "is really"],
        [
            "great",
            "cool",
            "good",
            "very good"],
        [".", "..", "...", "!", "!!", "!!!"],
    ]


```
I everybody, first, all apologizes for the issue i opened yesterday. Here is my problem since the update to the 7.6 version.

Also, i really need more explonation about a personnal config that i could do! i use Brackets, could you tll me in wich directory i can modify options of the program ?

thank you for everything you do with this bot and for your fast answers!! you're really kind.

Thx

**Comment by nickgryg** [comment]
This issue isn't related to recent updates. I've just noticed that `max_like_for_one_tag: 0` is set in the configuration. That's why you are getting this error. Because you are literally saying to a bot: "Please choose 0 medias from medias you found and proceed with them".

What can I do here is to check if `max_like_for_one_tag: 0` is set in the configuration and report about this to a user.
