### ISSUE TITLE
Bot stops if post is deleted

### ISSUE THREAD

**Issue by DanielZanchi** [instabot-py/instabot.py#2610]
A lot of times it happens that the bot stops if the post is deleted and I get a message like this:

Could not like media: id: 2287031780472996098, url: https://www.instagram.com/p/B-9K0mBH0EC/, status code: 400. Reason: Sorry, this photo has been deleted

Is it possible to fix?

**Comment by nickgryg** [comment]
This issue has been fixed in version `0.7.17`

**Comment by DanielZanchi** [comment]
I think that it didn't get fixed completely. The bot stopped 4 times in 30 minutes with this log:

> 2020-04-15 10:27:26,183 - danielzanchi - InstaBot - DEBUG - Trying to like media #49: id: 2287732716675861961, url: https://www.instagram.com/p/B-_qMjugQ3J/
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 376, in <module>
>     main()
>   File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 372, in main
>     bot.mainloop()
>   File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 869, in mainloop
>     self.new_auto_mod_like(media)
>   File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 919, in new_auto_mod_like
>     if self.like(media_id, media_url):
>   File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 645, in like
>     and resp.text['feedback_title'] == 'Action Blocked':
> TypeError: string indices must be integers

**Comment by nickgryg** [comment]
Yes, previous attempt was not successful. This issue should be fixed in version `0.7.18`.
