### ISSUE TITLE
Errors after the first actions

### ISSUE THREAD

**Issue by Ndlx** [instabot-py/instabot.py#2612]
The Program Likes one media , follow one user, unfollow another and than this error pops, since 2 days 

```
Traceback (most recent call last):
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\-\AppData\Local\Programs\Python\Python38-32\Scripts\instabot-py.exe\__main__.py", line 7, in <module>
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\__main__.py", line 372, in main
    bot.mainloop()
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 866, in mainloop
    medias = self.get_medias()
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 543, in get_medias
    medias_raw = self.get_media_id_by_tag(tag)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 514, in get_media_id_by_tag
    r = self.s.get(url_tag)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\-\appdata\local\programs\python\python38-32\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None))

```

My configs

```
---
login: "x"
password: "x"

start_at_h: 0
start_at_m: 0
end_at_h: 23
end_at_m: 59
window_check_every: 30

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["intellectual", "inspire", "motivationalmonday", "inspireddaily", "belief", "strongmind", 
"successfulmindset", "instainspiration", "persistance", "inspiredby", "millionermindset", "successlover", "simplequotes", "inspiringquotes", 
"motivation",  "instaclothes", "hoodiedesign", "blackhoodie", 
"graphictees", "womensshopping", "lookstylish", "fashionspeaks", "iwillwearwhatilike",  
"trendylooks", "witchhat", "witch", "witchythings", "magick", "pagan", "pagansofinstagram", "witchy",  
"loveyourself", "selflove", "hiddenfeelings", "cryingquotes", "wearethechange", "wearethechangers", "womenrise", 
"kindnessisfree", "makingadifference", "forabetterfuture", "shippingworlwide",]
tag_blacklist: ["sex", "porno"]

like_per_day: 336
max_like_for_one_tag: 8
media_min_like: 20
media_max_like: 600
like_followers_per_run: 10

unlike_per_day: 0
time_till_unlike: 604800

follow_per_day: 200
follow_time: 604800
follow_attempts: 10
user_min_follow: 20
user_max_follow: 200

unfollow_per_day: 20
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["sex", "porno"]
comments_per_day: 0
comment_list: [
                [   "great",
            "super",
            "good",
            "wow",
            "WOW",
            "cool",
            "beautiful",
            "lovely",         
            "excellent",
            "amazing",
            "fire",
            "dope",           
            "nice"],
        ["!", "!!", "!!!"],
    ]


```

**Comment by midas2-0** [comment]
I have the same issues for line 193 and 86. Did you fix it? I have that but i don't know how to fix it.
![instabot2](https://user-images.githubusercontent.com/59845210/79316590-ce8a7a80-7f04-11ea-95ee-ccb09e0be331.JPG)

**Comment by Ndlx** [comment]
Haven't found a solution yet

**Comment by nickgryg** [comment]
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None))

This error means that you have issues with Internet connection from your PC/device to Instagram. It is unrelated to `instabot-py` library.
