### ISSUE TITLE
Trying to use comments gives: ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by sunderplugs11** [instabot-py/instabot.py#342]
ive tried to figure this out but im dumb

Traceback (most recent call last):
  File "C:\Users\sunde\Downloads\instabot.py-master\instabot.py-master\example.py", line 59, in <module>
    bot.new_auto_mod()
  File "C:\Users\sunde\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 525, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\sunde\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 578, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "C:\Users\sunde\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 614, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Simon856** [comment]
Try to set comments per day to 0 "comments_per_day=0," in example.py

**Comment by sunderplugs11** [comment]
You need comments for something like this to work tho

Solution:
https://github.com/LevPasha/instabot.py/issues/186

**Comment by fireuniversal** [comment]
Here's solution click this #438 and leave a like after it helps :)

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
