### ISSUE TITLE
Error Expecting value after some time

### ISSUE THREAD

**Issue by 9BadWolf9** [instabot-py/instabot.py#362]
After a while on mode 0 I get this error, way before the number of the likes/comments I specify. Is it something I do or is it an actual bug?
Traceback (most recent call last):
File "\instabot.py-master\example.py", line 58, in <module>
bot.new_auto_mod()
File "\instabot.py-master\src\instabot.py", line 525, in new_auto_mod
self.new_auto_mod_comments()
File "\instabot.py-master\src\instabot.py", line 578, in new_auto_mod_comments
and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
File "\instabot.py-master\src\instabot.py", line 614, in check_exisiting_comment
all_data = json.loads(check_comment.text)
File "AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
return _default_decoder.decode(s)
File "AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>>

**Comment by sochix** [comment]
Have the same problem. Seems like Instagram sending wrong JSON.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
