### ISSUE TITLE
UserInfo Error

### ISSUE THREAD

**Issue by Marcgh1** [instabot-py/instabot.py#378]
I am trying to get a list of all my followers using UserInfo() But i get this:
`>>> import sys,os
>>> sys.path.append(os.path.join(sys.path[0],'src'))
>>> from userinfo import UserInfo
>>> ui = UserInfo()
>>> ui.hello()
True
>>> ui.get_user_id_by_login('instabotfollowlike')
'4535095929'
>>> ui.get_followers()
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    ui.get_followers()
  File "src\userinfo.py", line 85, in get_followers
    if self.user_id:
AttributeError: 'UserInfo' object has no attribute 'user_id'`

Or : 
`ui.get_followers()
Traceback (most recent call last):
  File "<pyshell#45>", line 1, in <module>
    ui.get_followers()
  File "src\userinfo.py", line 89, in get_followers
    r = json.loads(followers.text)
  File "C:\Users\marc\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\marc\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\marc\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by kantona80** [comment]
same issue occurred to me

**Comment by sou1t** [comment]
Run command `pip3 install requests` if you use Python 3, or type `pip install requests` if you use Python 2.

**Comment by Marcgh1** [comment]
@sou1t  tried it still error uninstalled pip and then reinstalled it with pip3 still error, i am using pyhton 3.5. 
Is there any other way to get a list of all the followers ?

**Comment by rajasimon** [comment]
Why this closed ? No solution ?
