### ISSUE TITLE
User Blacklist Error

### ISSUE THREAD

**Issue by AceOfHobbes** [instabot-py/instabot.py#433]
The error below is ocurring on the blacklist

user_blacklist={'m.a_r._y':'','launputri11':'','knishele':'','michelmigdal':''},

Traceback (most recent call last):
  File "C:\Utilities\instabot\example.py", line 38, in <module>
    unfollow_whitelist=['example_user_1','example_user_2'])
  File "C:\Utilities\instabot\src\instabot.py", line 188, in __init__
    self.populate_user_blacklist()
  File "C:\Utilities\instabot\src\instabot.py", line 197, in populate_user_blacklist
    all_data = json.loads(info.text)
  File "C:\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lpdx** [comment]
I'm having this kind of issue when an user change its name or delete account.
If I search manually on instagram web site it returns:
![capturar](https://cloud.githubusercontent.com/assets/13546280/25755506/a2c9342e-3199-11e7-9d18-fd5ddfe4e8cc.PNG)

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
