### ISSUE TITLE
Error using new comment solution #438

### ISSUE THREAD

**Issue by virginsince1997** [instabot-py/instabot.py#439]
Got an error while using proposed fix #438 by @fireuniversal for jSon error while using comments
'''
line 21, in <module> return _default_decoder.decode(s) File "/usr/lib/python3.5/json/decoder.py", line 339, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from Nonejson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)>>> 
'''

**Comment by Plushkin** [comment]
I have this error: 
Traceback (most recent call last):
  File "/Users/Plushkin/Downloads/instabot.py-master/example.py", line 39, in <module>
    unfollow_whitelist=['example_user_1','example_user_2'])
  File "/Users/Plushkin/Downloads/instabot.py-master/src/instabot.py", line 186, in __init__
    self.write_log(log_string)
AttributeError: 'InstaBot' object has no attribute 'write_log'
>>>

**Comment by virginsince1997** [comment]
@fireuniversal i got this error too

I have this error:
Traceback (most recent call last):
File "/Users/Plushkin/Downloads/instabot.py-master/example.py", line 39, in
unfollow_whitelist=['example_user_1','example_user_2'])
File "/Users/Plushkin/Downloads/instabot.py-master/src/instabot.py", line 186, in init
self.write_log(log_string)
AttributeError: 'InstaBot' object has no attribute 'write_log'

**Comment by virginsince1997** [comment]
@fireuniversal
got this error too
I have this error:
Traceback (most recent call last):
File "/Users/Plushkin/Downloads/instabot.py-master/example.py", line 39, in
unfollow_whitelist=['example_user_1','example_user_2'])
File "/Users/Plushkin/Downloads/instabot.py-master/src/instabot.py", line 186, in init
self.write_log(log_string)
AttributeError: 'InstaBot' object has no attribute 'write_log'

**Comment by ChipWolf** [comment]
I assume someone forgot to remove or change references to an old function, remove the line `self.write_log(log_string)` from `instabot.py` on line `186` and try again.

**Comment by ChipWolf** [comment]
#438 needs to be made into a pull request along with a fix for `write_log` here

**Comment by Plushkin** [comment]
Another error when delete self.write_log(log_string):

Traceback (most recent call last):
  File "C:\Users\s22\Desktop\instabot.py-master\src\example.py", line 36, in <module>
    unfollow_whitelist=['example_user_1','example_user_2'])
  File "C:\Users\s22\Desktop\instabot.py-master\src\instabot.py", line 181, in __init__
    self.login()
  File "C:\Users\s22\Desktop\instabot.py-master\src\instabot.py", line 204, in login
    self.write_log(log_string)
AttributeError: 'InstaBot' object has no attribute 'write_log'

**Comment by Hostile** [comment]
Traceback (most recent call last):
  File "/home/xaos/instabot.py/example.py", line 60, in <module>
    bot.new_auto_mod()
  File "/home/xaos/instabot.py/src/instabot.py", line 527, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/xaos/instabot.py/src/instabot.py", line 580, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/xaos/instabot.py/src/instabot.py", line 616, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>>

**Comment by ChipWolf** [comment]
@Plushkin please read the error output
```
File "C:\Users\s22\Desktop\instabot.py-master\src\instabot.py", line 204, in login
self.write_log(log_string)
```
There's another `self.write_log` at line 204 in instabot.py; delete it, try again.

**Comment by ChipWolf** [comment]
@Hostile see #438

**Comment by Plushkin** [comment]
I merge it) now it's work without any error https://github.com/Plushkin/instabot.py/tree/Plushkin-No-JSON-object-could

**Comment by ChipWolf** [comment]
Pull the latest version from instabot-py/instabot.py and if the problem persists there; make a pull request on the main repo so everyone else can benefit from your changes. Thanks!

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
