### ISSUE TITLE
Instabot Unfollow Feature Broken

### ISSUE THREAD

**Issue by jessmike10011** [instabot-py/instabot.py#454]
Hello! 

I'm relatively new to python but have been coding as a hobby for the past 3 years. I have tried running mode 0 and 1 and the follow module works really well. In my bot I've defined the follow time for 12 hours. After this time elapses, the bot begins to unfollow users. It usually unfollows about 4-10 users before I get the following error:

'''

Traceback (most recent call last):
  File "/home/jessmike10011/instabot.py/example.py", line 110, in <module>
    unfollow_protocol(bot)
  File "/home/jessmike10011/instabot.py/src/unfollow_protocol.py", line 22, in unfollow_protocol
    self.current_user = self.media_on_feed[chooser]["node"]["owner"]["username"]
KeyError: 'owner'

'''

I'm interpreting that this error is caused by the bot trying to unfollow itself and therefor crashes because that action is impossible. Additionally, I have added my own account to the black_list and unfollow_whitelist. Still hasn't worked. 

I'm running this script in PythonAnywhere's cloud because it wouldn't work on my local PyCharm IDE. (PyCharm Issue: Requests could not be found even after I did 'pip install requests' in the command prompt.)

Any advice or suggestions to get the unfollow module working is greatly appreciated!

**Comment by ChipWolf** [comment]
Looks like they changed the JSON layout again

**Comment by ErikBoesen** [comment]
Would be very nice if this could get fixed.

**Comment by ChipWolf** [comment]
Someone add `print(self.media_on_feed[chooser])` and dump the output on gist for me to look at

**Comment by jessmike10011** [comment]
Hey @ChipWolf, I added print(self.media_on_feed) before line 22 in unfollow_protocol.py and the output is below. I've highlighted the account I'm using to test this bot, which does appear in the printout. Because I am using pythonanywhere, I am unable to copy the results to the clipboard.

It seems strange that in the past unfollow works a few times, then I get the error listed above. The only cause I can think of is the bot tries to unfollow itself and therefore breaks. Is this hypothesis correct? Would love to hear your train of thought. This is a great learning experience for me!



<img width="924" alt="print self" src="https://cloud.githubusercontent.com/assets/26857649/24761269/e2b45980-1ab8-11e7-8755-6b605a8e3549.PNG">

**Comment by ChipWolf** [comment]
Replace `unfollow_protocol.py` with this version: https://gist.github.com/ChipWolf/6e68b3ac0e708f9d86c90348c0017c5a
On a failure, it'll dump a bunch of stuff into the output, I need the entire scrollback.

**Comment by jessmike10011** [comment]
I migrated the scripts and am starting over on my mac OSX 10.12.3 (python 3.6.1). I modded in your new unfollow_protocol. Will report error back when it hits. I'm running in Mode 1 right now.

**Comment by jessmike10011** [comment]
@ChipWolf, this seems to be spitting the error back? The script ran as expected, but then about an hour later it stopped working and started giving me these 'except' messages. It is still spitting these messages out.

I'm assuming this output is caused by your 'unfollow_protocol' file where instead of stopping the loop it just continually spits out the exceptions where the script breaks. I'm going to end the program.

It unfollowed about 15 accounts and then hit this exception loop.
~~~~~
gemma_the_kitty : Get user info 
06.04.2017 17:21
Checking user info..
Follower : 1340
Following : 3556
Media : 67
   >>>This is probably Fake account
   >>>This user is passive
   >>>This account is NOT following you
   >>>You are following this account
======> Get media id by user: cats.lovers.club <======
Reject this account 
=================== 
Reason : 
   Is Selebgram : False 
   Is Fake Account : True 
   Is Active User : False 

Trying to unfollow: cats.lovers.club
Unfollow: cats.lovers.club #4.
gemma_the_kitty : Get media id on recent feed 
 06.04.2017 17:21
Media in recent feed = 24
gemma_the_kitty : Get user info 
06.04.2017 17:21
Checking user info..
Follower : 89
Following : 87
Media : 27
   >>>This is a normal account
   >>>This user is active
   >>>This account is following you
   >>>You are following this account
======> Get media id by user: catsbowieziggy <======
Get media by user success!
@@@@@@@@@@@@@@ This is your follower B****h!!! @@@@@@@@@@@@@
gemma_the_kitty : Get media id on recent feed 
 06.04.2017 17:21
Media in recent feed = 24
xxxxxxx user info list is empty!!! xxxxxxxxx
gemma_the_kitty : Get media id on recent feed 
 06.04.2017 17:21
Media in recent feed = 24
gemma_the_kitty : Get user info 
06.04.2017 17:21
Except on get_info!
======> Get media id by user: 1955352436 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:23
Except on get_info!
======> Get media id by user: 1955352436 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:25
Except on get_info!
======> Get media id by user: 1955352436 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:26
Except on get_info!
======> Get media id by user: 1955352436 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get media id on recent feed 
 06.04.2017 17:29
Media in recent feed = 24
gemma_the_kitty : Get user info 
06.04.2017 17:29
Except on get_info!
======> Get media id by user: 2976518138 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:30
Except on get_info!
======> Get media id by user: 2976518138 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:32
Except on get_info!
======> Get media id by user: 2976518138 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:34
Except on get_info!
======> Get media id by user: 2976518138 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get media id on recent feed 
 06.04.2017 17:36
Media in recent feed = 24
gemma_the_kitty : Get user info 
06.04.2017 17:36
Except on get_info!
======> Get media id by user: 3129122057 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:37
Except on get_info!
======> Get media id by user: 3129122057 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get media id on recent feed 
 06.04.2017 17:39
Media in recent feed = 24
gemma_the_kitty : Get user info 
06.04.2017 17:39
Except on get_info!
======> Get media id by user: 2648227462 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:41
Except on get_info!
======> Get media id by user: 2648227462 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:43
Except on get_info!
======> Get media id by user: 2648227462 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get media id on recent feed 
 06.04.2017 17:45
Media in recent feed = 24
gemma_the_kitty : Get user info 
06.04.2017 17:45
Except on get_info!
======> Get media id by user: 2331568212 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:47
Except on get_info!
======> Get media id by user: 2331568212 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:49
Except on get_info!
======> Get media id by user: 2331568212 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get media id on recent feed 
 06.04.2017 17:50
Media in recent feed = 24
gemma_the_kitty : Get user info 
06.04.2017 17:50
Except on get_info!
======> Get media id by user: 533971144 <======
XXXXXXX Except on get_media! XXXXXXX
gemma_the_kitty : Get user info 
06.04.2017 17:52
Except on get_info!
======> Get media id by user: 533971144 <======
XXXXXXX Except on get_media! XXXXXXX

**Comment by ChipWolf** [comment]
Ah yeah, looks like more than one problem.
That's going to need some local testing.

**Comment by olaims** [comment]
I'm still getting the error even with the "modified" unfollow_protocol.py (without getting any extended "log" :/ )

**Comment by ChipWolf** [comment]
@olaims the only purpose of that modified unfollow_protocol was to output more errors so the issue could be diagnosed

**Comment by olaims** [comment]
@ChipWolf that is what I mean, that I´m getting the same error as with the "normal" unfollow_protocol.py 

Here an example

**Comment by juliancnn** [comment]
Its a 404 error!,  tTemporary solution to avoid crash, add:

`       check_comment = self.s.get(url_check)
        if check_comment.status_code == 404
                return False
        all_data = json.loads(check_comment.text)`

If you want to debug and avoid crash of the application, it catch the exception the error and prints the page and redefine the function:

`    def check_exisiting_comment(self, media_code):
        url_check = self.url_media_detail % (media_code)
        check_comment = self.s.get(url_check)
        all_data = {}
        try:
            all_data = json.loads(check_comment.text)
        except json.decoder.JSONDecodeError as e :
            print('[!] Error while decoding response contents')
            print('[!] %s - %s' % (check_comment.status_code, check_comment.text))
            return False
        else
            if all_data['media']['owner']['id'] == self.user_id:
                self.write_log("Keep calm - It's your own media ;)")
                # Del media to don't loop on it
                del self.media_by_tag[0]
                return True
            comment_list = list(all_data['media']['comments']['nodes'])
            for d in comment_list:
                if d['user']['id'] == self.user_id:
                    self.write_log("Keep calm - Media already commented ;)")
                    # Del media to don't loop on it
                    del self.media_by_tag[0]
                    return True
            return False`

**Comment by DVassilev** [comment]
@chipwolf what can be done to get it to unfollow?

**Comment by ChipWolf** [comment]
@DVassilev see latest PR

**Comment by DVassilev** [comment]
@chipwolf #488?

**Comment by ske66** [comment]
Did anyone ever find a fix to this? I still get this issue, python 3.6.3 running on mac OSX with Sierra.

I'm still very new to python but I've been coding for a few years now. I'm noticing that the variable current_user and user_id have fixed values, I would have thought these changed depending on what was happening with the example.py. Seems to me like the unfollow section is always going to crash unless it takes in some form of static variable

**Comment by ErikBoesen** [comment]
This problem disappeared for me a while ago. I think it's just Instagram's throttling.

**Comment by ske66** [comment]
Think I see where the problem lies. I tried this out on a test account which had basically just been set up for the purpose of running the code. After switching it to my main account I no longer have any issues. Your Instagram account will need a bit of history, a few followers to begin with like friends or family plus some content that is currently on your feed, maybe 2 weeks worth. So the bot works fine as long as you aren't using a brand new account.

**Comment by brunooviedo** [comment]
I keep having problems

`'NoneType' object has no attribute '__getitem__'
{u'node': {u'gating_info': None, u'__typename': u'GraphImage', u'viewer_has_saved_to_collection': False, u'viewer_has_saved': False, u'owner': {u'username': u'restaurantetocadobode', u'requested_by_viewer': False, u'followed_by_viewer': True, u'has_blocked_viewer': False, u'profile_pic_url':`


someone had the same problem

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.

**Comment by gideon8011** [comment]
same issue here. I do think it has to do with running the script on 2 different pc's. 


error:

Traceback (most recent call last):
  File "xxxx.py", line 43, in <module>
    unfollow_whitelist=['', ''])
  File "/Users/xxxx/Documents/instagram/instagram/src/instabot.py", line 197, in __init__
    self.login()
  File "/Users/xxxx/Documents/instagram/instagram/src/instabot.py", line 266, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/xxxx/Documents/instagram/instagram/src/userinfo.py", line 45, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by JST51** [comment]
Same problem here. Not sure if this a version problem, I am using AWS and Ubuntu. I have tried running the script on the cloud and in my OSX and it doesn't work now. It had been working for a few days..

  File "example.py", line 52, in <module>
    unfollow_whitelist=[])
  File "/Users/Josete/Desktop/botinstabot/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/Josete/Desktop/botinstabot/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/Josete/Desktop/botinstabot/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
