### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Hostile** [instabot-py/instabot.py#460]
How to fix this? (using latest git clone)

Screenshoot https://gyazo.com/e946df1f3eb39e4c0127466f3a194e45

`Traceback (most recent call last):
  File "example.py", line 67, in <module>
    bot.new_auto_mod()
  File "/root/instabot.py/src/instabot.py", line 577, in new_auto_mod
    self.new_auto_mod_comments()
  File "/root/instabot.py/src/instabot.py", line 632, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/root/instabot.py/src/instabot.py", line 666, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Trying to unfollow: 4592359184
Unfollow: 4592359184 #15 of 15.
Pausing for 23 seconds... 15 of 15
Logout: likes - 45, follow - 15, unfollow - 15, comments - 14.
Bot work time: 1:10:17.788240
Logout success!
Exception KeyError: KeyError(139889955817216,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored`

**Comment by polaroi8d** [comment]
What python version do you use? You tried it on Windows?

**Comment by ChipWolf** [comment]
See #373

**Comment by Hostile** [comment]
it works for few hours then stops with above error

**Comment by Hostile** [comment]
i use linux

**Comment by ChipWolf** [comment]
Once again, see #373
