### ISSUE TITLE
KeyError: 'owner'

### ISSUE THREAD

**Issue by olaims** [instabot-py/instabot.py#466]
I have few accounts running and one of them is getting following error after 10/20 likes,

Media in recent feed = 25
Traceback (most recent call last):
  File "xxxxxxxxxxxxxxxxx/instabot.py-master/xxxxxxxx.py", line 67, in <module>
    bot.new_auto_mod()
  File "xxxxxxxxxxxxxxxxxinstabot.py-master/src/instabot.py", line 575, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "xxxxxxxxxxxxxxxxx/instabot.py-master/src/instabot.py", line 622, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "xxxxxxxxxxxxxxxxx/instabot.py-master/src/instabot.py", line 691, in auto_unfollow
    current_id = self.media_on_feed[chooser]['node']["owner"]["id"]
KeyError: 'owner'
>>>

**Comment by ChipWolf** [comment]
#454 search before opening a new issue :man_facepalming:
