### ISSUE TITLE
Unfollow bug

### ISSUE THREAD

**Issue by juliancnn** [instabot-py/instabot.py#469]
An uncaught exception appeared
is not the first time, sometimes works a few minutes and sometimes hours

```
Trying to unfollow: 3001566157
Traceback (most recent call last):
  File "/home/user2/PycharmProjects/instaBotServer/instabot.py/example.py", line 61, in <module>
    bot.new_auto_mod()
  File "/home/user2/PycharmProjects/instaBotServer/instabot.py/src/instabot.py", line 577, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/user2/PycharmProjects/instaBotServer/instabot.py/src/instabot.py", line 632, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/user2/PycharmProjects/instaBotServer/instabot.py/src/instabot.py", line 666, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Unfollow: 3001566157 #32 of 35.
Pausing for 25 seconds... 32 of 35
Trying to unfollow: 2977543544
Unfollow: 2977543544 #33 of 35.
Pausing for 22 seconds... 33 of 35
Logout: likes - 35, follow - 35, unfollow - 33, comments - 23.
Bot work time: 0:57:22.664629
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/user2/PycharmProjects/instaBotServer/instabot.py/src/instabot.py", line 300, in cleanup
    exit(0)
  File "/usr/lib/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Logout success!

Process finished with exit code 1

```

Does this occur because Julian is check_comment.text?

**Comment by ChipWolf** [comment]
#454
