### ISSUE TITLE
No Json object could be decoded

### ISSUE THREAD

**Issue by sushank1** [instabot-py/instabot.py#471]
Traceback (most recent call last):
  File "/home/sushank1/instabot.py/example.py", line 59,
 in <module>
    bot.new_auto_mod()
  File "/home/sushank1/instabot.py/src/instabot.py", lin
e 577, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/sushank1/instabot.py/src/instabot.py", lin
e 632, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0
]['code']) == False:
  File "/home/sushank1/instabot.py/src/instabot.py", lin
e 666, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, 
in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, i
n decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, i
n raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ChipWolf** [comment]
#460
