### ISSUE TITLE
Missing instabot and request

### ISSUE THREAD

**Issue by doctordeep** [instabot-py/instabot.py#474]
Hi I've tryed to run it in a linux mint with python 2.7.1 installed and I've this message:

```
oem@mint-PC ~/Documenti/instabot.py $ python example.py
 Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
  File "/home/oem/Documenti/instabot.py/src/instabot.py", line 14, in <module>
    import requests
ImportError: No module named requests
```

Someone know why?

Thanks for the attencion.

**Comment by samuelhopkins** [comment]
Try 'pip install requests' in your command prompt

**Comment by doctordeep** [comment]
thanks a lot
