### ISSUE TITLE
ImportError: No module named 'requests'

### ISSUE THREAD

**Issue by lemonetweb** [instabot-py/instabot.py#485]
Hi,

When I run python I find the following error:

```
root@ubuntu-4gb-lon1-01-XXXX:/var/www/html/XXXXXX/instagram# python3 example.py 
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
  File "/var/www/html/XXXXXXXXXX/instagram/src/instabot.py", line 15, in <module>
    import requests
ImportError: No module named 'requests'
```

Thank you very much for the help =)

**Comment by dcanones** [comment]
You need to install the requests library (pip install requests). It is a dependency of this bot.

**Comment by doomwalker328** [comment]
Hey, got the same error:

`Traceback (most recent call last):
  File "/Volumes/XXXX/instabot.py-master/example.py", line 12, in <module>
    from instabot import InstaBot
  File "/Volumes/XXXX/instabot.py-master/src/instabot.py", line 15, in <module>
    import requests
ImportError: No module named 'requests'`


I already installed the requests library via terminal:
`Collecting requests==2.12.4 (from -r requirements.txt (line 1))
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB)
    100% |████████████████████████████████| 583kB 1.5MB/s 
Installing collected packages: requests
Successfully installed requests-2.12.4`

**Comment by dcanones** [comment]
It looks that something is wrong with something related with your python environments. My suggestion is (this is what I do):

1. Install Anaconda (has a very powerful environment manager).
2. Create an environment (instabot_env or whatever you want as name).
3. Install requirements, particularly requests (importing the requirements.txt or one by one using Anaconda Navigator Interface).
4. Run the bot using that environment python with requests installed.
