### ISSUE TITLE
Why I can't make bot to follow only?

### ISSUE THREAD

**Issue by artemdumanov** [instabot-py/instabot.py#486]
Why I can't make bot ot follow only? 

Log:
```
Process Process-1:
Traceback (most recent call last):
  File "/opt/python/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/python/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/instafy_py/src/bot/controller.py", line 80, in create_bot
    bot.new_auto_mod()
  File "/usr/instafy_py/instabot/src/instabot.py", line 573, in new_auto_mod
    1, self.max_like_for_one_tag)
  File "/opt/python/lib/python3.5/random.py", line 218, in randint
    return self.randrange(a, b+1)
  File "/opt/python/lib/python3.5/random.py", line 196, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)
```

Parameters:
```
{
 "username": "secreeet",
 "follow_time": 0,
 "like_per_day": 0,
 "media_max_like": 0, 
 "comments_per_day": 0,
 "comment_list": [], 
 "mode": 0, 
 "password": "secreeeeet",
 "media_min_like": 0, 
 "user_blacklist": {}, 
 "max_like_for_one_tag": 0, 
 "tag_list": ["kiev", "kiyv"], 
 "follow_per_day": 720, 
 "unfollow_per_day": 0, 
 "tag_blacklist": []
}
```

**Comment by artemdumanov** [comment]
I found solution. For follow only use mod 5.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
