### ISSUE TITLE
Instabot module problem cannot import 

### ISSUE THREAD

**Issue by nikolay167** [instabot-py/instabot.py#497]
Hello i have a mac el capitan currently im facing a problem with installing and launching Instabot 
I did install dependencies.
but after trying to launch example.py it shows me an error 
admins-MacBook-Pro:~ admin$ /Users/admin/Desktop/instabot.py-master/example.py 
Traceback (most recent call last):
  File "/Users/admin/Desktop/instabot.py-master/example.py", line 12, in <module>
    from instabot import instabot
ImportError: cannot import name 'instabot'
admins-MacBook-Pro:~ admin$ /Users/admin/Desktop/instabot.py-master/src/instabot.py 
admins-MacBook-Pro:~ admin$ /Users/admin/Desktop/instabot.py-master/example.py 
Traceback (most recent call last):
  File "/Users/admin/Desktop/instabot.py-master/example.py", line 12, in <module>
    from instabot import instabot
ImportError: cannot import name 'instabot'

Thanks for your help

**Comment by nikolay167** [comment]
let me try this first if it will not work i need help:) https://github.com/instabot-py/instabot.py/issues/452

**Comment by nikolay167** [comment]
oh no dont really understand okey ive openned the way to example.py with ls
but its stil lshows same error(

**Comment by artemdumanov** [comment]
Did you find solution?

**Comment by nikolay167** [comment]
unfortunately not:(still it cannot find this module even if you will open with ls command

**Comment by nikolay167** [comment]
i have all dependencies needed tto be install such as requests.Maybe the reason because i have Jupiter notepad? i dont know (What kind of information do you need to check my problem?

**Comment by varishero** [comment]
To install the project's dependencies, run command pip install -r requirements.txt (specify pip2 or pip3 if you have multiple versions of Python installed)

**Comment by Bornagainfatkid** [comment]
I've tried to install requests every way possible. I've googled and read all possible links haha. I can not get this to run. I consistently just get. 

Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
  File "/Users/HomeBase/Documents/Projects/projectfolder/instabot.py-master/src/instabot.py", line 16, in <module>
    import requests
ImportError: No module named requests﻿

I've already installed this:
-MacBook-Pro:instabot.py-master HomeBase$ pip install -r requirements.txt
Requirement already satisfied: requests==2.12.4 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
-MacBook-Pro:instabot.py-master HomeBase$ python example.py
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot﻿

**Comment by artemdumanov** [comment]
@Bornagainfatkid try termainal command:
`pip3 install requests`

**Comment by Bornagainfatkid** [comment]
I've tried everything possible i feel haha. pip-pip3, nothing seems to work. I installed requests module on it's own even.

**Comment by mako-man** [comment]
the problem is u may previous install Install InstaBot using pip 
just uninstall using 
`pip uninstall InstaBot`

**Comment by ChipWolf** [comment]
virtualenv solves all of these issues

**Comment by wowissue** [comment]
having the same problem as spoke of. however, I have had instabot for 4 months working normally. This is now a thing as of 2 days now. In other words, something has gone wrong and it might be an update coming out.

**Comment by channelblackri** [comment]
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['ninilauri'])
  File "/Users/Maverix/Desktop/Bot2/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/Maverix/Desktop/Bot2/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/Maverix/Desktop/Bot2/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
Georges-Air:instabot.py-master Maverix$ 

This is my error log...
What does it mean?

Thank you very much for your efforts!

**Comment by channelblackri** [comment]
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/Maverix/Desktop/Bot/instabot.py-master/src/instabot.py", line 227, in __init__
    self.login()
  File "/Users/Maverix/Desktop/Bot/instabot.py-master/src/instabot.py", line 296, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/Maverix/Desktop/Bot/instabot.py-master/src/userinfo.py", line 45, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'


This is my error log...
What does it want? It run pretty good the days before, it have gotten this problem so suddenly.
Thanks for every helpful answer in advance.. this bot is really important for my business.. maybe for others as well. 

chbri

**Comment by yli30** [comment]
this is what I did and solved it for now:
1) find your fake_useragent directory. Mine is in ../python3.7/site-packages (0.1.11)you
2) copy it to your project folder, and it works
