### ISSUE TITLE
Bot loses track of people to unfollow

### ISSUE THREAD

**Issue by Ere-Eye** [instabot-py/instabot.py#514]
Hi, I've been trying to use the bot for a few days now, mostly trying to test if does what it's supposed to.

I'm not sure if I'm using it correctly either, I find the documentation isn't very clear in everything.

I interrupt with Ctrl+C and get the following

```
Trying to like media: 1502852608552170001
Liked: 1502852608552170001. Like #506.
^CTraceback (most recent call last):
  File "example.py", line 231, in <module>
    bot.new_auto_mod()
  File "/home/eray/instabot.py-master/src/instabot.py", line 566, in new_auto_mod
    time.sleep(3)
KeyboardInterrupt
Trying to unfollow: 2266447768
Unfollow: 2266447768 #152 of 207.
Pausing for 22 seconds... 152 of 207
Trying to unfollow: 4872130711
Unfollow: 4872130711 #153 of 207.
Pausing for 15 seconds... 153 of 207
Trying to unfollow: 1554992750
Unfollow: 1554992750 #154 of 207.
Pausing for 26 seconds... 154 of 207
Trying to unfollow: 672833902
Unfollow: 672833902 #155 of 207.
Pausing for 17 seconds... 155 of 207
Trying to unfollow: 1729561172
Unfollow: 1729561172 #156 of 207.
Pausing for 18 seconds... 156 of 207
Trying to unfollow: 4513594479
Unfollow: 4513594479 #157 of 207.
Pausing for 25 seconds... 157 of 207
Trying to unfollow: 1399704003
Unfollow: 1399704003 #158 of 207.
Pausing for 29 seconds... 158 of 207
Logout: likes - 506, follow - 207, unfollow - 158, comments - 0.
Bot work time: 16:39:11.241928
Logout success!
Exception KeyError: KeyError(140310321923840,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```
As you can see the I set the follow time to an hour. Out of 207 follows, it merely unfollowed 7 of them. Not 158. Some or most of them might have come from while running the bot however, I can see there are many accounts that were followed when I just started running the bot at the beginning of this session and they're still there.

```
bot = InstaBot(
    login="***",
    password="***",
    like_per_day=999,
    media_max_like=50,
    media_min_like=5,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
```

**Comment by ChipWolf** [comment]
#386 aims to remedy this issue.
