### ISSUE TITLE
error when comments are on

### ISSUE THREAD

**Issue by drovid** [instabot-py/instabot.py#516]
running time undetermined, gives off this code

Traceback (most recent call last): 
File "/home/pi/Desktop/Instagram Bot/----------/lenardograu.py", line 68, in <module> bot.newauto_mod() 
File "/home/pi/Desktop/Instagram Bot/----------/src/instabot.py", line 570, in new_auto_mod self.new_auto_mod_comments() 
File "/home/pi/Desktop/Instagram Bot/----------/src/instabot.py", line 625, in new_auto_mod_comments and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False: 
File "/home/pi/Desktop/Instagram Bot/----------/src/instabot.py", line 652, in check_exisiting_comment all_data = json.loads(check_comment.text) 
File "/usr/lib/python3.4/json/init_.py", line 318, in loads return _default_decoder.decode(s) 
File "/usr/lib/python3.4/json/decoder.py", line 343, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode raise ValueError(errmsg("Expecting value", s, err.value)) from None ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by luisramirez-m** [comment]
Read this: https://github.com/instabot-py/instabot.py/issues/489#issuecomment-296396541 maybe this your solution.

**Comment by drovid** [comment]
That issue was opened by me haha. Different filing, I'm using Artem'a update.

**Comment by mactrash** [comment]
Yes, noway to start up when turn on comment.

**Comment by aparcedo** [comment]
Solved. Update the files...

**Comment by kirigayaKazuto727** [comment]
I have re-download the file, but the problem still like that

**Comment by kirigayaKazuto727** [comment]
I have re-download this file, but the problem has not solved in me.. Please help !

**Comment by aparcedo** [comment]
What file did you update?

**Comment by kirigayaKazuto727** [comment]
I download it all.. but the error is still the same. how to solved it?

**Comment by ChipWolf** [comment]
Fixed
