### ISSUE TITLE
Getting a new error in latest version

### ISSUE THREAD

**Issue by Spshulem** [instabot-py/instabot.py#522]
When I run the script in the latest version I'm getting:

```
Trying to like media: 1504765785502671677
Liked: 1504765785502671677. Like #1.
Trying to follow: 2964162433
Followed: 2964162433 #1.
Traceback (most recent call last):
  File "example.py", line 67, in <module>
    bot.new_auto_mod()
  File "/Users/spencer/Downloads/instabot.py-master 3/src/instabot.py", line 564, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/spencer/Downloads/instabot.py-master 3/src/instabot.py", line 619, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/Users/spencer/Downloads/instabot.py-master 3/src/instabot.py", line 654, in check_exisiting_comment
    if all_data['media']['owner']['id'] == self.user_id:
KeyError: 'media'
Trying to unfollow: 2964162433
Unfollow: 2964162433 #1 of 1.
Pausing for 27 seconds... 1 of 1
Logout: likes - 1, follow - 1, unfollow - 1, comments - 0.
Bot work time: 0:00:36.966008
Logout success!
Exception KeyError: KeyError(4343608256,) in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored

```
and then it stops.

**Comment by raymondma1** [comment]
looks like comments is broken

**Comment by Spshulem** [comment]
@raymondma1 Thank you for the reply! Is there anything I can do in the mean time to fix this until it's pushed?

**Comment by raymondma1** [comment]
@Spshulem set comments to 0 or pull the branches with the fix.

**Comment by Josh452** [comment]
This is happening to me too. You could just use an older version of the code

**Comment by aparcedo** [comment]
Please update the files

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
