### ISSUE TITLE
keyerror: 'owner' 

### ISSUE THREAD

**Issue by james9120** [instabot-py/instabot.py#545]
After running mode 0 for a little while, get this error:

Traceback (most recent call last):
  File "/home/pi/instabot.py/example.py", line 67, in <module>
    bot.new_auto_mod()
  File "/home/pi/instabot.py/src/instabot.py", line 580, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/home/pi/instabot.py/src/instabot.py", line 627, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "/home/pi/instabot.py/src/instabot.py", line 687, in auto_unfollow
    current_id = self.media_on_feed[chooser]['node']["owner"]["id"]
KeyError: 'owner'

After some testing, this seems to be related to the unfollowing feature. I disabled unfollowing and it didn't crash over night.

**Comment by ChipWolf** [comment]
We're aware, there's lots of other issues with exactly the same issue. Please read the existing issues before posting a new one.
