### ISSUE TITLE
ERROR "No JSON object could be decoded"

### ISSUE THREAD

**Issue by Xenud** [instabot-py/instabot.py#547]
I got this error:

Traceback (most recent call last):
  File "example.py", line 59, in <module>
    bot.new_auto_mod()
  File "/home/instabot.py-master/src/instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/instabot.py-master/src/instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/instabot.py-master/src/instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**what it means? And why the bot stops?**

**Comment by ciripp** [comment]
I get the same error. Yesterday i get that error after 5 hours, today after an hour. (in both cases the script stopped and needed to restart the script). Does someone know how can it be fixed?

**Comment by Bigemm** [comment]
@Xenud and @ciripp  I had the same error and this suggestion was made to me which worked:

where it asks to put number of comments per day put = 0
 Basically stop the comment function. 
This worked for me - there seems to be a bug with the commenting aspect of this bot. The bot is trying to decode something but there is nothing to decode in the script causing it to stop working after a while.

**Comment by ChipWolf** [comment]
We're aware, there's lots of other issues with exactly the same issue. Please read the existing issues before posting a new one.

**Comment by AdrianaVecc** [comment]
@ChipWolf Could you link to the main issue where the conversation is happening instead? I have been through 50 of those issues, but it's not really helpful to close without redirecting.
