### ISSUE TITLE
raise ValueError(errmsg("Expecting value", s, err.value)) from None

### ISSUE THREAD

**Issue by kirigayaKazuto727** [instabot-py/instabot.py#552]
Thank for Instabot !
I only turn on the bot for 1 hour, so I the script like below:
 like_per_day=100000,
    comments_per_day=100000,
    tag_list=['bali',],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,

but, in the middle, I got the error like this :

Trying to comment: 1516438659036063594
Trying to like media: 1516438659036063594
Liked: 1516438659036063594. Like #354.
Trying to comment: 1516438648147460874
Trying to like media: 1516438648147460874
Liked: 1516438648147460874. Like #355.
Traceback (most recent call last):
  File "C:\Users\Unknown\Downloads\instabot.py-master\example.py", line 67, in <module>
    bot.new_auto_mod()
  File "C:\Users\Unknown\Downloads\instabot.py-master\src\instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\Unknown\Downloads\instabot.py-master\src\instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "C:\Users\Unknown\Downloads\instabot.py-master\src\instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

Could you tell me how to fix it, please? Thank you very much before

**Comment by abendplays** [comment]
Did you find any solution for this problem? Having the same trouble :/...

**Comment by ChipWolf** [comment]
We're aware, there's about 100 other issues with exactly the same issue. Please read the existing issues before posting a new one.

**Comment by AdrianaVecc** [comment]
@ChipWolf Could you link to the main issue where the conversation is happening instead? I have been through 50 of those issues, but it's not really helpful to close without redirecting.
