### ISSUE TITLE
 raise ValueError("No JSON object could be decoded")

### ISSUE THREAD

**Issue by Bigemm** [instabot-py/instabot.py#569]
Hey guys - let me start off by saying I am a complete newbie at coding. I've always been intrigued with how instagram growth via bots works and wanted to try it on my account. 

I keep getting this error after the script runs for a while: 

Traceback (most recent call last):
  File "/home/bigemm01/instabot.py/example.py", line 84, in <module>
    bot.new_auto_mod()
  File "/home/bigemm01/instabot.py/src/instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/bigemm01/instabot.py/src/instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/bigemm01/instabot.py/src/instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded 

Why is this happening and is there anyone that can assist me please?

Thank you!

**Comment by TehJokeR** [comment]
It looks as though it's trying to bug in the code for commenting. It's trying to decode something but it cant find what it's trying to decode. ( ValueError - object could not be decoded [ possibly empty ] )

If you're trying to suicide this script, you could de-activate commenting until this bug is fixed.

**Comment by Bigemm** [comment]
@TehJokeR seems you were right! I nulled the commenting function and the bad boy's been working error-less for some time. so it seems there is something wrong with source code for this bot (in the commenting function anyway. Thank you for the advice man! Is there anyway to make this known to everyone? I'm sure i'm not the only newbie that has experienced the problem with the commenting part of the code.

**Comment by TehJokeR** [comment]
I guess this issue will bring it to the attention of the developers. As for users, they'll have to come back here searching for issue/fix otherwise they wont know about it. I think your open issue is good enough for bringing light to the issue

**Comment by Bigemm** [comment]
@TehJokeR i just noticed this https://github.com/instabot-py/instabot.py/commit/be99125b62df24ec61cab33b614cdedf76109796#diff-91adcadbdf4fad3eb76d66f30bfba3af 

 def generate_comment(self):
 -        c_list = list(
 -            itertools.product(["this", "the", "your"], [
 -                "photo", "picture", "pic", "shot", "snapshot"
 -            ], ["is", "looks", "feels", "is really"], [
 -                "great", "super", "good", "very good", "good", "wow", "WOW",
 -                "cool", "GREAT", "magnificent", "magical", "very cool",
 -                "stylish", "beautiful", "so beautiful",
 -                "so stylish", "so professional", "lovely", "so lovely",
 -                "very lovely", "glorious", "so glorious", "very glorious",
 -                "adorable", "excellent", "amazing"
 -            ], [".", "..", "...", "!", "!!", "!!!"]))
 +        c_list = list(itertools.product(*self.comment_list))
  
          repl = [("  ", " "), (" .", "."), (" !", "!")]
          res = " ".join(random.choice(c_list))

That section is not in the source file when bot is cloned. Could this be the non existent part of the text the bot is trying to decode but finds nothing?

**Comment by TehJokeR** [comment]
To be honest I dont normally use the commenting function of the scripts. Personally, I think it's a dead giveaway that someone is running a bot when they comment a very generic comment. 

In your git terminal, when inside the insatbot.py parent directory you can run `'git reset --hard origin/master'` and then `'git pull'` to get the latest source code.

**Comment by ChipWolf** [comment]
We're aware, there's about 100 other issues with exactly the same issue. Please read the existing issues before posting a new one.
