### ISSUE TITLE
json.decoder.JSONDecodeError and stop the bot.

### ISSUE THREAD

**Issue by zhen737** [instabot-py/instabot.py#572]
Hi, the bot was running pretty smooth, but just one thing has been bothering me: it always randomly stop in the middle (Sometime after an hour it started running, sometime more than twelve hour, just random) and these were the codes it feedback. I've been looking for solution through out the internet, unfortunately have no luck. No idea what is the issue, any solution?

`Trying to like media: 1524788466730496386
Liked: 1524788466730496386. Like #50.
Get media id by tag: foodphotography
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\instabot.py-master\example.py", line 85, in <module>
    bot.new_auto_mod()
  File "C:\Users\PC\Desktop\instabot.py-master\src\instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\PC\Desktop\instabot.py-master\src\instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "C:\Users\PC\Desktop\instabot.py-master\src\instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> `

**Comment by ChipWolf** [comment]
We're aware, there's about 100 other issues with exactly the same issue. Please read the existing issues before posting a new one.

**Comment by AdrianaVecc** [comment]
@ChipWolf Could you link to the main issue where the conversation is happening instead? I have been through 50 of those issues, but it's not really helpful to close without redirecting.
