### ISSUE TITLE
when i add proxy i get an error 

### ISSUE THREAD

**Issue by newdjpower** [instabot-py/instabot.py#578]
hi , i`m using this bot on pythonanywhere and is running fine but when i add the proxy i`m getting this error : 
Traceback (most recent call last):
  File "/home/newdjpower/instabot.py-master4/sexylesley69.py", line 43, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/newdjpower/instabot.py-master4/src/instabot.py", line 203, in __init__
    self.login()
  File "/home/newdjpower/instabot.py-master4/src/instabot.py", line 258, in login
    r = self.s.get(self.url)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 465, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Ca
used by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))

can someone help me please ? 
thank you

**Comment by TehJokeR** [comment]
It looks as though the problem is actually with the unfollow_whitelist.. if you dont want to use the whitelist then remove the example_user_1 and example_user_2
i.e

`unfollow_whitelist = []`

**Comment by newdjpower** [comment]
where can i find this lines ? thank you

**Comment by TehJokeR** [comment]
in example.py set unfollow_whitelist = []

**Comment by newdjpower** [comment]
changed it and nothing change , still the same error :(

**Comment by TehJokeR** [comment]
In example.py ~line 30 what is your proxy variable set to?

`proxy='',`

**Comment by newdjpower** [comment]
this is 
proxy='198.55.109.144:3000',

**Comment by TehJokeR** [comment]
Have you tried a different proxy server? Or confirmed that the server at 198.55.109.144 is available and listening on 3000?

**Comment by TehJokeR** [comment]
It seems the server is available, are you sure you need to use port 3000?

[root@cloud-ms-1 ~]# ping 198.55.109.144
PING **198.55.109.144** (198.55.109.144) 56(84) bytes of data.
64 bytes from 198.55.109.144: icmp_seq=1 ttl=40 time=152 ms
64 bytes from 198.55.109.144: icmp_seq=2 ttl=40 time=153 ms
--- 198.55.109.144 ping statistics ---
2 packets transmitted, **2 received, 0% packet loss**, time 1603ms
rtt min/avg/max/mdev = 152.311/152.805/153.300/0.630 ms

**Comment by newdjpower** [comment]
is not port 3000 , i just chage it to not make it public , you need real port ?

**Comment by newdjpower** [comment]
i have to add this : 198.55.109.144 to authorizated ip`s list ?

**Comment by TehJokeR** [comment]
Where did you get the proxy server from? Which website? Check it again to see if it says which port to use

**Comment by newdjpower** [comment]
i`m using instantproxies

**Comment by newdjpower** [comment]
the port is 3128

**Comment by TehJokeR** [comment]
Set your proxy variable to 
`proxy='198.55.109.144:3128',`

**Comment by newdjpower** [comment]
it is setted like that

**Comment by TehJokeR** [comment]
You said earlier you have it set to 3000. Update this to be 3128

**Comment by newdjpower** [comment]
on this conversation i changed to 3000 , on the example.py it like you said

**Comment by ChipWolf** [comment]
🤦‍♂️

**Comment by TehJokeR** [comment]
This isnt a problem with the script, it's a problem with your proxy. You'll need to look into why your proxy server isnt responding to requests

**Comment by newdjpower** [comment]
can you give me skype or something ? we can`t chat here

**Comment by TehJokeR** [comment]
I'd suggest just trying a free public proxy. You can find them on google. Your configurations are correct so just keep trying. There's no issue here with instabot.py ( I'm running the bot with a proxy using the exact same configuration as you [different IP/port] )

**Comment by newdjpower** [comment]
can be pythonanywhere the problem ?

**Comment by ChipWolf** [comment]
https://help.pythonanywhere.com/pages/403ForbiddenError/
