### ISSUE TITLE
[SOLVED] Traceback (most recent call last):  ERROR

### ISSUE THREAD

**Issue by focamonca** [instabot-py/instabot.py#583]
I'm on Win 10, python 3.6.1, and my account has over 3 years.

this is what I get:

`C:\Users\Gianmaria\Desktop\instabot\instabottop\example.py
Traceback (most recent call last):
  File "C:\Users\Gianmaria\Desktop\instabot\instabottop\example.py", line 12, in <module>
    from instabot import InstaBot
  File "C:\Users\Gianmaria\Desktop\instabot\instabottop\src\instabot.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

WHY?

**Comment by focamonca** [comment]
[SOLVED]   I forgot to install: pip install -r requirements.txt
