### ISSUE TITLE
TypeError: urlopen() missing 1 required positional argument: 'request_method'

### ISSUE THREAD

**Issue by kthyaki** [instabot-py/instabot.py#602]
Hello guys, my Instabot was working perfectly for just one day after this day I am having this message:

```
Instabot v1.1.0 started at 19.06.2017 17:28:

Trying to login as afveterinarios...

Traceback (most recent call last):
  File "C:\Users\KTF\Desktop\instabot.py-master\src\example.py", line 55, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\KTF\Desktop\instabot.py-master\src\instabot.py", line 203, in __init__
    self.login()
  File "C:\Users\KTF\Desktop\instabot.py-master\src\instabot.py", line 258, in login
    r = self.s.get(self.url)
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\KTF\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
TypeError: urlopen() missing 1 required positional argument: 'request_method'
>>> 
```

Does anyone know what's wrong with it? Please help! 

Thank youuu in advance!

**Comment by kthyaki** [comment]
Please, does anyone know what it means

`TypeError: urlopen() missing 1 required positional argument: 'request_method'`

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
