### ISSUE TITLE
Hi! having some issue with commenting...

### ISSUE THREAD

**Issue by ching222** [instabot-py/instabot.py#632]
Really love this bot and I have to thank everyone who contributed!! But I am having random errors with comments. 

Here is the error message:

Traceback (most recent call last):
  File "C:\Users\Ryan\Desktop\instabot.py - 2\example.py", line 62, in <module>
    bot.new_auto_mod()
  File "C:\Users\Ryan\Desktop\instabot.py - 2\src\instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\Ryan\Desktop\instabot.py - 2\src\instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "C:\Users\Ryan\Desktop\instabot.py - 2\src\instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I am absolute noob in coding so I have no idea what is going on... anyone knows what is going on?

**Comment by uuaing** [comment]
You can ignore the error or fix it by my change as below
https://github.com/uuaing/instabot.py/commit/145a95825759c1e5c3928db168d61871057274b3#diff-91adcadbdf4fad3eb76d66f30bfba3af

**Comment by ching222** [comment]
Thanks a lot for your reply!! I will give it a try, thanks again

**Comment by zhen737** [comment]
@uuaing Hey sir, thanks for your answer, I've just tried, unfortunately it came up with another errors:

```
all_data = json.loads(check_comment.text.decode("utf-8"))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by uuaing** [comment]
It looks like server returns a 400 error at that time, then there is nothing can be loaded. The code will still continue right? so you can ignore it.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
