### ISSUE TITLE
Script Randomly Closes After A Few Hours

### ISSUE THREAD

**Issue by rusty-banks** [instabot-py/instabot.py#637]
Hey,

I am running this python script with these settings:

```
bot = InstaBot(
    login="***********",
    password="**********",
    like_per_day=600,
    comments_per_day=100,
    tag_list=['clothes', 'fashion', 'style', 'stylish', 'shopping', 'pants', 'jeans', 'makeup', 'looks', 'love', 'beautiful', 'clothing', 'girls', 'dress', 'apparel', 'shoes', 'outfit', 'heels', 'pretty', 'skirts', 'handbags', 'sunglasses', 'sundress' , 'lipstick'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=100,
    follow_per_day=400,
    follow_time=24 * 60 * 60,
    unfollow_per_day=400,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["This", "The", "Your", "The"],
                  ["photo", "picture", "pic", "shot", "snap", "image"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "interesting", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
```

The issue is that the script never runs for 24 hours or even to fulfill the desired settings (i.e. 600 likes/300 followers etc).
It just runs for a few hours and logs out. I have noticed that it only unfollows 50% of the people it follows. Could you guys please help?
For instance I ran it twice today and let me post the results:

**First Time:** 
```
Pausing for 19 seconds... 45 of 90
Logout: likes - 145, follow - 90, unfollow - 45, comments - 15.
Bot work time: 7:40:21.396564
Logout success!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\InstaBot v 1.1.0\src\instabot.py", line 318, in cleanup
    exit(0)
  File "C:\Python\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

```
**Second Time:** 
```
Unfollow: 1608622341 #12 of 24.
Pausing for 21 seconds... 12 of 24
Logout: likes - 34, follow - 24, unfollow - 12, comments - 6.
Bot work time: 1:29:24.098792
Logout success!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\InstaBot v 1.1.0\src\instabot.py", line 318, in cleanup
    exit(0)
  File "C:\Python\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
```

**JUST FYI IF IT HELPS:** I have noticed a few error messages like these just BEFORE it starts UNFOLLOWING:

```
Traceback (most recent call last):
  File "example.py", line 79, in <module>
    bot.new_auto_mod()
  File "C:\Users\Administrator\Desktop\InstaBot v 1.1.0\src\instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\Administrator\Desktop\InstaBot v 1.1.0\src\instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "C:\Users\Administrator\Desktop\InstaBot v 1.1.0\src\instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Python\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by omidedipidizi** [comment]
Same here !!!

**Comment by TehJokeR** [comment]
Disable commenting. This functionality is broken. Set your comments_per_day to 0

**Comment by pattymayo** [comment]
noticed this is still open. Was a patch released for this? I have noticed that the same is happening when comments are on, but specifically the time the bot runs is shorter and shorter in each run when the comments are on.

**Comment by rusty-banks** [comment]
I have stopped using this BOT. Switched to InstaPy: [https://github.com/timgrossmann/InstaPy](url)
Working flawlessly.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
