### ISSUE TITLE
ImportError: cannot import name JSONDecodeError

### ISSUE THREAD

**Issue by estavex** [instabot-py/instabot.py#638]
Every time I do python example.py it throws this exception:

Trying to login as <account_name>...

<account_name> login success!
Traceback (most recent call last):
  File "example.py", line 62, in <module>
    unfollow_whitelist=['example1', 'example2'])
  File "C:\xampp\htdocs\instabot\src\instabot.py", line 204, in __init__
    self.populate_user_blacklist()
  File "C:\xampp\htdocs\instabot\src\instabot.py", line 214, in populate_user_blacklist
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError

And yes, i've put the real usernames in the unfollow_whitelist. Why is this error showing?

**Comment by wbaxterh** [comment]
Hi! I had the same error and was able to fix this by installing simple json on my machine and replacing the call to "from json import jsonDecodeError" to: "from simplejson import jsonDecodeError" also import simplejson at the head of the document. That worked for me!

**Comment by Krustenviech** [comment]
Same error and no solving yet :(

As soon as i type in blacklist users i get this.

**Comment by estavex** [comment]
@wbaxterh DUDE THANK YOU!

**Comment by ymongo** [comment]
Worked for me as well. 

Thanks for the fix!

**Comment by panosru** [comment]
I did that but now I get "ValueError: No JSON object could be decoded" :(

**Comment by panosru** [comment]
This solved one issue but now there is a new one:

```
Traceback (most recent call last):                                                                                                                                                                                 
  File "./testing.py", line 55, in <module>                                                                                                                                                                           
    "******":"", "******":"", "******":"", "*****":""                                                                                                 
  File "/home/*****/script/src/instabot.py", line 205, in __init__                                                                                                                                               
    self.populate_user_blacklist()                                                                                                                                                                                 
  File "/home/*****/script/src/instabot.py", line 217, in populate_user_blacklist                                                                                                                                
    all_data = json.loads(info.text)                                                                                                                                                                               
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads                                                                                                                                                   
    return _default_decoder.decode(s)                                                                                                                                                                              
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode                                                                                                                                                   
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                                                                              
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode                                                                                                                                               
    raise ValueError("No JSON object could be decoded")                                                                                                                                                            
ValueError: No JSON object could be decoded
```

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
