### ISSUE TITLE
application crashes every once in a while 

### ISSUE THREAD

**Issue by incanus1** [instabot-py/instabot.py#650]
Traceback (most recent call last):
  File "C:\Users\AAA\Desktop\instabot.py-master\example.py", line 84, in <module>
    bot.new_auto_mod()
  File "C:\Users\AAA\Desktop\instabot.py-master\src\instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\AAA\Desktop\instabot.py-master\src\instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "C:\Users\AAA\Desktop\instabot.py-master\src\instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Users\AAA\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\AAA\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\AAA\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by TehJokeR** [comment]
Simple fix: Disable comments
Set in example.py:
`comments_per_day = 0`

**Comment by dv1pr** [comment]
@TehJokeR that's not a fix.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
