### ISSUE TITLE
Script stops working after seconds: user info list is empty!!!

### ISSUE THREAD

**Issue by eigentlichich** [instabot-py/instabot.py#688]
script ends after almost a minute with this error:

xxxxxxx user info list is empty!!! xxxxxxxxx
Traceback (most recent call last):
  File "/home/pi/Downloads/instabot.py-master/src/user_feed.py", line 28, in get_media_id_user_feed
    all_data = json.loads(r.text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Downloads/instabot.py-master/example.py", line 97, in <module>
    bot.new_auto_mod()
  File "/home/pi/Downloads/instabot.py-master/src/instabot.py", line 580, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/home/pi/Downloads/instabot.py-master/src/instabot.py", line 632, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/home/pi/Downloads/instabot.py-master/src/unfollow_protocol.py", line 40, in unfollow_protocol
    follow_protocol(self)
  File "/home/pi/Downloads/instabot.py-master/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/home/pi/Downloads/instabot.py-master/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/home/pi/Downloads/instabot.py-master/src/likers_graber_protocol.py", line 21, in likers_graber_protocol
    get_media_id_user_feed(self)
  File "/home/pi/Downloads/instabot.py-master/src/user_feed.py", line 39, in get_media_id_user_feed
    time.sleep(60)
KeyboardInterrupt

**Comment by sayanudin** [comment]
same

**Comment by Jones333** [comment]
I think I have the same problem. Sometimes it happen in few minutes after login and sometimes I first got the error after four hours running.

I always get this message:
Traceback (most recent call last):
  File "example.py", line 74, in <module>
    bot.new_auto_mod()
  File "/Users/Jonas/Desktop/instabot.py/src/instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/Jonas/Desktop/instabot.py/src/instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/Users/Jonas/Desktop/instabot.py/src/instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by emec1n** [comment]
same

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
