### ISSUE TITLE
Error 111

### ISSUE THREAD

**Issue by siddhshabd** [instabot-py/instabot.py#747]
Instabot v1.1.0 started at 17.09.2017 15:50:

Trying to login as *****...

Traceback (most recent call last):
  File "example.py", line 55, in <module>
    unfollow_whitelist=['****', '****','****'])
  File "/home/****/Desktop/****/src/instabot.py", line 203, in __init__
    self.login()
  File "/home/****/Desktop/****/src/instabot.py", line 258, in login
    r = self.s.get(self.url)
  File "/home/****/.local/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/*****/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/****/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/****/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb6c594cc>: Failed to establish a new connection: [Errno 111] Connection refused',))

Getting this error please help

**Comment by virginsince1997** [comment]
Connection problem , check your WiFi or whatever you connect with , if
you're using a proxy make sure it a working one

**Comment by ugurozturk** [comment]
this is not related to library, your internet or firewall or python requests module.
