### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by re2005** [instabot-py/instabot.py#788]
`
Traceback (most recent call last):
  File "example.py", line 74, in <module>
    bot.new_auto_mod()
  File "/Users/renatocardoso/renatex/repos/instabot.py/src/instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/renatocardoso/renatex/repos/instabot.py/src/instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/Users/renatocardoso/renatex/repos/instabot.py/src/instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by Plushkin** [comment]
The same error

**Comment by manhcuogntin4** [comment]
my code works well and one day I met this error. Anyone has solution ?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
