### ISSUE TITLE
How to run this 24/7 on a server

### ISSUE THREAD

**Issue by lordoftime39** [instabot-py/instabot.py#792]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
Hey,
I was interested in running this program 24/7 on a server, what services would you recommend me to use, like Phython anywhere. I also have a website hosting plan if i could run this program through that, some how. 
p.s. i have minimal coding experience besides java.

**Comment by rodentooth** [comment]
linux/windows server?
I am running it on a linux server, just cd to the project dic, type in 'python3 example.py' and voila

**Comment by lordoftime39** [comment]
Hello I could use Linux server if it was easier and what service do you use
to run a Linux serice 24 7, thanks

**Comment by drovid** [comment]
or just get a raspberry pi and let that mofo run?

**Comment by lordoftime39** [comment]
I would like to use this on some kind of cloud service, since it will be
not only my project but a friends so we would both like control over it,
I'm looking for more of an online verison.

**Comment by ravxl** [comment]
you can pick any vps in any flavour that you find affordable and let it run! :)

**Comment by wizarduk** [comment]
Just run in a screen and have it running 24/7

**Comment by ishalyminov** [comment]
I've got a Heroku-ready version here: https://github.com/ishalyminov/instabot.py
You'll just 100% need to run it via stable proxy, Instagram is very sensitive to location

**Comment by agustinx19** [comment]
Can u make a sh or a batch file, is the best way.

**Comment by wizarduk** [comment]
@rodentooth This bot doesn't work 24/7 if anyone has it running on a vps please advise as mine crashed every few hours which is no good...

**Comment by raymondma1** [comment]
dockerize the bot and deploy it on a compute engine instance on google cloud platform (free).

**Comment by eimis101** [comment]
@ishalyminov thank you for your fork, but I am getting an error trying to run it. Please help!!!

-----> Python app detected
-----> Installing python-3.6.2
-----> Installing pip
-----> Installing requirements with pip
       Collecting argparse==1.2.1 (from -r /tmp/build_94bbf2494ec3c628fbeaa89ecf6e1c8f/requirements.txt (line 1))
         Downloading argparse-1.2.1.tar.gz (69kB)
       Collecting requests==2.12.4 (from -r /tmp/build_94bbf2494ec3c628fbeaa89ecf6e1c8f/requirements.txt (line 2))
         Downloading requests-2.12.4-py2.py3-none-any.whl (576kB)
       Collecting retrying==1.3.3 (from -r /tmp/build_94bbf2494ec3c628fbeaa89ecf6e1c8f/requirements.txt (line 3))
         Downloading retrying-1.3.3.tar.gz
       Collecting six==1.10.0 (from -r /tmp/build_94bbf2494ec3c628fbeaa89ecf6e1c8f/requirements.txt (line 4))
         Downloading six-1.10.0-py2.py3-none-any.whl
       Collecting wsgiref==0.1.2 (from -r /tmp/build_94bbf2494ec3c628fbeaa89ecf6e1c8f/requirements.txt (line 5))
         Downloading wsgiref-0.1.2.zip
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-guhr_5t1/wsgiref/setup.py", line 5, in <module>
               import ez_setup
             File "/tmp/pip-build-guhr_5t1/wsgiref/ez_setup/__init__.py", line 170
               print "Setuptools version",version,"or greater has been installed."
                                        ^
           SyntaxError: Missing parentheses in call to 'print'
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-guhr_5t1/wsgiref/
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by ishalyminov** [comment]
@eimis101 it's supposed to work with Python 2.7. Please pull my fork again, I've added the `runtime.txt` file for Heroku to pick up the right Python version automatically.

**Comment by eimis101** [comment]
@ishalyminov you are a god!

**Comment by eimis101** [comment]
@ishalyminov there now seems to be a KEYERROR on the login credentials when I try to run it on heroku. 

Traceback (most recent call last):
  File "example.py", line 126, in <module>
    run_bot()
  File "example.py", line 20, in run_bot
    login=os.environ['my_username'],
  File "/app/.heroku/python/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'my_username'

**Comment by ishalyminov** [comment]
@eimis101 yeah, you have to pass env variables to Heroku differently: either log in to heroku.com and set them via the interface as Heroku Config Vars, or list them in the `.env` file (I actually couldn't get it to work for me).

**Comment by eimis101** [comment]
@ishalyminov as you mentioned im getting an error regarding location i think:

Login error! Connection error 400! ({"message": "checkpoint_required", "checkpoint_url": "/challenge/5545977832/6tb1zgxBZy/", "lock": false, "status": "fail"})

After this, once i log into insta on my phone, it says suspicious login attempt from Ireland, while im in Germany.

**Comment by ishalyminov** [comment]
@eimis101 exactly. A stable anonymous proxy in your town will help (set it via the PROXY env var)

**Comment by eimis101** [comment]
@ishalyminov fairly new here, how do i set the proxy? add an IP address?

**Comment by ishalyminov** [comment]
@eimis101 proxy server format is "<ip>:<port>". Also please check with your proxy provider/aggregator that it's not transparent -- both anonymous and elite would work I think.

**Comment by ishalyminov** [comment]
Hey @LevPasha, I can make a PR with a stable, and documented Heroku setup. Would you be interested in it?

**Comment by kanegovaert** [comment]
The script crashes sometimes caused by unexpected JSON responses from what I have seen debugging the script. I have found a solution so the script can run 24/7

If using Windows just create a new .bat file and insert:

```
title Instagram Bot
echo off
color b
cls
echo Starting script for Instagram...
python "path\example.py"
:A
echo Restarting script for bot after 5 minutes...
SLEEP 300
python "path\example.py"
GOTO A
```

Whenever the script crashes it pauses for 5 minutes and continues as usual. You can also give the cmd window text different colors if you're running multiple bots.

**Comment by HenryCooperGithub** [comment]
Not related to library issues . closed .
