### ISSUE TITLE
Mode 2 does not work 

### ISSUE THREAD

**Issue by taradell** [instabot-py/instabot.py#808]
Hi guys, I noticed that Mode 2 does not work anymore - I am using the latest version of the bot.

It checks all users info (such as #likes, follower status) but it does not unfollow any user and does not search and like any tag; finally, it crashes after a while. 

Anyone with the same issue? 
How to fix it?

thanks in advance ;-)

**Comment by ice1x** [comment]
Am i right - this exception exactly what you talking?
`
Traceback (most recent call last):
  File "example.py", line 98, in <module>
    bot.new_auto_mod()
  File "/Users/cold00n/repo/instabot.py/src/instabot.py", line 580, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/Users/cold00n/repo/instabot.py/src/instabot.py", line 632, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/Users/cold00n/repo/instabot.py/src/unfollow_protocol.py", line 40, in unfollow_protocol
    follow_protocol(self)
  File "/Users/cold00n/repo/instabot.py/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/Users/cold00n/repo/instabot.py/src/feed_scanner.py", line 37, in feed_scanner
    self.current_id = self.media_on_feed[chooser]["node"]["owner"][
TypeError: 'NoneType' object has no attribute '__getitem__'
`

**Comment by taradell** [comment]
@ice1x yes, it does not work at all. 
it seems that it is doing stuffs but in the end there are no results neither for likes nor for unfollowing

**Comment by JonasE99** [comment]
I got the same problem :/ I am running the latest version and the bot still doesent unfollow any people

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
