### ISSUE TITLE
[HELP] Feed Liker and Comments

### ISSUE THREAD

**Issue by xpathbrand** [instabot-py/instabot.py#819]
**I'm trying to develop a function that puts you likewise and that comments feed media**

Can anyone help me develop this function?
(file: instabot.py)
```
    def get_media_id_recent_feed(self):
        if self.login_status:
            now_time = datetime.datetime.now()
            log_string = "%s : Get media id on recent feed" % (self.user_login)
            self.write_log(log_string)
            if self.login_status == 1:
                url_tag = 'https://www.instagram.com/?__a=1'
                try:
                    r = self.s.get(url_tag)
                    all_data = json.loads(r.text)

                    self.media_on_feed = list(
                        all_data['graphql']['user']['edge_web_feed_timeline'][
                            'edges'])

                    log_string = "Media in recent feed = %i" % (
                        len(self.media_on_feed))
                    self.write_log(log_string)
                except:
                    self.media_on_feed = []
                    self.write_log("Except on get_media!")
                    time.sleep(20)
                    return 0
            else:
                return 0

    def like_all_exist_feedmedia(self, media_size=-1, delay=True):
        """ Like all media ID that have self.media_on_feed """

        if self.login_status:
            if self.media_on_feed != 0:
                i = 0
                for d in self.media_on_feed:
                    # Media count by this tag.
                    if media_size > 0 or media_size < 0:
                        media_size -= 1
                        l_c = self.media_on_feed[i]['likes']['count']
                        if ((l_c <= self.media_max_like and
                             l_c >= self.media_min_like) or
                            (self.media_max_like == 0 and
                             l_c >= self.media_min_like) or
                            (self.media_min_like == 0 and
                             l_c <= self.media_max_like) or
                            (self.media_min_like == 0 and
                             self.media_max_like == 0)):
                            for blacklisted_user_name, blacklisted_user_id in self.user_blacklist.items(
                            ):
                                if self.media_on_feed[i]['owner'][
                                        'id'] == blacklisted_user_id:
                                    self.write_log(
                                        "Not liking media owned by blacklisted user: "
                                        + blacklisted_user_name)
                                    return False
                            if self.media_on_feed[i]['owner'][
                                    'id'] == self.user_id:
                                self.write_log(
                                    "Keep calm - It's your own media ;)")
                                return False

                            try:
                                caption = self.media_on_feed[i][
                                    'caption'].encode(
                                        'ascii', errors='ignore')
                                tag_blacklist = set(self.tag_blacklist)
                                if sys.version_info[0] == 3:
                                    tags = {
                                        str.lower(
                                            (tag.decode('ASCII')).strip('#'))
                                        for tag in caption.split()
                                        if (tag.decode('ASCII')
                                            ).startswith("#")
                                    }
                                else:
                                    tags = {
                                        unicode.lower(
                                            (tag.decode('ASCII')).strip('#'))
                                        for tag in caption.split()
                                        if (tag.decode('ASCII')
                                            ).startswith("#")
                                    }

                                if tags.intersection(tag_blacklist):
                                    matching_tags = ', '.join(
                                        tags.intersection(tag_blacklist))
                                    self.write_log(
                                        "Not liking media with blacklisted tag(s): "
                                        + matching_tags)
                                    return False
                            except:
                                self.write_log(
                                    "Couldn't find caption - not liking")
                                return False

                            log_string = "Trying to like media: %s" % \
                                         (self.media_on_feed[i]['id'])
                            self.write_log(log_string)
                            like = self.like(self.media_on_feed[i]['id'])
                            # comment = self.comment(self.media_on_feed[i]['id'], 'Cool!')
                            # follow = self.follow(self.media_on_feed[i]["owner"]["id"])
                            if like != 0:
                                if like.status_code == 200:
                                    # Like, all ok!
                                    self.error_400 = 0
                                    self.like_counter += 1
                                    log_string = "Liked: %s. Like #%i." % \
                                                 (self.media_on_feed[i]['id'],
                                                  self.like_counter)
                                    self.write_log(log_string)
                                elif like.status_code == 400:
                                    log_string = "Not liked: %i" \
                                                 % (like.status_code)
                                    self.write_log(log_string)
                                    # Some error. If repeated - can be ban!
                                    if self.error_400 >= self.error_400_to_ban:
                                        # Look like you banned!
                                        time.sleep(self.ban_sleep_time)
                                    else:
                                        self.error_400 += 1
                                else:
                                    log_string = "Not liked: %i" \
                                                 % (like.status_code)
                                    self.write_log(log_string)
                                    return False
                                    # Some error.
                                i += 1
                                if delay:
                                    time.sleep(self.like_delay * 0.9 +
                                               self.like_delay * 0.2 *
                                               random.random())
                                else:
                                    return True
                            else:
                                return False
                        else:
                            return False
                    else:
                        return False
            else:
                self.write_log("No media to like!")

    def test123(self):
        # ------------------- Get media_id -------------------
        if len(self.media_on_feed) == 0:
            self.get_media_id_recent_feed()
            self.this_feed_like_count = 0
            self.max_feed_like_count = random.randint(
                1, self.max_like_for_one_feed)
        # ------------------- Like -------------------
        self.test123_like()
        # ------------------- Comment -------------------
        #self.new_auto_mod_comments()
        # Bot iteration in 1 sec
        time.sleep(3)
        # print("Tic!")

    def test123_like(self):
        if time.time() > self.next_iteration["Like"] and self.like_per_day != 0 \
                and len(self.media_on_feed) > 0:
            # You have media_id to like:
            if self.like_all_exist_feedmedia(media_size=1, delay=False):
                # If like go to sleep:
                self.next_iteration["Like"] = time.time() + \
                                              self.add_time(self.like_delay)
                # Count this tag likes:
                self.this_feed_like_count += 1
                if self.this_feed_like_count >= self.max_feed_like_count:
                    self.media_on_feed = [0]
            # Del first media_id
            del self.media_on_feed[0]
```

I got this error

```
Media in recent feed = 12
Traceback (most recent call last):
  File "example.py", line 119, in <module>
    bot.test123()
  File "./src/instabot.py", line 755, in test123
    self.test123_like()
  File "./src/instabot.py", line 766, in test123_like
    if self.like_all_exist_feedmedia(media_size=1, delay=False):
  **File "./src/instabot.py", line 643, in like_all_exist_feedmedia
    l_c = self.media_on_feed[i]['likes']['count']
KeyError: 'likes'**
Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
Bot work time: 0:00:10.351473
```

**Comment by ugurozturk** [comment]
@xpathbrand it looks inactive, if you are still keeping to develop this. Open a new issue
