### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by Blacksmith1234** [instabot-py/instabot.py#821]
I 've already read the other proxy issues but I can't find the answer how can use this bot through proxy.
I've seen a topic #71 and there is a lot of good information but that's a bit chaotic for me. 
Can someone explain what I have to do exactly?
When I'm trying to use a proxy I got this error message. 

"

> Trying to login as theexplorerpack...
> 
> Traceback (most recent call last):
>   File "C:\Users\Sun\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 588, in urlopen
>     self._prepare_proxy(conn)
>   File "C:\Users\Sun\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 801, in _prepare_proxy
>     conn.connect()
>   File "C:\Users\Sun\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\connection.py", line 291, in connect
>     self._tunnel()
>   File "C:\Users\Sun\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 914, in _tunnel
>     (version, code, message) = response._read_status()
>   File "C:\Users\Sun\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "C:\Users\Sun\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
>     return self._sock.recv_into(b)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Sun\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 423, in send
>     timeout=timeout
>   File "C:\Users\Sun\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 643, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "C:\Users\Sun\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\packages\urllib3\util\retry.py", line 363, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
> 

""

Please help
Thank you

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
