### ISSUE TITLE
self.media_on_feed[chooser] is absent after a 10-20 iterations if MODE == 2

### ISSUE THREAD

**Issue by ice1x** [instabot-py/instabot.py#828]
https://github.com/instabot-py/instabot.py/blob/f192a7ecc750432edfbb1137c78263c6ab6c76ad/src/feed_scanner.py#L37

**Comment by ice1x** [comment]
Followed: 235446566 #2.
Followed: 6425224395 #3.



___________________________________________________TypeError



Traceback (most recent call last):
  File "example.py", line 97, in <module>
    bot.new_auto_mod()
  File "/Users/cold00n/repo/instabot.py/src/instabot.py", line 580, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/Users/cold00n/repo/instabot.py/src/instabot.py", line 632, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/Users/cold00n/repo/instabot.py/src/unfollow_protocol.py", line 40, in unfollow_protocol
    follow_protocol(self)
  File "/Users/cold00n/repo/instabot.py/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/Users/cold00n/repo/instabot.py/src/feed_scanner.py", line 41, in feed_scanner
    print self.media_on_feed[chooser]["node"]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by ice1x** [comment]
Added my patched trace above (___________________________________________________TypeError message inside the try except processing)

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
