### ISSUE TITLE
mac os error  ((. ImportError: No module named requests ))

### ISSUE THREAD

**Issue by edwardium** [instabot-py/instabot.py#830]
i run this bot with out any problem on Win but when i run it on my macbook this error is come and not working !!!

**any idea ?>?**

MacBook-Pro:instabot mymac$ python example.py
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
  File "/Users/mymac/Desktop/instabot/src/instabot.py", line 16, in <module>
    import requests
ImportError: No module named requests

**Comment by jmfgdev** [comment]
open up terminal and run pip install requests,
if that fails, try pip3 install requests
