### ISSUE TITLE
Error line 79 and line 584??

### ISSUE THREAD

**Issue by Dervock** [instabot-py/instabot.py#834]
Hello there, I have a Debian server on which I am running this bot. The problem is that after some hours the bot stops. I thought it was some problem with cron but the process is starting just fine. So I tried to launch example.py by myself without cron and it gives me a login error followed by these messages. Any way to fix this?

File "example.py", line 79, in <module>
    bot.new_auto_mod()
  File "/root/instabot.py/src/instabot.py", line 584, in new_auto_mod
    time.sleep(3)
KeyboardInterrupt
Exception KeyError: KeyError(139759921501952,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by Dervock** [comment]
I also tried to run it with python3 but this happens.


Login error! Check your login data!
^CTraceback (most recent call last):
  File "example.py", line 79, in <module>
    bot.new_auto_mod()
  File "/root/instabot.py/src/instabot.py", line 584, in new_auto_mod
    time.sleep(3)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/instabot.py/src/instabot.py", line 318, in cleanup
    exit(0)
  File "/usr/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

**Comment by Dervock** [comment]
@ChipWolf @LevPasha

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
