### ISSUE TITLE
auto log out , help

### ISSUE THREAD

**Issue by suri4desplaines** [instabot-py/instabot.py#839]
hello world
hey , i'm noob in .py , can you help me ?
pc win 10 python 3.X

""
Trying to like media: 1662826576301293116
Liked: 1662826576301293116. Like #341.
Traceback (most recent call last):
  File "example.py", line 72, in <module>
    bot.new_auto_mod()
  File "E:\Users\valen\Desktop\bot instagram\instabot.py-master\src\instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "E:\Users\valen\Desktop\bot instagram\instabot.py-master\src\instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "E:\Users\valen\Desktop\bot instagram\instabot.py-master\src\instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Users\valen\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\valen\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\valen\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Logout: likes - 341, follow - 0, unfollow - 0, comments - 105.
Bot work time: 8:32:24.716269
Logout success!
""

**Comment by michab23** [comment]
the same issue:

Unfollow: 4078797909 #42 of 47.
Pausing for 24 seconds... 42 of 47
Logout: likes - 78, follow - 47, unfollow - 42, comments - 3.
Bot work time: 4:03:40.790841
Logout success!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/michaelb/pythonprojects/instabot.py-master/src/instabot.py", line 318, in cleanup
    exit(0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

Any help?

**Comment by suri4desplaines** [comment]
If using Windows just create a new .bat with a path off the location off example.py and run it :
"
title Instagram Bot
echo off
color b
cls
echo Starting script for Instagram...
python "path\example.py"
:A
echo Restarting script for bot after 5 minutes...
SLEEP 300
python "path\example.py"
GOTO A
Whenever the script crashes it pauses for 5 minutes and continues as usual. You can also give the cmd window text different colors if you're running multiple bots.
"

**Comment by Tifiloow** [comment]
suri4desplaines
Tu es Français a ce que je vois (i can see you are french)
Tu as trouvé pour le faire mais en .sh (pour mon cent os ) ?? (Did you know the code for .sh ? )
Thanks, merci

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
