### ISSUE TITLE
the code is not work

### ISSUE THREAD

**Issue by hamid-karimi** [instabot-py/instabot.py#862]
Hi
I used "python3 example.py" command and I get this error:

```
Traceback (most recent call last):
  File "example.py", line 56, in <module>
    unfollow_whitelist=[''])
  File "/Users/hamid/Desktop/instabot.py-master/src/instabot.py", line 203, in __init__
    self.login()
  File "/Users/hamid/Desktop/instabot.py-master/src/instabot.py", line 258, in login
    r = self.s.get(self.url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103d80588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

I've searched too much, and I can't fix my problem

**Comment by hamid-karimi** [comment]
now I get this error, please help
```
Traceback (most recent call last):
  File "example.py", line 56, in <module>
    unfollow_whitelist=['******'])
  File "/Users/hamid/Desktop/instabot.py-master/src/instabot.py", line 203, in __init__
    self.login()
  File "/Users/hamid/Desktop/instabot.py-master/src/instabot.py", line 271, in login
    ui = UserInfo()
  File "/Users/hamid/Desktop/instabot.py-master/src/userinfo.py", line 31, in __init__
    self.hello()
  File "/Users/hamid/Desktop/instabot.py-master/src/userinfo.py", line 36, in hello
    main = self.s.get(self.url_list[self.i_a]["main"])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by aruser1** [comment]
hey man, there's an error in your example file. Please go to telegram group and ask someone for their example file.

**Comment by GithubProgress** [comment]
This looks like a proxy / connection issue . Closed .
