### ISSUE TITLE
Bot has died or been slow the last couple times I have ran it (both in mode 0 and 2)

### ISSUE THREAD

**Issue by econn9** [instabot-py/instabot.py#863]
my internet speed/bandwidth is not the issue

my instabot.py: https://pastebin.com/9EZj9pRV

i broke out my constants (asterisks in place of sensitive data) into a separate file: https://pastebin.com/363txYiE

when i was first running this bot i was using mode 2, and it worked just fine ...in like 12-18 hours time it had done 500 some likes and many comments and you could see the console output was rolling along nicely. 

the mode switching hasnt really made a difference though, i noticed this slowness in both mode 0 and 2. now it seems to start up, go quickly, then reaaallllyyy slow down after 20-30 mins or so ... nothing else is running on my computer. 

last time i shutdown i did get some abnormal output, but only this last time:

^CTraceback (most recent call last):
  File "pup.py", line 66, in <module>
    bot.new_auto_mod()
  File "/Users/dont/worry/about/it/src/instabot.py", line 576, in new_auto_mod
    self.new_auto_mod_like()
  File "/Users/dont/worry/about/it/instabot.py/src/instabot.py", line 591, in new_auto_mod_like
    if self.like_all_exist_media(media_size=1, delay=False):
  File ""/Users/dont/worry/about/it/instabot.py/src/instabot.py", line 428, in like_all_exist_media
    time.sleep(self.ban_sleep_time)
KeyboardInterrupt
Logout: likes - 44, follow - 0, unfollow - 0, comments - 3.
Bot work time: 3:09:27.504121

as you can see, 44 likes in 3 hours ... any ideas?

**Comment by forgottensword** [comment]
This bot is dead.

**Comment by econn9** [comment]
@forgottensword huh? then why does it kind of work?

**Comment by aruser1** [comment]
this bot is not dead. your example file is dead. It has errors. If you are not a coder then replace it with someone else's working example file

**Comment by econn9** [comment]
@forgottensword @aruser1 did you even read the stack trace? traces back to your files. it was running very slowly and was shut down manually (see the "^C" and "Keyboard Interrupt") ... the line from my "example" file is innocuous, tracing it back to 428 in instabot.py theres a comment saying im probably banned. 

i was running a very unaggressive bot ... has instagram upped its bot sniffing capabilities? what to do from here? is it temporary?

**Comment by ugurozturk** [comment]
@forgottensword check my fork with a lot new features https://github.com/ugurozturk/instabot.pyV2

**Comment by GithubProgress** [comment]
Please update to the recent version .

If the problem persists please post a full console output log and your current settings .
