### ISSUE TITLE
Error when add comments per day

### ISSUE THREAD

**Issue by remiremiremi** [instabot-py/instabot.py#880]
Hi, im trying to add comments per day, but when i add a number, the cmd makes this:

Traceback (most recent call last):
  File "C:\Users\Usuario\Downloads\instabot.py-master\example.py", line 79, in <module>
    bot.new_auto_mod()
  File "C:\Users\Usuario\Downloads\instabot.py-master\src\instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\Usuario\Downloads\instabot.py-master\src\instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['comments_disabled']) == False:
  File "C:\Users\Usuario\Downloads\instabot.py-master\src\instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Trying to unfollow: 569290747
Unfollow: 569290747 #1 of 1.
Pausing for 30 seconds... 1 of 1
Logout: likes - 1, follow - 1, unfollow - 1, comments - 0.
Bot work time: 0:00:42.944137
Logout success!

How can i fix it?

Thanks!!!

**Comment by GithubProgress** [comment]
Please update to the recent version and re-try .

If the issue still occurs , please provide your configuration .
