### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by matteoFeduzi** [instabot-py/instabot.py#912]
I have Mac and i have this error after download example.py

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/FeduziMatteo/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/FeduziMatteo/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/FeduziMatteo/Desktop/instabot.py-master/src/userinfo.py", line 6, in <module>
    import requests
ImportError: No module named requests

**Comment by ugurozturk** [comment]
@matteoFeduzi ImportError: No module named requests . do google it

**Comment by ugurozturk** [comment]
ALSO use https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md when you going to create new issue

**Comment by matteoFeduzi** [comment]
? I don’t understand

Il giorno mar 16 gen 2018 alle 17:12 ugurozturk <notifications@github.com>
ha scritto:
