### ISSUE TITLE
No module named 'fake_useragent'

### ISSUE THREAD

**Issue by volkv** [instabot-py/instabot.py#920]
Hey! Got **fake_useragent** installed
```
instabot$ pip install fake_useragent
Collecting fake_useragent
Installing collected packages: fake-useragent
Successfully installed fake-useragent-0.1.8
```
but receiving 

```
instabot$ python bot.py
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    from src import InstaBot
  File "/home/cp/Desktop/instabot/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/cp/Desktop/instabot/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/home/cp/Desktop/instabot/src/userinfo.py", line 6, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'
```

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket.
