### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by enriqueg** [instabot-py/instabot.py#929]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
MAC 10.13.1
## Python Version?
 3

## Description
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/MC/instabot.py-master2/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/MC/instabot.py-master2/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/MC/instabot.py-master2/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/Users/MC/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/MC/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/MC/miniconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Type the description of your issue here.
can't login
```
Include the contents of the error.log here (if applicable).
```

**Comment by aopiskin** [comment]
Me too I can't #930

**Comment by eltoro3** [comment]
Same
Maybe Instagram changed some features preventing this bot from logging in?

**Comment by bgokden** [comment]
It seems like user info request response has changed.

**Comment by aopiskin** [comment]
Probably everybody gettin' thesame error. Instagram may change algorithm.

**Comment by bgokden** [comment]
Ok, this change only applies to user info and only required field is user id. It is still in the response but we need to parse and extract json. I hardcoded the user id, then everything worked.

**Comment by eltoro3** [comment]
How do you do that?

**Comment by bgokden** [comment]
We can use beautifulSoup to extract data. Does anybody know a better endpoint?
We can do something like this:
https://stackoverflow.com/questions/13323976/how-to-extract-a-json-object-that-was-defined-in-a-html-page-javascript-block-us

**Comment by eltoro3** [comment]
Please send me an example

**Comment by NodalPoint** [comment]
Phew, I thought it was me...

**Comment by bgokden** [comment]
I can parse the user id this way:

soup = BeautifulSoup(info.text, "html.parser")
script = soup.find('script', text=re.compile('window\._sharedData')) # window._sharedData
json_text = re.search(r'^\s*window\._sharedData\s*=\s*({.*?})\s*;\s*$',
                      script.string, flags=re.DOTALL | re.MULTILINE).group(1)
data = json.loads(json_text)
print(data['entry_data']['ProfilePage'][0]['user']['id'])

**Comment by eltoro3** [comment]
And you paste that in example.py?

**Comment by pablosproject** [comment]
The webpage is returning a JSON again, before it was sending an HTML which was not parsing. Try this `https://www.instagram.com/{USERNAME}/?__a=1` and you should see a JSON and not an HTML

**Comment by aopiskin** [comment]
@indiscreetak Are you sure? I can't still :D i tired with old version and new version.

**Comment by indiscreetak** [comment]
@aopiskin Positive. See @pablosproject comment.

**Comment by bgokden** [comment]
It started working again by just reading json. It seems like they tried something :D

**Comment by eltoro3** [comment]
Now its says login error

**Comment by aopiskin** [comment]
I will try a few min. later.

**Comment by NodalPoint** [comment]
Imagine this just being a honeypot, like they can log everyone using this bot hahaha, rip.

**Comment by ugurozturk** [comment]
Keep calm everybody, wait 15-30mins then lets fix together

**Comment by aopiskin** [comment]
@NodalPoint Heaven forbid. Lol
--

**Comment by bgokden** [comment]
@ugurozturk I was writing a fix to parse the response but now it returned back to respond with json.

It can't be a honeypot, since request didn't change. They will just see that someone logins but then do nothing.

**Comment by enriqueg** [comment]
It is working again for me! Feel free to close this!

**Comment by bgokden** [comment]
@ugurozturk I was getting this error:

Traceback (most recent call last):
  File "./app.py", line 139, in <module>
    unfollow_whitelist=[])
  File "/usr/src/app/src/instabot.py", line 231, in __init__
    self.login()
  File "/usr/src/app/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/usr/src/app/src/userinfo.py", line 43, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/opt/conda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I debugged an it was failing at 
    all_data = json.loads(info.text)

since info.text was not a json but it was an html file. (I saved the context if you need)
but it fixed itself after a while. I don't get any error now.

**Comment by ugurozturk** [comment]
@bgokden i got it, i will fix it now

**Comment by enriqueg** [comment]
@ugurozturk It seems that Instagram tried something..at least for me it is working again! Many Thanks! (feel free to close this)

**Comment by eltoro3** [comment]
I get login error

**Comment by eltoro3** [comment]
Is it working fine without fixing anything?

**Comment by indiscreetak** [comment]
@eltoro3 I have been running it for the last 30 minutes without changing anything.

**Comment by ugurozturk** [comment]
@eltoro3 yes it is working fine right now without changing anything

**Comment by ugurozturk** [comment]
@bgokden what about you ?

**Comment by eltoro3** [comment]
Oh you`re right, it's just that instagram was asking me to verify my account with my phone number. And the bot was unable to login because if that

**Comment by ugurozturk** [comment]
Closing it because the main problem of this issue looks gone
