### ISSUE TITLE
I don't know this error? What is this?

### ISSUE THREAD

**Issue by aopiskin** [instabot-py/instabot.py#930]
```
24.01.2018_22:59 Trying to login as ...!!!account!!!...

Traceback (most recent call last):
  File "dsc.py", line 30, in <module>
    comment_list=[['👍👍👍','Comment!👍']])
  File "C:\Users\user\Downloads\instabot.py\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\user\Downloads\instabot.py\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\user\Downloads\instabot.py\src\userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I downloaded last version.  I tried connect with my account but I got this error. 

How can I solve this error?

Thanks....

**Comment by eltoro3** [comment]
Same here

**Comment by eltoro3** [comment]
Maybe Instagram changed some features preventing this bot from logging in?

**Comment by aopiskin** [comment]
Probably everybody gettin' thesame error. Instagram may change algorithm.

**Comment by aopiskin** [comment]
#929 I'm closing because everybody can't login
