### ISSUE TITLE
ModuleNotFoundError: No module named 'fake_useragent'

### ISSUE THREAD

**Issue by MaxCovet** [instabot-py/instabot.py#933]
Traceback (most recent call last):
  File "/home/moneybillionair/instabot.py/example.py", line 5, in <module>
    from src import InstaBot
  File "/home/moneybillionair/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/moneybillionair/instabot.py/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

This is what I get when I try running it

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md

**Comment by ugurozturk** [comment]
Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket.
