### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by NodalPoint** [instabot-py/instabot.py#951]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
macOS High Sierra 10.13.2

## Python Version?
3

## Description

After my bot adds people to the blacklist, it says ValueError: No JSON object could be decoded
Last time this happened, everyone had the same error for a couple hours but now, I can't seem to find any other submissions on this error.

Include the contents of the error.log here (if applicable).

Traceback (most recent call last):
  File "script_blacklist.py", line 47, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/x/Desktop/instabot.py-master/src/instabot.py", line 228, in __init__
    self.populate_user_blacklist()
  File "/Users/x/Desktop/instabot.py-master/src/instabot.py", line 240, in populate_user_blacklist
    all_data = json.loads(info.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
