### ISSUE TITLE
Getting this error in prompt. What to do next??

### ISSUE THREAD

**Issue by aakash74052** [instabot-py/instabot.py#957]
C:\Users\Aakash\Downloads\instabot.py-master1>python example.py
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from src import InstaBot
  File "C:\Users\Aakash\Downloads\instabot.py-master1\src\__init__.py", line 1,
in <module>
    from .instabot import InstaBot
  File "C:\Users\Aakash\Downloads\instabot.py-master1\src\instabot.py", line 6,
in <module>
    from .userinfo import UserInfo
  File "C:\Users\Aakash\Downloads\instabot.py-master1\src\userinfo.py", line 5,
in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\Users\Aakash\Downloads\instabot.py-master1>

C:\Users\Aakash\Downloads\instabot.py-master1>python example.py
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from src import InstaBot
  File "C:\Users\Aakash\Downloads\instabot.py-master1\src\__init__.py", line 1,
in <module>
    from .instabot import InstaBot
  File "C:\Users\Aakash\Downloads\instabot.py-master1\src\instabot.py", line 6,
in <module>
    from .userinfo import UserInfo
  File "C:\Users\Aakash\Downloads\instabot.py-master1\src\userinfo.py", line 5,
in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\Users\Aakash\Downloads\instabot.py-master1>

**Comment by carlisillo** [comment]
I'm having the same issue! :(

**Comment by MackPerfecto** [comment]
pip install -r requirements.txt

try this :)

**Comment by MackPerfecto** [comment]
pip install requests

run this command
