### ISSUE TITLE
I couldn't comment using the instabot

### ISSUE THREAD

**Issue by pratik96** [instabot-py/instabot.py#984]
For Like and all other things, the code is working correctly.

I am facing issue while commenting.

I got the following error:

Traceback (most recent call last):
  File "example.py", line 79, in <module>
    bot.new_auto_mod()
  File "/Users/admin/Desktop/instabot.py/src/instabot.py", line 576, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/admin/Desktop/instabot.py/src/instabot.py", line 631, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['comments_disabled']) == False:
  File "/Users/admin/Desktop/instabot.py/src/instabot.py", line 655, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/anaconda/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/anaconda/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
Bot work time: 0:00:18.781086
Logout success!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/admin/Desktop/instabot.py/src/instabot.py", line 312, in cleanup
    exit(0)
  File "/anaconda/lib/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

Can someone please help me with this.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
